import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const dir = dirname(fileURLToPath(import.meta.url));
const TIMER = { review: 5, vocab: 8, grammar: 8, talk: 5, ai: 4 };

function v(han, pinyin, vi, exHan, exPy, exVi) {
  return {
    han,
    pinyin,
    vi,
    example: { han: exHan, pinyin: exPy, vi: exVi },
  };
}

function line(speaker, han, pinyin, vi) {
  return { speaker, han, pinyin, vi };
}

function drill(prompt, answer) {
  return { prompt, answer };
}

function ex(prompt, answer) {
  return { type: "write", prompt, answer };
}

const LESSONS = [
  {
    id: 169,
    theme: "Lương",
    kind: "learn",
    vocab: [
      v("工资", "gōngzī", "Lương", "我的工资提高了。", "Wǒ de gōngzī tígāo le.", "Lương tôi tăng rồi."),
      v("收入", "shōurù", "Thu nhập", "他的收入不错。", "Tā de shōurù búcuò.", "Thu nhập anh ấy khá."),
      v("经济", "jīngjì", "Kinh tế", "经济在发展。", "Jīngjì zài fāzhǎn.", "Kinh tế đang phát triển."),
      v("经验", "jīngyàn", "Kinh nghiệm", "我有工作经验。", "Wǒ yǒu gōngzuò jīngyàn.", "Tôi có kinh nghiệm làm việc."),
      v("成功", "chénggōng", "Thành công", "祝你成功。", "Zhù nǐ chénggōng.", "Chúc bạn thành công."),
    ],
    grammar: {
      title: "对…满意",
      pattern: "对 + N + 满意",
      explainVi: "对…满意 (ôn): hài lòng với điều gì. 对工资满意、对工作满意.",
      drills: [
        drill("Dịch: Lương tôi tăng rồi.", "我的工资提高了。"),
        drill("Dịch: Tôi có kinh nghiệm làm việc.", "我有工作经验。"),
        drill("Dịch: Tôi hài lòng với thu nhập.", "我对收入满意。"),
        drill("Dịch: Chúc bạn thành công.", "祝你成功。"),
      ],
    },
    dialogue: [
      line("A", "你对现在的工资满意吗？", "Nǐ duì xiànzài de gōngzī mǎnyì ma?", "Bạn hài lòng với lương hiện tại không?"),
      line("B", "满意。收入比以前好。", "Mǎnyì. Shōurù bǐ yǐqián hǎo.", "Hài lòng. Thu nhập tốt hơn trước."),
      line("A", "你有几年工作经验？", "Nǐ yǒu jǐ nián gōngzuò jīngyàn?", "Bạn có mấy năm kinh nghiệm?"),
      line("B", "三年。经济好了，机会也多。", "Sān nián. Jīngjì hǎo le, jīhuì yě duō.", "Ba năm. Kinh tế tốt, cơ hội cũng nhiều."),
    ],
    exercises: [
      ex("Tự viết: Lương tôi tăng rồi. Tôi hài lòng.", "我的工资提高了。我很满意。"),
      ex("Tự viết: Tôi có ba năm kinh nghiệm.", "我有三年工作经验。"),
    ],
    scenario: "Nói về lương, thu nhập, kinh nghiệm và có hài lòng không.",
    start: "你对现在的工资满意吗？",
  },
  {
    id: 170,
    theme: "Hợp đồng",
    kind: "learn",
    vocab: [
      v("合同", "hétong", "Hợp đồng", "请看一下合同。", "Qǐng kàn yíxià hétong.", "Hãy xem hợp đồng."),
      v("签字", "qiānzì", "Ký tên", "请在这里签字。", "Qǐng zài zhèlǐ qiānzì.", "Hãy ký ở đây."),
      v("法律", "fǎlǜ", "Pháp luật", "这是法律规定。", "Zhè shì fǎlǜ guīdìng.", "Đây là quy định pháp luật."),
      v("安排", "ānpái", "Sắp xếp", "经理安排了会议。", "Jīnglǐ ānpái le huìyì.", "Giám đốc sắp họp."),
      v("通知", "tōngzhī", "Thông báo", "我收到通知了。", "Wǒ shōudào tōngzhī le.", "Tôi nhận được thông báo."),
    ],
    grammar: {
      title: "安排 + danh từ",
      pattern: "安排 + N",
      explainVi: "安排 đi với sự việc cụ thể: 安排会议、安排工作.",
      drills: [
        drill("Dịch: Hãy xem hợp đồng.", "请看一下合同。"),
        drill("Dịch: Hãy ký ở đây.", "请在这里签字。"),
        drill("Dịch: Giám đốc sắp họp.", "经理安排了会议。"),
        drill("Dịch: Tôi nhận được thông báo.", "我收到通知了。"),
      ],
    },
    dialogue: [
      line("A", "请看一下合同，没问题就签字。", "Qǐng kàn yíxià hétong, méi wèntí jiù qiānzì.", "Xem hợp đồng, không vấn đề thì ký."),
      line("B", "好。这是法律规定的吗？", "Hǎo. Zhè shì fǎlǜ guīdìng de ma?", "Được. Đây là quy định pháp luật à?"),
      line("A", "对。公司也发了通知。", "Duì. Gōngsī yě fā le tōngzhī.", "Đúng. Công ty cũng gửi thông báo."),
      line("B", "经理安排了什么时候开始？", "Jīnglǐ ānpái le shénme shíhou kāishǐ?", "Giám đốc sắp bắt đầu khi nào?"),
    ],
    exercises: [
      ex("Tự viết: Xem hợp đồng rồi ký.", "看一下合同，然后签字。"),
      ex("Tự viết: Tôi nhận được thông báo của công ty.", "我收到公司的通知了。"),
    ],
    scenario: "Ký hợp đồng làm việc: xem điều khoản, ký tên, nhận thông báo.",
    start: "请看一下合同，没问题就签字。",
  },
  {
    id: 171,
    theme: "Trách nhiệm",
    kind: "learn",
    vocab: [
      v("负责", "fùzé", "Phụ trách", "我负责这个项目。", "Wǒ fùzé zhège xiàngmù.", "Tôi phụ trách dự án này."),
      v("任务", "rènwu", "Nhiệm vụ", "今天的任务完成了。", "Jīntiān de rènwu wánchéng le.", "Nhiệm vụ hôm nay xong rồi."),
      v("责任", "zérèn", "Trách nhiệm", "这是我的责任。", "Zhè shì wǒ de zérèn.", "Đây là trách nhiệm của tôi."),
      v("按时", "ànshí", "Đúng giờ", "请按时完成。", "Qǐng ànshí wánchéng.", "Hãy hoàn thành đúng hạn."),
      v("准时", "zhǔnshí", "Đúng giờ (chính xác)", "请准时到。", "Qǐng zhǔnshí dào.", "Hãy đến đúng giờ."),
    ],
    grammar: {
      title: "负责 + việc",
      pattern: "负责 + N / V",
      explainVi: "负责: chịu trách nhiệm việc gì. 负责项目、负责检查.",
      drills: [
        drill("Dịch: Tôi phụ trách dự án này.", "我负责这个项目。"),
        drill("Dịch: Nhiệm vụ hôm nay xong rồi.", "今天的任务完成了。"),
        drill("Dịch: Hãy hoàn thành đúng hạn.", "请按时完成。"),
        drill("Dịch: Hãy đến đúng giờ.", "请准时到。"),
      ],
    },
    dialogue: [
      line("A", "这个项目谁负责？", "Zhège xiàngmù shéi fùzé?", "Dự án này ai phụ trách?"),
      line("B", "我负责。今天的任务很重要。", "Wǒ fùzé. Jīntiān de rènwu hěn zhòngyào.", "Tôi phụ trách. Nhiệm vụ hôm nay quan trọng."),
      line("A", "请按时完成，准时开会。", "Qǐng ànshí wánchéng, zhǔnshí kāi huì.", "Hoàn thành đúng hạn, họp đúng giờ."),
      line("B", "明白。这是我的责任。", "Míngbai. Zhè shì wǒ de zérèn.", "Hiểu rồi. Đây là trách nhiệm tôi."),
    ],
    exercises: [
      ex("Tự viết: Tôi phụ trách dự án này.", "我负责这个项目。"),
      ex("Tự viết: Hãy hoàn thành đúng hạn, đến đúng giờ.", "请按时完成，准时到。"),
    ],
    scenario: "Phân công việc: ai phụ trách, nhiệm vụ, hoàn thành đúng hạn.",
    start: "这个项目谁负责？",
  },
  {
    id: 172,
    theme: "Phát triển",
    kind: "learn",
    vocab: [
      v("发展", "fāzhǎn", "Phát triển", "公司在发展。", "Gōngsī zài fāzhǎn.", "Công ty đang phát triển."),
      v("进步", "jìnbù", "Tiến bộ", "你进步很快。", "Nǐ jìnbù hěn kuài.", "Bạn tiến bộ nhanh."),
      v("能力", "nénglì", "Năng lực", "提高工作能力。", "Tígāo gōngzuò nénglì.", "Nâng năng lực làm việc."),
      v("适合", "shìhé", "Phù hợp", "这个工作适合我。", "Zhège gōngzuò shìhé wǒ.", "Việc này phù hợp tôi."),
      v("改变", "gǎibiàn", "Thay đổi", "我想改变方法。", "Wǒ xiǎng gǎibiàn fāngfǎ.", "Tôi muốn đổi cách."),
    ],
    grammar: {
      title: "适合 + N / V",
      pattern: "适合 + N / V",
      explainVi: "适合: phù hợp với ai/cái gì. 适合我、适合这个工作.",
      drills: [
        drill("Dịch: Công ty đang phát triển.", "公司在发展。"),
        drill("Dịch: Bạn tiến bộ nhanh.", "你进步很快。"),
        drill("Dịch: Việc này phù hợp tôi.", "这个工作适合我。"),
        drill("Dịch: Nâng năng lực làm việc.", "提高工作能力。"),
      ],
    },
    dialogue: [
      line("A", "你觉得这个工作适合你吗？", "Nǐ juéde zhège gōngzuò shìhé nǐ ma?", "Bạn thấy việc này phù hợp không?"),
      line("B", "适合。公司发展很快，我也进步。", "Shìhé. Gōngsī fāzhǎn hěn kuài, wǒ yě jìnbù.", "Phù hợp. Công ty phát triển nhanh, tôi cũng tiến."),
      line("A", "你的能力提高了。", "Nǐ de nénglì tígāo le.", "Năng lực bạn tăng rồi."),
      line("B", "对。我想改变一下学习方法。", "Duì. Wǒ xiǎng gǎibiàn yíxià xuéxí fāngfǎ.", "Đúng. Tôi muốn đổi cách học."),
    ],
    exercises: [
      ex("Tự viết: Việc này phù hợp tôi. Công ty phát triển nhanh.", "这个工作适合我。公司发展很快。"),
      ex("Tự viết: Tôi muốn nâng năng lực.", "我想提高能力。"),
    ],
    scenario: "Nói về phát triển công ty, tiến bộ cá nhân, việc có phù hợp không.",
    start: "你觉得这个工作适合你吗？",
  },
  {
    id: 173,
    theme: "Xin việc",
    kind: "learn",
    vocab: [
      v("辞职", "cízhí", "Nghỉ việc", "他打算辞职。", "Tā dǎsuàn cízhí.", "Anh ấy định nghỉ việc."),
      v("面试", "miànshì", "Phỏng vấn", "明天有面试。", "Míngtiān yǒu miànshì.", "Mai có phỏng vấn."),
      v("申请", "shēnqǐng", "Nộp đơn", "我申请了这份工作。", "Wǒ shēnqǐng le zhè fèn gōngzuò.", "Tôi nộp đơn việc này."),
      v("结果", "jiéguǒ", "Kết quả", "结果出来了。", "Jiéguǒ chūlái le.", "Kết quả ra rồi."),
      v("失败", "shībài", "Thất bại", "别害怕失败。", "Bié hàipà shībài.", "Đừng sợ thất bại."),
    ],
    grammar: {
      title: "申请 + danh từ",
      pattern: "申请 + N",
      explainVi: "申请 đi với đối tượng: 申请工作、申请签证.",
      drills: [
        drill("Dịch: Mai có phỏng vấn.", "明天有面试。"),
        drill("Dịch: Tôi nộp đơn việc này.", "我申请了这份工作。"),
        drill("Dịch: Kết quả ra rồi.", "结果出来了。"),
        drill("Dịch: Đừng sợ thất bại.", "别害怕失败。"),
      ],
    },
    dialogue: [
      line("A", "你申请这份工作了吗？", "Nǐ shēnqǐng le zhè fèn gōngzuò le ma?", "Bạn nộp đơn việc này chưa?"),
      line("B", "申请了。明天有面试。", "Shēnqǐng le. Míngtiān yǒu miànshì.", "Rồi. Mai có phỏng vấn."),
      line("A", "别紧张。别害怕失败。", "Bié jǐnzhāng. Bié hàipà shībài.", "Đừng căng. Đừng sợ thất bại."),
      line("B", "好。结果出来我再告诉你。", "Hǎo. Jiéguǒ chūlái wǒ zài gàosu nǐ.", "Được. Ra kết quả tôi báo bạn."),
    ],
    exercises: [
      ex("Tự viết: Tôi nộp đơn rồi. Mai phỏng vấn.", "我申请了。明天面试。"),
      ex("Tự viết: Kết quả ra rồi. Tôi成功了。", "结果出来了。我成功了。"),
    ],
    scenario: "Nộp đơn xin việc, chuẩn bị phỏng vấn, chờ kết quả.",
    start: "你申请这份工作了吗？",
  },
  {
    id: 174,
    theme: "Tổng hợp công việc",
    kind: "review",
    vocab: [
      v("负责", "fùzé", "Phụ trách (ôn)", "我负责报告。", "Wǒ fùzé bàogào.", "Tôi phụ trách báo cáo."),
      v("按时", "ànshí", "Đúng hạn (ôn)", "请按时交。", "Qǐng ànshí jiāo.", "Hãy nộp đúng hạn."),
      v("工资", "gōngzī", "Lương (ôn)", "对工资满意。", "Duì gōngzī mǎnyì.", "Hài lòng lương."),
      v("申请", "shēnqǐng", "Nộp đơn (ôn)", "申请了工作。", "Shēnqǐng le gōngzuò.", "Nộp đơn việc rồi."),
      v("适合", "shìhé", "Phù hợp (ôn)", "工作适合我。", "Gōngzuò shìhé wǒ.", "Việc phù hợp tôi."),
    ],
    grammar: {
      title: "负责 / 按时",
      pattern: "负责 + N；按时 + V",
      explainVi: "Ôn tuần 25: báo cáo công việc, phụ trách việc, hoàn thành đúng hạn.",
      drills: [
        drill("Dịch: Tôi phụ trách báo cáo.", "我负责报告。"),
        drill("Dịch: Hãy nộp đúng hạn.", "请按时交。"),
        drill("Dịch: Việc phù hợp tôi.", "工作适合我。"),
        drill("Dịch: Tôi hài lòng lương.", "我对工资满意。"),
      ],
    },
    dialogue: [
      line("A", "这周你负责什么？", "Zhè zhōu nǐ fùzé shénme?", "Tuần này bạn phụ trách gì?"),
      line("B", "负责报告。请按时完成。", "Fùzé bàogào. Qǐng ànshí wánchéng.", "Báo cáo. Hãy hoàn thành đúng hạn."),
      line("A", "你对工资满意吗？", "Nǐ duì gōngzī mǎnyì ma?", "Bạn hài lòng lương không?"),
      line("B", "满意。这个工作适合我。", "Mǎnyì. Zhège gōngzuò shìhé wǒ.", "Hài lòng. Việc này phù hợp tôi."),
    ],
    exercises: [
      ex("Tự viết: Tuần này tôi phụ trách báo cáo.", "这周我负责报告。"),
      ex("Tự viết: Hãy hoàn thành đúng hạn.", "请按时完成。"),
    ],
    scenario: "Báo cáo tuần: phụ trách gì, đúng hạn, lương, việc có phù hợp.",
    start: "这周你负责什么？",
  },
  {
    id: 175,
    theme: "Sếp vs nhân viên mới",
    kind: "review",
    vocab: [
      v("合同", "hétong", "Hợp đồng (ôn)", "签了合同。", "Qiān le hétong.", "Ký hợp đồng rồi."),
      v("任务", "rènwu", "Nhiệm vụ (ôn)", "新任务来了。", "Xīn rènwu lái le.", "Nhiệm vụ mới tới."),
      v("经验", "jīngyàn", "Kinh nghiệm (ôn)", "有经验就好。", "Yǒu jīngyàn jiù hǎo.", "Có kinh nghiệm là tốt."),
      v("通知", "tōngzhī", "Thông báo (ôn)", "收到通知了吗？", "Shōudào tōngzhī le ma?", "Nhận thông báo chưa?"),
      v("面试", "miànshì", "Phỏng vấn (ôn)", "面试怎么样？", "Miànshì zěnmeyàng?", "Phỏng vấn thế nào?"),
    ],
    grammar: {
      title: "Chỉ công việc",
      pattern: "负责 / 安排 / 申请",
      explainVi: "Roleplay sếp vs nhân viên mới. Khoá từ tuần 25.",
      drills: [
        drill("Dịch: Ký hợp đồng rồi.", "签了合同。"),
        drill("Dịch: Nhiệm vụ mới tới.", "新任务来了。"),
        drill("Dịch: Nhận thông báo chưa?", "收到通知了吗？"),
        drill("Dịch: Có kinh nghiệm là tốt.", "有经验就好。"),
      ],
    },
    dialogue: [
      line("A", "欢迎。你签了合同吗？", "Huānyíng. Nǐ qiān le hétong ma?", "Hoan nghênh. Bạn ký hợp đồng chưa?"),
      line("B", "签了。也收到通知了。", "Qiān le. Yě shōudào tōngzhī le.", "Rồi. Cũng nhận thông báo rồi."),
      line("A", "好。你有工作经验吗？", "Hǎo. Nǐ yǒu gōngzuò jīngyàn ma?", "Tốt. Bạn có kinh nghiệm không?"),
      line("B", "有。我会认真完成任务。", "Yǒu. Wǒ huì rènzhēn wánchéng rènwu.", "Có. Tôi sẽ hoàn thành nhiệm vụ nghiêm túc."),
    ],
    exercises: [
      ex("Tự viết: Chào mừng. Bạn ký hợp đồng chưa?", "欢迎。你签了合同吗？"),
      ex("Tự viết: Tôi sẽ hoàn thành nhiệm vụ.", "我会完成任务。"),
    ],
    scenario: "Ngày đầu làm việc: ký hợp đồng, nhận thông báo, kinh nghiệm, nhiệm vụ.",
    start: "欢迎。你签了合同吗？",
  },
  {
    id: 176,
    theme: "Tin",
    kind: "learn",
    vocab: [
      v("新闻", "xīnwén", "Tin tức", "你看新闻了吗？", "Nǐ kàn xīnwén le ma?", "Bạn xem tin chưa?"),
      v("消息", "xiāoxi", "Tin nhắn / tin", "有个好消息。", "Yǒu ge hǎo xiāoxi.", "Có tin tốt."),
      v("广播", "guǎngbō", "Phát thanh", "听广播。", "Tīng guǎngbō.", "Nghe đài."),
      v("报道", "bàodào", "Đưa tin", "新闻报道了。", "Xīnwén bàodào le.", "Tin đưa rồi."),
      v("引起", "yǐnqǐ", "Gây ra", "引起了讨论。", "Yǐnqǐ le tǎolùn.", "Gây ra thảo luận."),
    ],
    grammar: {
      title: "引起 + sự kiện",
      pattern: "引起 + N",
      explainVi: "引起: làm phát sinh điều gì. 引起讨论、引起注意.",
      drills: [
        drill("Dịch: Bạn xem tin chưa?", "你看新闻了吗？"),
        drill("Dịch: Có tin tốt.", "有个好消息。"),
        drill("Dịch: Tin đưa rồi.", "新闻报道了。"),
        drill("Dịch: Gây ra thảo luận.", "引起了讨论。"),
      ],
    },
    dialogue: [
      line("A", "你看今天的新闻了吗？", "Nǐ kàn jīntiān de xīnwén le ma?", "Bạn xem tin hôm nay chưa?"),
      line("B", "看了。广播也报道了。", "Kàn le. Guǎngbō yě bàodào le.", "Rồi. Đài cũng đưa tin."),
      line("A", "这个消息引起了讨论。", "Zhège xiāoxi yǐnqǐ le tǎolùn.", "Tin này gây thảo luận."),
      line("B", "对。同事都在讨论。", "Duì. Tóngshì dōu zài tǎolùn.", "Đúng. Đồng nghiệp đều bàn."),
    ],
    exercises: [
      ex("Tự viết: Bạn xem tin hôm nay chưa?", "你看今天的新闻了吗？"),
      ex("Tự viết: Tin này gây thảo luận.", "这个消息引起了讨论。"),
    ],
    scenario: "Đọc tin, nghe đài, chia sẻ tin gây thảo luận.",
    start: "你看今天的新闻了吗？",
  },
  {
    id: 177,
    theme: "Ý kiến",
    kind: "learn",
    vocab: [
      v("意见", "yìjiàn", "Ý kiến", "你有什么意见？", "Nǐ yǒu shénme yìjiàn?", "Bạn có ý kiến gì?"),
      v("讨论", "tǎolùn", "Thảo luận", "我们讨论一下。", "Wǒmen tǎolùn yíxià.", "Chúng ta thảo luận."),
      v("建议", "jiànyì", "Đề xuất", "我建议改变。", "Wǒ jiànyì gǎibiàn.", "Tôi đề xuất thay đổi."),
      v("批评", "pīpíng", "Phê bình", "别批评他。", "Bié pīpíng tā.", "Đừng phê bình anh ấy."),
      v("接受", "jiēshòu", "Chấp nhận", "我接受你的建议。", "Wǒ jiēshòu nǐ de jiànyì.", "Tôi chấp nhận đề xuất bạn."),
    ],
    grammar: {
      title: "接受 + ý kiến",
      pattern: "接受 + N",
      explainVi: "接受: đồng ý nhận ý kiến/đề xuất. 接受建议、接受意见.",
      drills: [
        drill("Dịch: Bạn có ý kiến gì?", "你有什么意见？"),
        drill("Dịch: Chúng ta thảo luận.", "我们讨论一下。"),
        drill("Dịch: Tôi chấp nhận đề xuất bạn.", "我接受你的建议。"),
        drill("Dịch: Đừng phê bình anh ấy.", "别批评他。"),
      ],
    },
    dialogue: [
      line("A", "关于这个项目，你有什么意见？", "Guānyú zhège xiàngmù, nǐ yǒu shénme yìjiàn?", "Về dự án này, bạn có ý kiến gì?"),
      line("B", "我建议改变一下方法。", "Wǒ jiànyì gǎibiàn yíxià fāngfǎ.", "Tôi đề xuất đổi cách."),
      line("A", "好。我们讨论一下。", "Hǎo. Wǒmen tǎolùn yíxià.", "Được. Thảo luận đi."),
      line("B", "我接受你的意见。别批评同事。", "Wǒ jiēshòu nǐ de yìjiàn. Bié pīpíng tóngshì.", "Tôi chấp nhận ý bạn. Đừng phê bình đồng nghiệp."),
    ],
    exercises: [
      ex("Tự viết: Về dự án, bạn có ý kiến gì?", "关于这个项目，你有什么意见？"),
      ex("Tự viết: Tôi chấp nhận đề xuất của bạn.", "我接受你的建议。"),
    ],
    scenario: "Thảo luận dự án: đưa ý kiến, đề xuất, chấp nhận.",
    start: "关于这个项目，你有什么意见？",
  },
  {
    id: 178,
    theme: "Cảm xúc",
    kind: "learn",
    vocab: [
      v("精彩", "jīngcǎi", "Hay / xuất sắc", "电影很精彩。", "Diànyǐng hěn jīngcǎi.", "Phim rất hay."),
      v("无聊", "wúliáo", "Nhàm chán", "我觉得无聊。", "Wǒ juéde wúliáo.", "Tôi thấy nhàm."),
      v("新鲜", "xīnxiān", "Mới lạ", "这个想法很新鲜。", "Zhège xiǎngfǎ hěn xīnxiān.", "Ý tưởng này mới lạ."),
      v("感动", "gǎndòng", "Cảm động", "我很感动。", "Wǒ hěn gǎndòng.", "Tôi rất cảm động."),
      v("后悔", "hòuhuǐ", "Hối hận", "我不后悔。", "Wǒ bù hòuhuǐ.", "Tôi không hối hận."),
    ],
    grammar: {
      title: "adj + 极了",
      pattern: "adj + 极了 (ôn)",
      explainVi: "极了 (ôn): rất, cực kỳ. 精彩极了、无聊极了.",
      drills: [
        drill("Dịch: Phim rất hay.", "电影精彩极了。"),
        drill("Dịch: Tôi thấy nhàm.", "我觉得无聊。"),
        drill("Dịch: Tôi rất cảm động.", "我很感动。"),
        drill("Dịch: Tôi không hối hận.", "我不后悔。"),
      ],
    },
    dialogue: [
      line("A", "昨天的电影怎么样？", "Zuótiān de diànyǐng zěnmeyàng?", "Phim hôm qua thế nào?"),
      line("B", "精彩极了。我很感动。", "Jīngcǎi jí le. Wǒ hěn gǎndòng.", "Hay cực. Tôi cảm động."),
      line("A", "那个节目呢？新鲜吗？", "Nàge jiémù ne? Xīnxiān ma?", "Chương trình kia? Mới lạ không?"),
      line("B", "新鲜。以前那个无聊，我不后悔没去。", "Xīnxiān. Yǐqián nàge wúliáo, wǒ bù hòuhuǐ méi qù.", "Mới lạ. Cái trước nhàm, tôi không hối hận vì không đi."),
    ],
    exercises: [
      ex("Tự viết: Phim hay cực. Tôi rất cảm động.", "电影精彩极了。我很感动。"),
      ex("Tự viết: Chương trình mới lạ.", "这个节目很新鲜。"),
    ],
    scenario: "Kể cảm giác xem phim, chương trình hay hay nhàm.",
    start: "昨天的电影怎么样？",
  },
  {
    id: 179,
    theme: "Quan hệ",
    kind: "learn",
    vocab: [
      v("尊重", "zūnzhòng", "Tôn trọng", "要尊重别人。", "Yào zūnzhòng biérén.", "Phải tôn trọng người khác."),
      v("礼貌", "lǐmào", "Lịch sự", "他很有礼貌。", "Tā hěn yǒu lǐmào.", "Anh ấy rất lịch sự."),
      v("邀请", "yāoqǐng", "Mời", "我邀请你来。", "Wǒ yāoqǐng nǐ lái.", "Tôi mời bạn đến."),
      v("祝贺", "zhùhè", "Chúc mừng", "祝贺你成功。", "Zhùhè nǐ chénggōng.", "Chúc mừng bạn thành công."),
      v("参观", "cānguān", "Tham quan", "欢迎参观。", "Huānyíng cānguān.", "Hoan nghênh tham quan."),
    ],
    grammar: {
      title: "邀请 + người",
      pattern: "邀请 + người + V",
      explainVi: "邀请 ai làm gì: 邀请你来、邀请同事参观.",
      drills: [
        drill("Dịch: Phải tôn trọng người khác.", "要尊重别人。"),
        drill("Dịch: Tôi mời bạn đến.", "我邀请你来。"),
        drill("Dịch: Chúc mừng bạn thành công.", "祝贺你成功。"),
        drill("Dịch: Hoan nghênh tham quan.", "欢迎参观。"),
      ],
    },
    dialogue: [
      line("A", "我邀请你参加庆祝活动。", "Wǒ yāoqǐng nǐ cānjiā qìngzhù huódòng.", "Tôi mời bạn dự lễ kỷ niệm."),
      line("B", "谢谢。祝贺你成功。", "Xièxie. Zhùhè nǐ chénggōng.", "Cảm ơn. Chúc mừng bạn."),
      line("A", "欢迎带朋友来参观。", "Huānyíng dài péngyou lái cānguān.", "Mời bạn bè đến tham quan."),
      line("B", "好。我会很有礼貌，也尊重别人。", "Hǎo. Wǒ huì hěn yǒu lǐmào, yě zūnzhòng biérén.", "Được. Tôi sẽ lịch sự, tôn trọng mọi người."),
    ],
    exercises: [
      ex("Tự viết: Tôi mời bạn dự lễ.", "我邀请你参加活动。"),
      ex("Tự viết: Chúc mừng bạn thành công.", "祝贺你成功。"),
    ],
    scenario: "Mời dự lễ, chúc mừng, tham quan, cư xử lịch sự.",
    start: "我邀请你参加庆祝活动。",
  },
  {
    id: 180,
    theme: "Lịch sự",
    kind: "learn",
    vocab: [
      v("恐怕", "kǒngpà", "E rằng / sợ rằng", "恐怕我来不了。", "Kǒngpà wǒ lái bù liǎo.", "E rằng tôi không đến được."),
      v("抱歉", "bàoqiàn", "Xin lỗi", "真抱歉。", "Zhēn bàoqiàn.", "Thật xin lỗi."),
      v("麻烦", "máfan", "Phiền", "麻烦你了。", "Máfan nǐ le.", "Làm phiền bạn rồi."),
      v("打扰", "dǎrǎo", "Làm phiền", "打扰一下。", "Dǎrǎo yíxià.", "Xin phép làm phiền."),
      v("专门", "zhuānmén", "Chuyên / đặc biệt", "我专门来看你。", "Wǒ zhuānmén lái kàn nǐ.", "Tôi đến đặc biệt để gặp bạn."),
    ],
    grammar: {
      title: "恐怕 + câu",
      pattern: "恐怕 + câu",
      explainVi: "恐怕: e rằng, lo rằng. 恐怕我来不了、恐怕要下雨.",
      drills: [
        drill("Dịch: E rằng tôi không đến được.", "恐怕我来不了。"),
        drill("Dịch: Thật xin lỗi.", "真抱歉。"),
        drill("Dịch: Làm phiền bạn rồi.", "麻烦你了。"),
        drill("Dịch: Xin phép làm phiền.", "打扰一下。"),
      ],
    },
    dialogue: [
      line("A", "打扰一下。恐怕我来晚了。", "Dǎrǎo yíxià. Kǒngpà wǒ lái wǎn le.", "Xin phép. E rằng tôi đến muộn."),
      line("B", "没关系。真抱歉让你等。", "Méi guānxi. Zhēn bàoqiàn ràng nǐ děng.", "Không sao. Xin lỗi để bạn đợi."),
      line("A", "麻烦你了。我专门来解释。", "Máfan nǐ le. Wǒ zhuānmén lái jiěshì.", "Làm phiền bạn. Tôi đến giải thích."),
      line("B", "不麻烦。请坐。", "Bù máfan. Qǐng zuò.", "Không phiền. Mời ngồi."),
    ],
    exercises: [
      ex("Tự viết: E rằng tôi không đến được. Xin lỗi.", "恐怕我来不了。真抱歉。"),
      ex("Tự viết: Xin phép làm phiền một chút.", "打扰一下。"),
    ],
    scenario: "Xin lỗi vì đến muộn, làm phiền, giải thích lịch sự.",
    start: "打扰一下。恐怕我来晚了。",
  },
  {
    id: 181,
    theme: "Tổng hợp giao tiếp",
    kind: "review",
    vocab: [
      v("邀请", "yāoqǐng", "Mời (ôn)", "邀请你参观。", "Yāoqǐng nǐ cānguān.", "Mời bạn tham quan."),
      v("恐怕", "kǒngpà", "E rằng (ôn)", "恐怕不行。", "Kǒngpà bù xíng.", "E rằng không được."),
      v("意见", "yìjiàn", "Ý kiến (ôn)", "有什么意见？", "Yǒu shénme yìjiàn?", "Có ý kiến gì?"),
      v("接受", "jiēshòu", "Chấp nhận (ôn)", "我接受。", "Wǒ jiēshòu.", "Tôi chấp nhận."),
      v("新闻", "xīnwén", "Tin tức (ôn)", "看新闻了吗？", "Kàn xīnwén le ma?", "Xem tin chưa?"),
    ],
    grammar: {
      title: "恐怕 / 邀请",
      pattern: "恐怕 + câu；邀请 + người",
      explainVi: "Ôn tuần 26: mời bạn xem triển lãm, xin lỗi lịch sự.",
      drills: [
        drill("Dịch: Mời bạn tham quan.", "邀请你参观。"),
        drill("Dịch: E rằng không được.", "恐怕不行。"),
        drill("Dịch: Có ý kiến gì?", "有什么意见？"),
        drill("Dịch: Tôi chấp nhận.", "我接受。"),
      ],
    },
    dialogue: [
      line("A", "我邀请你参观展览，你有空吗？", "Wǒ yāoqǐng nǐ cānguān zhǎnlǎn, nǐ yǒu kòng ma?", "Mời bạn xem triển lãm, rảnh không?"),
      line("B", "恐怕周末不行。真抱歉。", "Kǒngpà zhōumò bù xíng. Zhēn bàoqiàn.", "E rằng cuối tuần không được. Xin lỗi."),
      line("A", "没关系。你有什么意见？", "Méi guānxi. Nǐ yǒu shénme yìjiàn?", "Không sao. Bạn có ý kiến gì?"),
      line("B", "我建议下周去。我接受你的邀请。", "Wǒ jiànyì xià zhōu qù. Wǒ jiēshòu nǐ de yāoqǐng.", "Tôi đề xuất tuần sau. Tôi nhận lời mời."),
    ],
    exercises: [
      ex("Tự viết: Mời bạn xem triển lãm.", "邀请你参观展览。"),
      ex("Tự viết: E rằng cuối tuần không được.", "恐怕周末不行。"),
    ],
    scenario: "Mời xem triển lãm, xin lỗi bận, đề xuất tuần sau.",
    start: "我邀请你参观展览，你有空吗？",
  },
  {
    id: 182,
    theme: "Bạn mời dự sinh nhật",
    kind: "review",
    vocab: [
      v("祝贺", "zhùhè", "Chúc mừng (ôn)", "祝贺生日快乐。", "Zhùhè shēngrì kuàilè.", "Chúc mừng sinh nhật."),
      v("礼貌", "lǐmào", "Lịch sự (ôn)", "很有礼貌。", "Hěn yǒu lǐmào.", "Rất lịch sự."),
      v("麻烦", "máfan", "Phiền (ôn)", "不麻烦。", "Bù máfan.", "Không phiền."),
      v("讨论", "tǎolùn", "Thảo luận (ôn)", "大家讨论。", "Dàjiā tǎolùn.", "Mọi người thảo luận."),
      v("感动", "gǎndòng", "Cảm động (ôn)", "很感动。", "Hěn gǎndòng.", "Rất cảm động."),
    ],
    grammar: {
      title: "Chỉ tin / lễ",
      pattern: "邀请 / 祝贺 / 恐怕",
      explainVi: "Roleplay bạn mời dự sinh nhật. Khoá từ đến tuần 26.",
      drills: [
        drill("Dịch: Chúc mừng sinh nhật.", "祝贺生日快乐。"),
        drill("Dịch: Rất lịch sự.", "很有礼貌。"),
        drill("Dịch: Mời bạn đến.", "邀请你来。"),
        drill("Dịch: Rất cảm động.", "很感动。"),
      ],
    },
    dialogue: [
      line("A", "我邀请你来我的生日聚会。", "Wǒ yāoqǐng nǐ lái wǒ de shēngrì jùhuì.", "Mời bạn dự tiệc sinh nhật tôi."),
      line("B", "谢谢邀请。祝贺你。", "Xièxie yāoqǐng. Zhùhè nǐ.", "Cảm ơn lời mời. Chúc mừng bạn."),
      line("A", "恐怕人很多。别麻烦带礼物。", "Kǒngpà rén hěn duō. Bié máfan dài lǐwù.", "E rằng đông người. Đừng phiền mang quà."),
      line("B", "不麻烦。我很感动。", "Bù máfan. Wǒ hěn gǎndòng.", "Không phiền. Tôi cảm động lắm."),
    ],
    exercises: [
      ex("Tự viết: Mời bạn dự tiệc sinh nhật.", "邀请你来生日聚会。"),
      ex("Tự viết: Cảm ơn lời mời. Chúc mừng bạn.", "谢谢邀请。祝贺你。"),
    ],
    scenario: "Bạn mời dự sinh nhật: lời mời, chúc mừng, đừng phiền mang quà.",
    start: "我邀请你来我的生日聚会。",
  },
  {
    id: 183,
    theme: "Internet",
    kind: "learn",
    vocab: [
      v("网络", "wǎngluò", "Mạng", "网络很慢。", "Wǎngluò hěn màn.", "Mạng chậm."),
      v("网站", "wǎngzhàn", "Trang web", "请打开网站。", "Qǐng dǎkāi wǎngzhàn.", "Hãy mở trang web."),
      v("密码", "mìmǎ", "Mật khẩu", "请输入密码。", "Qǐng shūrù mìmǎ.", "Hãy nhập mật khẩu."),
      v("登录", "dēnglù", "Đăng nhập", "请登录系统。", "Qǐng dēnglù xìtǒng.", "Hãy đăng nhập hệ thống."),
      v("下载", "xiàzǎi", "Tải xuống", "下载这个文件。", "Xiàzǎi zhège wénjiàn.", "Tải file này."),
    ],
    grammar: {
      title: "登录 + hệ thống",
      pattern: "登录 + N",
      explainVi: "登录: đăng nhập vào hệ thống/trang. 登录系统、登录网站.",
      drills: [
        drill("Dịch: Hãy đăng nhập hệ thống.", "请登录系统。"),
        drill("Dịch: Hãy nhập mật khẩu.", "请输入密码。"),
        drill("Dịch: Tải file này.", "下载这个文件。"),
        drill("Dịch: Mạng chậm.", "网络很慢。"),
      ],
    },
    dialogue: [
      line("A", "请先登录系统，再下载文件。", "Qǐng xiān dēnglù xìtǒng, zài xiàzǎi wénjiàn.", "Đăng nhập hệ thống trước, rồi tải file."),
      line("B", "好。密码是什么？", "Hǎo. Mìmǎ shì shénme?", "Được. Mật khẩu là gì?"),
      line("A", "在网站上看。网络正常吗？", "Zài wǎngzhàn shàng kàn. Wǎngluò zhèngcháng ma?", "Xem trên web. Mạng bình thường không?"),
      line("B", "正常。我已经登录了。", "Zhèngcháng. Wǒ yǐjīng dēnglù le.", "Bình thường. Tôi đăng nhập rồi."),
    ],
    exercises: [
      ex("Tự viết: Hãy đăng nhập rồi tải file.", "请登录，然后下载文件。"),
      ex("Tự viết: Hãy nhập mật khẩu.", "请输入密码。"),
    ],
    scenario: "Đăng nhập hệ thống, nhập mật khẩu, tải tài liệu.",
    start: "请先登录系统，再下载文件。",
  },
  {
    id: 184,
    theme: "Máy tính",
    kind: "learn",
    vocab: [
      v("电脑", "diànnǎo", "Máy tính", "我的电脑坏了。", "Wǒ de diànnǎo huài le.", "Máy tính tôi hỏng."),
      v("软件", "ruǎnjiàn", "Phần mềm", "请安装软件。", "Qǐng ānzhuāng ruǎnjiàn.", "Hãy cài phần mềm."),
      v("打印", "dǎyìn", "In", "请打印报告。", "Qǐng dǎyìn bàogào.", "Hãy in báo cáo."),
      v("发送", "fāsòng", "Gửi", "发送邮件。", "Fāsòng yóujiàn.", "Gửi email."),
      v("收到", "shōudào", "Nhận được", "我收到了。", "Wǒ shōudào le.", "Tôi nhận được rồi."),
    ],
    grammar: {
      title: "发送 + email",
      pattern: "发送 + N",
      explainVi: "发送: gửi đi. 发送邮件、发送文件.",
      drills: [
        drill("Dịch: Hãy in báo cáo.", "请打印报告。"),
        drill("Dịch: Gửi email.", "发送邮件。"),
        drill("Dịch: Tôi nhận được rồi.", "我收到了。"),
        drill("Dịch: Hãy cài phần mềm.", "请安装软件。"),
      ],
    },
    dialogue: [
      line("A", "请打印报告，然后发送邮件。", "Qǐng dǎyìn bàogào, ránhòu fāsòng yóujiàn.", "In báo cáo rồi gửi email."),
      line("B", "好。电脑正常吗？", "Hǎo. Diànnǎo zhèngcháng ma?", "Được. Máy tính bình thường không?"),
      line("A", "正常。软件也更新了。", "Zhèngcháng. Ruǎnjiàn yě gēngxīn le.", "Bình thường. Phần mềm cũng cập nhật rồi."),
      line("B", "发送了。你收到了吗？", "Fāsòng le. Nǐ shōudào le ma?", "Gửi rồi. Bạn nhận được chưa?"),
    ],
    exercises: [
      ex("Tự viết: In báo cáo rồi gửi email.", "打印报告，发送邮件。"),
      ex("Tự viết: Tôi nhận được file rồi.", "我收到文件了。"),
    ],
    scenario: "In và gửi báo cáo cho đồng nghiệp qua email.",
    start: "请打印报告，然后发送邮件。",
  },
  {
    id: 185,
    theme: "Điện thoại",
    kind: "learn",
    vocab: [
      v("视频", "shìpín", "Video", "你看视频了吗？", "Nǐ kàn shìpín le ma?", "Bạn xem video chưa?"),
      v("分享", "fēnxiǎng", "Chia sẻ", "请分享一下。", "Qǐng fēnxiǎng yíxià.", "Hãy chia sẻ."),
      v("联系", "liánxì", "Liên lạc", "请随时联系。", "Qǐng suíshí liánxì.", "Hãy liên lạc bất cứ lúc nào."),
      v("关注", "guānzhù", "Theo dõi", "请关注账号。", "Qǐng guānzhù zhànghào.", "Hãy theo dõi tài khoản."),
      v("更新", "gēngxīn", "Cập nhật", "请更新一下。", "Qǐng gēngxīn yíxià.", "Hãy cập nhật."),
    ],
    grammar: {
      title: "关注 + tài khoản",
      pattern: "关注 + N",
      explainVi: "关注: theo dõi trên mạng. 关注账号、关注新闻.",
      drills: [
        drill("Dịch: Bạn xem video chưa?", "你看视频了吗？"),
        drill("Dịch: Hãy chia sẻ.", "请分享一下。"),
        drill("Dịch: Hãy theo dõi tài khoản.", "请关注账号。"),
        drill("Dịch: Hãy liên lạc bất cứ lúc nào.", "请随时联系。"),
      ],
    },
    dialogue: [
      line("A", "你看那个视频了吗？请分享一下。", "Nǐ kàn nàge shìpín le ma? Qǐng fēnxiǎng yíxià.", "Bạn xem video đó chưa? Chia sẻ nhé."),
      line("B", "看了。请关注公司的账号。", "Kàn le. Qǐng guānzhù gōngsī de zhànghào.", "Rồi. Hãy theo dõi tài khoản công ty."),
      line("A", "好。有消息请随时联系。", "Hǎo. Yǒu xiāoxi qǐng suíshí liánxì.", "Được. Có tin hãy liên lạc."),
      line("B", "请更新一下资料。", "Qǐng gēngxīn yíxià zīliào.", "Hãy cập nhật hồ sơ."),
    ],
    exercises: [
      ex("Tự viết: Xem video rồi chia sẻ.", "看视频，然后分享。"),
      ex("Tự viết: Hãy theo dõi tài khoản công ty.", "请关注公司账号。"),
    ],
    scenario: "Xem video, chia sẻ, theo dõi tài khoản, liên lạc.",
    start: "你看那个视频了吗？请分享一下。",
  },
  {
    id: 186,
    theme: "Mạng",
    kind: "learn",
    vocab: [
      v("评论", "pínglùn", "Bình luận", "请写评论。", "Qǐng xiě pínglùn.", "Hãy viết bình luận."),
      v("点赞", "diǎnzàn", "Thích / like", "请点个赞。", "Qǐng diǎn ge zàn.", "Hãy like."),
      v("收藏", "shōucáng", "Lưu / bookmark", "我收藏了。", "Wǒ shōucáng le.", "Tôi đã lưu."),
      v("搜索", "sōusuǒ", "Tìm kiếm", "请搜索关键词。", "Qǐng sōusuǒ guānjiàncí.", "Hãy tìm từ khóa."),
      v("信息", "xìnxī", "Thông tin", "信息很重要。", "Xìnxī hěn zhòngyào.", "Thông tin quan trọng."),
    ],
    grammar: {
      title: "搜索 + từ khóa",
      pattern: "搜索 + N",
      explainVi: "搜索: tìm trên mạng. 搜索关键词、搜索信息.",
      drills: [
        drill("Dịch: Hãy tìm từ khóa.", "请搜索关键词。"),
        drill("Dịch: Hãy viết bình luận.", "请写评论。"),
        drill("Dịch: Tôi đã lưu.", "我收藏了。"),
        drill("Dịch: Thông tin quan trọng.", "信息很重要。"),
      ],
    },
    dialogue: [
      line("A", "请在网站搜索这个信息。", "Qǐng zài wǎngzhàn sōusuǒ zhège xìnxī.", "Hãy tìm thông tin này trên web."),
      line("B", "找到了。我收藏了。", "Zhǎodào le. Wǒ shōucáng le.", "Tìm thấy rồi. Tôi lưu rồi."),
      line("A", "请写评论，点个赞。", "Qǐng xiě pínglùn, diǎn ge zàn.", "Viết bình luận, like nhé."),
      line("B", "好。这个信息很有用。", "Hǎo. Zhège xìnxī hěn yǒuyòng.", "Được. Thông tin này hữu ích."),
    ],
    exercises: [
      ex("Tự viết: Tìm thông tin trên mạng.", "在网上搜索信息。"),
      ex("Tự viết: Viết bình luận và like.", "写评论，点赞。"),
    ],
    scenario: "Tìm thông tin trên mạng, lưu, bình luận, like.",
    start: "请在网站搜索这个信息。",
  },
  {
    id: 187,
    theme: "Kỹ thuật",
    kind: "learn",
    vocab: [
      v("技术", "jìshù", "Kỹ thuật", "这是新技术。", "Zhè shì xīn jìshù.", "Đây là kỹ thuật mới."),
      v("系统", "xìtǒng", "Hệ thống", "系统有问题。", "Xìtǒng yǒu wèntí.", "Hệ thống có vấn đề."),
      v("正常", "zhèngcháng", "Bình thường", "现在正常了。", "Xiànzài zhèngcháng le.", "Giờ bình thường rồi."),
      v("错误", "cuòwù", "Lỗi", "有一个错误。", "Yǒu yí ge cuòwù.", "Có một lỗi."),
      v("修", "xiū", "Sửa", "请修一下。", "Qǐng xiū yíxià.", "Hãy sửa."),
    ],
    grammar: {
      title: "系统 + adj",
      pattern: "系统 + adj / 有问题",
      explainVi: "Mô tả hệ thống: 系统正常、系统有问题、系统错误.",
      drills: [
        drill("Dịch: Hệ thống có vấn đề.", "系统有问题。"),
        drill("Dịch: Có một lỗi.", "有一个错误。"),
        drill("Dịch: Hãy sửa.", "请修一下。"),
        drill("Dịch: Giờ bình thường rồi.", "现在正常了。"),
      ],
    },
    dialogue: [
      line("A", "我的电脑系统有问题。", "Wǒ de diànnǎo xìtǒng yǒu wèntí.", "Hệ thống máy tôi có vấn đề."),
      line("B", "什么错误？请说一下。", "Shénme cuòwù? Qǐng shuō yíxià.", "Lỗi gì? Nói xem."),
      line("A", "不能登录。请修一下。", "Bù néng dēnglù. Qǐng xiū yíxià.", "Không đăng nhập được. Hãy sửa."),
      line("B", "好。这是新技术，很快就好。", "Hǎo. Zhè shì xīn jìshù, hěn kuài jiù hǎo.", "Được. Kỹ thuật mới, mau xong."),
    ],
    exercises: [
      ex("Tự viết: Hệ thống có lỗi. Hãy sửa.", "系统有错误。请修一下。"),
      ex("Tự viết: Giờ hệ thống bình thường rồi.", "现在系统正常了。"),
    ],
    scenario: "Báo lỗi máy, nhờ IT sửa hệ thống.",
    start: "我的电脑系统有问题。",
  },
  {
    id: 188,
    theme: "Tổng hợp công nghệ",
    kind: "review",
    vocab: [
      v("登录", "dēnglù", "Đăng nhập (ôn)", "请登录。", "Qǐng dēnglù.", "Hãy đăng nhập."),
      v("发送", "fāsòng", "Gửi (ôn)", "发送文件。", "Fāsòng wénjiàn.", "Gửi file."),
      v("下载", "xiàzǎi", "Tải (ôn)", "下载了吗？", "Xiàzǎi le ma?", "Tải chưa?"),
      v("搜索", "sōusuǒ", "Tìm kiếm (ôn)", "搜索一下。", "Sōusuǒ yíxià.", "Tìm thử."),
      v("系统", "xìtǒng", "Hệ thống (ôn)", "系统正常。", "Xìtǒng zhèngcháng.", "Hệ thống bình thường."),
    ],
    grammar: {
      title: "登录 / 发送",
      pattern: "登录 + N；发送 + N",
      explainVi: "Ôn tuần 27: gửi file cho đồng nghiệp, đăng nhập tải tài liệu.",
      drills: [
        drill("Dịch: Hãy đăng nhập.", "请登录。"),
        drill("Dịch: Gửi file.", "发送文件。"),
        drill("Dịch: Tải chưa?", "下载了吗？"),
        drill("Dịch: Hệ thống bình thường.", "系统正常。"),
      ],
    },
    dialogue: [
      line("A", "请先登录，再下载文件。", "Qǐng xiān dēnglù, zài xiàzǎi wénjiàn.", "Đăng nhập trước, rồi tải file."),
      line("B", "下载了。请发送给经理。", "Xiàzǎi le. Qǐng fāsòng gěi jīnglǐ.", "Tải rồi. Gửi cho giám đốc."),
      line("A", "好。系统正常吗？", "Hǎo. Xìtǒng zhèngcháng ma?", "Được. Hệ thống bình thường không?"),
      line("B", "正常。有问题就搜索一下。", "Zhèngcháng. Yǒu wèntí jiù sōusuǒ yíxià.", "Bình thường. Có vấn đề thì tìm thử."),
    ],
    exercises: [
      ex("Tự viết: Đăng nhập rồi tải file.", "登录，然后下载文件。"),
      ex("Tự viết: Gửi file cho đồng nghiệp.", "发送文件给同事。"),
    ],
    scenario: "Gửi file cho đồng nghiệp: đăng nhập, tải, gửi.",
    start: "请先登录，再下载文件。",
  },
  {
    id: 189,
    theme: "IT vs người dùng",
    kind: "review",
    vocab: [
      v("电脑", "diànnǎo", "Máy tính (ôn)", "电脑坏了。", "Diànnǎo huài le.", "Máy hỏng."),
      v("密码", "mìmǎ", "Mật khẩu (ôn)", "忘记密码了。", "Wàngjì mìmǎ le.", "Quên mật khẩu."),
      v("错误", "cuòwù", "Lỗi (ôn)", "有错误。", "Yǒu cuòwù.", "Có lỗi."),
      v("修", "xiū", "Sửa (ôn)", "修好了。", "Xiū hǎo le.", "Sửa xong rồi."),
      v("网络", "wǎngluò", "Mạng (ôn)", "网络很慢。", "Wǎngluò hěn màn.", "Mạng chậm."),
    ],
    grammar: {
      title: "Chỉ mạng / máy",
      pattern: "登录 / 修 / 系统",
      explainVi: "Roleplay IT vs người dùng. Khoá từ đến tuần 27.",
      drills: [
        drill("Dịch: Máy hỏng.", "电脑坏了。"),
        drill("Dịch: Quên mật khẩu.", "忘记密码了。"),
        drill("Dịch: Có lỗi.", "有错误。"),
        drill("Dịch: Sửa xong rồi.", "修好了。"),
      ],
    },
    dialogue: [
      line("A", "IT，我的电脑坏了，网络也很慢。", "IT, wǒ de diànnǎo huài le, wǎngluò yě hěn màn.", "IT, máy tôi hỏng, mạng cũng chậm."),
      line("B", "请说一下错误。密码对吗？", "Qǐng shuō yíxià cuòwù. Mìmǎ duì ma?", "Nói lỗi xem. Mật khẩu đúng không?"),
      line("A", "我忘记密码了。不能登录。", "Wǒ wàngjì mìmǎ le. Bù néng dēnglù.", "Tôi quên mật khẩu. Không đăng nhập được."),
      line("B", "修好了。现在系统正常了。", "Xiū hǎo le. Xiànzài xìtǒng zhèngcháng le.", "Sửa xong. Giờ hệ thống bình thường."),
    ],
    exercises: [
      ex("Tự viết: Máy hỏng, mạng chậm.", "电脑坏了，网络很慢。"),
      ex("Tự viết: Quên mật khẩu, không đăng nhập được.", "忘记密码，不能登录。"),
    ],
    scenario: "Gọi IT: máy hỏng, quên mật khẩu, sửa xong.",
    start: "IT，我的电脑坏了，网络也很慢。",
  },
  {
    id: 190,
    theme: "Thuê",
    kind: "learn",
    vocab: [
      v("租金", "zūjīn", "Tiền thuê", "租金很贵。", "Zūjīn hěn guì.", "Tiền thuê đắt."),
      v("房东", "fángdōng", "Chủ nhà", "房东很热情。", "Fángdōng hěn rèqíng.", "Chủ nhà nhiệt tình."),
      v("顾客", "gùkè", "Khách hàng", "顾客很多。", "Gùkè hěn duō.", "Khách rất nhiều."),
      v("邻居", "línjū", "Hàng xóm", "邻居很友好。", "Línjū hěn yǒuhǎo.", "Hàng xóm thân thiện."),
      v("商量", "shāngliang", "Thương lượng", "跟房东商量。", "Gēn fángdōng shāngliang.", "Thương lượng với chủ nhà."),
    ],
    grammar: {
      title: "跟 + người + 商量",
      pattern: "跟 + N + 商量",
      explainVi: "商量 với ai: 跟房东商量、跟邻居商量.",
      drills: [
        drill("Dịch: Tiền thuê đắt.", "租金很贵。"),
        drill("Dịch: Thương lượng với chủ nhà.", "跟房东商量。"),
        drill("Dịch: Hàng xóm thân thiện.", "邻居很友好。"),
        drill("Dịch: Chủ nhà nhiệt tình.", "房东很热情。"),
      ],
    },
    dialogue: [
      line("A", "我想跟房东商量租金。", "Wǒ xiǎng gēn fángdōng shāngliang zūjīn.", "Tôi muốn thương lượng tiền thuê với chủ nhà."),
      line("B", "租金贵吗？邻居怎么样？", "Zūjīn guì ma? Línjū zěnmeyàng?", "Tiền thuê đắt không? Hàng xóm thế nào?"),
      line("A", "有点贵。邻居很友好。", "Yǒudiǎnr guì. Línjū hěn yǒuhǎo.", "Hơi đắt. Hàng xóm thân thiện."),
      line("B", "跟房东商量一下，也许可以便宜。", "Gēn fángdōng shāngliang yíxià, yěxǔ kěyǐ piányi.", "Thương lượng với chủ nhà, có thể rẻ hơn."),
    ],
    exercises: [
      ex("Tự viết: Tôi muốn thương lượng tiền thuê.", "我想商量租金。"),
      ex("Tự viết: Hàng xóm rất thân thiện.", "邻居很友好。"),
    ],
    scenario: "Thuê nhà: thương lượng tiền thuê với chủ nhà, hỏi hàng xóm.",
    start: "我想跟房东商量租金。",
  },
  {
    id: 191,
    theme: "Điện",
    kind: "learn",
    vocab: [
      v("冰箱", "bīngxiāng", "Tủ lạnh", "冰箱坏了。", "Bīngxiāng huài le.", "Tủ lạnh hỏng."),
      v("空调", "kōngtiáo", "Máy lạnh", "请打开空调。", "Qǐng dǎkāi kōngtiáo.", "Hãy bật máy lạnh."),
      v("洗衣机", "xǐyījī", "Máy giặt", "洗衣机不转了。", "Xǐyījī bù zhuǎn le.", "Máy giặt không quay."),
      v("沙发", "shāfā", "Ghế sofa", "沙发很新。", "Shāfā hěn xīn.", "Sofa rất mới."),
      v("修理", "xiūlǐ", "Sửa chữa", "需要修理。", "Xūyào xiūlǐ.", "Cần sửa."),
    ],
    grammar: {
      title: "需要 + 修理",
      pattern: "需要 + 修理",
      explainVi: "需要修理: cần sửa chữa. 冰箱需要修理.",
      drills: [
        drill("Dịch: Tủ lạnh hỏng.", "冰箱坏了。"),
        drill("Dịch: Máy giặt không quay.", "洗衣机不转了。"),
        drill("Dịch: Cần sửa.", "需要修理。"),
        drill("Dịch: Hãy bật máy lạnh.", "请打开空调。"),
      ],
    },
    dialogue: [
      line("A", "房东，冰箱坏了，需要修理。", "Fángdōng, bīngxiāng huài le, xūyào xiūlǐ.", "Chủ nhà, tủ lạnh hỏng, cần sửa."),
      line("B", "好。空调和洗衣机呢？", "Hǎo. Kōngtiáo hé xǐyījī ne?", "Được. Máy lạnh và máy giặt?"),
      line("A", "空调正常。洗衣机也不转了。", "Kōngtiáo zhèngcháng. Xǐyījī yě bù zhuǎn le.", "Máy lạnh bình thường. Máy giặt cũng không quay."),
      line("B", "我安排人修理。沙发别动。", "Wǒ ānpái rén xiūlǐ. Shāfā bié dòng.", "Tôi sắp người sửa. Đừng động sofa."),
    ],
    exercises: [
      ex("Tự viết: Tủ lạnh hỏng, cần sửa.", "冰箱坏了，需要修理。"),
      ex("Tự viết: Máy giặt không quay.", "洗衣机不转了。"),
    ],
    scenario: "Báo chủ nhà máy hỏng: tủ lạnh, máy giặt cần sửa.",
    start: "房东，冰箱坏了，需要修理。",
  },
  {
    id: 192,
    theme: "Phòng",
    kind: "learn",
    vocab: [
      v("卧室", "wòshì", "Phòng ngủ", "卧室很大。", "Wòshì hěn dà.", "Phòng ngủ rộng."),
      v("厨房", "chúfáng", "Nhà bếp", "厨房很干净。", "Chúfáng hěn gānjìng.", "Bếp rất sạch."),
      v("卫生间", "wèishēngjiān", "Nhà vệ sinh", "卫生间在左边。", "Wèishēngjiān zài zuǒbian.", "Nhà vệ sinh bên trái."),
      v("阳台", "yángtái", "Ban công", "阳台有阳光。", "Yángtái yǒu yángguāng.", "Ban công có nắng."),
      v("垃圾", "lājī", "Rác", "请倒垃圾。", "Qǐng dǎo lājī.", "Hãy đổ rác."),
    ],
    grammar: {
      title: "在 + phòng",
      pattern: "在 + phòng + V",
      explainVi: "在 + phòng: ở/việc trong phòng. 在厨房做饭、在卧室休息.",
      drills: [
        drill("Dịch: Phòng ngủ rộng.", "卧室很大。"),
        drill("Dịch: Bếp rất sạch.", "厨房很干净。"),
        drill("Dịch: Nhà vệ sinh bên trái.", "卫生间在左边。"),
        drill("Dịch: Hãy đổ rác.", "请倒垃圾。"),
      ],
    },
    dialogue: [
      line("A", "欢迎参观。卧室在右边。", "Huānyíng cānguān. Wòshì zài yòubian.", "Hoan nghênh tham quan. Phòng ngủ bên phải."),
      line("B", "厨房和卫生间呢？", "Chúfáng hé wèishēngjiān ne?", "Bếp và nhà vệ sinh?"),
      line("A", "厨房很干净。卫生间在阳台旁边。", "Chúfáng hěn gānjìng. Wèishēngjiān zài yángtái pángbiān.", "Bếp sạch. Nhà vệ sinh cạnh ban công."),
      line("B", "好。垃圾每天倒吗？", "Hǎo. Lājī měitiān dǎo ma?", "Được. Rác đổ hàng ngày à?"),
    ],
    exercises: [
      ex("Tự viết: Phòng ngủ rộng, bếp sạch.", "卧室很大，厨房很干净。"),
      ex("Tự viết: Ban công có nắng.", "阳台有阳光。"),
    ],
    scenario: "Mô tả căn hộ: phòng ngủ, bếp, nhà vệ sinh, ban công.",
    start: "欢迎参观。卧室在右边。",
  },
  {
    id: 193,
    theme: "Sinh hoạt",
    kind: "learn",
    vocab: [
      v("打扫", "dǎsǎo", "Dọn dẹp", "请打扫房间。", "Qǐng dǎsǎo fángjiān.", "Hãy dọn phòng."),
      v("收拾", "shōushi", "Thu dọn", "请收拾一下。", "Qǐng shōushi yíxià.", "Hãy thu dọn."),
      v("节约", "jiéyuē", "Tiết kiệm", "要节约用水。", "Yào jiéyuē yòng shuǐ.", "Phải tiết kiệm nước."),
      v("爱护", "àihù", "Bảo vệ / giữ gìn", "要爱护家具。", "Yào àihù jiājù.", "Phải giữ gìn đồ nội thất."),
      v("定期", "dìngqī", "Định kỳ", "定期检查。", "Dìngqī jiǎnchá.", "Kiểm tra định kỳ."),
    ],
    grammar: {
      title: "定期 + V",
      pattern: "定期 + V",
      explainVi: "定期: đều đặn theo chu kỳ. 定期打扫、定期检查.",
      drills: [
        drill("Dịch: Hãy dọn phòng.", "请打扫房间。"),
        drill("Dịch: Phải tiết kiệm nước.", "要节约用水。"),
        drill("Dịch: Phải giữ gìn đồ nội thất.", "要爱护家具。"),
        drill("Dịch: Kiểm tra định kỳ.", "定期检查。"),
      ],
    },
    dialogue: [
      line("A", "请打扫厨房，收拾阳台。", "Qǐng dǎsǎo chúfáng, shōushi yángtái.", "Dọn bếp, thu dọn ban công."),
      line("B", "好。要节约用水吗？", "Hǎo. Yào jiéyuē yòng shuǐ ma?", "Được. Tiết kiệm nước không?"),
      line("A", "对。也要爱护家具，定期检查。", "Duì. Yě yào àihù jiājù, dìngqī jiǎnchá.", "Đúng. Cũng giữ gìn đồ, kiểm tra định kỳ."),
      line("B", "明白。垃圾我也倒了。", "Míngbai. Lājī wǒ yě dǎo le.", "Hiểu rồi. Rác tôi cũng đổ rồi."),
    ],
    exercises: [
      ex("Tự viết: Dọn phòng, thu dọn ban công.", "打扫房间，收拾阳台。"),
      ex("Tự viết: Tiết kiệm nước, giữ gìn đồ.", "节约用水，爱护家具。"),
    ],
    scenario: "Dọn dẹp nhà, tiết kiệm, giữ gìn đồ, kiểm tra định kỳ.",
    start: "请打扫厨房，收拾阳台。",
  },
  {
    id: 194,
    theme: "An toàn",
    kind: "learn",
    vocab: [
      v("安全", "ānquán", "An toàn", "这里很安全。", "Zhèlǐ hěn ānquán.", "Ở đây rất an toàn."),
      v("危险", "wēixiǎn", "Nguy hiểm", "这很危险。", "Zhè hěn wēixiǎn.", "Cái này nguy hiểm."),
      v("火", "huǒ", "Lửa", "小心火。", "Xiǎoxīn huǒ.", "Cẩn thận lửa."),
      v("灯", "dēng", "Đèn", "请关灯。", "Qǐng guān dēng.", "Hãy tắt đèn."),
      v("检查", "jiǎnchá", "Kiểm tra", "请检查煤气。", "Qǐng jiǎnchá méiqì.", "Hãy kiểm tra gas."),
    ],
    grammar: {
      title: "检查 + thiết bị",
      pattern: "检查 + N",
      explainVi: "检查: kiểm tra thiết bị/an toàn. 检查煤气、检查电.",
      drills: [
        drill("Dịch: Ở đây rất an toàn.", "这里很安全。"),
        drill("Dịch: Cái này nguy hiểm.", "这很危险。"),
        drill("Dịch: Hãy kiểm tra gas.", "请检查煤气。"),
        drill("Dịch: Hãy tắt đèn.", "请关灯。"),
      ],
    },
    dialogue: [
      line("A", "离开前请检查煤气和灯。", "Líkāi qián qǐng jiǎnchá méiqì hé dēng.", "Trước khi đi hãy kiểm tra gas và đèn."),
      line("B", "好。火关了吗？", "Hǎo. Huǒ guān le ma?", "Được. Lửa tắt chưa?"),
      line("A", "关了。这里安全，不危险。", "Guān le. Zhèlǐ ānquán, bù wēixiǎn.", "Tắt rồi. Ở đây an toàn, không nguy hiểm."),
      line("B", "请定期检查一下。", "Qǐng dìngqī jiǎnchá yíxià.", "Hãy kiểm tra định kỳ."),
    ],
    exercises: [
      ex("Tự viết: Trước khi đi kiểm tra gas, tắt đèn.", "离开前检查煤气，关灯。"),
      ex("Tự viết: Cẩn thận lửa.", "小心火。"),
    ],
    scenario: "Kiểm tra an toàn: gas, đèn, lửa trước khi ra ngoài.",
    start: "离开前请检查煤气和灯。",
  },
  {
    id: 195,
    theme: "Tổng hợp nhà ở",
    kind: "review",
    vocab: [
      v("商量", "shāngliang", "Thương lượng (ôn)", "跟房东商量。", "Gēn fángdōng shāngliang.", "Thương lượng với chủ nhà."),
      v("修理", "xiūlǐ", "Sửa chữa (ôn)", "需要修理。", "Xūyào xiūlǐ.", "Cần sửa."),
      v("冰箱", "bīngxiāng", "Tủ lạnh (ôn)", "冰箱坏了。", "Bīngxiāng huài le.", "Tủ lạnh hỏng."),
      v("打扫", "dǎsǎo", "Dọn dẹp (ôn)", "打扫房间。", "Dǎsǎo fángjiān.", "Dọn phòng."),
      v("检查", "jiǎnchá", "Kiểm tra (ôn)", "检查煤气。", "Jiǎnchá méiqì.", "Kiểm tra gas."),
    ],
    grammar: {
      title: "商量 / 修理",
      pattern: "跟 + N + 商量；需要 + 修理",
      explainVi: "Ôn tuần 28: báo chủ nhà máy lạnh hỏng, dọn dẹp an toàn.",
      drills: [
        drill("Dịch: Thương lượng với chủ nhà.", "跟房东商量。"),
        drill("Dịch: Tủ lạnh hỏng, cần sửa.", "冰箱坏了，需要修理。"),
        drill("Dịch: Dọn phòng.", "打扫房间。"),
        drill("Dịch: Kiểm tra gas.", "检查煤气。"),
      ],
    },
    dialogue: [
      line("A", "房东，空调坏了，需要修理。", "Fángdōng, kōngtiáo huài le, xūyào xiūlǐ.", "Chủ nhà, máy lạnh hỏng, cần sửa."),
      line("B", "好。我跟工人商量一下。", "Hǎo. Wǒ gēn gōngrén shāngliang yíxià.", "Được. Tôi thương lượng với thợ."),
      line("A", "谢谢。我也打扫了房间。", "Xièxie. Wǒ yě dǎsǎo le fángjiān.", "Cảm ơn. Tôi cũng dọn phòng rồi."),
      line("B", "很好。离开前请检查煤气。", "Hěn hǎo. Líkāi qián qǐng jiǎnchá méiqì.", "Tốt. Trước khi đi hãy kiểm tra gas."),
    ],
    exercises: [
      ex("Tự viết: Máy lạnh hỏng, cần sửa.", "空调坏了，需要修理。"),
      ex("Tự viết: Trước khi đi kiểm tra gas.", "离开前检查煤气。"),
    ],
    scenario: "Báo chủ nhà máy lạnh hỏng, dọn phòng, kiểm tra an toàn.",
    start: "房东，空调坏了，需要修理。",
  },
  {
    id: 196,
    theme: "Hàng xóm vs chủ nhà",
    kind: "review",
    vocab: [
      v("邻居", "línjū", "Hàng xóm (ôn)", "邻居很好。", "Línjū hěn hǎo.", "Hàng xóm tốt."),
      v("租金", "zūjīn", "Tiền thuê (ôn)", "租金多少？", "Zūjīn duōshao?", "Tiền thuê bao nhiêu?"),
      v("阳台", "yángtái", "Ban công (ôn)", "阳台很大。", "Yángtái hěn dà.", "Ban công rộng."),
      v("节约", "jiéyuē", "Tiết kiệm (ôn)", "要节约。", "Yào jiéyuē.", "Phải tiết kiệm."),
      v("安全", "ānquán", "An toàn (ôn)", "很安全。", "Hěn ānquán.", "Rất an toàn."),
    ],
    grammar: {
      title: "Chỉ thuê / sửa",
      pattern: "商量 / 修理 / 爱护",
      explainVi: "Roleplay hàng xóm vs chủ nhà. Khoá từ đến tuần 28.",
      drills: [
        drill("Dịch: Hàng xóm tốt.", "邻居很好。"),
        drill("Dịch: Tiền thuê bao nhiêu?", "租金多少？"),
        drill("Dịch: Ban công rộng.", "阳台很大。"),
        drill("Dịch: Rất an toàn.", "很安全。"),
      ],
    },
    dialogue: [
      line("A", "邻居，这里的租金贵吗？", "Línjū, zhèlǐ de zūjīn guì ma?", "Hàng xóm, tiền thuê đắt không?"),
      line("B", "有点贵。但房东很好，很安全。", "Yǒudiǎnr guì. Dàn fángdōng hěn hǎo, hěn ānquán.", "Hơi đắt. Nhưng chủ nhà tốt, an toàn."),
      line("A", "阳台可以收拾吗？", "Yángtái kěyǐ shōushi ma?", "Ban công thu dọn được không?"),
      line("B", "可以。要节约用水，爱护家具。", "Kěyǐ. Yào jiéyuē yòng shuǐ, àihù jiājù.", "Được. Tiết kiệm nước, giữ gìn đồ."),
    ],
    exercises: [
      ex("Tự viết: Tiền thuê hơi đắt nhưng an toàn.", "租金有点贵，但很安全。"),
      ex("Tự viết: Tiết kiệm nước, giữ gìn đồ.", "节约用水，爱护家具。"),
    ],
    scenario: "Hàng xóm tư vấn thuê nhà: tiền thuê, an toàn, sinh hoạt.",
    start: "邻居，这里的租金贵吗？",
  },
  {
    id: 197,
    theme: "Chi phí",
    kind: "learn",
    vocab: [
      v("费用", "fèiyòng", "Chi phí", "费用是多少？", "Fèiyòng shì duōshao?", "Chi phí bao nhiêu?"),
      v("预算", "yùsuàn", "Ngân sách", "我的预算不多。", "Wǒ de yùsuàn bù duō.", "Ngân sách tôi không nhiều."),
      v("省", "shěng", "Tiết kiệm", "可以省一点。", "Kěyǐ shěng yìdiǎn.", "Có thể tiết kiệm chút."),
      v("浪费", "làngfèi", "Lãng phí", "别浪费钱。", "Bié làngfèi qián.", "Đừng lãng phí tiền."),
      v("值得", "zhíde", "Đáng", "值得去。", "Zhíde qù.", "Đáng đi."),
    ],
    grammar: {
      title: "值得 + V",
      pattern: "值得 + V",
      explainVi: "值得: đáng làm/đi. 值得去、值得购买.",
      drills: [
        drill("Dịch: Chi phí bao nhiêu?", "费用是多少？"),
        drill("Dịch: Ngân sách tôi không nhiều.", "我的预算不多。"),
        drill("Dịch: Đáng đi.", "值得去。"),
        drill("Dịch: Đừng lãng phí tiền.", "别浪费钱。"),
      ],
    },
    dialogue: [
      line("A", "这次旅行的费用是多少？", "Zhè cì lǚxíng de fèiyòng shì duōshao?", "Chi phí chuyến đi bao nhiêu?"),
      line("B", "不多。在我的预算里。", "Bù duō. Zài wǒ de yùsuàn lǐ.", "Không nhiều. Trong ngân sách tôi."),
      line("A", "值得去吗？", "Zhíde qù ma?", "Có đáng đi không?"),
      line("B", "值得。可以省一点，别浪费。", "Zhíde. Kěyǐ shěng yìdiǎn, bié làngfèi.", "Đáng. Tiết kiệm chút, đừng lãng phí."),
    ],
    exercises: [
      ex("Tự viết: Chi phí không nhiều, trong ngân sách.", "费用不多，在预算里。"),
      ex("Tự viết: Đáng đi. Đừng lãng phí tiền.", "值得去。别浪费钱。"),
    ],
    scenario: "Hỏi chi phí du lịch, ngân sách, có đáng đi không.",
    start: "这次旅行的费用是多少？",
  },
  {
    id: 198,
    theme: "Điểm",
    kind: "learn",
    vocab: [
      v("著名", "zhùmíng", "Nổi tiếng", "这是著名景点。", "Zhè shì zhùmíng jǐngdiǎn.", "Đây là điểm nổi tiếng."),
      v("风景", "fēngjǐng", "Phong cảnh", "风景很美。", "Fēngjǐng hěn měi.", "Cảnh đẹp."),
      v("参观", "cānguān", "Tham quan (ôn)", "欢迎参观。", "Huānyíng cānguān.", "Hoan nghênh tham quan."),
      v("纪念品", "jìniànpǐn", "Quà lưu niệm", "买纪念品。", "Mǎi jìniànpǐn.", "Mua quà lưu niệm."),
      v("适合", "shìhé", "Phù hợp (ôn)", "适合旅游。", "Shìhé lǚyóu.", "Phù hợp du lịch."),
    ],
    grammar: {
      title: "适合 + du lịch",
      pattern: "适合 + N / V",
      explainVi: "适合 du lịch: phù hợp đi chơi. 这个地方适合旅游.",
      drills: [
        drill("Dịch: Đây là điểm nổi tiếng.", "这是著名景点。"),
        drill("Dịch: Cảnh đẹp.", "风景很美。"),
        drill("Dịch: Phù hợp du lịch.", "适合旅游。"),
        drill("Dịch: Mua quà lưu niệm.", "买纪念品。"),
      ],
    },
    dialogue: [
      line("A", "这个地方著名吗？风景怎么样？", "Zhège dìfang zhùmíng ma? Fēngjǐng zěnmeyàng?", "Chỗ này nổi tiếng không? Cảnh thế nào?"),
      line("B", "很著名。风景很美，适合旅游。", "Hěn zhùmíng. Fēngjǐng hěn měi, shìhé lǚyóu.", "Rất nổi tiếng. Cảnh đẹp, phù hợp du lịch."),
      line("A", "欢迎参观。可以买纪念品。", "Huānyíng cānguān. Kěyǐ mǎi jìniànpǐn.", "Hoan nghênh tham quan. Có thể mua quà."),
      line("B", "好。值得来。", "Hǎo. Zhíde lái.", "Được. Đáng đến."),
    ],
    exercises: [
      ex("Tự viết: Điểm nổi tiếng, cảnh đẹp.", "著名景点，风景很美。"),
      ex("Tự viết: Phù hợp du lịch, mua quà lưu niệm.", "适合旅游，买纪念品。"),
    ],
    scenario: "Chọn điểm tham quan: nổi tiếng, cảnh đẹp, quà lưu niệm.",
    start: "这个地方著名吗？风景怎么样？",
  },
  {
    id: 199,
    theme: "Phương tiện",
    kind: "learn",
    vocab: [
      v("航班", "hángbān", "Chuyến bay", "航班几点？", "Hángbān jǐ diǎn?", "Chuyến bay mấy giờ?"),
      v("乘客", "chéngkè", "Hành khách", "乘客很多。", "Chéngkè hěn duō.", "Hành khách rất đông."),
      v("停车", "tíngchē", "Đỗ xe", "这里可以停车。", "Zhèlǐ kěyǐ tíngchē.", "Ở đây đỗ xe được."),
      v("加油", "jiāyóu", "Đổ xăng", "请加油。", "Qǐng jiāyóu.", "Hãy đổ xăng."),
      v("堵车", "dǔchē", "Kẹt xe", "路上堵车了。", "Lù shàng dǔchē le.", "Đường kẹt xe rồi."),
    ],
    grammar: {
      title: "堵车 + 了",
      pattern: "堵车 + 了",
      explainVi: "堵车了: đang/đã kẹt xe. 路上堵车了.",
      drills: [
        drill("Dịch: Chuyến bay mấy giờ?", "航班几点？"),
        drill("Dịch: Ở đây đỗ xe được.", "这里可以停车。"),
        drill("Dịch: Đường kẹt xe rồi.", "路上堵车了。"),
        drill("Dịch: Hãy đổ xăng.", "请加油。"),
      ],
    },
    dialogue: [
      line("A", "去机场，航班几点？", "Qù jīchǎng, hángbān jǐ diǎn?", "Đi sân bay, chuyến bay mấy giờ?"),
      line("B", "十点。但现在堵车了。", "Shí diǎn. Dàn xiànzài dǔchē le.", "10 giờ. Nhưng giờ kẹt xe."),
      line("A", "怎么办？先加油吗？", "Zěnme bàn? Xiān jiāyóu ma?", "Làm sao? Đổ xăng trước không?"),
      line("B", "对。前面可以停车加油。", "Duì. Qiánmiàn kěyǐ tíngchē jiāyóu.", "Đúng. Phía trước đỗ xe đổ xăng được."),
    ],
    exercises: [
      ex("Tự viết: Chuyến bay 10 giờ. Đường kẹt xe.", "航班十点。路上堵车了。"),
      ex("Tự viết: Phía trước đỗ xe đổ xăng được.", "前面可以停车加油。"),
    ],
    scenario: "Đi sân bay: giờ bay, kẹt xe, đổ xăng.",
    start: "去机场，航班几点？",
  },
  {
    id: 200,
    theme: "Khách sạn",
    kind: "learn",
    vocab: [
      v("预定", "yùdìng", "Đặt trước", "我预定了房间。", "Wǒ yùdìng le fángjiān.", "Tôi đặt phòng rồi."),
      v("服务", "fúwù", "Dịch vụ", "服务很好。", "Fúwù hěn hǎo.", "Dịch vụ tốt."),
      v("行李", "xíngli", "Hành lý", "行李在这儿。", "Xíngli zài zhèr.", "Hành lý ở đây."),
      v("导游", "dǎoyóu", "Hướng dẫn viên", "导游在等你。", "Dǎoyóu zài děng nǐ.", "Hướng dẫn viên đợi bạn."),
      v("安排", "ānpái", "Sắp xếp (ôn)", "经理安排了。", "Jīnglǐ ānpái le.", "Giám đốc sắp xếp rồi."),
    ],
    grammar: {
      title: "预定 + phòng",
      pattern: "预定 + N",
      explainVi: "预定: đặt trước. 预定房间、预定航班.",
      drills: [
        drill("Dịch: Tôi đặt phòng rồi.", "我预定了房间。"),
        drill("Dịch: Dịch vụ tốt.", "服务很好。"),
        drill("Dịch: Hành lý ở đây.", "行李在这儿。"),
        drill("Dịch: Hướng dẫn viên đợi bạn.", "导游在等你。"),
      ],
    },
    dialogue: [
      line("A", "你好，我预定了房间。", "Nǐ hǎo, wǒ yùdìng le fángjiān.", "Xin chào, tôi đặt phòng rồi."),
      line("B", "欢迎。请把行李放这儿。服务有问题请说。", "Huānyíng. Qǐng bǎ xíngli fàng zhèr. Fúwù yǒu wèntí qǐng shuō.", "Hoan nghênh. Để hành lý đây. Dịch vụ có vấn đề hãy nói."),
      line("A", "好。导游什么时候来？", "Hǎo. Dǎoyóu shénme shíhou lái?", "Được. Hướng dẫn viên khi nào đến?"),
      line("B", "九点。公司已经安排好了。", "Jiǔ diǎn. Gōngsī yǐjīng ānpái hǎo le.", "9 giờ. Công ty sắp xếp rồi."),
    ],
    exercises: [
      ex("Tự viết: Tôi đặt phòng rồi. Hành lý ở đây.", "我预定了房间。行李在这儿。"),
      ex("Tự viết: Hướng dẫn viên 9 giờ đến.", "导游九点来。"),
    ],
    scenario: "Đặt phòng khách sạn, gặp hướng dẫn viên, hành lý.",
    start: "你好，我预定了房间。",
  },
  {
    id: 201,
    theme: "Phong tục",
    kind: "learn",
    vocab: [
      v("当地", "dāngdì", "Địa phương", "当地的习惯。", "Dāngdì de xíguàn.", "Thói quen địa phương."),
      v("传统", "chuántǒng", "Truyền thống", "这是传统。", "Zhè shì chuántǒng.", "Đây là truyền thống."),
      v("体验", "tǐyàn", "Trải nghiệm", "我想体验一下。", "Wǒ xiǎng tǐyàn yíxià.", "Tôi muốn trải nghiệm."),
      v("了解", "liǎojiě", "Tìm hiểu (ôn)", "想了解文化。", "Xiǎng liǎojiě wénhuà.", "Muốn hiểu văn hóa."),
      v("专门", "zhuānmén", "Đặc biệt (ôn)", "专门来学习。", "Zhuānmén lái xuéxí.", "Đến đặc biệt để học."),
    ],
    grammar: {
      title: "体验 + hoạt động",
      pattern: "体验 + N / V",
      explainVi: "体验: trải nghiệm trực tiếp. 体验文化、体验当地生活.",
      drills: [
        drill("Dịch: Thói quen địa phương.", "当地的习惯。"),
        drill("Dịch: Đây là truyền thống.", "这是传统。"),
        drill("Dịch: Tôi muốn trải nghiệm.", "我想体验一下。"),
        drill("Dịch: Muốn hiểu văn hóa.", "想了解文化。"),
      ],
    },
    dialogue: [
      line("A", "我想了解当地的传统。", "Wǒ xiǎng liǎojiě dāngdì de chuántǒng.", "Tôi muốn hiểu truyền thống địa phương."),
      line("B", "好。你可以体验一下。", "Hǎo. Nǐ kěyǐ tǐyàn yíxià.", "Được. Bạn có thể trải nghiệm."),
      line("A", "这是专门的活动吗？", "Zhè shì zhuānmén de huódòng ma?", "Đây là hoạt động đặc biệt à?"),
      line("B", "对。值得参加，可以了解文化。", "Duì. Zhíde cānjiā, kěyǐ liǎojiě wénhuà.", "Đúng. Đáng tham gia, hiểu văn hóa."),
    ],
    exercises: [
      ex("Tự viết: Muốn hiểu truyền thống địa phương.", "想了解当地传统。"),
      ex("Tự viết: Trải nghiệm văn hóa, đáng tham gia.", "体验文化，值得参加。"),
    ],
    scenario: "Trải nghiệm văn hóa địa phương, tìm hiểu truyền thống.",
    start: "我想了解当地的传统。",
  },
  {
    id: 202,
    theme: "Tổng hợp du lịch",
    kind: "review",
    vocab: [
      v("值得", "zhíde", "Đáng (ôn)", "值得去。", "Zhíde qù.", "Đáng đi."),
      v("当地", "dāngdì", "Địa phương (ôn)", "当地文化。", "Dāngdì wénhuà.", "Văn hóa địa phương."),
      v("预定", "yùdìng", "Đặt trước (ôn)", "预定房间。", "Yùdìng fángjiān.", "Đặt phòng."),
      v("堵车", "dǔchē", "Kẹt xe (ôn)", "堵车了。", "Dǔchē le.", "Kẹt xe rồi."),
      v("风景", "fēngjǐng", "Phong cảnh (ôn)", "风景很美。", "Fēngjǐng hěn měi.", "Cảnh đẹp."),
    ],
    grammar: {
      title: "值得 / 当地",
      pattern: "值得 + V；当地 + N",
      explainVi: "Ôn tuần 29: lên lịch cuối tuần, chọn điểm đáng đi.",
      drills: [
        drill("Dịch: Đáng đi.", "值得去。"),
        drill("Dịch: Văn hóa địa phương.", "当地文化。"),
        drill("Dịch: Đặt phòng.", "预定房间。"),
        drill("Dịch: Cảnh đẹp.", "风景很美。"),
      ],
    },
    dialogue: [
      line("A", "周末去哪儿？值得去吗？", "Zhōumò qù nǎr? Zhíde qù ma?", "Cuối tuần đi đâu? Đáng đi không?"),
      line("B", "去著名景点。风景很美，值得。", "Qù zhùmíng jǐngdiǎn. Fēngjǐng hěn měi, zhíde.", "Đi điểm nổi tiếng. Cảnh đẹp, đáng."),
      line("A", "好。我先预定房间。", "Hǎo. Wǒ xiān yùdìng fángjiān.", "Được. Tôi đặt phòng trước."),
      line("B", "别堵车。早点出发。", "Bié dǔchē. Zǎodiǎn chūfā.", "Đừng kẹt xe. Xuất phát sớm."),
    ],
    exercises: [
      ex("Tự viết: Cuối tuần đi điểm nổi tiếng, đáng đi.", "周末去著名景点，值得。"),
      ex("Tự viết: Đặt phòng trước, xuất phát sớm.", "先预定房间，早点出发。"),
    ],
    scenario: "Lên lịch cuối tuần: chọn điểm, đặt phòng, tránh kẹt xe.",
    start: "周末去哪儿？值得去吗？",
  },
  {
    id: 203,
    theme: "Du khách vs hướng dẫn",
    kind: "review",
    vocab: [
      v("导游", "dǎoyóu", "Hướng dẫn (ôn)", "导游你好。", "Dǎoyóu nǐ hǎo.", "Hướng dẫn xin chào."),
      v("体验", "tǐyàn", "Trải nghiệm (ôn)", "想体验文化。", "Xiǎng tǐyàn wénhuà.", "Muốn trải nghiệm văn hóa."),
      v("纪念品", "jìniànpǐn", "Quà lưu niệm (ôn)", "买纪念品。", "Mǎi jìniànpǐn.", "Mua quà."),
      v("费用", "fèiyòng", "Chi phí (ôn)", "费用多少？", "Fèiyòng duōshao?", "Chi phí bao nhiêu?"),
      v("航班", "hángbān", "Chuyến bay (ôn)", "航班改了。", "Hángbān gǎi le.", "Chuyến bay đổi rồi."),
    ],
    grammar: {
      title: "Chỉ du lịch",
      pattern: "预定 / 体验 / 值得",
      explainVi: "Roleplay du khách vs hướng dẫn. Khoá từ đến tuần 29.",
      drills: [
        drill("Dịch: Muốn trải nghiệm văn hóa.", "想体验文化。"),
        drill("Dịch: Mua quà lưu niệm.", "买纪念品。"),
        drill("Dịch: Chi phí bao nhiêu?", "费用多少？"),
        drill("Dịch: Chuyến bay đổi rồi.", "航班改了。"),
      ],
    },
    dialogue: [
      line("A", "导游，我想体验当地文化。", "Dǎoyóu, wǒ xiǎng tǐyàn dāngdì wénhuà.", "Hướng dẫn, tôi muốn trải nghiệm văn hóa địa phương."),
      line("B", "好。参观后可以买纪念品。", "Hǎo. Cānguān hòu kěyǐ mǎi jìniànpǐn.", "Được. Tham quan xong mua quà."),
      line("A", "费用包括什么？", "Fèiyòng bāokuò shénme?", "Chi phí gồm gì?"),
      line("B", "包括导游和服务。值得参加。", "Bāokuò dǎoyóu hé fúwù. Zhíde cānjiā.", "Gồm hướng dẫn và dịch vụ. Đáng tham gia."),
    ],
    exercises: [
      ex("Tự viết: Muốn trải nghiệm văn hóa địa phương.", "想体验当地文化。"),
      ex("Tự viết: Chi phí gồm hướng dẫn và dịch vụ.", "费用包括导游和服务。"),
    ],
    scenario: "Du khách hỏi hướng dẫn: trải nghiệm văn hóa, chi phí, quà lưu niệm.",
    start: "导游，我想体验当地文化。",
  },
  {
    id: 204,
    theme: "Bảo hiểm",
    kind: "learn",
    vocab: [
      v("保险", "bǎoxiǎn", "Bảo hiểm", "我有保险。", "Wǒ yǒu bǎoxiǎn.", "Tôi có bảo hiểm."),
      v("治疗", "zhìliáo", "Điều trị", "需要治疗。", "Xūyào zhìliáo.", "Cần điều trị."),
      v("恢复", "huīfù", "Hồi phục", "恢复很快。", "Huīfù hěn kuài.", "Hồi phục nhanh."),
      v("定期", "dìngqī", "Định kỳ (ôn)", "定期体检。", "Dìngqī tǐjiǎn.", "Khám định kỳ."),
      v("检查", "jiǎnchá", "Kiểm tra (ôn)", "请检查身体。", "Qǐng jiǎnchá shēntǐ.", "Hãy kiểm tra sức khỏe."),
    ],
    grammar: {
      title: "定期 + khám",
      pattern: "定期 + V",
      explainVi: "定期体检: khám sức khỏe định kỳ. 定期检查.",
      drills: [
        drill("Dịch: Tôi có bảo hiểm.", "我有保险。"),
        drill("Dịch: Cần điều trị.", "需要治疗。"),
        drill("Dịch: Khám định kỳ.", "定期体检。"),
        drill("Dịch: Hồi phục nhanh.", "恢复很快。"),
      ],
    },
    dialogue: [
      line("A", "你有保险吗？请定期检查。", "Nǐ yǒu bǎoxiǎn ma? Qǐng dìngqī jiǎnchá.", "Bạn có bảo hiểm không? Hãy khám định kỳ."),
      line("B", "有。我定期体检。", "Yǒu. Wǒ dìngqī tǐjiǎn.", "Có. Tôi khám định kỳ."),
      line("A", "如果需要治疗，别担心。", "Rúguǒ xūyào zhìliáo, bié dānxīn.", "Nếu cần điều trị, đừng lo."),
      line("B", "好。上次恢复很快。", "Hǎo. Shàng cì huīfù hěn kuài.", "Được. Lần trước hồi phục nhanh."),
    ],
    exercises: [
      ex("Tự viết: Có bảo hiểm, khám định kỳ.", "有保险，定期体检。"),
      ex("Tự viết: Cần điều trị, hồi phục nhanh.", "需要治疗，恢复很快。"),
    ],
    scenario: "Khám định kỳ: bảo hiểm, kiểm tra sức khỏe, điều trị.",
    start: "你有保险吗？请定期检查。",
  },
  {
    id: 205,
    theme: "Tập",
    kind: "learn",
    vocab: [
      v("锻炼", "duànliàn", "Tập luyện", "要多锻炼。", "Yào duō duànliàn.", "Phải tập nhiều."),
      v("效果", "xiàoguǒ", "Hiệu quả", "效果很好。", "Xiàoguǒ hěn hǎo.", "Hiệu quả tốt."),
      v("坚持", "jiānchí", "Kiên trì", "要坚持。", "Yào jiānchí.", "Phải kiên trì."),
      v("营养", "yíngyǎng", "Dinh dưỡng", "注意营养。", "Zhùyì yíngyǎng.", "Chú ý dinh dưỡng."),
      v("平衡", "pínghéng", "Cân bằng", "保持平衡。", "Bǎochí pínghéng.", "Giữ cân bằng."),
    ],
    grammar: {
      title: "坚持 + V",
      pattern: "坚持 + V",
      explainVi: "坚持: kiên trì làm việc. 坚持锻炼、坚持学习.",
      drills: [
        drill("Dịch: Phải tập nhiều.", "要多锻炼。"),
        drill("Dịch: Phải kiên trì.", "要坚持。"),
        drill("Dịch: Hiệu quả tốt.", "效果很好。"),
        drill("Dịch: Chú ý dinh dưỡng.", "注意营养。"),
      ],
    },
    dialogue: [
      line("A", "你坚持锻炼吗？", "Nǐ jiānchí duànliàn ma?", "Bạn kiên trì tập không?"),
      line("B", "坚持。效果很好。", "Jiānchí. Xiàoguǒ hěn hǎo.", "Có. Hiệu quả tốt."),
      line("A", "也要注意营养，保持平衡。", "Yě yào zhùyì yíngyǎng, bǎochí pínghéng.", "Cũng chú ý dinh dưỡng, giữ cân bằng."),
      line("B", "对。医生也这么说。", "Duì. Yīshēng yě zhème shuō.", "Đúng. Bác sĩ cũng nói vậy."),
    ],
    exercises: [
      ex("Tự viết: Kiên trì tập, hiệu quả tốt.", "坚持锻炼，效果很好。"),
      ex("Tự viết: Chú ý dinh dưỡng, giữ cân bằng.", "注意营养，保持平衡。"),
    ],
    scenario: "Tập thể dục đều: kiên trì, dinh dưỡng, cân bằng.",
    start: "你坚持锻炼吗？",
  },
  {
    id: 206,
    theme: "Ô nhiễm",
    kind: "learn",
    vocab: [
      v("污染", "wūrǎn", "Ô nhiễm", "污染很严重。", "Wūrǎn hěn yánzhòng.", "Ô nhiễm nghiêm trọng."),
      v("噪音", "zàoyīn", "Tiếng ồn", "噪音太大。", "Zàoyīn tài dà.", "Tiếng ồn quá lớn."),
      v("保护", "bǎohù", "Bảo vệ", "要保护环境。", "Yào bǎohù huánjìng.", "Phải bảo vệ môi trường."),
      v("减少", "jiǎnshǎo", "Giảm", "减少污染。", "Jiǎnshǎo wūrǎn.", "Giảm ô nhiễm."),
      v("禁止", "jìnzhǐ", "Cấm", "这里禁止吸烟。", "Zhèlǐ jìnzhǐ xīyān.", "Ở đây cấm hút thuốc."),
    ],
    grammar: {
      title: "减少 + N",
      pattern: "减少 + N",
      explainVi: "减少: làm ít đi. 减少污染、减少浪费.",
      drills: [
        drill("Dịch: Ô nhiễm nghiêm trọng.", "污染很严重。"),
        drill("Dịch: Giảm ô nhiễm.", "减少污染。"),
        drill("Dịch: Phải bảo vệ môi trường.", "要保护环境。"),
        drill("Dịch: Ở đây cấm hút thuốc.", "这里禁止吸烟。"),
      ],
    },
    dialogue: [
      line("A", "这里的污染怎么样？", "Zhèlǐ de wūrǎn zěnmeyàng?", "Ô nhiễm ở đây thế nào?"),
      line("B", "很严重。噪音也大。", "Hěn yánzhòng. Zàoyīn yě dà.", "Rất nghiêm trọng. Tiếng ồn cũng lớn."),
      line("A", "我们要减少污染，保护环境。", "Wǒmen yào jiǎnshǎo wūrǎn, bǎohù huánjìng.", "Chúng ta phải giảm ô nhiễm, bảo vệ môi trường."),
      line("B", "对。这里也禁止乱扔垃圾。", "Duì. Zhèlǐ yě jìnzhǐ luàn rēng lājī.", "Đúng. Ở đây cũng cấm vứt rác bừa."),
    ],
    exercises: [
      ex("Tự viết: Ô nhiễm nghiêm trọng, tiếng ồn lớn.", "污染严重，噪音大。"),
      ex("Tự viết: Giảm ô nhiễm, bảo vệ môi trường.", "减少污染，保护环境。"),
    ],
    scenario: "Nói về ô nhiễm, tiếng ồn, giảm rác, bảo vệ môi trường.",
    start: "这里的污染怎么样？",
  },
  {
    id: 207,
    theme: "Tài nguyên",
    kind: "learn",
    vocab: [
      v("回收", "huíshōu", "Tái chế", "请回收。", "Qǐng huíshōu.", "Hãy tái chế."),
      v("资源", "zīyuán", "Tài nguyên", "节约资源。", "Jiéyuē zīyuán.", "Tiết kiệm tài nguyên."),
      v("节约", "jiéyuē", "Tiết kiệm (ôn)", "要节约用水。", "Yào jiéyuē yòng shuǐ.", "Phải tiết kiệm nước."),
      v("浪费", "làngfèi", "Lãng phí (ôn)", "别浪费水。", "Bié làngfèi shuǐ.", "Đừng lãng phí nước."),
      v("影响", "yǐngxiǎng", "Ảnh hưởng", "对环境影响大。", "Duì huánjìng yǐngxiǎng dà.", "Ảnh hưởng môi trường lớn."),
    ],
    grammar: {
      title: "对…影响",
      pattern: "对 + N + 影响 (ôn)",
      explainVi: "对…影响 (ôn): ảnh hưởng tới điều gì. 对环境影响很大.",
      drills: [
        drill("Dịch: Hãy tái chế.", "请回收。"),
        drill("Dịch: Tiết kiệm tài nguyên.", "节约资源。"),
        drill("Dịch: Đừng lãng phí nước.", "别浪费水。"),
        drill("Dịch: Ảnh hưởng môi trường lớn.", "对环境影响大。"),
      ],
    },
    dialogue: [
      line("A", "我们要节约资源，减少浪费。", "Wǒmen yào jiéyuē zīyuán, jiǎnshǎo làngfèi.", "Phải tiết kiệm tài nguyên, giảm lãng phí."),
      line("B", "对。垃圾要回收。", "Duì. Lājī yào huíshōu.", "Đúng. Rác phải tái chế."),
      line("A", "浪费水对环境影响很大。", "Làngfèi shuǐ duì huánjìng yǐngxiǎng hěn dà.", "Lãng phí nước ảnh hưởng môi trường lớn."),
      line("B", "明白。我会节约用水。", "Míngbai. Wǒ huì jiéyuē yòng shuǐ.", "Hiểu rồi. Tôi sẽ tiết kiệm nước."),
    ],
    exercises: [
      ex("Tự viết: Tiết kiệm tài nguyên, tái chế rác.", "节约资源，回收垃圾。"),
      ex("Tự viết: Lãng phí nước ảnh hưởng môi trường lớn.", "浪费水对环境影响大。"),
    ],
    scenario: "Tái chế, tiết kiệm nước, ảnh hưởng môi trường.",
    start: "我们要节约资源，减少浪费。",
  },
  {
    id: 208,
    theme: "Thiên tai",
    kind: "learn",
    vocab: [
      v("地震", "dìzhèn", "Động đất", "发生地震了。", "Fāshēng dìzhèn le.", "Xảy ra động đất rồi."),
      v("安全", "ānquán", "An toàn (ôn)", "请到安全的地方。", "Qǐng dào ānquán de dìfang.", "Hãy đến chỗ an toàn."),
      v("危险", "wēixiǎn", "Nguy hiểm (ôn)", "这里危险。", "Zhèlǐ wēixiǎn.", "Ở đây nguy hiểm."),
      v("通知", "tōngzhī", "Thông báo (ôn)", "收到通知了吗？", "Shōudào tōngzhī le ma?", "Nhận thông báo chưa?"),
      v("离开", "líkāi", "Rời đi (ôn)", "请快离开。", "Qǐng kuài líkāi.", "Hãy rời đi nhanh."),
    ],
    grammar: {
      title: "如果…就…",
      pattern: "如果…就… (ôn)",
      explainVi: "如果…就… (ôn): nếu… thì…. 如果地震，就离开.",
      drills: [
        drill("Dịch: Xảy ra động đất rồi.", "发生地震了。"),
        drill("Dịch: Hãy đến chỗ an toàn.", "请到安全的地方。"),
        drill("Dịch: Ở đây nguy hiểm.", "这里危险。"),
        drill("Dịch: Nếu có báo thì rời đi.", "如果有通知就离开。"),
      ],
    },
    dialogue: [
      line("A", "发生地震了！请快离开。", "Fāshēng dìzhèn le! Qǐng kuài líkāi.", "Động đất rồi! Hãy rời nhanh."),
      line("B", "收到通知了吗？这里安全吗？", "Shōudào tōngzhī le ma? Zhèlǐ ānquán ma?", "Nhận thông báo chưa? Ở đây an toàn không?"),
      line("A", "不安全，很危险。如果听到广播就离开。", "Bù ānquán, hěn wēixiǎn. Rúguǒ tīngdào guǎngbō jiù líkāi.", "Không an toàn, nguy hiểm. Nghe đài thì đi."),
      line("B", "好。我们到安全的地方。", "Hǎo. Wǒmen dào ānquán de dìfang.", "Được. Chúng ta đến chỗ an toàn."),
    ],
    exercises: [
      ex("Tự viết: Động đất rồi! Hãy rời nhanh.", "发生地震了！请快离开。"),
      ex("Tự viết: Nghe thông báo thì đến chỗ an toàn.", "收到通知就到安全的地方。"),
    ],
    scenario: "Nghe báo động động đất, sơ tán đến chỗ an toàn.",
    start: "发生地震了！请快离开。",
  },
  {
    id: 209,
    theme: "Tổng hợp môi trường",
    kind: "review",
    vocab: [
      v("坚持", "jiānchí", "Kiên trì (ôn)", "要坚持。", "Yào jiānchí.", "Phải kiên trì."),
      v("减少", "jiǎnshǎo", "Giảm (ôn)", "减少污染。", "Jiǎnshǎo wūrǎn.", "Giảm ô nhiễm."),
      v("保护", "bǎohù", "Bảo vệ (ôn)", "保护环境。", "Bǎohù huánjìng.", "Bảo vệ môi trường."),
      v("锻炼", "duànliàn", "Tập luyện (ôn)", "多锻炼。", "Duō duànliàn.", "Tập nhiều."),
      v("回收", "huíshōu", "Tái chế (ôn)", "要回收。", "Yào huíshōu.", "Phải tái chế."),
    ],
    grammar: {
      title: "坚持 / 减少",
      pattern: "坚持 + V；减少 + N",
      explainVi: "Ôn tuần 30: nói thói quen xanh, tập luyện, bảo vệ môi trường.",
      drills: [
        drill("Dịch: Phải kiên trì tập.", "要坚持锻炼。"),
        drill("Dịch: Giảm ô nhiễm.", "减少污染。"),
        drill("Dịch: Bảo vệ môi trường.", "保护环境。"),
        drill("Dịch: Phải tái chế.", "要回收。"),
      ],
    },
    dialogue: [
      line("A", "你怎么保护环境？", "Nǐ zěnme bǎohù huánjìng?", "Bạn bảo vệ môi trường thế nào?"),
      line("B", "减少污染，回收垃圾，节约资源。", "Jiǎnshǎo wūrǎn, huíshōu lājī, jiéyuē zīyuán.", "Giảm ô nhiễm, tái chế rác, tiết kiệm."),
      line("A", "健康呢？", "Jiànkāng ne?", "Sức khỏe thì sao?"),
      line("B", "坚持锻炼，注意营养。", "Jiānchí duànliàn, zhùyì yíngyǎng.", "Kiên trì tập, chú ý dinh dưỡng."),
    ],
    exercises: [
      ex("Tự viết: Giảm ô nhiễm, tái chế rác.", "减少污染，回收垃圾。"),
      ex("Tự viết: Kiên trì tập, chú ý dinh dưỡng.", "坚持锻炼，注意营养。"),
    ],
    scenario: "Nói thói quen xanh: tái chế, giảm ô nhiễm, tập luyện.",
    start: "你怎么保护环境？",
  },
  {
    id: 210,
    theme: "Bác sĩ vs bệnh nhân",
    kind: "review",
    vocab: [
      v("保险", "bǎoxiǎn", "Bảo hiểm (ôn)", "有保险吗？", "Yǒu bǎoxiǎn ma?", "Có bảo hiểm không?"),
      v("治疗", "zhìliáo", "Điều trị (ôn)", "需要治疗。", "Xūyào zhìliáo.", "Cần điều trị."),
      v("恢复", "huīfù", "Hồi phục (ôn)", "恢复很快。", "Huīfù hěn kuài.", "Hồi phục nhanh."),
      v("污染", "wūrǎn", "Ô nhiễm (ôn)", "污染严重。", "Wūrǎn yánzhòng.", "Ô nhiễm nặng."),
      v("禁止", "jìnzhǐ", "Cấm (ôn)", "禁止吸烟。", "Jìnzhǐ xīyān.", "Cấm hút thuốc."),
    ],
    grammar: {
      title: "Chỉ sức khỏe / môi trường",
      pattern: "定期 / 坚持 / 减少",
      explainVi: "Roleplay bác sĩ vs bệnh nhân. Khoá từ đến tuần 30.",
      drills: [
        drill("Dịch: Có bảo hiểm không?", "有保险吗？"),
        drill("Dịch: Cần điều trị.", "需要治疗。"),
        drill("Dịch: Hồi phục nhanh.", "恢复很快。"),
        drill("Dịch: Khám định kỳ.", "定期体检。"),
      ],
    },
    dialogue: [
      line("A", "医生，我不舒服。有保险。", "Yīshēng, wǒ bù shūfu. Yǒu bǎoxiǎn.", "Bác sĩ, tôi không khỏe. Có bảo hiểm."),
      line("B", "好。需要治疗，但恢复很快。", "Hǎo. Xūyào zhìliáo, dàn huīfù hěn kuài.", "Được. Cần điều trị, nhưng hồi phục nhanh."),
      line("A", "以后要注意什么？", "Yǐhòu yào zhùyì shénme?", "Sau này chú ý gì?"),
      line("B", "坚持锻炼，定期体检。别在污染严重的地方。", "Jiānchí duànliàn, dìngqī tǐjiǎn. Bié zài wūrǎn yánzhòng de dìfang.", "Kiên trì tập, khám định kỳ. Đừng ở chỗ ô nhiễm nặng."),
    ],
    exercises: [
      ex("Tự viết: Có bảo hiểm, cần điều trị.", "有保险，需要治疗。"),
      ex("Tự viết: Kiên trì tập, khám định kỳ.", "坚持锻炼，定期体检。"),
    ],
    scenario: "Khám bệnh: bảo hiểm, điều trị, khám định kỳ, tập luyện.",
    start: "医生，我不舒服。有保险。",
  },
  {
    id: 211,
    theme: "任何 / 按照",
    kind: "learn",
    vocab: [
      v("任何", "rènhé", "Bất kỳ", "任何问题都可以问。", "Rènhé wèntí dōu kěyǐ wèn.", "Câu hỏi nào cũng hỏi được."),
      v("一切", "yíqiè", "Tất cả", "一切都很顺利。", "Yíqiè dōu hěn shùnlì.", "Mọi thứ suôn sẻ."),
      v("按照", "ànzhào", "Theo / làm theo", "按照规定做。", "Ànzhào guīdìng zuò.", "Làm theo quy định."),
      v("无论", "wúlùn", "Bất kể", "无论多忙都要完成。", "Wúlùn duō máng dōu yào wánchéng.", "Bất kể bận cũng phải xong."),
      v("既然", "jìrán", "既然 / vì đã", "既然答应了，就要做。", "Jìrán dāying le, jiù yào zuò.", "Đã hứa thì phải làm."),
    ],
    grammar: {
      title: "既然…就…",
      pattern: "既然…就…",
      explainVi: "既然…就…: vì đã… thì…. 既然答应了，就要按时完成.",
      drills: [
        drill("Dịch: Làm theo quy định.", "按照规定做。"),
        drill("Dịch: Bất kể bận cũng phải xong.", "无论多忙都要完成。"),
        drill("Dịch: Đã hứa thì phải làm.", "既然答应了，就要做。"),
        drill("Dịch: Mọi thứ suôn sẻ.", "一切都很顺利。"),
      ],
    },
    dialogue: [
      line("A", "任何问题都可以问经理。", "Rènhé wèntí dōu kěyǐ wèn jīnglǐ.", "Câu hỏi nào cũng hỏi giám đốc được."),
      line("B", "好。我们按照规定做。", "Hǎo. Wǒmen ànzhào guīdìng zuò.", "Được. Làm theo quy định."),
      line("A", "无论多忙，都要按时完成。", "Wúlùn duō máng, dōu yào ànshí wánchéng.", "Bất kể bận, phải xong đúng hạn."),
      line("B", "既然答应了，就一定会做。", "Jìrán dāying le, jiù yídìng huì zuò.", "Đã hứa thì nhất định làm."),
    ],
    exercises: [
      ex("Tự viết: Làm theo quy định, bất kể bận cũng phải xong.", "按照规定做，无论多忙都要完成。"),
      ex("Tự viết: Đã hứa thì phải làm.", "既然答应了，就要做。"),
    ],
    scenario: "Làm theo quy định công ty, đã hứa thì phải hoàn thành.",
    start: "任何问题都可以问经理。",
  },
  {
    id: 212,
    theme: "只好 / 原来",
    kind: "learn",
    vocab: [
      v("只好", "zhǐhǎo", "Đành phải", "只好明天去。", "Zhǐhǎo míngtiān qù.", "Đành mai đi."),
      v("直接", "zhíjiē", "Trực tiếp", "请直接说。", "Qǐng zhíjiē shuō.", "Hãy nói thẳng."),
      v("原来", "yuánlái", "Hóa ra / vốn", "原来是你。", "Yuánlái shì nǐ.", "Hóa ra là bạn."),
      v("果然", "guǒrán", "Quả nhiên", "果然下雨了。", "Guǒrán xià yǔ le.", "Quả nhiên mưa rồi."),
      v("接着", "jiēzhe", "Tiếp theo", "接着讨论。", "Jiēzhe tǎolùn.", "Tiếp tục thảo luận."),
    ],
    grammar: {
      title: "只好 + V",
      pattern: "只好 + V",
      explainVi: "只好: không còn cách, đành phải. 只好明天去、只好同意.",
      drills: [
        drill("Dịch: Đành mai đi.", "只好明天去。"),
        drill("Dịch: Hãy nói thẳng.", "请直接说。"),
        drill("Dịch: Hóa ra là bạn.", "原来是你。"),
        drill("Dịch: Quả nhiên mưa rồi.", "果然下雨了。"),
      ],
    },
    dialogue: [
      line("A", "航班改了，我们只好明天去。", "Hángbān gǎi le, wǒmen zhǐhǎo míngtiān qù.", "Chuyến bay đổi, đành mai đi."),
      line("B", "原来是这样。请直接告诉我。", "Yuánlái shì zhèyàng. Qǐng zhíjiē gàosu wǒ.", "Hóa ra vậy. Nói thẳng cho tôi."),
      line("A", "果然堵车了。只好改计划。", "Guǒrán dǔchē le. Zhǐhǎo gǎi jìhuà.", "Quả nhiên kẹt xe. Đành đổi kế hoạch."),
      line("B", "好。接着讨论新安排。", "Hǎo. Jiēzhe tǎolùn xīn ānpái.", "Được. Tiếp tục bàn sắp xếp mới."),
    ],
    exercises: [
      ex("Tự viết: Chuyến bay đổi, đành mai đi.", "航班改了，只好明天去。"),
      ex("Tự viết: Quả nhiên kẹt xe. Đành đổi kế hoạch.", "果然堵车了，只好改计划。"),
    ],
    scenario: "Kế hoạch đổi: đành phải đổi ngày, nói thẳng, tiếp tục thảo luận.",
    start: "航班改了，我们只好明天去。",
  },
  {
    id: 213,
    theme: "即使 / 哪怕",
    kind: "learn",
    vocab: [
      v("哪怕", "nǎpà", "Dù / ngay cả khi", "哪怕下雨也去。", "Nǎpà xià yǔ yě qù.", "Dù mưa cũng đi."),
      v("依然", "yīrán", "Vẫn", "他依然坚持。", "Tā yīrán jiānchí.", "Anh ấy vẫn kiên trì."),
      v("仍然", "réngrán", "Vẫn còn", "仍然很忙。", "Réngrán hěn máng.", "Vẫn còn bận."),
      v("不得不", "bùdébù", "Buộc phải", "不得不离开。", "Bùdébù líkāi.", "Buộc phải rời đi."),
      v("当时", "dāngshí", "Lúc đó", "当时很忙。", "Dāngshí hěn máng.", "Lúc đó rất bận."),
    ],
    grammar: {
      title: "即使…也…",
      pattern: "即使…也…",
      explainVi: "即使…也…: dù… vẫn…. 即使下雨，也要去.",
      drills: [
        drill("Dịch: Dù mưa cũng đi.", "哪怕下雨也去。"),
        drill("Dịch: Anh ấy vẫn kiên trì.", "他依然坚持。"),
        drill("Dịch: Buộc phải rời đi.", "不得不离开。"),
        drill("Dịch: Lúc đó rất bận.", "当时很忙。"),
      ],
    },
    dialogue: [
      line("A", "即使下雨，你也去吗？", "Jíshǐ xià yǔ, nǐ yě qù ma?", "Dù mưa bạn cũng đi à?"),
      line("B", "去。哪怕很忙，我依然去。", "Qù. Nǎpà hěn máng, wǒ yīrán qù.", "Đi. Dù bận tôi vẫn đi."),
      line("A", "当时你怎么决定的？", "Dāngshí nǐ zěnme juédìng de?", "Lúc đó bạn quyết định thế nào?"),
      line("B", "不得不改时间，但仍然参加。", "Bùdébù gǎi shíjiān, dàn réngrán cānjiā.", "Buộc đổi giờ, nhưng vẫn tham gia."),
    ],
    exercises: [
      ex("Tự viết: Dù mưa cũng đi.", "哪怕下雨也去。"),
      ex("Tự viết: Dù bận vẫn kiên trì tập.", "即使很忙，也坚持锻炼。"),
    ],
    scenario: "Dù mưa vẫn đi, dù bận vẫn kiên trì.",
    start: "即使下雨，你也去吗？",
  },
  {
    id: 214,
    theme: "连 / 甚至",
    kind: "learn",
    vocab: [
      v("甚至", "shènzhì", "Thậm chí", "甚至经理也知道。", "Shènzhì jīnglǐ yě zhīdào.", "Thậm chí giám đốc cũng biết."),
      v("居然", "jūrán", "Lại / không ngờ", "他居然来了。", "Tā jūrán lái le.", "Anh ấy lại đến."),
      v("难道", "nándào", "Lẽ nào", "难道你不知道？", "Nándào nǐ bù zhīdào?", "Lẽ nào bạn không biết?"),
      v("究竟", "jiūjìng", "Rốt cuộc", "究竟怎么回事？", "Jiūjìng zěnme huí shì?", "Rốt cuộc chuyện gì?"),
      v("越", "yuè", "Càng", "越学越好。", "Yuè xué yuè hǎo.", "Càng học càng tốt."),
    ],
    grammar: {
      title: "连…都…",
      pattern: "连…都…",
      explainVi: "连…都…: ngay cả… cũng…. 连经理都知道.",
      drills: [
        drill("Dịch: Thậm chí giám đốc cũng biết.", "甚至经理也知道。"),
        drill("Dịch: Lẽ nào bạn không biết?", "难道你不知道？"),
        drill("Dịch: Rốt cuộc chuyện gì?", "究竟怎么回事？"),
        drill("Dịch: Ngay cả anh ấy cũng đến.", "连他也来了。"),
      ],
    },
    dialogue: [
      line("A", "连同事都知道了，难道你不知道？", "Lián tóngshì dōu zhīdào le, nándào nǐ bù zhīdào?", "Ngay cả đồng nghiệp cũng biết, lẽ nào bạn không?"),
      line("B", "我知道。甚至经理也讨论了。", "Wǒ zhīdào. Shènzhì jīnglǐ yě tǎolùn le.", "Tôi biết. Thậm chí giám đốc cũng bàn."),
      line("A", "他居然同意了。究竟为什么？", "Tā jūrán tóngyì le. Jiūjìng wèishénme?", "Anh ấy lại đồng ý. Rốt cuộc vì sao?"),
      line("B", "因为计划越改越好。", "Yīnwèi jìhuà yuè gǎi yuè hǎo.", "Vì kế hoạch càng sửa càng tốt."),
    ],
    exercises: [
      ex("Tự viết: Ngay cả giám đốc cũng biết.", "连经理都知道。"),
      ex("Tự viết: Rốt cuộc chuyện gì?", "究竟怎么回事？"),
    ],
    scenario: "Ngay cả sếp cũng biết, lẽ nào bạn không, rốt cuộc sao.",
    start: "连同事都知道了，难道你不知道？",
  },
  {
    id: 215,
    theme: "越…越…",
    kind: "learn",
    vocab: [
      v("当时", "dāngshí", "Lúc đó (ôn)", "当时很难。", "Dāngshí hěn nán.", "Lúc đó rất khó."),
      v("接着", "jiēzhe", "Tiếp theo (ôn)", "接着学。", "Jiēzhe xué.", "Tiếp tục học."),
      v("依然", "yīrán", "Vẫn (ôn)", "依然努力。", "Yīrán nǔlì.", "Vẫn cố gắng."),
      v("仍然", "réngrán", "Vẫn còn (ôn)", "仍然坚持。", "Réngrán jiānchí.", "Vẫn kiên trì."),
      v("越", "yuè", "Càng (ôn)", "越学越喜欢。", "Yuè xué yuè xǐhuan.", "Càng học càng thích."),
    ],
    grammar: {
      title: "越 + adj + 越 + adj",
      pattern: "越 + V/adj + 越 + V/adj",
      explainVi: "越…越…: càng… càng…. 越学越喜欢、越说越明白.",
      drills: [
        drill("Dịch: Càng học càng thích.", "越学越喜欢。"),
        drill("Dịch: Càng nói càng hiểu.", "越说越明白。"),
        drill("Dịch: Lúc đó khó, giờ càng học càng tốt.", "当时很难，现在越学越好。"),
        drill("Dịch: Vẫn kiên trì, càng tập càng khỏe.", "仍然坚持，越锻炼越健康。"),
      ],
    },
    dialogue: [
      line("A", "你学中文多久了？", "Nǐ xué Zhōngwén duō jiǔ le?", "Bạn học tiếng Trung bao lâu rồi?"),
      line("B", "当时很难，现在越学越喜欢。", "Dāngshí hěn nán, xiànzài yuè xué yuè xǐhuan.", "Lúc đó khó, giờ càng học càng thích."),
      line("A", "接着坚持吗？", "Jiēzhe jiānchí ma?", "Tiếp tục kiên trì không?"),
      line("B", "当然。仍然每天学，越说越明白。", "Dāngrán. Réngrán měitiān xué, yuè shuō yuè míngbai.", "Đương nhiên. Vẫn học hàng ngày, càng nói càng hiểu."),
    ],
    exercises: [
      ex("Tự viết: Càng học càng thích.", "越学越喜欢。"),
      ex("Tự viết: Vẫn kiên trì, càng nói càng hiểu.", "仍然坚持，越说越明白。"),
    ],
    scenario: "Càng học càng thích, vẫn kiên trì mỗi ngày.",
    start: "你学中文多久了？",
  },
  {
    id: 216,
    theme: "Tổng hợp ngữ pháp",
    kind: "review",
    vocab: [
      v("既然", "jìrán", "既然 (ôn)", "既然答应…", "Jìrán dāying…", "Đã hứa thì…"),
      v("只好", "zhǐhǎo", "Đành phải (ôn)", "只好改计划。", "Zhǐhǎo gǎi jìhuà.", "Đành đổi kế hoạch."),
      v("哪怕", "nǎpà", "Dù (ôn)", "哪怕下雨…", "Nǎpà xià yǔ…", "Dù mưa…"),
      v("甚至", "shènzhì", "Thậm chí (ôn)", "甚至经理…", "Shènzhì jīnglǐ…", "Thậm chí giám đốc…"),
      v("越", "yuè", "Càng (ôn)", "越学越好。", "Yuè xué yuè hǎo.", "Càng học càng tốt."),
    ],
    grammar: {
      title: "不仅 / 即使",
      pattern: "既然…就… / 即使…也… / 越…越…",
      explainVi: "Ôn tuần 31: tranh luận nhẹ, dùng mẫu phức.",
      drills: [
        drill("Dịch: Đã hứa thì phải làm.", "既然答应了，就要做。"),
        drill("Dịch: Dù mưa cũng đi.", "哪怕下雨也去。"),
        drill("Dịch: Thậm chí giám đốc cũng biết.", "甚至经理也知道。"),
        drill("Dịch: Càng học càng tốt.", "越学越好。"),
      ],
    },
    dialogue: [
      line("A", "既然决定了，就要坚持。", "Jìrán juédìng le, jiù yào jiānchí.", "Đã quyết thì phải kiên trì."),
      line("B", "哪怕很难，我仍然努力。", "Nǎpà hěn nán, wǒ réngrán nǔlì.", "Dù khó tôi vẫn cố."),
      line("A", "甚至同事都说你进步快。", "Shènzhì tóngshì dōu shuō nǐ jìnbù kuài.", "Thậm chí đồng nghiệp nói bạn tiến nhanh."),
      line("B", "对。越学越有信心。", "Duì. Yuè xué yuè yǒu xìnxīn.", "Đúng. Càng học càng tự tin."),
    ],
    exercises: [
      ex("Tự viết: Đã quyết thì kiên trì. Dù khó vẫn cố.", "既然决定了，就要坚持。哪怕很难也努力。"),
      ex("Tự viết: Càng học càng tự tin.", "越学越有信心。"),
    ],
    scenario: "Tranh luận nhẹ: kiên trì, dù khó vẫn làm, càng học càng tốt.",
    start: "既然决定了，就要坚持。",
  },
  {
    id: 217,
    theme: "Giải thích quyết định",
    kind: "review",
    vocab: [
      v("原来", "yuánlái", "Hóa ra (ôn)", "原来如此。", "Yuánlái rúcǐ.", "Hóa ra vậy."),
      v("果然", "guǒrán", "Quả nhiên (ôn)", "果然对了。", "Guǒrán duì le.", "Quả nhiên đúng."),
      v("究竟", "jiūjìng", "Rốt cuộc (ôn)", "究竟为什么？", "Jiūjìng wèishénme?", "Rốt cuộc vì sao?"),
      v("不得不", "bùdébù", "Buộc phải (ôn)", "不得不改。", "Bùdébù gǎi.", "Buộc phải đổi."),
      v("无论", "wúlùn", "Bất kể (ôn)", "无论如何。", "Wúlùn rúhé.", "Bất kể thế nào."),
    ],
    grammar: {
      title: "Chỉ mẫu phức",
      pattern: "既然 / 只好 / 难道",
      explainVi: "Roleplay giải thích quyết định. Khoá từ đến tuần 31.",
      drills: [
        drill("Dịch: Hóa ra vậy.", "原来如此。"),
        drill("Dịch: Quả nhiên đúng.", "果然对了。"),
        drill("Dịch: Rốt cuộc vì sao?", "究竟为什么？"),
        drill("Dịch: Buộc phải đổi.", "不得不改。"),
      ],
    },
    dialogue: [
      line("A", "你究竟为什么辞职？", "Nǐ jiūjìng wèishénme cízhí?", "Rốt cuộc bạn vì sao nghỉ việc?"),
      line("B", "原来公司安排变了，我不得不改计划。", "Yuánlái gōngsī ānpái biàn le, wǒ bùdébù gǎi jìhuà.", "Hóa ra công ty đổi sắp xếp, tôi buộc đổi kế hoạch."),
      line("A", "无论怎么样，你果然选对了。", "Wúlùn zěnmeyàng, nǐ guǒrán xuǎn duì le.", "Bất kể thế nào, bạn quả nhiên chọn đúng."),
      line("B", "对。新工作更适合我。", "Duì. Xīn gōngzuò gèng shìhé wǒ.", "Đúng. Việc mới phù hợp hơn."),
    ],
    exercises: [
      ex("Tự viết: Rốt cuộc vì sao nghỉ việc?", "究竟为什么辞职？"),
      ex("Tự viết: Buộc đổi kế hoạch. Việc mới phù hợp hơn.", "不得不改计划。新工作更适合。"),
    ],
    scenario: "Giải thích quyết định nghỉ việc, buộc đổi kế hoạch.",
    start: "你究竟为什么辞职？",
  },
  {
    id: 218,
    theme: "Ôn công việc + giao tiếp",
    kind: "review",
    vocab: [
      v("负责", "fùzé", "Phụ trách (ôn)", "负责项目。", "Fùzé xiàngmù.", "Phụ trách dự án."),
      v("恐怕", "kǒngpà", "E rằng (ôn)", "恐怕不行。", "Kǒngpà bù xíng.", "E rằng không được."),
      v("面试", "miànshì", "Phỏng vấn (ôn)", "面试怎么样？", "Miànshì zěnmeyàng?", "Phỏng vấn thế nào?"),
      v("邀请", "yāoqǐng", "Mời (ôn)", "邀请同事。", "Yāoqǐng tóngshì.", "Mời đồng nghiệp."),
      v("新闻", "xīnwén", "Tin tức (ôn)", "看新闻。", "Kàn xīnwén.", "Xem tin."),
    ],
    grammar: {
      title: "负责 / 恐怕",
      pattern: "负责 + N；恐怕 + câu",
      explainVi: "Ôn công việc + giao tiếp: phỏng vấn, báo tin, mời đồng nghiệp.",
      drills: [
        drill("Dịch: Phụ trách dự án.", "负责项目。"),
        drill("Dịch: E rằng không được.", "恐怕不行。"),
        drill("Dịch: Phỏng vấn thế nào?", "面试怎么样？"),
        drill("Dịch: Mời đồng nghiệp.", "邀请同事。"),
      ],
    },
    dialogue: [
      line("A", "面试怎么样？结果出来了吗？", "Miànshì zěnmeyàng? Jiéguǒ chūlái le ma?", "Phỏng vấn thế nào? Ra kết quả chưa?"),
      line("B", "成功了。我负责新项目。", "Chénggōng le. Wǒ fùzé xīn xiàngmù.", "Thành công. Tôi phụ trách dự án mới."),
      line("A", "祝贺。我邀请大家看新闻。", "Zhùhè. Wǒ yāoqǐng dàjiā kàn xīnwén.", "Chúc mừng. Mời mọi người xem tin."),
      line("B", "恐怕今天不行。明天可以吗？", "Kǒngpà jīntiān bù xíng. Míngtiān kěyǐ ma?", "E rằng hôm nay không được. Mai được không?"),
    ],
    exercises: [
      ex("Tự viết: Phỏng vấn thành công. Phụ trách dự án mới.", "面试成功。负责新项目。"),
      ex("Tự viết: E rằng hôm nay không được.", "恐怕今天不行。"),
    ],
    scenario: "Phỏng vấn rồi báo tin, mời đồng nghiệp, xin lỗi bận.",
    start: "面试怎么样？结果出来了吗？",
  },
  {
    id: 219,
    theme: "Ôn công nghệ + nhà ở",
    kind: "review",
    vocab: [
      v("登录", "dēnglù", "Đăng nhập (ôn)", "请登录。", "Qǐng dēnglù.", "Hãy đăng nhập."),
      v("修理", "xiūlǐ", "Sửa chữa (ôn)", "需要修理。", "Xūyào xiūlǐ.", "Cần sửa."),
      v("网络", "wǎngluò", "Mạng (ôn)", "网络很慢。", "Wǎngluò hěn màn.", "Mạng chậm."),
      v("房东", "fángdōng", "Chủ nhà (ôn)", "告诉房东。", "Gàosu fángdōng.", "Báo chủ nhà."),
      v("密码", "mìmǎ", "Mật khẩu (ôn)", "忘记密码。", "Wàngjì mìmǎ.", "Quên mật khẩu."),
    ],
    grammar: {
      title: "登录 / 修理",
      pattern: "登录 + N；需要 + 修理",
      explainVi: "Ôn công nghệ + nhà ở: sửa wifi, báo chủ nhà.",
      drills: [
        drill("Dịch: Mạng chậm, không đăng nhập được.", "网络很慢，不能登录。"),
        drill("Dịch: Cần sửa.", "需要修理。"),
        drill("Dịch: Báo chủ nhà.", "告诉房东。"),
        drill("Dịch: Quên mật khẩu.", "忘记密码。"),
      ],
    },
    dialogue: [
      line("A", "网络很慢，我不能登录。", "Wǎngluò hěn màn, wǒ bù néng dēnglù.", "Mạng chậm, tôi không đăng nhập được."),
      line("B", "请IT修一下。是不是忘记密码？", "Qǐng IT xiū yíxià. Shì bu shì wàngjì mìmǎ?", "Nhờ IT sửa. Quên mật khẩu à?"),
      line("A", "对。空调也坏了，我告诉房东。", "Duì. Kōngtiáo yě huài le, wǒ gàosu fángdōng.", "Đúng. Máy lạnh cũng hỏng, tôi báo chủ nhà."),
      line("B", "好。需要修理就安排。", "Hǎo. Xūyào xiūlǐ jiù ānpái.", "Được. Cần sửa thì sắp xếp."),
    ],
    exercises: [
      ex("Tự viết: Mạng chậm, không đăng nhập được.", "网络很慢，不能登录。"),
      ex("Tự viết: Máy lạnh hỏng, báo chủ nhà.", "空调坏了，告诉房东。"),
    ],
    scenario: "Sửa wifi, quên mật khẩu, báo chủ nhà máy hỏng.",
    start: "网络很慢，我不能登录。",
  },
  {
    id: 220,
    theme: "Ôn du lịch + môi trường",
    kind: "review",
    vocab: [
      v("值得", "zhíde", "Đáng (ôn)", "值得去。", "Zhíde qù.", "Đáng đi."),
      v("减少", "jiǎnshǎo", "Giảm (ôn)", "减少污染。", "Jiǎnshǎo wūrǎn.", "Giảm ô nhiễm."),
      v("当地", "dāngdì", "Địa phương (ôn)", "当地文化。", "Dāngdì wénhuà.", "Văn hóa địa phương."),
      v("预算", "yùsuàn", "Ngân sách (ôn)", "在预算里。", "Zài yùsuàn lǐ.", "Trong ngân sách."),
      v("保护", "bǎohù", "Bảo vệ (ôn)", "保护环境。", "Bǎohù huánjìng.", "Bảo vệ môi trường."),
    ],
    grammar: {
      title: "值得 / 减少",
      pattern: "值得 + V；减少 + N",
      explainVi: "Ôn du lịch + môi trường: kế hoạch du lịch xanh.",
      drills: [
        drill("Dịch: Đáng đi.", "值得去。"),
        drill("Dịch: Giảm ô nhiễm.", "减少污染。"),
        drill("Dịch: Trong ngân sách.", "在预算里。"),
        drill("Dịch: Bảo vệ môi trường.", "保护环境。"),
      ],
    },
    dialogue: [
      line("A", "绿色旅行值得吗？", "Lǜsè lǚxíng zhíde ma?", "Du lịch xanh có đáng không?"),
      line("B", "值得。可以体验当地文化。", "Zhíde. Kěyǐ tǐyàn dāngdì wénhuà.", "Đáng. Trải nghiệm văn hóa địa phương."),
      line("A", "费用在预算里吗？", "Fèiyòng zài yùsuàn lǐ ma?", "Chi phí trong ngân sách không?"),
      line("B", "在。我们也要减少污染，保护环境。", "Zài. Wǒmen yě yào jiǎnshǎo wūrǎn, bǎohù huánjìng.", "Có. Cũng giảm ô nhiễm, bảo vệ môi trường."),
    ],
    exercises: [
      ex("Tự viết: Du lịch xanh đáng đi, trải nghiệm văn hóa.", "绿色旅行值得，体验当地文化。"),
      ex("Tự viết: Giảm ô nhiễm, bảo vệ môi trường.", "减少污染，保护环境。"),
    ],
    scenario: "Kế hoạch du lịch xanh: ngân sách, văn hóa, bảo vệ môi trường.",
    start: "绿色旅行值得吗？",
  },
  {
    id: 221,
    theme: "Ôn ngữ pháp nâng",
    kind: "review",
    vocab: [
      v("既然", "jìrán", "既然 (ôn)", "既然决定…", "Jìrán juédìng…", "Đã quyết…"),
      v("哪怕", "nǎpà", "Dù / ngay cả (ôn)", "哪怕下雨也去。", "Nǎpà xià yǔ yě qù.", "Dù mưa cũng đi."),
      v("甚至", "shènzhì", "Thậm chí (ôn)", "甚至经理也知道。", "Shènzhì jīnglǐ yě zhīdào.", "Thậm chí giám đốc cũng biết."),
      v("越", "yuè", "Càng (ôn)", "越来越好。", "Yuè lái yuè hǎo.", "Ngày càng tốt."),
      v("难道", "nándào", "Lẽ nào (ôn)", "难道不对？", "Nándào bù duì?", "Lẽ nào không đúng?"),
    ],
    grammar: {
      title: "即使 / 连",
      pattern: "即使…也… / 连…都… / 越…越…",
      explainVi: "Ôn ngữ pháp nâng: giải thích lựa chọn bằng mẫu phức.",
      drills: [
        drill("Dịch: Dù mưa cũng đi.", "即使下雨也去。"),
        drill("Dịch: Ngay cả anh ấy cũng biết.", "连他也知道。"),
        drill("Dịch: Ngày càng tốt.", "越来越好。"),
        drill("Dịch: Lẽ nào không đúng?", "难道不对？"),
      ],
    },
    dialogue: [
      line("A", "你为什么选择这个工作？", "Nǐ wèishénme xuǎnzé zhège gōngzuò?", "Sao bạn chọn việc này?"),
      line("B", "即使工资不高，我也喜欢。连朋友都支持。", "Jíshǐ gōngzī bù gāo, wǒ yě xǐhuan. Lián péngyou dōu zhīchí.", "Dù lương không cao tôi cũng thích. Ngay cả bạn bè ủng hộ."),
      line("A", "难道你不担心失败？", "Nándào nǐ bù dānxīn shībài?", "Lẽ nào bạn không lo thất bại?"),
      line("B", "既然选择了，就越做越有信心。", "Jìrán xuǎnzé le, jiù yuè zuò yuè yǒu xìnxīn.", "Đã chọn thì càng làm càng tự tin."),
    ],
    exercises: [
      ex("Tự viết: Dù lương không cao cũng thích.", "即使工资不高，我也喜欢。"),
      ex("Tự viết: Đã chọn thì càng làm càng tự tin.", "既然选择了，就越做越有信心。"),
    ],
    scenario: "Giải thích lựa chọn nghề bằng mẫu 即使, 连, 既然, 越.",
    start: "你为什么选择这个工作？",
  },
  {
    id: 222,
    theme: "Mock mini-test",
    kind: "review",
    vocab: [
      v("任何", "rènhé", "Bất kỳ (ôn)", "任何问题。", "Rènhé wèntí.", "Câu hỏi nào."),
      v("按照", "ànzhào", "Theo (ôn)", "按照规定。", "Ànzhào guīdìng.", "Theo quy định."),
      v("直接", "zhíjiē", "Trực tiếp (ôn)", "直接回答。", "Zhíjiē huídá.", "Trả lời trực tiếp."),
      v("仍然", "réngrán", "Vẫn (ôn)", "仍然正确。", "Réngrán zhèngquè.", "Vẫn đúng."),
      v("一切", "yíqiè", "Tất cả (ôn)", "一切顺利。", "Yíqiè shùnlì.", "Mọi thứ suôn sẻ."),
    ],
    grammar: {
      title: "Nghe + đọc hiểu ngắn",
      pattern: "HSK 4 mẫu phức",
      explainVi: "Mock mini-test ~624 từ. Nghe + đọc hiểu 20 câu ngắn.",
      drills: [
        drill("Dịch: Câu hỏi nào cũng được.", "任何问题都可以。"),
        drill("Dịch: Làm theo quy định.", "按照规定做。"),
        drill("Dịch: Trả lời trực tiếp.", "直接回答。"),
        drill("Dịch: Mọi thứ suôn sẻ.", "一切顺利。"),
      ],
    },
    dialogue: [
      line("A", "请直接回答：既然答应了，就要做什么？", "Qǐng zhíjiē huídá: jìrán dāying le, jiù yào zuò shénme?", "Trả lời trực tiếp: đã hứa thì phải làm gì?"),
      line("B", "就要按时完成。", "Jiù yào ànshí wánchéng.", "Phải hoàn thành đúng hạn."),
      line("A", "即使下雨，也应该减少什么？", "Jíshǐ xià yǔ, yě yīnggāi jiǎnshǎo shénme?", "Dù mưa cũng nên giảm gì?"),
      line("B", "仍然要减少污染。", "Réngrán yào jiǎnshǎo wūrǎn.", "Vẫn phải giảm ô nhiễm."),
    ],
    exercises: [
      ex("Tự viết: Đã hứa thì hoàn thành đúng hạn.", "既然答应了，就要按时完成。"),
      ex("Tự viết: Càng học càng tốt.", "越学越好。"),
    ],
    scenario: "Mini-test ngắn: trả lời trực tiếp câu ngữ pháp HSK 4.",
    start: "请直接回答：既然答应了，就要做什么？",
  },
  {
    id: 223,
    theme: "Hội thoại A",
    kind: "review",
    vocab: [
      v("讨论", "tǎolùn", "Thảo luận (ôn)", "讨论项目。", "Tǎolùn xiàngmù.", "Thảo luận dự án."),
      v("建议", "jiànyì", "Đề xuất (ôn)", "提出建议。", "Tíchū jiànyì.", "Đưa đề xuất."),
      v("接受", "jiēshòu", "Chấp nhận (ôn)", "接受意见。", "Jiēshòu yìjiàn.", "Chấp nhận ý kiến."),
      v("安排", "ānpái", "Sắp xếp (ôn)", "安排任务。", "Ānpái rènwu.", "Sắp nhiệm vụ."),
      v("负责", "fùzé", "Phụ trách (ôn)", "谁负责？", "Shéi fùzé?", "Ai phụ trách?"),
    ],
    grammar: {
      title: "Toàn mẫu HSK 4",
      pattern: "负责 / 讨论 / 既然 / 越",
      explainVi: "Thảo luận dự án nhóm: ý kiến, phân công, mẫu phức.",
      drills: [
        drill("Dịch: Thảo luận dự án.", "讨论项目。"),
        drill("Dịch: Ai phụ trách?", "谁负责？"),
        drill("Dịch: Chấp nhận ý kiến.", "接受意见。"),
        drill("Dịch: Sắp nhiệm vụ.", "安排任务。"),
      ],
    },
    dialogue: [
      line("A", "我们讨论一下新项目。谁负责？", "Wǒmen tǎolùn yíxià xīn xiàngmù. Shéi fùzé?", "Thảo luận dự án mới. Ai phụ trách?"),
      line("B", "我负责。我建议改变方法。", "Wǒ fùzé. Wǒ jiànyì gǎibiàn fāngfǎ.", "Tôi phụ trách. Tôi đề xuất đổi cách."),
      line("A", "既然决定了，就安排任务。", "Jìrán juédìng le, jiù ānpái rènwu.", "Đã quyết thì sắp nhiệm vụ."),
      line("B", "好。大家越合作越顺利。", "Hǎo. Dàjiā yuè hézuò yuè shùnlì.", "Được. Càng hợp tác càng suôn sẻ."),
    ],
    exercises: [
      ex("Tự viết: Thảo luận dự án mới. Tôi phụ trách.", "讨论新项目。我负责。"),
      ex("Tự viết: Càng hợp tác càng suôn sẻ.", "越合作越顺利。"),
    ],
    scenario: "Thảo luận dự án nhóm: phân công, đề xuất, hợp tác.",
    start: "我们讨论一下新项目。谁负责？",
  },
  {
    id: 224,
    theme: "AI tốt nghiệp",
    kind: "review",
    vocab: [
      v("同事", "tóngshì", "Đồng nghiệp (ôn)", "同事帮助你。", "Tóngshì bāngzhù nǐ.", "Đồng nghiệp giúp bạn."),
      v("经理", "jīnglǐ", "Giám đốc (ôn)", "经理欢迎你。", "Jīnglǐ huānyíng nǐ.", "Giám đốc chào bạn."),
      v("了解", "liǎojiě", "Tìm hiểu (ôn)", "了解工作。", "Liǎojiě gōngzuò.", "Hiểu việc."),
      v("成功", "chénggōng", "Thành công (ôn)", "祝你成功。", "Zhù nǐ chénggōng.", "Chúc thành công."),
      v("经验", "jīngyàn", "Kinh nghiệm (ôn)", "有经验。", "Yǒu jīngyàn.", "Có kinh nghiệm."),
    ],
    grammar: {
      title: "HSK 1–4 toàn mẫu",
      pattern: "HSK 1–4 toàn mẫu",
      explainVi: "Tốt nghiệp HSK 4: ngày đầu làm việc ở công ty. Chỉ từ đã khoá.",
      drills: [
        drill("Dịch: Giám đốc chào bạn.", "经理欢迎你。"),
        drill("Dịch: Hiểu việc trước.", "先了解工作。"),
        drill("Dịch: Đồng nghiệp giúp bạn.", "同事帮助你。"),
        drill("Dịch: Chúc thành công.", "祝你成功。"),
      ],
    },
    dialogue: [
      line("A", "欢迎！今天是你在公司的第一天。", "Huānyíng! Jīntiān shì nǐ zài gōngsī de dì yī tiān.", "Hoan nghênh! Hôm nay là ngày đầu bạn ở công ty."),
      line("B", "谢谢经理。我想先了解工作。", "Xièxie jīnglǐ. Wǒ xiǎng xiān liǎojiě gōngzuò.", "Cảm ơn giám đốc. Tôi muốn hiểu việc trước."),
      line("A", "好。同事会帮助你。你有经验。", "Hǎo. Tóngshì huì bāngzhù nǐ. Nǐ yǒu jīngyàn.", "Tốt. Đồng nghiệp sẽ giúp. Bạn có kinh nghiệm."),
      line("B", "我会努力。既然来了，就一定成功。", "Wǒ huì nǔlì. Jìrán lái le, jiù yídìng chénggōng.", "Tôi sẽ cố. Đã đến thì nhất định thành công."),
    ],
    exercises: [
      ex("Tự viết: Ngày đầu ở công ty. Muốn hiểu việc trước.", "今天是第一天。我想先了解工作。"),
      ex("Tự viết: Đồng nghiệp giúp. Nhất định thành công.", "同事帮助。一定成功。"),
    ],
    scenario: "Ngày đầu làm việc: chào, hiểu việc, đồng nghiệp giúp, quyết thành công.",
    start: "欢迎！今天是你在公司的第一天。",
  },
];

function weekOf(id) {
  return Math.ceil(id / 7);
}

function systemPrompt(level, words, start) {
  return `Bạn là bạn nói tiếng Trung trình độ HSK ${level}. Chỉ dùng các từ: ${words.join(", ")}. Mỗi lượt 1–2 câu ngắn. Viết Hán + pinyin. Nếu học viên sai, sửa nhẹ bằng tiếng Việt rồi hỏi lại. Không thêm từ mới. Bắt đầu bằng: ${start}`;
}

const hsk3 = JSON.parse(readFileSync(join(dir, "168.json"), "utf8"));
let allowed = [...hsk3.aiPrompt.allowedWords];

for (const lesson of LESSONS) {
  if (lesson.kind === "learn") {
    for (const item of lesson.vocab) {
      if (!item.vi.includes("(ôn") && !allowed.includes(item.han)) {
        allowed.push(item.han);
      }
    }
  }
  const week = weekOf(lesson.id);
  const payload = {
    id: lesson.id,
    week,
    hsk: 4,
    theme: lesson.theme,
    kind: lesson.kind,
    vocab: lesson.vocab,
    grammar: lesson.grammar,
    dialogue: lesson.dialogue,
    exercises: lesson.exercises,
    aiPrompt: {
      scenario: lesson.scenario,
      system: systemPrompt(4, allowed, lesson.start),
      allowedWords: [...allowed],
      turns: 5,
    },
    timer: TIMER,
  };
  const name = `${String(lesson.id).padStart(3, "0")}.json`;
  writeFileSync(join(dir, name), `${JSON.stringify(payload, null, 2)}\n`);
}

console.log(`Wrote ${LESSONS.length} lessons, last allowed ${allowed.length} words`);
