import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const dir = dirname(fileURLToPath(import.meta.url));
const TIMER = { review: 5, vocab: 8, grammar: 8, talk: 5, ai: 4 };

function v(han, pinyin, vi, exHan, exPy, exVi) {
  return {
    han,
    pinyin,
    vi,
    example: { han: exHan, pinyin: exPy, vi: exVi },
  };
}

function line(speaker, han, pinyin, vi) {
  return { speaker, han, pinyin, vi };
}

function drill(prompt, answer) {
  return { prompt, answer };
}

function ex(prompt, answer) {
  return { type: "write", prompt, answer };
}

const LESSONS = [
  {
    id: 113,
    theme: "Vừa mới / trước đây",
    kind: "learn",
    vocab: [
      v("刚才", "gāngcái", "Vừa mới", "我刚才看见他。", "Wǒ gāngcái kànjiàn tā.", "Tôi vừa thấy anh ấy."),
      v("一直", "yìzhí", "Luôn / suốt", "我一直在学习。", "Wǒ yìzhí zài xuéxí.", "Tôi học suốt."),
      v("最近", "zuìjìn", "Gần đây", "最近你忙吗？", "Zuìjìn nǐ máng ma?", "Gần đây bạn bận không?"),
      v("以前", "yǐqián", "Trước đây", "以前我住在北京。", "Yǐqián wǒ zhù zài Běijīng.", "Trước đây tôi ở Bắc Kinh."),
      v("后来", "hòulái", "Sau đó", "后来我去公司了。", "Hòulái wǒ qù gōngsī le.", "Sau đó tôi đến công ty."),
    ],
    grammar: {
      title: "刚才 + động từ",
      pattern: "刚才 + V",
      explainVi: "刚才: việc vừa xảy ra, không kèm 了. Khác 以前 (lâu hơn) và 后来 (sau đó).",
      drills: [
        drill("Dịch: Tôi vừa dậy.", "我刚才起床了。"),
        drill("Dịch: Gần đây tôi bận.", "最近我很忙。"),
        drill("Dịch: Trước đây tôi ở nhà.", "以前我住在家。"),
        drill("Dịch: Sau đó tôi đi học.", "后来我去学校了。"),
      ],
    },
    dialogue: [
      line("A", "最近你怎么样？", "Zuìjìn nǐ zěnmeyàng?", "Gần đây bạn thế nào?"),
      line("B", "我一直很忙。刚才才回来。", "Wǒ yìzhí hěn máng. Gāngcái cái huílai.", "Tôi bận suốt. Vừa mới về."),
      line("A", "以前你也一直忙吗？", "Yǐqián nǐ yě yìzhí máng ma?", "Trước đây bạn cũng bận suốt à?"),
      line("B", "不。后来公司的事多了。", "Bù. Hòulái gōngsī de shì duō le.", "Không. Sau đó việc công ty nhiều hơn."),
    ],
    exercises: [
      ex("Tự viết: Gần đây tôi bận suốt.", "最近我一直很忙。"),
      ex("Tự viết: Tôi vừa về.", "我刚才回来。"),
    ],
    scenario: "Bạn cũ hỏi gần đây bạn thế nào, vừa làm gì, trước đây có bận không.",
    start: "最近你怎么样？",
  },
  {
    id: 114,
    theme: "Gặp và tham gia",
    kind: "learn",
    vocab: [
      v("见面", "jiànmiàn", "Gặp mặt", "我们明天见。", "Wǒmen míngtiān jiànmiàn.", "Mai chúng ta gặp."),
      v("参加", "cānjiā", "Tham gia", "我想参加。", "Wǒ xiǎng cānjiā.", "Tôi muốn tham gia."),
      v("机会", "jīhuì", "Cơ hội", "这是好机会。", "Zhè shì hǎo jīhuì.", "Đây là cơ hội tốt."),
      v("出现", "chūxiàn", "Xuất hiện", "他没出现。", "Tā méi chūxiàn.", "Anh ấy không xuất hiện."),
      v("发现", "fāxiàn", "Phát hiện", "我发现一个问题。", "Wǒ fāxiàn yí ge wèntí.", "Tôi phát hiện một vấn đề."),
    ],
    grammar: {
      title: "参加 + sự kiện",
      pattern: "参加 + N",
      explainVi: "参加 đi với hoạt động: 参加考试、参加会议. 见面 là động từ gặp nhau, không cần tân ngữ người.",
      drills: [
        drill("Dịch: Mai chúng ta gặp.", "我们明天见。"),
        drill("Dịch: Tôi muốn tham gia.", "我想参加。"),
        drill("Dịch: Đây là cơ hội tốt.", "这是好机会。"),
        drill("Dịch: Tôi phát hiện vấn đề.", "我发现一个问题。"),
      ],
    },
    dialogue: [
      line("A", "周末我们见面，好吗？", "Zhōumò wǒmen jiànmiàn, hǎo ma?", "Cuối tuần gặp nhau nhé?"),
      line("B", "好。你参加吗？", "Hǎo. Nǐ cānjiā ma?", "Được. Bạn tham gia không?"),
      line("A", "想。这是好机会。", "Xiǎng. Zhè shì hǎo jīhuì.", "Muốn. Đây là cơ hội tốt."),
      line("B", "刚才我发现他没出现。", "Gāngcái wǒ fāxiàn tā méi chūxiàn.", "Vừa rồi tôi thấy anh ấy không đến."),
    ],
    exercises: [
      ex("Tự viết: Cuối tuần chúng ta gặp.", "周末我们见面。"),
      ex("Tự viết: Tôi muốn tham gia. Đây là cơ hội tốt.", "我想参加。这是好机会。"),
    ],
    scenario: "Hẹn gặp cuối tuần, hỏi có tham gia hoạt động không, ai chưa xuất hiện.",
    start: "周末我们见面，好吗？",
  },
  {
    id: 115,
    theme: "Lễ và tuần",
    kind: "learn",
    vocab: [
      v("节日", "jiérì", "Ngày lễ", "春节是节日。", "Chūnjié shì jiérì.", "Tết là ngày lễ."),
      v("周末", "zhōumò", "Cuối tuần", "周末你做什么？", "Zhōumò nǐ zuò shénme?", "Cuối tuần bạn làm gì?"),
      v("结束", "jiéshù", "Kết thúc", "会议结束了。", "Huìyì jiéshù le.", "Họp đã kết thúc."),
      v("离开", "líkāi", "Rời đi", "我明天离开。", "Wǒ míngtiān líkāi.", "Mai tôi rời đi."),
      v("回来", "huílai", "Quay về", "你什么时候回来？", "Nǐ shénme shíhou huílai?", "Bạn khi nào về?"),
    ],
    grammar: {
      title: "周末 + động từ",
      pattern: "周末 + V",
      explainVi: "周末 đặt trước hành động. 结束 / 离开 / 回来 nói việc khép lại hay đi-về.",
      drills: [
        drill("Dịch: Cuối tuần bạn làm gì?", "周末你做什么？"),
        drill("Dịch: Họp đã kết thúc.", "会议结束了。"),
        drill("Dịch: Mai tôi rời đi.", "我明天离开。"),
        drill("Dịch: Bạn khi nào về?", "你什么时候回来？"),
      ],
    },
    dialogue: [
      line("A", "节日你回家吗？", "Jiérì nǐ huí jiā ma?", "Ngày lễ bạn về nhà không?"),
      line("B", "回。周末结束以后我离开。", "Huí. Zhōumò jiéshù yǐhòu wǒ líkāi.", "Có. Hết cuối tuần tôi đi."),
      line("A", "你什么时候回来？", "Nǐ shénme shíhou huílai?", "Bạn khi nào về?"),
      line("B", "下个周末回来。我们见面吧。", "Xià ge zhōumò huílai. Wǒmen jiànmiàn ba.", "Cuối tuần sau về. Gặp nhau nhé."),
    ],
    exercises: [
      ex("Tự viết: Ngày lễ bạn về nhà không?", "节日你回家吗？"),
      ex("Tự viết: Cuối tuần tôi rời đi, tuần sau về.", "周末我离开，下个周末回来。"),
    ],
    scenario: "Hỏi kế hoạch ngày lễ / cuối tuần: về nhà, rời đi, khi nào quay lại.",
    start: "节日你回家吗？",
  },
  {
    id: 116,
    theme: "Nhớ / quên",
    kind: "learn",
    vocab: [
      v("记得", "jìde", "Nhớ", "我记得你。", "Wǒ jìde nǐ.", "Tôi nhớ bạn."),
      v("忘记", "wàngjì", "Quên", "我忘记带书。", "Wǒ wàngjì dài shū.", "Tôi quên mang sách."),
      v("经过", "jīngguò", "Đi qua / trải qua", "我经过学校。", "Wǒ jīngguò xuéxiào.", "Tôi đi qua trường."),
      v("中间", "zhōngjiān", "Ở giữa", "坐在中间。", "Zuò zài zhōngjiān.", "Ngồi ở giữa."),
    ],
    grammar: {
      title: "记得 / 忘记 + việc",
      pattern: "记得 / 忘记 + V / N",
      explainVi: "记得: còn nhớ. 忘记: đã quên. Có thể kèm động từ: 忘记带书.",
      drills: [
        drill("Dịch: Tôi nhớ bạn.", "我记得你。"),
        drill("Dịch: Tôi quên mang sách.", "我忘记带书。"),
        drill("Dịch: Tôi đi qua trường.", "我经过学校。"),
        drill("Dịch: Ngồi ở giữa.", "坐在中间。"),
      ],
    },
    dialogue: [
      line("A", "你记得那个地方吗？", "Nǐ jìde nàge dìfang ma?", "Bạn nhớ chỗ đó không?"),
      line("B", "记得。经过银行就到了。", "Jìde. Jīngguò yínháng jiù dào le.", "Nhớ. Đi qua ngân hàng là tới."),
      line("A", "我忘记带地图了。", "Wǒ wàngjì dài dìtú le.", "Tôi quên mang bản đồ."),
      line("B", "没关系。你站在中间等我。", "Méi guānxi. Nǐ zhàn zài zhōngjiān děng wǒ.", "Không sao. Đứng giữa đợi tôi."),
    ],
    exercises: [
      ex("Tự viết: Tôi quên mang sách.", "我忘记带书。"),
      ex("Tự viết: Đi qua ngân hàng là tới.", "经过银行就到了。"),
    ],
    scenario: "Nhắc chỗ hẹn: còn nhớ đường không, quên mang gì, đứng ở giữa đợi.",
    start: "你记得那个地方吗？",
  },
  {
    id: 117,
    theme: "Nếu / hoặc",
    kind: "learn",
    vocab: [
      v("或者", "huòzhě", "Hoặc", "茶或者水？", "Chá huòzhě shuǐ?", "Trà hoặc nước?"),
      v("如果", "rúguǒ", "Nếu", "如果下雨就不去。", "Rúguǒ xià yǔ jiù bú qù.", "Nếu mưa thì không đi."),
      v("选择", "xuǎnzé", "Lựa chọn", "你选择哪个？", "Nǐ xuǎnzé nǎge?", "Bạn chọn cái nào?"),
      v("还是", "háishì", "Hay là (ôn)", "茶还是水？", "Chá háishì shuǐ?", "Trà hay nước?"),
    ],
    grammar: {
      title: "如果…就…",
      pattern: "如果 + điều kiện，就 + kết quả",
      explainVi: "Nếu… thì…. 或者 nối hai lựa chọn (không phải câu hỏi A还是B).",
      drills: [
        drill("Dịch: Trà hoặc nước?", "茶或者水？"),
        drill("Dịch: Nếu mưa thì không đi.", "如果下雨就不去。"),
        drill("Dịch: Bạn chọn cái nào?", "你选择哪个？"),
        drill("Dịch: Nếu rảnh thì gặp.", "如果有时间就见面。"),
      ],
    },
    dialogue: [
      line("A", "周末你选择做什么？", "Zhōumò nǐ xuǎnzé zuò shénme?", "Cuối tuần bạn chọn làm gì?"),
      line("B", "看电影或者去公园。", "Kàn diànyǐng huòzhě qù gōngyuán.", "Xem phim hoặc đi công viên."),
      line("A", "如果下雨呢？", "Rúguǒ xià yǔ ne?", "Nếu mưa thì sao?"),
      line("B", "如果下雨就在家。你呢？", "Rúguǒ xià yǔ jiù zài jiā. Nǐ ne?", "Nếu mưa thì ở nhà. Còn bạn?"),
    ],
    exercises: [
      ex("Tự viết: Xem phim hoặc đi công viên.", "看电影或者去公园。"),
      ex("Tự viết: Nếu mưa thì ở nhà.", "如果下雨就在家。"),
    ],
    scenario: "Chọn việc cuối tuần: phim hoặc công viên; nếu mưa thì đổi kế hoạch.",
    start: "周末你选择做什么？",
  },
  {
    id: 118,
    theme: "Tổng hợp gặp gỡ",
    kind: "review",
    vocab: [
      v("刚才", "gāngcái", "Vừa mới (ôn)", "我刚才回来。", "Wǒ gāngcái huílai.", "Tôi vừa về."),
      v("见面", "jiànmiàn", "Gặp mặt (ôn)", "我们见面吧。", "Wǒmen jiànmiàn ba.", "Gặp nhau nhé."),
      v("周末", "zhōumò", "Cuối tuần (ôn)", "周末见。", "Zhōumò jiàn.", "Cuối tuần gặp."),
      v("忘记", "wàngjì", "Quên (ôn)", "别忘记。", "Bié wàngjì.", "Đừng quên."),
      v("如果", "rúguǒ", "Nếu (ôn)", "如果有时间就来。", "Rúguǒ yǒu shíjiān jiù lái.", "Nếu có giờ thì đến."),
    ],
    grammar: {
      title: "vừa / nếu",
      pattern: "刚才 / 如果…就…",
      explainVi: "Ôn tuần 17: kể việc vừa xảy ra và hẹn gặp có điều kiện.",
      drills: [
        drill("Dịch: Tôi vừa về. Gặp nhau nhé.", "我刚才回来。我们见面吧。"),
        drill("Dịch: Cuối tuần gặp. Đừng quên.", "周末见。别忘记。"),
        drill("Dịch: Nếu có giờ thì đến.", "如果有时间就来。"),
        drill("Dịch: Bạn chọn ngày nào?", "你选择哪一天？"),
      ],
    },
    dialogue: [
      line("A", "刚才你给我打电话了吗？", "Gāngcái nǐ gěi wǒ dǎ diànhuà le ma?", "Vừa rồi bạn gọi tôi à?"),
      line("B", "打了。周末我们见面吧。", "Dǎ le. Zhōumò wǒmen jiànmiàn ba.", "Có. Cuối tuần gặp nhau nhé."),
      line("A", "如果我有时间就来。", "Rúguǒ wǒ yǒu shíjiān jiù lái.", "Nếu tôi có giờ thì đến."),
      line("B", "好。别忘记这个机会。", "Hǎo. Bié wàngjì zhège jīhuì.", "Được. Đừng quên cơ hội này."),
    ],
    exercises: [
      ex("Tự viết: Cuối tuần gặp. Đừng quên.", "周末见。别忘记。"),
      ex("Tự viết: Nếu có giờ thì đến.", "如果有时间就来。"),
    ],
    scenario: "Hẹn cuối tuần: vừa gọi, nếu rảnh thì gặp, đừng quên.",
    start: "刚才你给我打电话了吗？",
  },
  {
    id: 119,
    theme: "Bạn cũ gặp lại",
    kind: "review",
    vocab: [
      v("最近", "zuìjìn", "Gần đây (ôn)", "最近好吗？", "Zuìjìn hǎo ma?", "Gần đây ổn không?"),
      v("以前", "yǐqián", "Trước đây (ôn)", "以前我们是同学。", "Yǐqián wǒmen shì tóngxué.", "Trước là bạn cùng lớp."),
      v("参加", "cānjiā", "Tham gia (ôn)", "你参加吗？", "Nǐ cānjiā ma?", "Bạn tham gia không?"),
      v("回来", "huílai", "Quay về (ôn)", "你回来了。", "Nǐ huílai le.", "Bạn đã về."),
      v("或者", "huòzhě", "Hoặc (ôn)", "今天或者明天。", "Jīntiān huòzhě míngtiān.", "Hôm nay hoặc ngày mai."),
    ],
    grammar: {
      title: "Chỉ hẹn / lễ",
      pattern: "最近 / 以前 / 或者",
      explainVi: "Roleplay: bạn cũ gặp lại. Khoá từ tuần 17.",
      drills: [
        drill("Dịch: Gần đây ổn không?", "最近好吗？"),
        drill("Dịch: Trước là bạn cùng lớp.", "以前我们是同学。"),
        drill("Dịch: Bạn tham gia không?", "你参加吗？"),
        drill("Dịch: Hôm nay hoặc ngày mai.", "今天或者明天。"),
      ],
    },
    dialogue: [
      line("A", "你回来了！最近怎么样？", "Nǐ huílai le! Zuìjìn zěnmeyàng?", "Bạn về rồi! Gần đây thế nào?"),
      line("B", "还好。以前我们是同学，记得吗？", "Hái hǎo. Yǐqián wǒmen shì tóngxué, jìde ma?", "Ổn. Trước là bạn cùng lớp, nhớ không?"),
      line("A", "记得。周末你参加吗？", "Jìde. Zhōumò nǐ cānjiā ma?", "Nhớ. Cuối tuần bạn tham gia không?"),
      line("B", "今天或者明天都可以见面。", "Jīntiān huòzhě míngtiān dōu kěyǐ jiànmiàn.", "Hôm nay hoặc mai đều gặp được."),
    ],
    exercises: [
      ex("Tự viết: Bạn về rồi! Gần đây thế nào?", "你回来了！最近怎么样？"),
      ex("Tự viết: Hôm nay hoặc mai đều gặp được.", "今天或者明天都可以见面。"),
    ],
    scenario: "Bạn cũ gặp lại sau chuyến đi: hỏi gần đây, nhớ lớp cũ, hẹn hôm nay hoặc mai.",
    start: "你回来了！最近怎么样？",
  },
  {
    id: 120,
    theme: "Lo lắng",
    kind: "learn",
    vocab: [
      v("担心", "dānxīn", "Lo lắng", "我很担心你。", "Wǒ hěn dānxīn nǐ.", "Tôi rất lo cho bạn."),
      v("害怕", "hàipà", "Sợ", "我害怕考试。", "Wǒ hàipà kǎoshì.", "Tôi sợ thi."),
      v("难过", "nánguò", "Buồn", "他很难过。", "Tā hěn nánguò.", "Anh ấy rất buồn."),
      v("着急", "zháojí", "Sốt ruột", "别着急。", "Bié zháojí.", "Đừng sốt ruột."),
    ],
    grammar: {
      title: "越来越 + tính từ",
      pattern: "越来越 + adj",
      explainVi: "Ngày càng…. 我越来越担心。Không thêm 很 trước 越来越.",
      drills: [
        drill("Dịch: Tôi lo cho bạn.", "我很担心你。"),
        drill("Dịch: Đừng sốt ruột.", "别着急。"),
        drill("Dịch: Tôi ngày càng lo.", "我越来越担心。"),
        drill("Dịch: Anh ấy rất buồn.", "他很难过。"),
      ],
    },
    dialogue: [
      line("A", "你怎么了？你很难过吗？", "Nǐ zěnme le? Nǐ hěn nánguò ma?", "Bạn sao thế? Bạn buồn à?"),
      line("B", "我害怕考试，越来越担心。", "Wǒ hàipà kǎoshì, yuè lái yuè dānxīn.", "Tôi sợ thi, ngày càng lo."),
      line("A", "别着急。我可以帮助你。", "Bié zháojí. Wǒ kěyǐ bāngzhù nǐ.", "Đừng sốt ruột. Tôi có thể giúp."),
      line("B", "谢谢。我现在好一点儿。", "Xièxie. Wǒ xiànzài hǎo yìdiǎnr.", "Cảm ơn. Giờ đỡ hơn."),
    ],
    exercises: [
      ex("Tự viết: Tôi sợ thi, ngày càng lo.", "我害怕考试，越来越担心。"),
      ex("Tự viết: Đừng sốt ruột.", "别着急。"),
    ],
    scenario: "An ủi bạn đang lo thi: đừng sốt ruột, có thể giúp.",
    start: "你怎么了？你很难过吗？",
  },
  {
    id: 121,
    theme: "Khỏe / ốm 2",
    kind: "learn",
    vocab: [
      v("舒服", "shūfu", "Dễ chịu", "我不太舒服。", "Wǒ bú tài shūfu.", "Tôi không được khỏe."),
      v("健康", "jiànkāng", "Khỏe mạnh", "身体健康。", "Shēntǐ jiànkāng.", "Sức khỏe tốt."),
      v("感冒", "gǎnmào", "Cảm cúm", "我感冒了。", "Wǒ gǎnmào le.", "Tôi bị cảm rồi."),
      v("发烧", "fāshāo", "Sốt", "他在发烧。", "Tā zài fāshāo.", "Anh ấy đang sốt."),
      v("疼", "téng", "Đau", "我头疼。", "Wǒ tóu téng.", "Tôi đau đầu."),
    ],
    grammar: {
      title: "V + 了 (ốm)",
      pattern: "感冒了 / 发烧了",
      explainVi: "Tình trạng bệnh dùng 了: 我感冒了。疼 đi sau bộ phận: 头疼、眼睛疼.",
      drills: [
        drill("Dịch: Tôi không được khỏe.", "我不太舒服。"),
        drill("Dịch: Tôi bị cảm rồi.", "我感冒了。"),
        drill("Dịch: Anh ấy đang sốt.", "他在发烧。"),
        drill("Dịch: Tôi đau đầu.", "我头疼。"),
      ],
    },
    dialogue: [
      line("A", "你不舒服吗？怎么了？", "Nǐ bù shūfu ma? Zěnme le?", "Bạn không khỏe à? Sao thế?"),
      line("B", "我感冒了，有点儿发烧。", "Wǒ gǎnmào le, yǒudiǎnr fāshāo.", "Tôi cảm, hơi sốt."),
      line("A", "头疼吗？要去看医生吗？", "Tóu téng ma? Yào qù kàn yīshēng ma?", "Đau đầu không? Có cần khám?"),
      line("B", "疼。我想身体健康，所以去医院。", "Téng. Wǒ xiǎng shēntǐ jiànkāng, suǒyǐ qù yīyuàn.", "Đau. Muốn khỏe nên đi bệnh viện."),
    ],
    exercises: [
      ex("Tự viết: Tôi cảm, hơi sốt.", "我感冒了，有点儿发烧。"),
      ex("Tự viết: Tôi đau đầu.", "我头疼。"),
    ],
    scenario: "Hỏi thăm bạn ốm: cảm, sốt, đau đầu, có đi khám không.",
    start: "你不舒服吗？怎么了？",
  },
  {
    id: 122,
    theme: "Vệ sinh thân",
    kind: "learn",
    vocab: [
      v("饿", "è", "Đói", "我饿了。", "Wǒ è le.", "Tôi đói rồi."),
      v("渴", "kě", "Khát", "我很渴。", "Wǒ hěn kě.", "Tôi rất khát."),
      v("刷牙", "shuāyá", "Đánh răng", "早上刷牙。", "Zǎoshang shuāyá.", "Sáng đánh răng."),
      v("洗澡", "xǐzǎo", "Tắm", "晚上洗澡。", "Wǎnshang xǐzǎo.", "Tối tắm."),
      v("干净", "gānjìng", "Sạch", "房间很干净。", "Fángjiān hěn gānjìng.", "Phòng rất sạch."),
    ],
    grammar: {
      title: "先…再… (ôn)",
      pattern: "先 + V1，再 + V2",
      explainVi: "Làm lần lượt: 先刷牙，再洗澡。饿了 / 渴了 thường kèm 了.",
      drills: [
        drill("Dịch: Tôi đói rồi.", "我饿了。"),
        drill("Dịch: Tôi rất khát.", "我很渴。"),
        drill("Dịch: Sáng đánh răng.", "早上刷牙。"),
        drill("Dịch: Trước đánh răng, rồi tắm.", "先刷牙，再洗澡。"),
      ],
    },
    dialogue: [
      line("A", "你饿了吗？想吃饭吗？", "Nǐ è le ma? Xiǎng chī fàn ma?", "Bạn đói chưa? Muốn ăn không?"),
      line("B", "饿了，也渴。先喝水。", "È le, yě kě. Xiān hē shuǐ.", "Đói rồi, cũng khát. Uống nước trước."),
      line("A", "晚上你先洗澡再睡觉吗？", "Wǎnshang nǐ xiān xǐzǎo zài shuìjiào ma?", "Tối bạn tắm rồi mới ngủ à?"),
      line("B", "是。先刷牙，再洗澡。这样干净。", "Shì. Xiān shuāyá, zài xǐzǎo. Zhèyàng gānjìng.", "Phải. Đánh răng rồi tắm. Như thế sạch."),
    ],
    exercises: [
      ex("Tự viết: Tôi đói rồi, cũng khát.", "我饿了，也渴。"),
      ex("Tự viết: Trước đánh răng, rồi tắm.", "先刷牙，再洗澡。"),
    ],
    scenario: "Hỏi bạn đói/khát chưa, tối tắm và đánh răng theo thứ tự nào.",
    start: "你饿了吗？想吃饭吗？",
  },
  {
    id: 123,
    theme: "Thái độ",
    kind: "learn",
    vocab: [
      v("安静", "ānjìng", "Yên tĩnh", "请安静。", "Qǐng ānjìng.", "Xin hãy yên lặng."),
      v("热情", "rèqíng", "Nhiệt tình", "她很热情。", "Tā hěn rèqíng.", "Cô ấy rất nhiệt tình."),
      v("认真", "rènzhēn", "Nghiêm túc", "他学习很认真。", "Tā xuéxí hěn rènzhēn.", "Anh ấy học rất nghiêm túc."),
      v("简单", "jiǎndān", "Đơn giản", "这个问题很简单。", "Zhège wèntí hěn jiǎndān.", "Câu này rất đơn giản."),
    ],
    grammar: {
      title: "tính từ + 极了",
      pattern: "adj + 极了",
      explainVi: "Cực kỳ: 简单极了、好极了. Mạnh hơn 很, không thêm 很 phía trước.",
      drills: [
        drill("Dịch: Xin hãy yên lặng.", "请安静。"),
        drill("Dịch: Cô ấy rất nhiệt tình.", "她很热情。"),
        drill("Dịch: Anh ấy học rất nghiêm túc.", "他学习很认真。"),
        drill("Dịch: Câu này đơn giản cực.", "这个问题简单极了。"),
      ],
    },
    dialogue: [
      line("A", "教室里请安静。大家认真一点儿。", "Jiàoshì lǐ qǐng ānjìng. Dàjiā rènzhēn yìdiǎnr.", "Trong lớp hãy yên. Mọi người nghiêm túc hơn."),
      line("B", "这个问题简单极了。", "Zhège wèntí jiǎndān jí le.", "Câu này đơn giản cực."),
      line("A", "老师很热情，也讲得很清楚。", "Lǎoshī hěn rèqíng, yě jiǎng de hěn qīngchu.", "Cô rất nhiệt tình, giảng cũng rõ."),
      line("B", "是。我越来越喜欢这门课。", "Shì. Wǒ yuè lái yuè xǐhuan zhè mén kè.", "Phải. Tôi ngày càng thích môn này."),
    ],
    exercises: [
      ex("Tự viết: Xin hãy yên lặng. Học nghiêm túc.", "请安静。学习要认真。"),
      ex("Tự viết: Câu này đơn giản cực.", "这个问题简单极了。"),
    ],
    scenario: "Trong lớp: nhắc yên lặng, khen cô nhiệt tình, bài đơn giản cực.",
    start: "教室里请安静。",
  },
  {
    id: 124,
    theme: "Rõ / thật ra",
    kind: "learn",
    vocab: [
      v("容易", "róngyì", "Dễ", "汉语不容易。", "Hànyǔ bù róngyì.", "Tiếng Trung không dễ."),
      v("清楚", "qīngchu", "Rõ ràng", "我说得清楚吗？", "Wǒ shuō de qīngchu ma?", "Tôi nói có rõ không?"),
      v("其实", "qíshí", "Thật ra", "其实不难。", "Qíshí bù nán.", "Thật ra không khó."),
      v("当然", "dāngrán", "Đương nhiên", "当然可以。", "Dāngrán kěyǐ.", "Đương nhiên được."),
    ],
    grammar: {
      title: "其实 / 当然",
      pattern: "其实 + câu / 当然 + V",
      explainVi: "其实 sửa hiểu lầm. 当然: lẽ đương nhiên, trả lời nhanh.",
      drills: [
        drill("Dịch: Tiếng Trung không dễ.", "汉语不容易。"),
        drill("Dịch: Tôi nói có rõ không?", "我说得清楚吗？"),
        drill("Dịch: Thật ra không khó.", "其实不难。"),
        drill("Dịch: Đương nhiên được.", "当然可以。"),
      ],
    },
    dialogue: [
      line("A", "汉语容易吗？我听不清楚。", "Hànyǔ róngyì ma? Wǒ tīng bù qīngchu.", "Tiếng Trung dễ không? Tôi nghe không rõ."),
      line("B", "其实不太难。你认真就行。", "Qíshí bú tài nán. Nǐ rènzhēn jiù xíng.", "Thật ra không khó lắm. Nghiêm túc là được."),
      line("A", "你可以帮助我吗？", "Nǐ kěyǐ bāngzhù wǒ ma?", "Bạn có thể giúp tôi không?"),
      line("B", "当然可以。别着急。", "Dāngrán kěyǐ. Bié zháojí.", "Đương nhiên được. Đừng sốt ruột."),
    ],
    exercises: [
      ex("Tự viết: Thật ra không khó.", "其实不难。"),
      ex("Tự viết: Đương nhiên được. Đừng sốt ruột.", "当然可以。别着急。"),
    ],
    scenario: "Bạn nghĩ tiếng Trung khó; giải thích thật ra không khó và nhận giúp.",
    start: "汉语容易吗？我听不清楚。",
  },
  {
    id: 125,
    theme: "Tổng hợp sức khỏe",
    kind: "review",
    vocab: [
      v("担心", "dānxīn", "Lo (ôn)", "别担心。", "Bié dānxīn.", "Đừng lo."),
      v("感冒", "gǎnmào", "Cảm (ôn)", "他感冒了。", "Tā gǎnmào le.", "Anh ấy bị cảm."),
      v("舒服", "shūfu", "Khỏe (ôn)", "现在舒服了。", "Xiànzài shūfu le.", "Giờ khỏe rồi."),
      v("认真", "rènzhēn", "Nghiêm túc (ôn)", "吃药要认真。", "Chī yào yào rènzhēn.", "Uống thuốc phải đúng."),
      v("其实", "qíshí", "Thật ra (ôn)", "其实不严重。", "Qíshí bù yánzhòng.", "Thật ra không nặng."),
    ],
    grammar: {
      title: "hỏi thăm",
      pattern: "越来越 / 其实",
      explainVi: "Ôn tuần 18: thăm bạn bị cảm, an ủi đừng lo.",
      drills: [
        drill("Dịch: Đừng lo. Anh ấy bị cảm.", "别担心。他感冒了。"),
        drill("Dịch: Giờ khỏe rồi.", "现在舒服了。"),
        drill("Dịch: Thật ra không nặng.", "其实不严重。"),
        drill("Dịch: Đương nhiên được.", "当然可以。"),
      ],
    },
    dialogue: [
      line("A", "我很担心你。你还发烧吗？", "Wǒ hěn dānxīn nǐ. Nǐ hái fāshāo ma?", "Tôi lo cho bạn. Còn sốt không?"),
      line("B", "不烧了。其实就是感冒。", "Bù shāo le. Qíshí jiù shì gǎnmào.", "Hết sốt. Thật ra chỉ là cảm."),
      line("A", "现在舒服了吗？", "Xiànzài shūfu le ma?", "Giờ khỏe chưa?"),
      line("B", "舒服多了。别着急。", "Shūfu duō le. Bié zháojí.", "Khỏe hơn nhiều. Đừng sốt ruột."),
    ],
    exercises: [
      ex("Tự viết: Đừng lo. Thật ra chỉ là cảm.", "别担心。其实就是感冒。"),
      ex("Tự viết: Giờ khỏe rồi.", "现在舒服了。"),
    ],
    scenario: "Thăm bạn bị cảm: còn sốt không, thật ra không nặng, giờ đã khỏe.",
    start: "我很担心你。你还发烧吗？",
  },
  {
    id: 126,
    theme: "Bác sĩ vs bệnh nhân",
    kind: "review",
    vocab: [
      v("发烧", "fāshāo", "Sốt (ôn)", "还发烧吗？", "Hái fāshāo ma?", "Còn sốt không?"),
      v("疼", "téng", "Đau (ôn)", "哪里疼？", "Nǎlǐ téng?", "Đau chỗ nào?"),
      v("洗澡", "xǐzǎo", "Tắm (ôn)", "先别洗澡。", "Xiān bié xǐzǎo.", "Đừng tắm vội."),
      v("干净", "gānjìng", "Sạch (ôn)", "房间要干净。", "Fángjiān yào gānjìng.", "Phòng phải sạch."),
      v("当然", "dāngrán", "Đương nhiên (ôn)", "当然要休息。", "Dāngrán yào xiūxi.", "Đương nhiên phải nghỉ."),
    ],
    grammar: {
      title: "Chỉ bệnh / cảm xúc",
      pattern: "感冒 / 疼 / 当然",
      explainVi: "Roleplay phòng khám. Khoá từ đến tuần 18.",
      drills: [
        drill("Dịch: Còn sốt không? Đau chỗ nào?", "还发烧吗？哪里疼？"),
        drill("Dịch: Đừng tắm vội.", "先别洗澡。"),
        drill("Dịch: Phòng phải sạch.", "房间要干净。"),
        drill("Dịch: Đương nhiên phải nghỉ.", "当然要休息。"),
      ],
    },
    dialogue: [
      line("A", "医生，我头疼，还发烧。", "Yīshēng, wǒ tóu téng, hái fāshāo.", "Bác sĩ, tôi đau đầu, còn sốt."),
      line("B", "你感冒了。先别洗澡，要休息。", "Nǐ gǎnmào le. Xiān bié xǐzǎo, yào xiūxi.", "Bạn bị cảm. Đừng tắm, hãy nghỉ."),
      line("A", "房间也要干净吗？", "Fángjiān yě yào gānjìng ma?", "Phòng cũng phải sạch à?"),
      line("B", "当然。别担心，很快就舒服。", "Dāngrán. Bié dānxīn, hěn kuài jiù shūfu.", "Đương nhiên. Đừng lo, mau khỏe."),
    ],
    exercises: [
      ex("Tự viết: Tôi đau đầu, còn sốt.", "我头疼，还发烧。"),
      ex("Tự viết: Đừng tắm, hãy nghỉ.", "先别洗澡，要休息。"),
    ],
    scenario: "Khám cảm: đau đầu, sốt; bác sĩ dặn nghỉ, đừng tắm, giữ phòng sạch.",
    start: "医生，我头疼，还发烧。",
  },
  {
    id: 127,
    theme: "Thành phố",
    kind: "learn",
    vocab: [
      v("城市", "chéngshì", "Thành phố", "北京是大城市。", "Běijīng shì dà chéngshì.", "Bắc Kinh là thành phố lớn."),
      v("地方", "dìfang", "Nơi / chỗ", "这是什么地方？", "Zhè shì shénme dìfang?", "Đây là chỗ gì?"),
      v("附近", "fùjìn", "Gần đây", "附近有地铁。", "Fùjìn yǒu dìtiě.", "Gần đây có tàu điện."),
      v("方便", "fāngbiàn", "Tiện", "这儿很方便。", "Zhèr hěn fāngbiàn.", "Ở đây rất tiện."),
      v("地铁", "dìtiě", "Tàu điện ngầm", "坐地铁去。", "Zuò dìtiě qù.", "Đi tàu điện ngầm."),
    ],
    grammar: {
      title: "A 附近",
      pattern: "N 附近 + 有 / 很方便",
      explainVi: "附近: khu vực lân cận. 学校附近有地铁.",
      drills: [
        drill("Dịch: Bắc Kinh là thành phố lớn.", "北京是大城市。"),
        drill("Dịch: Đây là chỗ gì?", "这是什么地方？"),
        drill("Dịch: Gần đây có tàu điện.", "附近有地铁。"),
        drill("Dịch: Ở đây rất tiện.", "这儿很方便。"),
      ],
    },
    dialogue: [
      line("A", "你觉得这个城市怎么样？", "Nǐ juéde zhège chéngshì zěnmeyàng?", "Bạn thấy thành phố này thế nào?"),
      line("B", "很好。附近有地铁，很方便。", "Hěn hǎo. Fùjìn yǒu dìtiě, hěn fāngbiàn.", "Tốt. Gần có tàu, rất tiện."),
      line("A", "去公司坐地铁吗？", "Qù gōngsī zuò dìtiě ma?", "Đi công ty đi tàu à?"),
      line("B", "是。这个地方我很喜欢。", "Shì. Zhège dìfang wǒ hěn xǐhuan.", "Phải. Chỗ này tôi thích."),
    ],
    exercises: [
      ex("Tự viết: Gần đây có tàu điện, rất tiện.", "附近有地铁，很方便。"),
      ex("Tự viết: Đây là chỗ gì?", "这是什么地方？"),
    ],
    scenario: "Nói về chỗ ở mới: thành phố, gần có tàu, đi làm tiện.",
    start: "你觉得这个城市怎么样？",
  },
  {
    id: 128,
    theme: "Trong nhà",
    kind: "learn",
    vocab: [
      v("电梯", "diàntī", "Thang máy", "坐电梯上楼。", "Zuò diàntī shàng lóu.", "Đi thang máy lên lầu."),
      v("地图", "dìtú", "Bản đồ", "看一下地图。", "Kàn yíxià dìtú.", "Xem bản đồ một chút."),
      v("站", "zhàn", "Ga / trạm", "下一站是学校。", "Xià yí zhàn shì xuéxiào.", "Ga sau là trường."),
      v("楼", "lóu", "Tòa nhà / lầu", "我在三号楼。", "Wǒ zài sān hào lóu.", "Tôi ở tòa số 3."),
      v("层", "céng", "Tầng", "三层。", "Sān céng.", "Tầng ba."),
    ],
    grammar: {
      title: "第 + số + 层",
      pattern: "在 + số + 层 / 号楼",
      explainVi: "Tầng dùng 层: 三层. Tòa nhà: 三号楼. Ga tàu: 站.",
      drills: [
        drill("Dịch: Đi thang máy lên lầu.", "坐电梯上楼。"),
        drill("Dịch: Xem bản đồ một chút.", "看一下地图。"),
        drill("Dịch: Ga sau là trường.", "下一站是学校。"),
        drill("Dịch: Tôi ở tầng ba.", "我在三层。"),
      ],
    },
    dialogue: [
      line("A", "办公室在几层？", "Bàngōngshì zài jǐ céng?", "Văn phòng ở tầng mấy?"),
      line("B", "在五层。坐电梯上去。", "Zài wǔ céng. Zuò diàntī shàng qù.", "Tầng năm. Đi thang máy lên."),
      line("A", "这是几号楼？我看一下地图。", "Zhè shì jǐ hào lóu? Wǒ kàn yíxià dìtú.", "Đây tòa số mấy? Tôi xem bản đồ."),
      line("B", "二号楼。地铁站就在附近。", "Èr hào lóu. Dìtiě zhàn jiù zài fùjìn.", "Tòa số 2. Ga tàu ngay gần."),
    ],
    exercises: [
      ex("Tự viết: Văn phòng ở tầng năm. Đi thang máy.", "办公室在五层。坐电梯。"),
      ex("Tự viết: Ga tàu ngay gần.", "地铁站就在附近。"),
    ],
    scenario: "Tìm văn phòng: tầng mấy, tòa số mấy, đi thang máy, ga tàu gần.",
    start: "办公室在几层？",
  },
  {
    id: 129,
    theme: "Phố và cửa",
    kind: "learn",
    vocab: [
      v("街道", "jiēdào", "Phố", "这条街道很安静。", "Zhè tiáo jiēdào hěn ānjìng.", "Phố này rất yên."),
      v("公园", "gōngyuán", "Công viên", "去公园走走。", "Qù gōngyuán zǒu zǒu.", "Đi công viên dạo."),
      v("银行", "yínháng", "Ngân hàng", "附近有银行。", "Fùjìn yǒu yínháng.", "Gần có ngân hàng."),
      v("超市", "chāoshì", "Siêu thị", "我去超市买东西。", "Wǒ qù chāoshì mǎi dōngxi.", "Tôi đi siêu thị mua đồ."),
    ],
    grammar: {
      title: "在 + chỗ",
      pattern: "在 + 街道 / 公园 / 银行",
      explainVi: "Chỉ vị trí phố, công viên, ngân hàng, siêu thị. 条 lượng từ cho phố.",
      drills: [
        drill("Dịch: Phố này rất yên.", "这条街道很安静。"),
        drill("Dịch: Đi công viên dạo.", "去公园走走。"),
        drill("Dịch: Gần có ngân hàng.", "附近有银行。"),
        drill("Dịch: Tôi đi siêu thị mua đồ.", "我去超市买东西。"),
      ],
    },
    dialogue: [
      line("A", "超市在哪条街道？", "Chāoshì zài nǎ tiáo jiēdào?", "Siêu thị ở phố nào?"),
      line("B", "在银行旁边。很方便。", "Zài yínháng pángbiān. Hěn fāngbiàn.", "Cạnh ngân hàng. Rất tiện."),
      line("A", "买完东西去公园，好吗？", "Mǎi wán dōngxi qù gōngyuán, hǎo ma?", "Mua xong đi công viên nhé?"),
      line("B", "好。那条街道也很安静。", "Hǎo. Nà tiáo jiēdào yě hěn ānjìng.", "Được. Phố đó cũng yên."),
    ],
    exercises: [
      ex("Tự viết: Siêu thị cạnh ngân hàng.", "超市在银行旁边。"),
      ex("Tự viết: Mua xong đi công viên.", "买完东西去公园。"),
    ],
    scenario: "Hỏi siêu thị ở phố nào, cạnh ngân hàng; mua xong đi công viên.",
    start: "超市在哪条街道？",
  },
  {
    id: 130,
    theme: "Chuyển / mang",
    kind: "learn",
    vocab: [
      v("办公室", "bàngōngshì", "Văn phòng", "去办公室开会。", "Qù bàngōngshì kāihuì.", "Đến văn phòng họp."),
      v("搬", "bān", "Chuyển / khiêng", "我搬家了。", "Wǒ bān jiā le.", "Tôi chuyển nhà rồi."),
      v("骑", "qí", "Cưỡi / đạp", "骑自行车。", "Qí zìxíngchē.", "Đạp xe."),
      v("带", "dài", "Mang theo", "带上护照。", "Dài shàng hùzhào.", "Mang hộ chiếu theo."),
      v("换", "huàn", "Đổi", "换地铁。", "Huàn dìtiě.", "Đổi tàu điện."),
    ],
    grammar: {
      title: "把 + tân ngữ + V",
      pattern: "把 + O + V (+ chỗ)",
      explainVi: "把 đưa việc xử lý đồ vật ra trước: 把东西搬到办公室. Ngày này tập 把 nhẹ.",
      drills: [
        drill("Dịch: Tôi chuyển nhà rồi.", "我搬家了。"),
        drill("Dịch: Đạp xe đi.", "骑自行车去。"),
        drill("Dịch: Đổi tàu điện.", "换地铁。"),
        drill("Dịch: Đưa đồ vào văn phòng.", "把东西搬到办公室。"),
      ],
    },
    dialogue: [
      line("A", "你怎么去新办公室？", "Nǐ zěnme qù xīn bàngōngshì?", "Bạn đến văn phòng mới bằng gì?"),
      line("B", "先骑自行车，再换地铁。", "Xiān qí zìxíngchē, zài huàn dìtiě.", "Đạp xe rồi đổi tàu."),
      line("A", "东西呢？你带了吗？", "Dōngxi ne? Nǐ dài le ma?", "Đồ đạc? Bạn mang chưa?"),
      line("B", "带了。请帮我把箱子搬上去。", "Dài le. Qǐng bāng wǒ bǎ xiāngzi bān shàng qù.", "Mang rồi. Nhờ khiêng thùng lên."),
    ],
    exercises: [
      ex("Tự viết: Đạp xe rồi đổi tàu.", "先骑自行车，再换地铁。"),
      ex("Tự viết: Đưa đồ vào văn phòng.", "把东西搬到办公室。"),
    ],
    scenario: "Chuyển văn phòng: đi xe rồi đổi tàu, nhờ khiêng đồ lên.",
    start: "你怎么去新办公室？",
  },
  {
    id: 131,
    theme: "Bay / hộ chiếu",
    kind: "learn",
    vocab: [
      v("护照", "hùzhào", "Hộ chiếu", "护照在这儿。", "Hùzhào zài zhèr.", "Hộ chiếu ở đây."),
      v("行李箱", "xínglixiāng", "Vali", "行李箱太重了。", "Xínglixiāng tài zhòng le.", "Vali nặng quá."),
      v("起飞", "qǐfēi", "Cất cánh", "飞机要起飞了。", "Fēijī yào qǐfēi le.", "Máy bay sắp cất cánh."),
      v("离开", "líkāi", "Rời đi (ôn)", "快要离开了。", "Kuài yào líkāi le.", "Sắp rời đi rồi."),
    ],
    grammar: {
      title: "要…了",
      pattern: "要 + V + 了",
      explainVi: "Sắp xảy ra: 要起飞了、要离开了. Nhớ mang 护照 và 行李箱.",
      drills: [
        drill("Dịch: Hộ chiếu ở đây.", "护照在这儿。"),
        drill("Dịch: Vali nặng quá.", "行李箱太重了。"),
        drill("Dịch: Máy bay sắp cất cánh.", "飞机要起飞了。"),
        drill("Dịch: Đừng quên hộ chiếu.", "别忘记护照。"),
      ],
    },
    dialogue: [
      line("A", "护照带了吗？飞机要起飞了。", "Hùzhào dài le ma? Fēijī yào qǐfēi le.", "Mang hộ chiếu chưa? Máy bay sắp cất cánh."),
      line("B", "带了。行李箱在你旁边。", "Dài le. Xínglixiāng zài nǐ pángbiān.", "Mang rồi. Vali cạnh bạn."),
      line("A", "太好了。我们快走吧。", "Tài hǎo le. Wǒmen kuài zǒu ba.", "Tốt quá. Đi nhanh thôi."),
      line("B", "好。别着急，还有时间。", "Hǎo. Bié zháojí, hái yǒu shíjiān.", "Được. Đừng sốt, còn giờ."),
    ],
    exercises: [
      ex("Tự viết: Mang hộ chiếu chưa? Máy bay sắp cất cánh.", "护照带了吗？飞机要起飞了。"),
      ex("Tự viết: Vali cạnh bạn.", "行李箱在你旁边。"),
    ],
    scenario: "Ở sân bay: kiểm tra hộ chiếu, vali, máy bay sắp cất cánh.",
    start: "护照带了吗？飞机要起飞了。",
  },
  {
    id: 132,
    theme: "Hỏi đường 3",
    kind: "review",
    vocab: [
      v("附近", "fùjìn", "Gần (ôn)", "附近有站吗？", "Fùjìn yǒu zhàn ma?", "Gần có ga không?"),
      v("地铁", "dìtiě", "Tàu điện (ôn)", "坐地铁最方便。", "Zuò dìtiě zuì fāngbiàn.", "Đi tàu tiện nhất."),
      v("层", "céng", "Tầng (ôn)", "超市在地下一层。", "Chāoshì zài dìxià yì céng.", "Siêu thị ở tầng hầm 1."),
      v("换", "huàn", "Đổi (ôn)", "在下一站换。", "Zài xià yí zhàn huàn.", "Đổi ở ga sau."),
      v("地图", "dìtú", "Bản đồ (ôn)", "看地图。", "Kàn dìtú.", "Xem bản đồ."),
    ],
    grammar: {
      title: "附近 / 层",
      pattern: "附近有… / 在 + 层",
      explainVi: "Ôn tuần 19: tìm siêu thị gần ga, đổi tàu, xem tầng.",
      drills: [
        drill("Dịch: Gần có ga không?", "附近有站吗？"),
        drill("Dịch: Đi tàu tiện nhất.", "坐地铁最方便。"),
        drill("Dịch: Siêu thị ở tầng hầm 1.", "超市在地下一层。"),
        drill("Dịch: Đổi ở ga sau.", "在下一站换。"),
      ],
    },
    dialogue: [
      line("A", "请问，附近有超市吗？", "Qǐngwèn, fùjìn yǒu chāoshì ma?", "Xin hỏi, gần có siêu thị không?"),
      line("B", "有。坐地铁，下一站换，很方便。", "Yǒu. Zuò dìtiě, xià yí zhàn huàn, hěn fāngbiàn.", "Có. Đi tàu, ga sau đổi, tiện."),
      line("A", "超市在几层？", "Chāoshì zài jǐ céng?", "Siêu thị tầng mấy?"),
      line("B", "地下一层。你看一下地图。", "Dìxià yì céng. Nǐ kàn yíxià dìtú.", "Tầng hầm 1. Bạn xem bản đồ."),
    ],
    exercises: [
      ex("Tự viết: Gần có siêu thị không?", "附近有超市吗？"),
      ex("Tự viết: Đi tàu, ga sau đổi.", "坐地铁，下一站换。"),
    ],
    scenario: "Hỏi siêu thị gần ga: đi tàu, đổi ga, tầng hầm, xem bản đồ.",
    start: "请问，附近有超市吗？",
  },
  {
    id: 133,
    theme: "Du khách ở sân bay",
    kind: "review",
    vocab: [
      v("护照", "hùzhào", "Hộ chiếu (ôn)", "请出示护照。", "Qǐng chūshì hùzhào.", "Xin đưa hộ chiếu."),
      v("行李箱", "xínglixiāng", "Vali (ôn)", "把行李箱放这儿。", "Bǎ xínglixiāng fàng zhèr.", "Để vali đây."),
      v("起飞", "qǐfēi", "Cất cánh (ôn)", "什么时候起飞？", "Shénme shíhou qǐfēi?", "Khi nào cất cánh?"),
      v("电梯", "diàntī", "Thang máy (ôn)", "坐电梯下楼。", "Zuò diàntī xià lóu.", "Đi thang máy xuống."),
      v("方便", "fāngbiàn", "Tiện (ôn)", "这样很方便。", "Zhèyàng hěn fāngbiàn.", "Như vậy rất tiện."),
    ],
    grammar: {
      title: "Chỉ đường / bay",
      pattern: "把 / 要…了",
      explainVi: "Roleplay sân bay. Khoá từ đến tuần 19.",
      drills: [
        drill("Dịch: Xin đưa hộ chiếu.", "请出示护照。"),
        drill("Dịch: Để vali đây.", "把行李箱放这儿。"),
        drill("Dịch: Khi nào cất cánh?", "什么时候起飞？"),
        drill("Dịch: Đi thang máy xuống.", "坐电梯下楼。"),
      ],
    },
    dialogue: [
      line("A", "请问，什么时候起飞？护照在这儿。", "Qǐngwèn, shénme shíhou qǐfēi? Hùzhào zài zhèr.", "Xin hỏi, khi nào cất cánh? Hộ chiếu đây."),
      line("B", "十一点。请把行李箱放这儿。", "Shíyī diǎn. Qǐng bǎ xínglixiāng fàng zhèr.", "11 giờ. Để vali đây."),
      line("A", "去二层坐电梯方便吗？", "Qù èr céng zuò diàntī fāngbiàn ma?", "Lên tầng 2 đi thang máy có tiện không?"),
      line("B", "方便。别着急，还有时间。", "Fāngbiàn. Bié zháojí, hái yǒu shíjiān.", "Tiện. Đừng sốt, còn giờ."),
    ],
    exercises: [
      ex("Tự viết: Khi nào cất cánh? Hộ chiếu đây.", "什么时候起飞？护照在这儿。"),
      ex("Tự viết: Để vali đây.", "把行李箱放这儿。"),
    ],
    scenario: "Làm thủ tục sân bay: giờ cất cánh, hộ chiếu, vali, thang máy lên tầng.",
    start: "请问，什么时候起飞？",
  },
  {
    id: 134,
    theme: "Dự định",
    kind: "learn",
    vocab: [
      v("打算", "dǎsuàn", "Dự định", "我打算学习。", "Wǒ dǎsuàn xuéxí.", "Tôi định học."),
      v("决定", "juédìng", "Quyết định", "我决定留下。", "Wǒ juédìng liú xià.", "Tôi quyết định ở lại."),
      v("必须", "bìxū", "Phải / bắt buộc", "必须复习。", "Bìxū fùxí.", "Phải ôn bài."),
      v("提高", "tígāo", "Nâng cao", "提高汉语水平。", "Tígāo Hànyǔ shuǐpíng.", "Nâng cao trình độ tiếng Trung."),
    ],
    grammar: {
      title: "打算 + động từ",
      pattern: "打算 + V；必须 + V",
      explainVi: "打算: kế hoạch. 决定: đã chốt. 必须: bắt buộc, mạnh hơn 要.",
      drills: [
        drill("Dịch: Tôi định học.", "我打算学习。"),
        drill("Dịch: Tôi quyết định ở lại.", "我决定留下。"),
        drill("Dịch: Phải ôn bài.", "必须复习。"),
        drill("Dịch: Nâng cao tiếng Trung.", "提高汉语水平。"),
      ],
    },
    dialogue: [
      line("A", "这个周末你打算做什么？", "Zhège zhōumò nǐ dǎsuàn zuò shénme?", "Cuối tuần này bạn định làm gì?"),
      line("B", "我打算复习。必须提高成绩。", "Wǒ dǎsuàn fùxí. Bìxū tígāo chéngjì.", "Tôi định ôn. Phải nâng điểm."),
      line("A", "你决定不出去了？", "Nǐ juédìng bù chū qù le?", "Bạn quyết không ra ngoài à?"),
      line("B", "对。如果考完就去公园。", "Duì. Rúguǒ kǎo wán jiù qù gōngyuán.", "Đúng. Nếu thi xong thì đi công viên."),
    ],
    exercises: [
      ex("Tự viết: Tôi định ôn bài.", "我打算复习。"),
      ex("Tự viết: Phải nâng cao trình độ.", "必须提高水平。"),
    ],
    scenario: "Hỏi kế hoạch cuối tuần: định ôn thi, phải nâng điểm, quyết ở nhà.",
    start: "这个周末你打算做什么？",
  },
  {
    id: 135,
    theme: "Bài tập",
    kind: "learn",
    vocab: [
      v("完成", "wánchéng", "Hoàn thành", "作业完成了。", "Zuòyè wánchéng le.", "Bài tập xong rồi."),
      v("作业", "zuòyè", "Bài tập", "今天有作业。", "Jīntiān yǒu zuòyè.", "Hôm nay có bài tập."),
      v("练习", "liànxí", "Luyện tập", "多练习。", "Duō liànxí.", "Luyện nhiều."),
      v("复习", "fùxí", "Ôn tập", "晚上复习。", "Wǎnshang fùxí.", "Tối ôn bài."),
      v("成绩", "chéngjì", "Thành tích / điểm", "成绩很好。", "Chéngjì hěn hǎo.", "Điểm rất tốt."),
    ],
    grammar: {
      title: "把…完成",
      pattern: "把 + 作业 + 完成",
      explainVi: "Hoàn tất việc: 把作业完成. 练习 / 复习 là thói quen học.",
      drills: [
        drill("Dịch: Bài tập xong rồi.", "作业完成了。"),
        drill("Dịch: Hôm nay có bài tập.", "今天有作业。"),
        drill("Dịch: Luyện nhiều.", "多练习。"),
        drill("Dịch: Làm xong bài tập.", "把作业完成。"),
      ],
    },
    dialogue: [
      line("A", "作业完成了吗？", "Zuòyè wánchéng le ma?", "Bài tập xong chưa?"),
      line("B", "还没。我必须先练习再复习。", "Hái méi. Wǒ bìxū xiān liànxí zài fùxí.", "Chưa. Phải luyện rồi mới ôn."),
      line("A", "把作业完成，成绩会更好。", "Bǎ zuòyè wánchéng, chéngjì huì gèng hǎo.", "Làm xong bài thì điểm sẽ tốt hơn."),
      line("B", "我知道。我打算今天完成。", "Wǒ zhīdào. Wǒ dǎsuàn jīntiān wánchéng.", "Tôi biết. Tôi định hôm nay xong."),
    ],
    exercises: [
      ex("Tự viết: Bài tập xong chưa?", "作业完成了吗？"),
      ex("Tự viết: Làm xong bài tập.", "把作业完成。"),
    ],
    scenario: "Nhắc bạn làm bài: luyện rồi ôn, làm xong thì điểm tốt hơn.",
    start: "作业完成了吗？",
  },
  {
    id: 136,
    theme: "Giảng / hiểu",
    kind: "learn",
    vocab: [
      v("水平", "shuǐpíng", "Trình độ", "你的水平很高。", "Nǐ de shuǐpíng hěn gāo.", "Trình độ bạn cao."),
      v("检查", "jiǎnchá", "Kiểm tra", "请检查作业。", "Qǐng jiǎnchá zuòyè.", "Hãy kiểm tra bài."),
      v("讲", "jiǎng", "Giảng / nói", "老师讲得清楚。", "Lǎoshī jiǎng de qīngchu.", "Cô giảng rõ."),
      v("教", "jiāo", "Dạy", "她教汉语。", "Tā jiāo Hànyǔ.", "Cô ấy dạy tiếng Trung."),
      v("明白", "míngbai", "Hiểu", "我明白了。", "Wǒ míngbai le.", "Tôi hiểu rồi."),
    ],
    grammar: {
      title: "V + 明白",
      pattern: "听 / 看 + 明白；明白了",
      explainVi: "明白: đã hiểu. 听明白了、看明白了. 讲 / 教 là hành động giáo viên.",
      drills: [
        drill("Dịch: Trình độ bạn cao.", "你的水平很高。"),
        drill("Dịch: Hãy kiểm tra bài.", "请检查作业。"),
        drill("Dịch: Cô giảng rõ.", "老师讲得清楚。"),
        drill("Dịch: Tôi hiểu rồi.", "我明白了。"),
      ],
    },
    dialogue: [
      line("A", "老师讲得怎么样？你明白吗？", "Lǎoshī jiǎng de zěnmeyàng? Nǐ míngbai ma?", "Cô giảng thế nào? Bạn hiểu không?"),
      line("B", "讲得很清楚。我明白了。", "Jiǎng de hěn qīngchu. Wǒ míngbai le.", "Giảng rất rõ. Tôi hiểu rồi."),
      line("A", "她也教你检查作业吗？", "Tā yě jiāo nǐ jiǎnchá zuòyè ma?", "Cô cũng dạy bạn kiểm bài à?"),
      line("B", "教。这样水平会提高。", "Jiāo. Zhèyàng shuǐpíng huì tígāo.", "Có. Như thế trình độ sẽ lên."),
    ],
    exercises: [
      ex("Tự viết: Cô giảng rõ. Tôi hiểu rồi.", "老师讲得清楚。我明白了。"),
      ex("Tự viết: Hãy kiểm tra bài.", "请检查作业。"),
    ],
    scenario: "Hỏi giờ học: cô giảng có rõ không, đã hiểu chưa, có kiểm bài không.",
    start: "老师讲得怎么样？你明白吗？",
  },
  {
    id: 137,
    theme: "Họp",
    kind: "learn",
    vocab: [
      v("了解", "liǎojiě", "Tìm hiểu", "我想了解公司。", "Wǒ xiǎng liǎojiě gōngsī.", "Tôi muốn hiểu công ty."),
      v("会议", "huìyì", "Cuộc họp", "下午有会议。", "Xiàwǔ yǒu huìyì.", "Chiều có họp."),
      v("经理", "jīnglǐ", "Giám đốc", "经理很热情。", "Jīnglǐ hěn rèqíng.", "Giám đốc rất nhiệt tình."),
      v("同事", "tóngshì", "Đồng nghiệp", "我的同事帮助我。", "Wǒ de tóngshì bāngzhù wǒ.", "Đồng nghiệp giúp tôi."),
    ],
    grammar: {
      title: "了解 + danh từ",
      pattern: "了解 + N",
      explainVi: "了解: nắm thông tin, khác 明白 (hiểu ý). 了解公司、了解情况.",
      drills: [
        drill("Dịch: Tôi muốn hiểu công ty.", "我想了解公司。"),
        drill("Dịch: Chiều có họp.", "下午有会议。"),
        drill("Dịch: Giám đốc rất nhiệt tình.", "经理很热情。"),
        drill("Dịch: Đồng nghiệp giúp tôi.", "同事帮助我。"),
      ],
    },
    dialogue: [
      line("A", "下午的会议，经理来吗？", "Xiàwǔ de huìyì, jīnglǐ lái ma?", "Họp chiều, giám đốc đến không?"),
      line("B", "来。他想了解我们的工作。", "Lái. Tā xiǎng liǎojiě wǒmen de gōngzuò.", "Đến. Ông muốn nắm việc chúng ta."),
      line("A", "同事都参加吗？", "Tóngshì dōu cānjiā ma?", "Đồng nghiệp đều tham gia à?"),
      line("B", "都参加。你必须准备一下。", "Dōu cānjiā. Nǐ bìxū zhǔnbèi yíxià.", "Đều tham gia. Bạn phải chuẩn bị."),
    ],
    exercises: [
      ex("Tự viết: Chiều có họp. Giám đốc đến.", "下午有会议。经理来。"),
      ex("Tự viết: Ông muốn nắm việc chúng ta.", "他想了解我们的工作。"),
    ],
    scenario: "Nhắc họp chiều: giám đốc muốn nắm việc, đồng nghiệp đều tham gia.",
    start: "下午的会议，经理来吗？",
  },
  {
    id: 138,
    theme: "Quan hệ",
    kind: "learn",
    vocab: [
      v("同意", "tóngyì", "Đồng ý", "我同意。", "Wǒ tóngyì.", "Tôi đồng ý."),
      v("关系", "guānxi", "Quan hệ", "我们关系很好。", "Wǒmen guānxi hěn hǎo.", "Quan hệ chúng tôi tốt."),
      v("关心", "guānxīn", "Quan tâm", "谢谢你关心我。", "Xièxie nǐ guānxīn wǒ.", "Cảm ơn bạn quan tâm."),
      v("关于", "guānyú", "Về (chủ đề)", "关于这个问题…", "Guānyú zhège wèntí…", "Về vấn đề này…"),
    ],
    grammar: {
      title: "关于 + chủ đề",
      pattern: "关于 + N，…",
      explainVi: "关于 mở đầu chủ đề. 关心 + người. 同意: tán thành ý kiến.",
      drills: [
        drill("Dịch: Tôi đồng ý.", "我同意。"),
        drill("Dịch: Quan hệ chúng tôi tốt.", "我们关系很好。"),
        drill("Dịch: Cảm ơn bạn quan tâm.", "谢谢你关心我。"),
        drill("Dịch: Về vấn đề này…", "关于这个问题…"),
      ],
    },
    dialogue: [
      line("A", "关于这个计划，你同意吗？", "Guānyú zhège jìhuà, nǐ tóngyì ma?", "Về kế hoạch này, bạn đồng ý không?"),
      line("B", "我同意。同事也关心这件事。", "Wǒ tóngyì. Tóngshì yě guānxīn zhè jiàn shì.", "Tôi đồng ý. Đồng nghiệp cũng quan tâm."),
      line("A", "我和经理的关系怎么样？", "Wǒ hé jīnglǐ de guānxi zěnmeyàng?", "Quan hệ tôi với giám đốc thế nào?"),
      line("B", "很好。他一直很热情。", "Hěn hǎo. Tā yìzhí hěn rèqíng.", "Tốt. Ông ấy luôn nhiệt tình."),
    ],
    exercises: [
      ex("Tự viết: Về kế hoạch này, tôi đồng ý.", "关于这个计划，我同意。"),
      ex("Tự viết: Cảm ơn bạn quan tâm.", "谢谢你关心我。"),
    ],
    scenario: "Họp: hỏi có đồng ý kế hoạch không, quan hệ với sếp, ai quan tâm việc này.",
    start: "关于这个计划，你同意吗？",
  },
  {
    id: 139,
    theme: "Tổng hợp học / làm",
    kind: "review",
    vocab: [
      v("打算", "dǎsuàn", "Dự định (ôn)", "你打算怎么办？", "Nǐ dǎsuàn zěnme bàn?", "Bạn định làm sao?"),
      v("必须", "bìxū", "Phải (ôn)", "必须完成。", "Bìxū wánchéng.", "Phải hoàn thành."),
      v("会议", "huìyì", "Họp (ôn)", "参加会议。", "Cānjiā huìyì.", "Tham gia họp."),
      v("明白", "míngbai", "Hiểu (ôn)", "现在明白了。", "Xiànzài míngbai le.", "Giờ hiểu rồi."),
      v("同意", "tóngyì", "Đồng ý (ôn)", "大家都同意。", "Dàjiā dōu tóngyì.", "Mọi người đều đồng ý."),
    ],
    grammar: {
      title: "打算 / 必须",
      pattern: "打算 + V；必须 + V",
      explainVi: "Ôn tuần 20: kể kế hoạch tuần, họp, phải hoàn thành.",
      drills: [
        drill("Dịch: Bạn định làm sao?", "你打算怎么办？"),
        drill("Dịch: Phải hoàn thành.", "必须完成。"),
        drill("Dịch: Tham gia họp.", "参加会议。"),
        drill("Dịch: Mọi người đều đồng ý.", "大家都同意。"),
      ],
    },
    dialogue: [
      line("A", "这周你打算怎么办？", "Zhè zhōu nǐ dǎsuàn zěnme bàn?", "Tuần này bạn định làm sao?"),
      line("B", "先完成作业，再参加会议。", "Xiān wánchéng zuòyè, zài cānjiā huìyì.", "Xong bài rồi mới họp."),
      line("A", "经理同意这个计划吗？", "Jīnglǐ tóngyì zhège jìhuà ma?", "Giám đốc đồng ý kế hoạch này không?"),
      line("B", "同意。我明白必须提高水平。", "Tóngyì. Wǒ míngbai bìxū tígāo shuǐpíng.", "Đồng ý. Tôi hiểu phải nâng trình độ."),
    ],
    exercises: [
      ex("Tự viết: Xong bài rồi mới họp.", "先完成作业，再参加会议。"),
      ex("Tự viết: Tôi hiểu phải nâng trình độ.", "我明白必须提高水平。"),
    ],
    scenario: "Kể kế hoạch tuần: xong bài, họp, sếp đồng ý, phải nâng trình độ.",
    start: "这周你打算怎么办？",
  },
  {
    id: 140,
    theme: "Sếp vs nhân viên mới",
    kind: "review",
    vocab: [
      v("经理", "jīnglǐ", "Giám đốc (ôn)", "经理叫你。", "Jīnglǐ jiào nǐ.", "Giám đốc gọi bạn."),
      v("同事", "tóngshì", "Đồng nghiệp (ôn)", "问同事。", "Wèn tóngshì.", "Hỏi đồng nghiệp."),
      v("了解", "liǎojiě", "Tìm hiểu (ôn)", "先了解工作。", "Xiān liǎojiě gōngzuò.", "Tìm hiểu việc trước."),
      v("检查", "jiǎnchá", "Kiểm tra (ôn)", "请检查。", "Qǐng jiǎnchá.", "Hãy kiểm tra."),
      v("关于", "guānyú", "Về (ôn)", "关于工作…", "Guānyú gōngzuò…", "Về công việc…"),
    ],
    grammar: {
      title: "Chỉ họp / bài",
      pattern: "关于 / 了解 / 必须",
      explainVi: "Roleplay ngày đầu đi làm. Khoá từ đến tuần 20.",
      drills: [
        drill("Dịch: Giám đốc gọi bạn.", "经理叫你。"),
        drill("Dịch: Tìm hiểu việc trước.", "先了解工作。"),
        drill("Dịch: Hãy kiểm tra.", "请检查。"),
        drill("Dịch: Về công việc…", "关于工作…"),
      ],
    },
    dialogue: [
      line("A", "欢迎。关于工作，你必须先了解。", "Huānyíng. Guānyú gōngzuò, nǐ bìxū xiān liǎojiě.", "Hoan nghênh. Về việc, bạn phải tìm hiểu trước."),
      line("B", "好。同事可以教我吗？", "Hǎo. Tóngshì kěyǐ jiāo wǒ ma?", "Được. Đồng nghiệp có thể dạy tôi không?"),
      line("A", "当然。下午有会议，请检查材料。", "Dāngrán. Xiàwǔ yǒu huìyì, qǐng jiǎnchá cáiliào.", "Đương nhiên. Chiều họp, hãy kiểm tài liệu."),
      line("B", "我明白了。我打算认真做。", "Wǒ míngbai le. Wǒ dǎsuàn rènzhēn zuò.", "Tôi hiểu rồi. Tôi định làm nghiêm túc."),
    ],
    exercises: [
      ex("Tự viết: Về việc, bạn phải tìm hiểu trước.", "关于工作，你必须先了解。"),
      ex("Tự viết: Chiều họp, hãy kiểm tra.", "下午有会议，请检查。"),
    ],
    scenario: "Ngày đầu: sếp dặn tìm hiểu việc, hỏi đồng nghiệp, chiều họp kiểm tài liệu.",
    start: "欢迎。关于工作，你必须先了解。",
  },
  {
    id: 141,
    theme: "Cần / thẻ",
    kind: "learn",
    vocab: [
      v("需要", "xūyào", "Cần", "我需要帮助。", "Wǒ xūyào bāngzhù.", "Tôi cần giúp."),
      v("信用卡", "xìnyòngkǎ", "Thẻ tín dụng", "用信用卡付钱。", "Yòng xìnyòngkǎ fù qián.", "Trả bằng thẻ."),
      v("万", "wàn", "Vạn (10.000)", "一万块。", "Yí wàn kuài.", "Mười nghìn tệ."),
      v("位", "wèi", "Vị (lượng từ người)", "三位客人。", "Sān wèi kèrén.", "Ba vị khách."),
    ],
    grammar: {
      title: "需要 + danh từ",
      pattern: "需要 + N / V",
      explainVi: "需要: cần. 位 lịch sự cho người. 万: 10.000.",
      drills: [
        drill("Dịch: Tôi cần giúp.", "我需要帮助。"),
        drill("Dịch: Trả bằng thẻ.", "用信用卡付钱。"),
        drill("Dịch: Mười nghìn tệ.", "一万块。"),
        drill("Dịch: Ba vị khách.", "三位客人。"),
      ],
    },
    dialogue: [
      line("A", "两位需要什么？", "Liǎng wèi xūyào shénme?", "Hai vị cần gì?"),
      line("B", "我们需要这件衣服。可以用信用卡吗？", "Wǒmen xūyào zhè jiàn yīfu. Kěyǐ yòng xìnyòngkǎ ma?", "Chúng tôi cần cái áo này. Dùng thẻ được không?"),
      line("A", "可以。一共一万块。", "Kěyǐ. Yígòng yí wàn kuài.", "Được. Cộng một vạn tệ."),
      line("B", "好。请帮我。", "Hǎo. Qǐng bāng wǒ.", "Được. Làm ơn giúp."),
    ],
    exercises: [
      ex("Tự viết: Hai vị cần gì?", "两位需要什么？"),
      ex("Tự viết: Trả bằng thẻ. Một vạn tệ.", "用信用卡付钱。一万块。"),
    ],
    scenario: "Ở cửa hàng: nhân viên hỏi cần gì, khách trả thẻ, giá một vạn.",
    start: "两位需要什么？",
  },
  {
    id: 142,
    theme: "Quà và hoa",
    kind: "learn",
    vocab: [
      v("满意", "mǎnyì", "Hài lòng", "我很满意。", "Wǒ hěn mǎnyì.", "Tôi rất hài lòng."),
      v("礼物", "lǐwù", "Quà", "这是礼物。", "Zhè shì lǐwù.", "Đây là quà."),
      v("花", "huā", "Hoa / tiêu", "买花。", "Mǎi huā.", "Mua hoa."),
      v("新鲜", "xīnxiān", "Tươi", "花很新鲜。", "Huā hěn xīnxiān.", "Hoa rất tươi."),
      v("甜", "tián", "Ngọt", "这个很甜。", "Zhège hěn tián.", "Cái này rất ngọt."),
    ],
    grammar: {
      title: "对…满意",
      pattern: "对 + N + 很满意",
      explainVi: "Hài lòng với: 我对这个礼物很满意.",
      drills: [
        drill("Dịch: Tôi rất hài lòng.", "我很满意。"),
        drill("Dịch: Đây là quà.", "这是礼物。"),
        drill("Dịch: Hoa rất tươi.", "花很新鲜。"),
        drill("Dịch: Tôi hài lòng món này.", "我对这个很满意。"),
      ],
    },
    dialogue: [
      line("A", "这个礼物怎么样？花新鲜吗？", "Zhège lǐwù zěnmeyàng? Huā xīnxiān ma?", "Quà này thế nào? Hoa tươi không?"),
      line("B", "很新鲜，也甜。我对这个很满意。", "Hěn xīnxiān, yě tián. Wǒ duì zhège hěn mǎnyì.", "Rất tươi, cũng ngọt. Tôi hài lòng."),
      line("A", "需要我帮你付钱吗？", "Xūyào wǒ bāng nǐ fù qián ma?", "Cần tôi trả giúp không?"),
      line("B", "不用。我用信用卡。", "Bú yòng. Wǒ yòng xìnyòngkǎ.", "Không. Tôi dùng thẻ."),
    ],
    exercises: [
      ex("Tự viết: Hoa rất tươi. Tôi hài lòng.", "花很新鲜。我很满意。"),
      ex("Tự viết: Đây là quà.", "这是礼物。"),
    ],
    scenario: "Chọn quà sinh nhật: hoa tươi, vị ngọt, có hài lòng không, trả thẻ.",
    start: "这个礼物怎么样？花新鲜吗？",
  },
  {
    id: 143,
    theme: "Bàn ăn",
    kind: "learn",
    vocab: [
      v("面包", "miànbāo", "Bánh mì", "买面包。", "Mǎi miànbāo.", "Mua bánh mì."),
      v("啤酒", "píjiǔ", "Bia", "喝啤酒。", "Hē píjiǔ.", "Uống bia."),
      v("瓶子", "píngzi", "Chai / lọ", "一个瓶子。", "Yí ge píngzi.", "Một cái chai."),
      v("盘子", "pánzi", "Đĩa", "这个盘子。", "Zhège pánzi.", "Cái đĩa này."),
      v("碗", "wǎn", "Bát", "一碗米饭。", "Yì wǎn mǐfàn.", "Một bát cơm."),
    ],
    grammar: {
      title: "Lượng từ bàn ăn",
      pattern: "个瓶子 / 碗 / 盘",
      explainVi: "瓶子、盘子 dùng 个. 碗 vừa là danh từ vừa lượng từ: 一碗米饭.",
      drills: [
        drill("Dịch: Mua bánh mì.", "买面包。"),
        drill("Dịch: Uống bia.", "喝啤酒。"),
        drill("Dịch: Một cái chai.", "一个瓶子。"),
        drill("Dịch: Một bát cơm.", "一碗米饭。"),
      ],
    },
    dialogue: [
      line("A", "你需要什么？面包还是啤酒？", "Nǐ xūyào shénme? Miànbāo háishì píjiǔ?", "Bạn cần gì? Bánh mì hay bia?"),
      line("B", "都要。再要一个盘子和一碗米饭。", "Dōu yào. Zài yào yí ge pánzi hé yì wǎn mǐfàn.", "Cả hai. Thêm một đĩa và một bát cơm."),
      line("A", "啤酒几瓶？", "Píjiǔ jǐ píng?", "Bia mấy chai?"),
      line("B", "两瓶。瓶子可以带走吗？", "Liǎng píng. Píngzi kěyǐ dài zǒu ma?", "Hai chai. Chai mang đi được không?"),
    ],
    exercises: [
      ex("Tự viết: Thêm một đĩa và một bát cơm.", "再要一个盘子和一碗米饭。"),
      ex("Tự viết: Hai chai bia.", "两瓶啤酒。"),
    ],
    scenario: "Gọi đồ: bánh mì, bia, đĩa, bát cơm; hỏi mang chai đi được không.",
    start: "你需要什么？面包还是啤酒？",
  },
  {
    id: 144,
    theme: "Đôi / chiếc",
    kind: "learn",
    vocab: [
      v("筷子", "kuàizi", "Đũa", "一双筷子。", "Yì shuāng kuàizi.", "Một đôi đũa."),
      v("双", "shuāng", "Đôi", "一双筷子。", "Yì shuāng kuàizi.", "Một đôi đũa."),
      v("条", "tiáo", "Cái (dài)", "一条鱼。", "Yì tiáo yú.", "Một con cá."),
      v("辆", "liàng", "Chiếc (xe)", "一辆车。", "Yí liàng chē.", "Một chiếc xe."),
    ],
    grammar: {
      title: "双 / 条 / 辆",
      pattern: "一双 / 一条 / 一辆 + N",
      explainVi: "双: đôi (đũa, giày). 条: vật dài (phố, váy, cá). 辆: xe.",
      drills: [
        drill("Dịch: Một đôi đũa.", "一双筷子。"),
        drill("Dịch: Một con cá.", "一条鱼。"),
        drill("Dịch: Một chiếc xe.", "一辆车。"),
        drill("Dịch: Tôi cần một đôi đũa.", "我需要一双筷子。"),
      ],
    },
    dialogue: [
      line("A", "请给我一双筷子。", "Qǐng gěi wǒ yì shuāng kuàizi.", "Cho tôi một đôi đũa."),
      line("B", "好。你还需要一条鱼吗？", "Hǎo. Nǐ hái xūyào yì tiáo yú ma?", "Được. Bạn còn cần một con cá không?"),
      line("A", "需要。吃完我骑自行车回去。", "Xūyào. Chī wán wǒ qí zìxíngchē huí qù.", "Cần. Ăn xong tôi đạp xe về."),
      line("B", "那是一辆很方便的车。", "Nà shì yí liàng hěn fāngbiàn de chē.", "Đó là một chiếc xe rất tiện."),
    ],
    exercises: [
      ex("Tự viết: Cho tôi một đôi đũa.", "请给我一双筷子。"),
      ex("Tự viết: Một chiếc xe rất tiện.", "一辆很方便的车。"),
    ],
    scenario: "Ở quán: xin đôi đũa, gọi thêm cá, ăn xong đạp xe về.",
    start: "请给我一双筷子。",
  },
  {
    id: 145,
    theme: "Áo quần 2",
    kind: "learn",
    vocab: [
      v("衬衫", "chènshān", "Áo sơ mi", "一件衬衫。", "Yí jiàn chènshān.", "Một cái sơ mi."),
      v("裙子", "qúnzi", "Váy", "这条裙子很漂亮。", "Zhè tiáo qúnzi hěn piàoliang.", "Váy này đẹp."),
      v("裤子", "kùzi", "Quần", "裤子有点儿长。", "Kùzi yǒudiǎnr cháng.", "Quần hơi dài."),
      v("帽子", "màozi", "Mũ", "戴帽子。", "Dài màozi.", "Đội mũ."),
    ],
    grammar: {
      title: "件 / 条 (ôn)",
      pattern: "一件衬衫 / 一条裤子",
      explainVi: "Áo sơ mi dùng 件. Váy và quần dài dùng 条. Mũ dùng 顶 hoặc 个; bài này tập 帽子.",
      drills: [
        drill("Dịch: Một cái sơ mi.", "一件衬衫。"),
        drill("Dịch: Váy này đẹp.", "这条裙子很漂亮。"),
        drill("Dịch: Quần hơi dài.", "裤子有点儿长。"),
        drill("Dịch: Đội mũ.", "戴帽子。"),
      ],
    },
    dialogue: [
      line("A", "我想买一件衬衫和一顶帽子。", "Wǒ xiǎng mǎi yí jiàn chènshān hé yì dǐng màozi.", "Tôi muốn mua một sơ mi và một mũ."),
      line("B", "这条裙子也需要吗？", "Zhè tiáo qúnzi yě xūyào ma?", "Váy này cũng cần không?"),
      line("A", "先看看裤子。有点儿长。", "Xiān kànkan kùzi. Yǒudiǎnr cháng.", "Xem quần trước. Hơi dài."),
      line("B", "可以换一条。你对颜色满意吗？", "Kěyǐ huàn yì tiáo. Nǐ duì yánsè mǎnyì ma?", "Đổi một cái được. Màu bạn hài lòng không?"),
    ],
    exercises: [
      ex("Tự viết: Tôi muốn mua một sơ mi và một mũ.", "我想买一件衬衫和一顶帽子。"),
      ex("Tự viết: Quần hơi dài. Đổi một cái được.", "裤子有点儿长。可以换一条。"),
    ],
    scenario: "Mua đồ: sơ mi, mũ, váy, quần hơi dài thì đổi, hỏi có hài lòng màu không.",
    start: "我想买一件衬衫和一顶帽子。",
  },
  {
    id: 146,
    theme: "Ở cửa hàng 3",
    kind: "review",
    vocab: [
      v("需要", "xūyào", "Cần (ôn)", "还需要别的吗？", "Hái xūyào bié de ma?", "Còn cần gì nữa không?"),
      v("礼物", "lǐwù", "Quà (ôn)", "买生日礼物。", "Mǎi shēngrì lǐwù.", "Mua quà sinh nhật."),
      v("双", "shuāng", "Đôi (ôn)", "一双筷子。", "Yì shuāng kuàizi.", "Một đôi đũa."),
      v("满意", "mǎnyì", "Hài lòng (ôn)", "您满意吗？", "Nín mǎnyì ma?", "Bạn hài lòng không?"),
      v("信用卡", "xìnyòngkǎ", "Thẻ (ôn)", "刷信用卡。", "Shuā xìnyòngkǎ.", "Quẹt thẻ."),
    ],
    grammar: {
      title: "hỏi size / giá",
      pattern: "需要 / 对…满意 / 双",
      explainVi: "Ôn tuần 21: chọn quà sinh nhật, lượng từ, trả thẻ.",
      drills: [
        drill("Dịch: Còn cần gì nữa không?", "还需要别的吗？"),
        drill("Dịch: Mua quà sinh nhật.", "买生日礼物。"),
        drill("Dịch: Bạn hài lòng không?", "您满意吗？"),
        drill("Dịch: Quẹt thẻ.", "刷信用卡。"),
      ],
    },
    dialogue: [
      line("A", "我需要买生日礼物。这条裙子怎么样？", "Wǒ xūyào mǎi shēngrì lǐwù. Zhè tiáo qúnzi zěnmeyàng?", "Tôi cần mua quà sinh nhật. Váy này thế nào?"),
      line("B", "很漂亮。您满意吗？还需要一双筷子吗？", "Hěn piàoliang. Nín mǎnyì ma? Hái xūyào yì shuāng kuàizi ma?", "Đẹp. Hài lòng không? Còn cần đôi đũa không?"),
      line("A", "裙子就行。可以用信用卡吗？", "Qúnzi jiù xíng. Kěyǐ yòng xìnyòngkǎ ma?", "Váy là đủ. Dùng thẻ được không?"),
      line("B", "当然可以。一共八百块。", "Dāngrán kěyǐ. Yígòng bā bǎi kuài.", "Đương nhiên. Cộng 800 tệ."),
    ],
    exercises: [
      ex("Tự viết: Tôi cần mua quà sinh nhật.", "我需要买生日礼物。"),
      ex("Tự viết: Váy này đẹp. Dùng thẻ được không?", "这条裙子很漂亮。可以用信用卡吗？"),
    ],
    scenario: "Chọn quà sinh nhật: váy, hỏi hài lòng, trả thẻ, không cần thêm đũa.",
    start: "我需要买生日礼物。",
  },
  {
    id: 147,
    theme: "Thu ngân vs khách",
    kind: "review",
    vocab: [
      v("万", "wàn", "Vạn (ôn)", "两万块。", "Liǎng wàn kuài.", "Hai vạn tệ."),
      v("位", "wèi", "Vị (ôn)", "三位。", "Sān wèi.", "Ba vị."),
      v("新鲜", "xīnxiān", "Tươi (ôn)", "这些花很新鲜。", "Zhèxiē huā hěn xīnxiān.", "Hoa này rất tươi."),
      v("衬衫", "chènshān", "Sơ mi (ôn)", "换一件衬衫。", "Huàn yí jiàn chènshān.", "Đổi một sơ mi."),
      v("辆", "liàng", "Chiếc xe (ôn)", "那辆车。", "Nà liàng chē.", "Chiếc xe kia."),
    ],
    grammar: {
      title: "Chỉ mua / thẻ",
      pattern: "需要 / 万 / 信用卡",
      explainVi: "Roleplay thu ngân. Khoá từ đến tuần 21.",
      drills: [
        drill("Dịch: Hai vạn tệ.", "两万块。"),
        drill("Dịch: Ba vị.", "三位。"),
        drill("Dịch: Hoa này rất tươi.", "这些花很新鲜。"),
        drill("Dịch: Đổi một sơ mi.", "换一件衬衫。"),
      ],
    },
    dialogue: [
      line("A", "三位需要付钱吗？一共两万块。", "Sān wèi xūyào fù qián ma? Yígòng liǎng wàn kuài.", "Ba vị cần thanh toán không? Cộng hai vạn."),
      line("B", "花很新鲜，衬衫也满意。用信用卡。", "Huā hěn xīnxiān, chènshān yě mǎnyì. Yòng xìnyòngkǎ.", "Hoa tươi, sơ mi cũng ưng. Dùng thẻ."),
      line("A", "好。那辆车是您的吗？可以带上。", "Hǎo. Nà liàng chē shì nín de ma? Kěyǐ dài shàng.", "Được. Chiếc xe kia của bạn à? Có thể mang theo."),
      line("B", "是。谢谢，我对服务很满意。", "Shì. Xièxie, wǒ duì fúwù hěn mǎnyì.", "Phải. Cảm ơn, tôi hài lòng dịch vụ."),
    ],
    exercises: [
      ex("Tự viết: Cộng hai vạn. Dùng thẻ.", "一共两万块。用信用卡。"),
      ex("Tự viết: Hoa tươi, sơ mi cũng ưng.", "花很新鲜，衬衫也满意。"),
    ],
    scenario: "Thanh toán: ba vị, hai vạn, hoa và sơ mi, quẹt thẻ, xe mang đồ.",
    start: "三位需要付钱吗？",
  },
  {
    id: 148,
    theme: "Văn hóa",
    kind: "learn",
    vocab: [
      v("文化", "wénhuà", "Văn hóa", "中国文化。", "Zhōngguó wénhuà.", "Văn hóa Trung Quốc."),
      v("历史", "lìshǐ", "Lịch sử", "我喜欢历史。", "Wǒ xǐhuan lìshǐ.", "Tôi thích lịch sử."),
      v("国家", "guójiā", "Đất nước", "很多国家。", "Hěn duō guójiā.", "Nhiều quốc gia."),
      v("世界", "shìjiè", "Thế giới", "世界很大。", "Shìjiè hěn dà.", "Thế giới rất lớn."),
      v("有名", "yǒumíng", "Nổi tiếng", "很有名。", "Hěn yǒumíng.", "Rất nổi tiếng."),
    ],
    grammar: {
      title: "对…有兴趣",
      pattern: "对 + N + 有兴趣 / 感兴趣",
      explainVi: "Thích một lĩnh vực: 我对历史有兴趣. Có thể nói 感兴趣.",
      drills: [
        drill("Dịch: Văn hóa Trung Quốc.", "中国文化。"),
        drill("Dịch: Tôi thích lịch sử.", "我喜欢历史。"),
        drill("Dịch: Thế giới rất lớn.", "世界很大。"),
        drill("Dịch: Tôi thích lịch sử Trung Quốc.", "我对历史有兴趣。"),
      ],
    },
    dialogue: [
      line("A", "你对什么有兴趣？文化还是历史？", "Nǐ duì shénme yǒu xìngqù? Wénhuà háishì lìshǐ?", "Bạn thích gì? Văn hóa hay lịch sử?"),
      line("B", "都喜欢。中国文化很有名。", "Dōu xǐhuan. Zhōngguó wénhuà hěn yǒumíng.", "Thích cả. Văn hóa Trung Quốc nổi tiếng."),
      line("A", "世界上很多国家都来学习。", "Shìjiè shàng hěn duō guójiā dōu lái xuéxí.", "Nhiều nước trên thế giới đến học."),
      line("B", "是。我想多了解这个国家。", "Shì. Wǒ xiǎng duō liǎojiě zhège guójiā.", "Phải. Tôi muốn hiểu đất nước này hơn."),
    ],
    exercises: [
      ex("Tự viết: Tôi thích lịch sử.", "我对历史有兴趣。"),
      ex("Tự viết: Văn hóa Trung Quốc rất nổi tiếng.", "中国文化很有名。"),
    ],
    scenario: "Nói sở thích: văn hóa hay lịch sử, đất nước nổi tiếng, muốn tìm hiểu thêm.",
    start: "你对什么有兴趣？文化还是历史？",
  },
  {
    id: 149,
    theme: "Bốn mùa",
    kind: "learn",
    vocab: [
      v("季节", "jìjié", "Mùa", "四个季节。", "Sì ge jìjié.", "Bốn mùa."),
      v("春天", "chūntiān", "Mùa xuân", "春天来了。", "Chūntiān lái le.", "Xuân đến rồi."),
      v("夏天", "xiàtiān", "Mùa hè", "夏天很热。", "Xiàtiān hěn rè.", "Hè rất nóng."),
      v("秋天", "qiūtiān", "Mùa thu", "我爱秋天。", "Wǒ ài qiūtiān.", "Tôi yêu mùa thu."),
      v("冬天", "dōngtiān", "Mùa đông", "冬天很冷。", "Dōngtiān hěn lěng.", "Đông rất lạnh."),
    ],
    grammar: {
      title: "最 + tính từ",
      pattern: "最 + adj / 最喜欢",
      explainVi: "So sánh trong nhóm: 我最喜欢秋天. 四个季节.",
      drills: [
        drill("Dịch: Bốn mùa.", "四个季节。"),
        drill("Dịch: Xuân đến rồi.", "春天来了。"),
        drill("Dịch: Hè rất nóng.", "夏天很热。"),
        drill("Dịch: Tôi thích mùa thu nhất.", "我最喜欢秋天。"),
      ],
    },
    dialogue: [
      line("A", "四个季节，你最喜欢哪个？", "Sì ge jìjié, nǐ zuì xǐhuan nǎge?", "Bốn mùa, bạn thích nhất mùa nào?"),
      line("B", "我最喜欢秋天。冬天太冷了。", "Wǒ zuì xǐhuan qiūtiān. Dōngtiān tài lěng le.", "Tôi thích thu nhất. Đông lạnh quá."),
      line("A", "春天和夏天呢？", "Chūntiān hé xiàtiān ne?", "Còn xuân và hè?"),
      line("B", "春天很好。夏天有点儿热。", "Chūntiān hěn hǎo. Xiàtiān yǒudiǎnr rè.", "Xuân tốt. Hè hơi nóng."),
    ],
    exercises: [
      ex("Tự viết: Bốn mùa, bạn thích nhất mùa nào?", "四个季节，你最喜欢哪个？"),
      ex("Tự viết: Tôi thích thu nhất. Đông lạnh quá.", "我最喜欢秋天。冬天太冷了。"),
    ],
    scenario: "Chọn mùa yêu thích: thu, đông lạnh, xuân dễ chịu, hè nóng.",
    start: "四个季节，你最喜欢哪个？",
  },
  {
    id: 150,
    theme: "Môi trường",
    kind: "learn",
    vocab: [
      v("环境", "huánjìng", "Môi trường", "环境很好。", "Huánjìng hěn hǎo.", "Môi trường rất tốt."),
      v("动物", "dòngwù", "Động vật", "我喜欢动物。", "Wǒ xǐhuan dòngwù.", "Tôi thích động vật."),
      v("树", "shù", "Cây", "很多树。", "Hěn duō shù.", "Nhiều cây."),
      v("草", "cǎo", "Cỏ", "草很绿。", "Cǎo hěn lǜ.", "Cỏ rất xanh."),
      v("鸟", "niǎo", "Chim", "鸟在树上。", "Niǎo zài shù shàng.", "Chim trên cây."),
    ],
    grammar: {
      title: "越来越 (ôn)",
      pattern: "环境越来越好",
      explainVi: "Nói thay đổi môi trường: 树越来越多. Ôn 越来越 với chủ đề thiên nhiên.",
      drills: [
        drill("Dịch: Môi trường rất tốt.", "环境很好。"),
        drill("Dịch: Tôi thích động vật.", "我喜欢动物。"),
        drill("Dịch: Chim trên cây.", "鸟在树上。"),
        drill("Dịch: Môi trường ngày càng tốt.", "环境越来越好。"),
      ],
    },
    dialogue: [
      line("A", "公园的环境怎么样？", "Gōngyuán de huánjìng zěnmeyàng?", "Môi trường công viên thế nào?"),
      line("B", "很好。树很多，草很绿，还有鸟。", "Hěn hǎo. Shù hěn duō, cǎo hěn lǜ, hái yǒu niǎo.", "Tốt. Nhiều cây, cỏ xanh, còn có chim."),
      line("A", "你喜欢这些动物吗？", "Nǐ xǐhuan zhèxiē dòngwù ma?", "Bạn thích những con vật này không?"),
      line("B", "喜欢。这儿的环境越来越好。", "Xǐhuan. Zhèr de huánjìng yuè lái yuè hǎo.", "Thích. Ở đây môi trường ngày càng tốt."),
    ],
    exercises: [
      ex("Tự viết: Nhiều cây, cỏ xanh, còn có chim.", "树很多，草很绿，还有鸟。"),
      ex("Tự viết: Môi trường ngày càng tốt.", "环境越来越好。"),
    ],
    scenario: "Dạo công viên: cây, cỏ, chim, môi trường ngày càng tốt.",
    start: "公园的环境怎么样？",
  },
  {
    id: 151,
    theme: "Tin / nghĩ",
    kind: "learn",
    vocab: [
      v("习惯", "xíguàn", "Thói quen / quen", "我习惯了。", "Wǒ xíguàn le.", "Tôi quen rồi."),
      v("相信", "xiāngxìn", "Tin", "我相信你。", "Wǒ xiāngxìn nǐ.", "Tôi tin bạn."),
      v("认为", "rènwéi", "Cho rằng", "我认为很好。", "Wǒ rènwéi hěn hǎo.", "Tôi cho là rất tốt."),
      v("注意", "zhùyì", "Chú ý", "请注意。", "Qǐng zhùyì.", "Xin hãy chú ý."),
    ],
    grammar: {
      title: "认为 + câu",
      pattern: "认为 + ý kiến",
      explainVi: "认为 nêu quan điểm, trang trọng hơn 觉得. 相信 + người / điều. 习惯了: đã quen.",
      drills: [
        drill("Dịch: Tôi quen rồi.", "我习惯了。"),
        drill("Dịch: Tôi tin bạn.", "我相信你。"),
        drill("Dịch: Tôi cho là rất tốt.", "我认为很好。"),
        drill("Dịch: Xin hãy chú ý.", "请注意。"),
      ],
    },
    dialogue: [
      line("A", "你习惯这儿的生活了吗？", "Nǐ xíguàn zhèr de shēnghuó le ma?", "Bạn quen cuộc sống ở đây chưa?"),
      line("B", "习惯了。我认为环境很重要。", "Xíguàn le. Wǒ rènwéi huánjìng hěn zhòngyào.", "Quen rồi. Tôi cho môi trường rất quan trọng."),
      line("A", "我也相信这一点。请注意身体。", "Wǒ yě xiāngxìn zhè yì diǎn. Qǐng zhùyì shēntǐ.", "Tôi cũng tin điều đó. Hãy chú ý sức khỏe."),
      line("B", "谢谢你关心我。", "Xièxie nǐ guānxīn wǒ.", "Cảm ơn bạn quan tâm."),
    ],
    exercises: [
      ex("Tự viết: Tôi quen rồi. Tôi cho là rất tốt.", "我习惯了。我认为很好。"),
      ex("Tự viết: Xin hãy chú ý sức khỏe.", "请注意身体。"),
    ],
    scenario: "Hỏi đã quen chỗ mới chưa; nêu ý kiến môi trường; nhắc chú ý sức khỏe.",
    start: "你习惯这儿的生活了吗？",
  },
  {
    id: 152,
    theme: "Quan trọng",
    kind: "learn",
    vocab: [
      v("重要", "zhòngyào", "Quan trọng", "这很重要。", "Zhè hěn zhòngyào.", "Cái này rất quan trọng."),
      v("主要", "zhǔyào", "Chủ yếu", "主要问题。", "Zhǔyào wèntí.", "Vấn đề chính."),
      v("终于", "zhōngyú", "Cuối cùng", "终于完成了。", "Zhōngyú wánchéng le.", "Cuối cùng cũng xong."),
      v("相信", "xiāngxìn", "Tin (ôn)", "我相信你。", "Wǒ xiāngxìn nǐ.", "Tôi tin bạn."),
    ],
    grammar: {
      title: "终于 + động từ",
      pattern: "终于 + V + 了",
      explainVi: "终于: chờ đã lâu mới được. 重要 / 主要 phân biệt: quan trọng vs chủ yếu.",
      drills: [
        drill("Dịch: Cái này rất quan trọng.", "这很重要。"),
        drill("Dịch: Vấn đề chính.", "主要问题。"),
        drill("Dịch: Cuối cùng cũng xong.", "终于完成了。"),
        drill("Dịch: Tôi cho đây là việc chính.", "我认为这是主要的。"),
      ],
    },
    dialogue: [
      line("A", "作业终于完成了！", "Zuòyè zhōngyú wánchéng le!", "Bài tập cuối cùng cũng xong!"),
      line("B", "太好了。复习也很重要。", "Tài hǎo le. Fùxí yě hěn zhòngyào.", "Tốt quá. Ôn bài cũng quan trọng."),
      line("A", "主要问题没有了吗？", "Zhǔyào wèntí méiyǒu le ma?", "Vấn đề chính hết chưa?"),
      line("B", "没有了。我相信成绩会提高。", "Méiyǒu le. Wǒ xiāngxìn chéngjì huì tígāo.", "Hết rồi. Tôi tin điểm sẽ lên."),
    ],
    exercises: [
      ex("Tự viết: Cuối cùng cũng xong.", "终于完成了。"),
      ex("Tự viết: Ôn bài cũng quan trọng.", "复习也很重要。"),
    ],
    scenario: "Mừng làm xong bài: ôn vẫn quan trọng, vấn đề chính đã xong.",
    start: "作业终于完成了！",
  },
  {
    id: 153,
    theme: "Tổng hợp văn hóa",
    kind: "review",
    vocab: [
      v("季节", "jìjié", "Mùa (ôn)", "哪个季节去？", "Nǎge jìjié qù?", "Đi mùa nào?"),
      v("秋天", "qiūtiān", "Mùa thu (ôn)", "秋天去最好。", "Qiūtiān qù zuì hǎo.", "Đi mùa thu tốt nhất."),
      v("文化", "wénhuà", "Văn hóa (ôn)", "了解文化。", "Liǎojiě wénhuà.", "Tìm hiểu văn hóa."),
      v("认为", "rènwéi", "Cho rằng (ôn)", "你认为呢？", "Nǐ rènwéi ne?", "Bạn nghĩ sao?"),
      v("有名", "yǒumíng", "Nổi tiếng (ôn)", "那儿很有名。", "Nàr hěn yǒumíng.", "Chỗ đó nổi tiếng."),
    ],
    grammar: {
      title: "mùa / nghĩ",
      pattern: "最喜欢 / 认为",
      explainVi: "Ôn tuần 22: chọn mùa đi du lịch, nói về văn hóa nổi tiếng.",
      drills: [
        drill("Dịch: Đi mùa nào?", "哪个季节去？"),
        drill("Dịch: Đi mùa thu tốt nhất.", "秋天去最好。"),
        drill("Dịch: Bạn nghĩ sao?", "你认为呢？"),
        drill("Dịch: Chỗ đó nổi tiếng.", "那儿很有名。"),
      ],
    },
    dialogue: [
      line("A", "你认为哪个季节去北京最好？", "Nǐ rènwéi nǎge jìjié qù Běijīng zuì hǎo?", "Bạn nghĩ mùa nào đi Bắc Kinh tốt nhất?"),
      line("B", "秋天。那儿的文化很有名。", "Qiūtiān. Nàr de wénhuà hěn yǒumíng.", "Mùa thu. Văn hóa ở đó nổi tiếng."),
      line("A", "春天呢？环境也好吗？", "Chūntiān ne? Huánjìng yě hǎo ma?", "Còn xuân? Môi trường cũng tốt chứ?"),
      line("B", "也好。我最喜欢秋天。", "Yě hǎo. Wǒ zuì xǐhuan qiūtiān.", "Cũng tốt. Tôi thích thu nhất."),
    ],
    exercises: [
      ex("Tự viết: Bạn nghĩ mùa nào đi Bắc Kinh tốt nhất?", "你认为哪个季节去北京最好？"),
      ex("Tự viết: Mùa thu. Văn hóa ở đó nổi tiếng.", "秋天。那儿的文化很有名。"),
    ],
    scenario: "Chọn mùa du lịch Bắc Kinh: thu đẹp, văn hóa nổi tiếng, xuân cũng ổn.",
    start: "你认为哪个季节去北京最好？",
  },
  {
    id: 154,
    theme: "Bạn nước ngoài hỏi Tết",
    kind: "review",
    vocab: [
      v("历史", "lìshǐ", "Lịch sử (ôn)", "节日有历史。", "Jiérì yǒu lìshǐ.", "Ngày lễ có lịch sử."),
      v("习惯", "xíguàn", "Thói quen (ôn)", "这是习惯。", "Zhè shì xíguàn.", "Đây là thói quen."),
      v("注意", "zhùyì", "Chú ý (ôn)", "注意身体。", "Zhùyì shēntǐ.", "Chú ý sức khỏe."),
      v("终于", "zhōngyú", "Cuối cùng (ôn)", "终于放假了。", "Zhōngyú fàngjià le.", "Cuối cùng cũng nghỉ."),
      v("世界", "shìjiè", "Thế giới (ôn)", "世界各地。", "Shìjiè gè dì.", "Khắp thế giới."),
    ],
    grammar: {
      title: "Chỉ văn hóa",
      pattern: "对…有兴趣 / 认为",
      explainVi: "Roleplay bạn nước ngoài hỏi Tết. Khoá từ đến tuần 22.",
      drills: [
        drill("Dịch: Ngày lễ có lịch sử.", "节日有历史。"),
        drill("Dịch: Đây là thói quen.", "这是习惯。"),
        drill("Dịch: Cuối cùng cũng nghỉ.", "终于放假了。"),
        drill("Dịch: Chú ý sức khỏe.", "注意身体。"),
      ],
    },
    dialogue: [
      line("A", "春节有很长的历史吗？我对文化有兴趣。", "Chūnjié yǒu hěn cháng de lìshǐ ma? Wǒ duì wénhuà yǒu xìngqù.", "Tết có lịch sử dài không? Tôi thích văn hóa."),
      line("B", "有。回家是习惯。世界各地都知道。", "Yǒu. Huí jiā shì xíguàn. Shìjiè gè dì dōu zhīdào.", "Có. Về nhà là thói quen. Khắp nơi đều biết."),
      line("A", "终于放假了。要注意什么？", "Zhōngyú fàngjià le. Yào zhùyì shénme?", "Cuối cùng được nghỉ. Cần chú ý gì?"),
      line("B", "注意身体，也关心家里的人。", "Zhùyì shēntǐ, yě guānxīn jiā lǐ de rén.", "Chú ý sức khỏe, quan tâm người nhà."),
    ],
    exercises: [
      ex("Tự viết: Tôi thích văn hóa. Tết có lịch sử dài.", "我对文化有兴趣。春节有很长的历史。"),
      ex("Tự viết: Về nhà là thói quen.", "回家是习惯。"),
    ],
    scenario: "Bạn nước ngoài hỏi Tết: lịch sử, về nhà, chú ý sức khỏe người thân.",
    start: "春节有很长的历史吗？",
  },
  {
    id: 155,
    theme: "Sau này",
    kind: "learn",
    vocab: [
      v("以后", "yǐhòu", "Sau này / sau khi", "以后再来。", "Yǐhòu zài lái.", "Sau này đến lại."),
      v("一会儿", "yíhuìr", "Một lát", "一会儿见。", "Yíhuìr jiàn.", "Lát nữa gặp."),
      v("一样", "yíyàng", "Giống nhau", "我们一样。", "Wǒmen yíyàng.", "Chúng ta giống nhau."),
      v("一定", "yídìng", "Nhất định", "我一定来。", "Wǒ yídìng lái.", "Tôi nhất định đến."),
    ],
    grammar: {
      title: "以后 / 一会儿",
      pattern: "V 以后；一会儿 + V",
      explainVi: "以后: sau một mốc hoặc về sau. 一会儿: trong thời gian ngắn. 一定: cam kết.",
      drills: [
        drill("Dịch: Sau này đến lại.", "以后再来。"),
        drill("Dịch: Lát nữa gặp.", "一会儿见。"),
        drill("Dịch: Chúng ta giống nhau.", "我们一样。"),
        drill("Dịch: Tôi nhất định đến.", "我一定来。"),
      ],
    },
    dialogue: [
      line("A", "你一会儿来办公室吗？", "Nǐ yíhuìr lái bàngōngshì ma?", "Lát nữa bạn đến văn phòng không?"),
      line("B", "来。下课以后我一定来。", "Lái. Xià kè yǐhòu wǒ yídìng lái.", "Đến. Tan học tôi nhất định đến."),
      line("A", "我们想的一样。", "Wǒmen xiǎng de yíyàng.", "Chúng ta nghĩ giống nhau."),
      line("B", "好。一会儿见。", "Hǎo. Yíhuìr jiàn.", "Được. Lát nữa gặp."),
    ],
    exercises: [
      ex("Tự viết: Tan học tôi nhất định đến.", "下课以后我一定来。"),
      ex("Tự viết: Lát nữa gặp.", "一会儿见。"),
    ],
    scenario: "Hẹn lát nữa: tan học đến văn phòng, nghĩ giống nhau, nhất định đến.",
    start: "你一会儿来办公室吗？",
  },
  {
    id: 156,
    theme: "Để / rồi",
    kind: "learn",
    vocab: [
      v("愿意", "yuànyì", "Muốn / sẵn lòng", "我愿意帮助你。", "Wǒ yuànyì bāngzhù nǐ.", "Tôi sẵn lòng giúp bạn."),
      v("为了", "wèile", "Để / vì", "为了学习。", "Wèile xuéxí.", "Để học."),
      v("而且", "érqiě", "Hơn nữa", "便宜而且好。", "Piányi érqiě hǎo.", "Rẻ mà lại tốt."),
      v("然后", "ránhòu", "Sau đó", "先复习，然后休息。", "Xiān fùxí, ránhòu xiūxi.", "Ôn trước, rồi nghỉ."),
      v("先", "xiān", "Trước", "你先说。", "Nǐ xiān shuō.", "Bạn nói trước."),
    ],
    grammar: {
      title: "为了…; 先…然后…",
      pattern: "为了 + mục đích；先 V1，然后 V2",
      explainVi: "为了 nêu mục đích. 先…然后… sắp thứ tự. 而且 thêm ý cùng chiều.",
      drills: [
        drill("Dịch: Tôi sẵn lòng giúp bạn.", "我愿意帮助你。"),
        drill("Dịch: Để học.", "为了学习。"),
        drill("Dịch: Rẻ mà lại tốt.", "便宜而且好。"),
        drill("Dịch: Ôn trước, rồi nghỉ.", "先复习，然后休息。"),
      ],
    },
    dialogue: [
      line("A", "你愿意留下来吗？", "Nǐ yuànyì liú xiàlai ma?", "Bạn sẵn lòng ở lại không?"),
      line("B", "愿意。为了提高水平，而且同事很好。", "Yuànyì. Wèile tígāo shuǐpíng, érqiě tóngshì hěn hǎo.", "Sẵn lòng. Để nâng trình độ, hơn nữa đồng nghiệp tốt."),
      line("A", "那你先工作，然后去学习？", "Nà nǐ xiān gōngzuò, ránhòu qù xuéxí?", "Vậy bạn làm trước, rồi đi học?"),
      line("B", "对。我一定努力。", "Duì. Wǒ yídìng nǔlì.", "Đúng. Tôi nhất định cố gắng."),
    ],
    exercises: [
      ex("Tự viết: Sẵn lòng ở lại để nâng trình độ.", "愿意留下来，为了提高水平。"),
      ex("Tự viết: Làm trước, rồi đi học.", "先工作，然后去学习。"),
    ],
    scenario: "Hỏi có ở lại không: để học, đồng nghiệp tốt, làm rồi mới học thêm.",
    start: "你愿意留下来吗？",
  },
  {
    id: 157,
    theme: "Chỉ / trừ",
    kind: "learn",
    vocab: [
      v("又", "yòu", "Lại (đã xảy ra)", "他又来了。", "Tā yòu lái le.", "Anh ấy lại đến rồi."),
      v("只有", "zhǐyǒu", "Chỉ có", "只有周末有时间。", "Zhǐyǒu zhōumò yǒu shíjiān.", "Chỉ cuối tuần mới có giờ."),
      v("除了", "chúle", "Ngoại trừ", "除了今天都可以。", "Chúle jīntiān dōu kěyǐ.", "Trừ hôm nay đều được."),
      v("才", "cái", "Mới (muộn / điều kiện)", "现在才来。", "Xiànzài cái lái.", "Bây giờ mới đến."),
    ],
    grammar: {
      title: "只有…才…; 除了",
      pattern: "只有 + điều kiện，才 + kết quả",
      explainVi: "只有…才…: chỉ khi ấy mới. 除了 A，都 B. 又: lặp lại việc đã xảy ra.",
      drills: [
        drill("Dịch: Anh ấy lại đến rồi.", "他又来了。"),
        drill("Dịch: Chỉ cuối tuần mới có giờ.", "只有周末有时间。"),
        drill("Dịch: Trừ hôm nay đều được.", "除了今天都可以。"),
        drill("Dịch: Chỉ cuối tuần mới rảnh.", "只有周末才有时间。"),
      ],
    },
    dialogue: [
      line("A", "你又忙了吗？我们什么时候见面？", "Nǐ yòu máng le ma? Wǒmen shénme shíhou jiànmiàn?", "Bạn lại bận à? Khi nào gặp?"),
      line("B", "只有周末才有时间。", "Zhǐyǒu zhōumò cái yǒu shíjiān.", "Chỉ cuối tuần mới có giờ."),
      line("A", "除了周六，周日行吗？", "Chúle zhōuliù, zhōurì xíng ma?", "Trừ thứ bảy, chủ nhật được không?"),
      line("B", "周日才行。我一定来。", "Zhōurì cái xíng. Wǒ yídìng lái.", "Chủ nhật mới được. Tôi nhất định đến."),
    ],
    exercises: [
      ex("Tự viết: Chỉ cuối tuần mới có giờ.", "只有周末才有时间。"),
      ex("Tự viết: Trừ hôm nay đều được.", "除了今天都可以。"),
    ],
    scenario: "Hẹn gặp khi bận: chỉ cuối tuần mới rảnh, trừ thứ bảy thì chủ nhật.",
    start: "你又忙了吗？我们什么时候见面？",
  },
  {
    id: 158,
    theme: "把 / 被",
    kind: "learn",
    vocab: [
      v("把", "bǎ", "Đem / đưa (câu 把)", "把书给我。", "Bǎ shū gěi wǒ.", "Đưa sách cho tôi."),
      v("被", "bèi", "Bị (câu bị động)", "杯子被打破了。", "Bēizi bèi dǎ pò le.", "Cốc bị làm vỡ."),
      v("应该", "yīnggāi", "Nên", "你应该休息。", "Nǐ yīnggāi xiūxi.", "Bạn nên nghỉ."),
      v("要求", "yāoqiú", "Yêu cầu", "经理有要求。", "Jīnglǐ yǒu yāoqiú.", "Giám đốc có yêu cầu."),
    ],
    grammar: {
      title: "把 / 被",
      pattern: "把 + O + V；N + 被 + V",
      explainVi: "把: xử lý đồ vật (đưa, đặt, hoàn thành). 被: bị động, việc đã xảy ra với chủ ngữ.",
      drills: [
        drill("Dịch: Đưa sách cho tôi.", "把书给我。"),
        drill("Dịch: Cốc bị làm vỡ.", "杯子被打破了。"),
        drill("Dịch: Bạn nên nghỉ.", "你应该休息。"),
        drill("Dịch: Giám đốc có yêu cầu.", "经理有要求。"),
      ],
    },
    dialogue: [
      line("A", "请把护照给我。经理有要求。", "Qǐng bǎ hùzhào gěi wǒ. Jīnglǐ yǒu yāoqiú.", "Đưa hộ chiếu cho tôi. Giám đốc yêu cầu."),
      line("B", "好。行李箱被放在门口了。", "Hǎo. Xínglixiāng bèi fàng zài ménkǒu le.", "Được. Vali bị để ở cửa rồi."),
      line("A", "你应该先检查。", "Nǐ yīnggāi xiān jiǎnchá.", "Bạn nên kiểm tra trước."),
      line("B", "明白。我把东西都带上。", "Míngbai. Wǒ bǎ dōngxi dōu dài shàng.", "Hiểu. Tôi mang hết đồ theo."),
    ],
    exercises: [
      ex("Tự viết: Đưa hộ chiếu cho tôi.", "请把护照给我。"),
      ex("Tự viết: Vali bị để ở cửa rồi.", "行李箱被放在门口了。"),
    ],
    scenario: "Chuẩn bị đi: đưa hộ chiếu, vali bị để cửa, nên kiểm, mang hết đồ.",
    start: "请把护照给我。经理有要求。",
  },
  {
    id: 159,
    theme: "Cố gắng",
    kind: "learn",
    vocab: [
      v("影响", "yǐngxiǎng", "Ảnh hưởng", "这会影响成绩。", "Zhè huì yǐngxiǎng chéngjì.", "Cái này sẽ ảnh hưởng điểm."),
      v("解决", "jiějué", "Giải quyết", "问题解决了。", "Wèntí jiějué le.", "Vấn đề đã giải quyết."),
      v("努力", "nǔlì", "Nỗ lực", "努力学习。", "Nǔlì xuéxí.", "Học chăm."),
      v("年轻", "niánqīng", "Trẻ", "他还年轻。", "Tā hái niánqīng.", "Anh ấy còn trẻ."),
      v("老", "lǎo", "Già / cũ", "老师傅。", "Lǎo shīfu.", "Bậc thầy già."),
    ],
    grammar: {
      title: "努力 + động từ",
      pattern: "努力 + V；对…有影响",
      explainVi: "努力 học/làm chăm. 影响 + việc. 年轻 / 老 đối lập.",
      drills: [
        drill("Dịch: Cái này sẽ ảnh hưởng điểm.", "这会影响成绩。"),
        drill("Dịch: Vấn đề đã giải quyết.", "问题解决了。"),
        drill("Dịch: Học chăm.", "努力学习。"),
        drill("Dịch: Anh ấy còn trẻ.", "他还年轻。"),
      ],
    },
    dialogue: [
      line("A", "你还年轻，应该努力学习。", "Nǐ hái niánqīng, yīnggāi nǔlì xuéxí.", "Bạn còn trẻ, nên học chăm."),
      line("B", "我知道。不努力会影响以后。", "Wǒ zhīdào. Bù nǔlì huì yǐngxiǎng yǐhòu.", "Tôi biết. Không cố sẽ ảnh hưởng về sau."),
      line("A", "主要问题解决了吗？", "Zhǔyào wèntí jiějué le ma?", "Vấn đề chính giải quyết chưa?"),
      line("B", "解决了。老同事一直帮助我。", "Jiějué le. Lǎo tóngshì yìzhí bāngzhù wǒ.", "Rồi. Đồng nghiệp lâu năm luôn giúp tôi."),
    ],
    exercises: [
      ex("Tự viết: Bạn còn trẻ, nên học chăm.", "你还年轻，应该努力学习。"),
      ex("Tự viết: Không cố sẽ ảnh hưởng về sau.", "不努力会影响以后。"),
    ],
    scenario: "Khuyên bạn trẻ học chăm: không cố sẽ ảnh hưởng sau này, vấn đề đã xong.",
    start: "你还年轻，应该努力学习。",
  },
  {
    id: 160,
    theme: "Tổng hợp kế hoạch",
    kind: "review",
    vocab: [
      v("为了", "wèile", "Để (ôn)", "为了搬家。", "Wèile bān jiā.", "Để chuyển nhà."),
      v("把", "bǎ", "Đem (ôn)", "把东西搬进去。", "Bǎ dōngxi bān jìn qù.", "Đưa đồ vào."),
      v("应该", "yīnggāi", "Nên (ôn)", "应该先休息。", "Yīnggāi xiān xiūxi.", "Nên nghỉ trước."),
      v("一定", "yídìng", "Nhất định (ôn)", "我一定帮忙。", "Wǒ yídìng bāngmáng.", "Tôi nhất định giúp."),
      v("然后", "ránhòu", "Sau đó (ôn)", "然后吃饭。", "Ránhòu chī fàn.", "Rồi ăn cơm."),
    ],
    grammar: {
      title: "把 / 为了",
      pattern: "为了…把…",
      explainVi: "Ôn tuần 23: sắp một ngày bận, nhờ chuyển đồ.",
      drills: [
        drill("Dịch: Để chuyển nhà.", "为了搬家。"),
        drill("Dịch: Đưa đồ vào.", "把东西搬进去。"),
        drill("Dịch: Nên nghỉ trước.", "应该先休息。"),
        drill("Dịch: Tôi nhất định giúp.", "我一定帮忙。"),
      ],
    },
    dialogue: [
      line("A", "为了搬家，你打算怎么做？", "Wèile bān jiā, nǐ dǎsuàn zěnme zuò?", "Để chuyển nhà, bạn định làm sao?"),
      line("B", "先把东西搬进去，然后休息。", "Xiān bǎ dōngxi bān jìn qù, ránhòu xiūxi.", "Đưa đồ vào trước, rồi nghỉ."),
      line("A", "我愿意帮忙。你应该早点儿开始。", "Wǒ yuànyì bāngmáng. Nǐ yīnggāi zǎo diǎnr kāishǐ.", "Tôi sẵn lòng giúp. Bạn nên bắt đầu sớm."),
      line("B", "好。一会儿见，我一定等你。", "Hǎo. Yíhuìr jiàn, wǒ yídìng děng nǐ.", "Được. Lát gặp, tôi nhất định đợi."),
    ],
    exercises: [
      ex("Tự viết: Đưa đồ vào trước, rồi nghỉ.", "先把东西搬进去，然后休息。"),
      ex("Tự viết: Tôi sẵn lòng giúp.", "我愿意帮忙。"),
    ],
    scenario: "Sắp ngày chuyển nhà: đưa đồ vào, rồi nghỉ, bạn sẵn lòng giúp.",
    start: "为了搬家，你打算怎么做？",
  },
  {
    id: 161,
    theme: "Nhờ bạn chuyển nhà",
    kind: "review",
    vocab: [
      v("被", "bèi", "Bị (ôn)", "箱子被放错了。", "Xiāngzi bèi fàng cuò le.", "Thùng bị để nhầm."),
      v("只有", "zhǐyǒu", "Chỉ có (ôn)", "只有你能帮我。", "Zhǐyǒu nǐ néng bāng wǒ.", "Chỉ bạn mới giúp được."),
      v("除了", "chúle", "Trừ (ôn)", "除了桌子都搬了。", "Chúle zhuōzi dōu bān le.", "Trừ bàn đều chuyển rồi."),
      v("努力", "nǔlì", "Nỗ lực (ôn)", "大家都很努力。", "Dàjiā dōu hěn nǔlì.", "Mọi người đều cố."),
      v("要求", "yāoqiú", "Yêu cầu (ôn)", "没有别的要求。", "Méiyǒu bié de yāoqiú.", "Không yêu cầu gì thêm."),
    ],
    grammar: {
      title: "Chỉ 把 / kế hoạch",
      pattern: "把 / 被 / 只有…才…",
      explainVi: "Roleplay nhờ chuyển nhà. Khoá từ đến tuần 23.",
      drills: [
        drill("Dịch: Thùng bị để nhầm.", "箱子被放错了。"),
        drill("Dịch: Chỉ bạn mới giúp được.", "只有你能帮我。"),
        drill("Dịch: Trừ bàn đều chuyển rồi.", "除了桌子都搬了。"),
        drill("Dịch: Mọi người đều cố.", "大家都很努力。"),
      ],
    },
    dialogue: [
      line("A", "只有你才愿意帮我搬家。", "Zhǐyǒu nǐ cái yuànyì bāng wǒ bān jiā.", "Chỉ bạn mới sẵn lòng giúp tôi chuyển nhà."),
      line("B", "当然。把箱子搬上去。那个被放错了。", "Dāngrán. Bǎ xiāngzi bān shàng qù. Nàge bèi fàng cuò le.", "Đương nhiên. Khiêng thùng lên. Cái kia bị để nhầm."),
      line("A", "除了桌子，都完成了吗？", "Chúle zhuōzi, dōu wánchéng le ma?", "Trừ bàn, đều xong chưa?"),
      line("B", "快了。大家都很努力，没有别的要求。", "Kuài le. Dàjiā dōu hěn nǔlì, méiyǒu bié de yāoqiú.", "Sắp. Mọi người đều cố, không yêu cầu gì thêm."),
    ],
    exercises: [
      ex("Tự viết: Chỉ bạn mới sẵn lòng giúp tôi chuyển nhà.", "只有你才愿意帮我搬家。"),
      ex("Tự viết: Khiêng thùng lên. Cái kia bị để nhầm.", "把箱子搬上去。那个被放错了。"),
    ],
    scenario: "Nhờ chuyển nhà: khiêng thùng, cái bị để nhầm, trừ bàn thì gần xong.",
    start: "只有你才愿意帮我搬家。",
  },
  {
    id: 162,
    theme: "Hẹn gặp rồi hỏi thăm",
    kind: "review",
    vocab: [
      v("刚才", "gāngcái", "Vừa mới (ôn)", "刚才见面了。", "Gāngcái jiànmiàn le.", "Vừa gặp rồi."),
      v("如果", "rúguǒ", "Nếu (ôn)", "如果有空就来。", "Rúguǒ yǒu kòng jiù lái.", "Nếu rảnh thì đến."),
      v("担心", "dānxīn", "Lo (ôn)", "别担心。", "Bié dānxīn.", "Đừng lo."),
      v("舒服", "shūfu", "Khỏe (ôn)", "现在舒服吗？", "Xiànzài shūfu ma?", "Giờ khỏe không?"),
      v("着急", "zháojí", "Sốt ruột (ôn)", "别着急。", "Bié zháojí.", "Đừng sốt ruột."),
    ],
    grammar: {
      title: "刚才 如果 越来越",
      pattern: "刚才 / 如果…就… / 越来越",
      explainVi: "Ôn gặp gỡ + cảm xúc. Không thêm từ mới.",
      drills: [
        drill("Dịch: Vừa gặp rồi.", "刚才见面了。"),
        drill("Dịch: Nếu rảnh thì đến.", "如果有空就来。"),
        drill("Dịch: Đừng lo. Giờ khỏe không?", "别担心。现在舒服吗？"),
        drill("Dịch: Ngày càng tốt.", "越来越好。"),
      ],
    },
    dialogue: [
      line("A", "刚才我们见面了。你还好吗？", "Gāngcái wǒmen jiànmiàn le. Nǐ hái hǎo ma?", "Vừa gặp rồi. Bạn vẫn ổn chứ?"),
      line("B", "越来越好。其实刚才有点儿不舒服。", "Yuè lái yuè hǎo. Qíshí gāngcái yǒudiǎnr bù shūfu.", "Ngày càng tốt. Thật ra vừa hơi mệt."),
      line("A", "我有点儿担心。如果累就休息。", "Wǒ yǒudiǎnr dānxīn. Rúguǒ lèi jiù xiūxi.", "Tôi hơi lo. Nếu mệt thì nghỉ."),
      line("B", "别担心。我已经舒服了。", "Bié dānxīn. Wǒ yǐjīng shūfu le.", "Đừng lo. Tôi đã khỏe rồi."),
    ],
    exercises: [
      ex("Tự viết: Vừa gặp rồi. Bạn vẫn ổn chứ?", "刚才我们见面了。你还好吗？"),
      ex("Tự viết: Nếu mệt thì nghỉ. Đừng lo.", "如果累就休息。别担心。"),
    ],
    scenario: "Gặp lại: hỏi sức khỏe, ngày càng đỡ, nếu mệt thì nghỉ.",
    start: "刚才我们见面了。你还好吗？",
  },
  {
    id: 163,
    theme: "Tìm ga, chuyển đồ",
    kind: "review",
    vocab: [
      v("附近", "fùjìn", "Gần (ôn)", "附近有地铁。", "Fùjìn yǒu dìtiě.", "Gần có tàu."),
      v("层", "céng", "Tầng (ôn)", "在二层。", "Zài èr céng.", "Ở tầng hai."),
      v("把", "bǎ", "Đem (ôn)", "把行李箱带上。", "Bǎ xínglixiāng dài shàng.", "Mang vali theo."),
      v("换", "huàn", "Đổi (ôn)", "换电梯。", "Huàn diàntī.", "Đổi thang máy."),
      v("方便", "fāngbiàn", "Tiện (ôn)", "这样方便。", "Zhèyàng fāngbiàn.", "Như thế tiện."),
    ],
    grammar: {
      title: "附近 把 层",
      pattern: "附近 / 把 / 层",
      explainVi: "Ôn thành phố + đi lại. Không thêm từ mới.",
      drills: [
        drill("Dịch: Gần có tàu.", "附近有地铁。"),
        drill("Dịch: Ở tầng hai.", "在二层。"),
        drill("Dịch: Mang vali theo.", "把行李箱带上。"),
        drill("Dịch: Như thế tiện.", "这样方便。"),
      ],
    },
    dialogue: [
      line("A", "地铁站在附近吗？行李箱怎么办？", "Dìtiě zhàn zài fùjìn ma? Xínglixiāng zěnme bàn?", "Ga tàu gần không? Vali thì sao?"),
      line("B", "很近。把行李箱带到二层，再换电梯。", "Hěn jìn. Bǎ xínglixiāng dài dào èr céng, zài huàn diàntī.", "Rất gần. Mang vali lên tầng 2, rồi đổi thang máy."),
      line("A", "这样方便吗？", "Zhèyàng fāngbiàn ma?", "Như thế có tiện không?"),
      line("B", "方便。下一站就到办公室。", "Fāngbiàn. Xià yí zhàn jiù dào bàngōngshì.", "Tiện. Ga sau là tới văn phòng."),
    ],
    exercises: [
      ex("Tự viết: Ga tàu gần không? Mang vali theo.", "地铁站在附近吗？把行李箱带上。"),
      ex("Tự viết: Mang vali lên tầng 2, rồi đổi thang máy.", "把行李箱带到二层，再换电梯。"),
    ],
    scenario: "Tìm ga gần, mang vali lên tầng, đổi thang máy tới văn phòng.",
    start: "地铁站在附近吗？行李箱怎么办？",
  },
  {
    id: 164,
    theme: "Kế hoạch ôn thi",
    kind: "review",
    vocab: [
      v("打算", "dǎsuàn", "Dự định (ôn)", "打算怎么复习？", "Dǎsuàn zěnme fùxí?", "Định ôn thế nào?"),
      v("必须", "bìxū", "Phải (ôn)", "必须完成练习。", "Bìxū wánchéng liànxí.", "Phải xong bài luyện."),
      v("成绩", "chéngjì", "Điểm (ôn)", "提高成绩。", "Tígāo chéngjì.", "Nâng điểm."),
      v("明白", "míngbai", "Hiểu (ôn)", "现在明白了。", "Xiànzài míngbai le.", "Giờ hiểu rồi."),
      v("努力", "nǔlì", "Nỗ lực (ôn)", "一起努力。", "Yìqǐ nǔlì.", "Cùng cố gắng."),
    ],
    grammar: {
      title: "打算 必须",
      pattern: "打算 / 必须 / 把…完成",
      explainVi: "Ôn học / làm. Không thêm từ mới.",
      drills: [
        drill("Dịch: Định ôn thế nào?", "打算怎么复习？"),
        drill("Dịch: Phải xong bài luyện.", "必须完成练习。"),
        drill("Dịch: Nâng điểm.", "提高成绩。"),
        drill("Dịch: Cùng cố gắng.", "一起努力。"),
      ],
    },
    dialogue: [
      line("A", "考试以前，你打算怎么复习？", "Kǎoshì yǐqián, nǐ dǎsuàn zěnme fùxí?", "Trước thi, bạn định ôn thế nào?"),
      line("B", "必须把练习完成，再检查。", "Bìxū bǎ liànxí wánchéng, zài jiǎnchá.", "Phải xong bài luyện rồi kiểm."),
      line("A", "这样成绩会提高。你明白吗？", "Zhèyàng chéngjì huì tígāo. Nǐ míngbai ma?", "Như thế điểm sẽ lên. Bạn hiểu không?"),
      line("B", "明白。我们一起努力。", "Míngbai. Wǒmen yìqǐ nǔlì.", "Hiểu. Chúng ta cùng cố."),
    ],
    exercises: [
      ex("Tự viết: Trước thi, bạn định ôn thế nào?", "考试以前，你打算怎么复习？"),
      ex("Tự viết: Phải xong bài luyện rồi kiểm.", "必须把练习完成，再检查。"),
    ],
    scenario: "Lập kế hoạch ôn thi: xong bài luyện, kiểm, cùng cố để nâng điểm.",
    start: "考试以前，你打算怎么复习？",
  },
  {
    id: 165,
    theme: "Mua quà Tết",
    kind: "review",
    vocab: [
      v("需要", "xūyào", "Cần (ôn)", "需要买礼物。", "Xūyào mǎi lǐwù.", "Cần mua quà."),
      v("认为", "rènwéi", "Cho rằng (ôn)", "你认为呢？", "Nǐ rènwéi ne?", "Bạn nghĩ sao?"),
      v("新鲜", "xīnxiān", "Tươi (ôn)", "花很新鲜。", "Huā hěn xīnxiān.", "Hoa rất tươi."),
      v("文化", "wénhuà", "Văn hóa (ôn)", "这是文化。", "Zhè shì wénhuà.", "Đây là văn hóa."),
      v("满意", "mǎnyì", "Hài lòng (ôn)", "我很满意。", "Wǒ hěn mǎnyì.", "Tôi rất hài lòng."),
    ],
    grammar: {
      title: "需要 认为",
      pattern: "需要 / 认为 / 对…满意",
      explainVi: "Ôn mua sắm + văn hóa. Không thêm từ mới.",
      drills: [
        drill("Dịch: Cần mua quà.", "需要买礼物。"),
        drill("Dịch: Bạn nghĩ sao?", "你认为呢？"),
        drill("Dịch: Hoa rất tươi.", "花很新鲜。"),
        drill("Dịch: Tôi rất hài lòng.", "我很满意。"),
      ],
    },
    dialogue: [
      line("A", "过节需要买什么礼物？你认为呢？", "Guò jié xūyào mǎi shénme lǐwù? Nǐ rènwéi ne?", "Tết cần mua quà gì? Bạn nghĩ sao?"),
      line("B", "花很新鲜，而且有文化意思。", "Huā hěn xīnxiān, érqiě yǒu wénhuà yìsi.", "Hoa tươi, lại có ý văn hóa."),
      line("A", "用信用卡可以吗？", "Yòng xìnyòngkǎ kěyǐ ma?", "Dùng thẻ được không?"),
      line("B", "可以。我对这个选择很满意。", "Kěyǐ. Wǒ duì zhège xuǎnzé hěn mǎnyì.", "Được. Tôi hài lòng lựa chọn này."),
    ],
    exercises: [
      ex("Tự viết: Tết cần mua quà gì? Bạn nghĩ sao?", "过节需要买什么礼物？你认为呢？"),
      ex("Tự viết: Hoa tươi, lại có ý văn hóa.", "花很新鲜，而且有文化意思。"),
    ],
    scenario: "Chọn quà Tết: hoa tươi có ý văn hóa, trả thẻ, hài lòng lựa chọn.",
    start: "过节需要买什么礼物？你认为呢？",
  },
  {
    id: 166,
    theme: "Mock mini-test",
    kind: "review",
    vocab: [
      v("选择", "xuǎnzé", "Lựa chọn (ôn)", "请选择。", "Qǐng xuǎnzé.", "Hãy chọn."),
      v("明白", "míngbai", "Hiểu (ôn)", "你明白题吗？", "Nǐ míngbai tí ma?", "Bạn hiểu câu không?"),
      v("如果", "rúguǒ", "Nếu (ôn)", "如果错了就再试。", "Rúguǒ cuò le jiù zài shì.", "Nếu sai thì thử lại."),
      v("应该", "yīnggāi", "Nên (ôn)", "应该注意。", "Yīnggāi zhùyì.", "Nên chú ý."),
      v("终于", "zhōngyú", "Cuối cùng (ôn)", "终于做完了。", "Zhōngyú zuò wán le.", "Cuối cùng làm xong."),
    ],
    grammar: {
      title: "Ngân 20 câu",
      pattern: "HSK 3 — nghe + đọc hiểu ngắn",
      explainVi: "Mini-test: nếu…thì, 把/被, cần, cho rằng. Không thêm từ mới.",
      drills: [
        drill("Dịch: Hãy chọn. Bạn hiểu câu không?", "请选择。你明白题吗？"),
        drill("Dịch: Nếu sai thì thử lại.", "如果错了就再试。"),
        drill("Dịch: Nên chú ý.", "应该注意。"),
        drill("Dịch: Cuối cùng làm xong.", "终于做完了。"),
      ],
    },
    dialogue: [
      line("A", "你明白这道题吗？请选择。", "Nǐ míngbai zhè dào tí ma? Qǐng xuǎnzé.", "Bạn hiểu câu này không? Hãy chọn."),
      line("B", "明白。如果不确定，应该再看。", "Míngbai. Rúguǒ bù quèdìng, yīnggāi zài kàn.", "Hiểu. Nếu chưa chắc, nên xem lại."),
      line("A", "把答案写清楚。", "Bǎ dá'àn xiě qīngchu.", "Viết đáp án cho rõ."),
      line("B", "好。终于做完了。", "Hǎo. Zhōngyú zuò wán le.", "Được. Cuối cùng xong rồi."),
    ],
    exercises: [
      ex("Tự viết: Bạn hiểu câu này không? Hãy chọn.", "你明白这道题吗？请选择。"),
      ex("Tự viết: Nếu chưa chắc, nên xem lại.", "如果不确定，应该再看。"),
    ],
    scenario: "Mini-test nói: hiểu đề, chọn, nếu chưa chắc thì xem lại, viết rõ, xong.",
    start: "你明白这道题吗？请选择。",
  },
  {
    id: 167,
    theme: "Phỏng vấn xin việc",
    kind: "review",
    vocab: [
      v("经理", "jīnglǐ", "Giám đốc (ôn)", "经理好。", "Jīnglǐ hǎo.", "Chào giám đốc."),
      v("愿意", "yuànyì", "Sẵn lòng (ôn)", "我愿意学习。", "Wǒ yuànyì xuéxí.", "Tôi sẵn lòng học."),
      v("了解", "liǎojiě", "Tìm hiểu (ôn)", "我了解公司。", "Wǒ liǎojiě gōngsī.", "Tôi hiểu công ty."),
      v("要求", "yāoqiú", "Yêu cầu (ôn)", "有什么要求？", "Yǒu shénme yāoqiú?", "Có yêu cầu gì?"),
      v("一定", "yídìng", "Nhất định (ôn)", "我一定努力。", "Wǒ yídìng nǔlì.", "Tôi nhất định cố."),
    ],
    grammar: {
      title: "Toàn mẫu",
      pattern: "为了 / 愿意 / 必须",
      explainVi: "Hội thoại A: phỏng vấn xin việc. Khoá HSK 3.",
      drills: [
        drill("Dịch: Chào giám đốc.", "经理好。"),
        drill("Dịch: Tôi sẵn lòng học.", "我愿意学习。"),
        drill("Dịch: Tôi hiểu công ty.", "我了解公司。"),
        drill("Dịch: Tôi nhất định cố.", "我一定努力。"),
      ],
    },
    dialogue: [
      line("A", "你为什么想来我们公司？", "Nǐ wèishénme xiǎng lái wǒmen gōngsī?", "Vì sao bạn muốn vào công ty chúng tôi?"),
      line("B", "为了提高自己。我了解你们，也愿意学习。", "Wèile tígāo zìjǐ. Wǒ liǎojiě nǐmen, yě yuànyì xuéxí.", "Để nâng mình. Tôi hiểu các bạn, sẵn lòng học."),
      line("A", "工作有要求，必须认真。你能做到吗？", "Gōngzuò yǒu yāoqiú, bìxū rènzhēn. Nǐ néng zuò dào ma?", "Việc có yêu cầu, phải nghiêm túc. Bạn làm được không?"),
      line("B", "能。我一定努力，请经理放心。", "Néng. Wǒ yídìng nǔlì, qǐng jīnglǐ fàngxīn.", "Được. Tôi nhất định cố, giám đốc yên tâm."),
    ],
    exercises: [
      ex("Tự viết: Để nâng mình. Tôi sẵn lòng học.", "为了提高自己。我愿意学习。"),
      ex("Tự viết: Việc có yêu cầu, phải nghiêm túc.", "工作有要求，必须认真。"),
    ],
    scenario: "Phỏng vấn: vì sao ứng tuyển, hiểu công ty, yêu cầu nghiêm túc, cam kết cố gắng.",
    start: "你为什么想来我们公司？",
  },
  {
    id: 168,
    theme: "Ngày đầu du học ở Bắc Kinh",
    kind: "review",
    vocab: [
      v("习惯", "xíguàn", "Quen (ôn)", "会习惯的。", "Huì xíguàn de.", "Sẽ quen thôi."),
      v("环境", "huánjìng", "Môi trường (ôn)", "这儿环境很好。", "Zhèr huánjìng hěn hǎo.", "Ở đây môi trường tốt."),
      v("以后", "yǐhòu", "Sau này (ôn)", "以后常联系。", "Yǐhòu cháng liánxì.", "Sau này thường liên lạc."),
      v("机会", "jīhuì", "Cơ hội (ôn)", "好机会。", "Hǎo jīhuì.", "Cơ hội tốt."),
      v("终于", "zhōngyú", "Cuối cùng (ôn)", "终于到了。", "Zhōngyú dào le.", "Cuối cùng cũng tới."),
    ],
    grammar: {
      title: "Không thêm mẫu mới",
      pattern: "HSK 1–3 toàn mẫu",
      explainVi: "Tốt nghiệp HSK 3: ngày đầu du học ở Bắc Kinh. Chỉ từ đã khoá.",
      drills: [
        drill("Dịch: Sẽ quen thôi.", "会习惯的。"),
        drill("Dịch: Ở đây môi trường tốt.", "这儿环境很好。"),
        drill("Dịch: Sau này thường liên lạc.", "以后常联系。"),
        drill("Dịch: Cuối cùng cũng tới.", "终于到了。"),
      ],
    },
    dialogue: [
      line("A", "欢迎来北京！你终于到了。", "Huānyíng lái Běijīng! Nǐ zhōngyú dào le.", "Hoan nghênh đến Bắc Kinh! Cuối cùng bạn cũng tới."),
      line("B", "谢谢。这儿环境很好。我有点儿不习惯。", "Xièxie. Zhèr huánjìng hěn hǎo. Wǒ yǒudiǎnr bù xíguàn.", "Cảm ơn. Ở đây môi trường tốt. Tôi hơi chưa quen."),
      line("A", "会习惯的。这是学习的好机会。", "Huì xíguàn de. Zhè shì xuéxí de hǎo jīhuì.", "Sẽ quen. Đây là cơ hội học tốt."),
      line("B", "我一定努力。以后常联系。", "Wǒ yídìng nǔlì. Yǐhòu cháng liánxì.", "Tôi nhất định cố. Sau này thường liên lạc."),
    ],
    exercises: [
      ex("Tự viết: Cuối cùng bạn cũng tới. Ở đây môi trường tốt.", "你终于到了。这儿环境很好。"),
      ex("Tự viết: Sẽ quen. Đây là cơ hội học tốt.", "会习惯的。这是学习的好机会。"),
    ],
    scenario: "Ngày đầu du học Bắc Kinh: chào, môi trường, chưa quen, cơ hội học, hẹn liên lạc.",
    start: "欢迎来北京！你终于到了。",
  },
];

function weekOf(id) {
  return Math.ceil(id / 7);
}

function systemPrompt(level, words, start) {
  return `Bạn là bạn nói tiếng Trung trình độ HSK ${level}. Chỉ dùng các từ: ${words.join(", ")}. Mỗi lượt 1–2 câu ngắn. Viết Hán + pinyin. Nếu học viên sai, sửa nhẹ bằng tiếng Việt rồi hỏi lại. Không thêm từ mới. Bắt đầu bằng: ${start}`;
}

const hsk2 = JSON.parse(readFileSync(join(dir, "112.json"), "utf8"));
let allowed = [...hsk2.aiPrompt.allowedWords];

for (const lesson of LESSONS) {
  if (lesson.kind === "learn") {
    for (const item of lesson.vocab) {
      if (!item.vi.includes("(ôn") && !allowed.includes(item.han)) {
        allowed.push(item.han);
      }
    }
  }
  const week = weekOf(lesson.id);
  const payload = {
    id: lesson.id,
    week,
    hsk: 3,
    theme: lesson.theme,
    kind: lesson.kind,
    vocab: lesson.vocab,
    grammar: lesson.grammar,
    dialogue: lesson.dialogue,
    exercises: lesson.exercises,
    aiPrompt: {
      scenario: lesson.scenario,
      system: systemPrompt(3, allowed, lesson.start),
      allowedWords: [...allowed],
      turns: 5,
    },
    timer: TIMER,
  };
  const name = `${String(lesson.id).padStart(3, "0")}.json`;
  writeFileSync(join(dir, name), `${JSON.stringify(payload, null, 2)}\n`);
}

console.log(`Wrote ${LESSONS.length} lessons, last allowed ${allowed.length} words`);
