import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const dir = dirname(fileURLToPath(import.meta.url));
const TIMER = { review: 5, vocab: 8, grammar: 8, talk: 5, ai: 4 };

function v(han, pinyin, vi, exHan, exPy, exVi) {
  return {
    han,
    pinyin,
    vi,
    example: { han: exHan, pinyin: exPy, vi: exVi },
  };
}

function line(speaker, han, pinyin, vi) {
  return { speaker, han, pinyin, vi };
}

function drill(prompt, answer) {
  return { prompt, answer };
}

function ex(prompt, answer) {
  return { type: "write", prompt, answer };
}

const LESSONS = [
  {
    id: 57,
    theme: "Thức và ngủ",
    kind: "learn",
    vocab: [
      v("起床", "qǐchuáng", "Thức dậy", "我起床了。", "Wǒ qǐchuáng le.", "Tôi đã dậy."),
      v("睡觉", "shuìjiào", "Ngủ", "晚上睡觉。", "Wǎnshang shuìjiào.", "Tối ngủ."),
      v("早上", "zǎoshang", "Buổi sáng", "早上你好。", "Zǎoshang nǐ hǎo.", "Chào buổi sáng."),
      v("晚上", "wǎnshang", "Buổi tối", "晚上见。", "Wǎnshang jiàn.", "Tối gặp."),
      v("已经", "yǐjīng", "Đã / rồi", "我已经起床了。", "Wǒ yǐjīng qǐchuáng le.", "Tôi đã dậy rồi."),
    ],
    grammar: {
      title: "已经 + động từ",
      pattern: "已经 + V + 了",
      explainVi: "已经 nói việc đã xảy ra. Thường kèm 了: 我已经起床了。",
      drills: [
        drill("Dịch: Tôi đã dậy rồi.", "我已经起床了。"),
        drill("Dịch: Tôi đã ngủ rồi.", "我已经睡觉了。"),
        drill("Hỏi: Bạn đã dậy chưa?", "你已经起床了吗？"),
        drill("Dịch: Tối tôi ngủ.", "晚上我睡觉。"),
      ],
    },
    dialogue: [
      line("A", "你已经起床了吗？", "Nǐ yǐjīng qǐchuáng le ma?", "Bạn đã dậy chưa?"),
      line("B", "我已经起床了。", "Wǒ yǐjīng qǐchuáng le.", "Tôi đã dậy rồi."),
      line("A", "早上你做什么？", "Zǎoshang nǐ zuò shénme?", "Sáng bạn làm gì?"),
      line("B", "早上我喝茶。晚上睡觉。", "Zǎoshang wǒ hē chá. Wǎnshang shuìjiào.", "Sáng tôi uống trà. Tối ngủ."),
    ],
    exercises: [
      ex("Tự viết: Tôi đã dậy rồi.", "我已经起床了。"),
      ex("Tự viết: Tối tôi ngủ.", "晚上我睡觉。"),
    ],
    scenario: "Bạn cùng phòng hỏi bạn đã dậy chưa, sáng làm gì, tối có ngủ sớm không.",
    start: "你已经起床了吗？",
  },
  {
    id: 58,
    theme: "Đang làm",
    kind: "learn",
    vocab: [
      v("正在", "zhèngzài", "Đang", "我正在喝茶。", "Wǒ zhèngzài hē chá.", "Tôi đang uống trà."),
      v("着", "zhe", "Đang (tiếp diễn)", "看着书。", "Kàn zhe shū.", "Đang xem sách."),
      v("洗", "xǐ", "Rửa", "我正在洗。", "Wǒ zhèngzài xǐ.", "Tôi đang rửa."),
      v("准备", "zhǔnbèi", "Chuẩn bị", "我准备去学校。", "Wǒ zhǔnbèi qù xuéxiào.", "Tôi chuẩn bị đi trường."),
      v("开始", "kāishǐ", "Bắt đầu", "现在开始。", "Xiànzài kāishǐ.", "Bây giờ bắt đầu."),
    ],
    grammar: {
      title: "正在 / V + 着",
      pattern: "正在 + V / V + 着",
      explainVi: "正在 + động từ: đang làm. 着 sau động từ: trạng thái đang tiếp diễn. Ngày này tập 正在 là chính.",
      drills: [
        drill("Dịch: Tôi đang rửa.", "我正在洗。"),
        drill("Dịch: Tôi đang chuẩn bị.", "我正在准备。"),
        drill("Dịch: Bây giờ bắt đầu.", "现在开始。"),
        drill("Hỏi: Bạn đang làm gì?", "你正在做什么？"),
      ],
    },
    dialogue: [
      line("A", "你正在做什么？", "Nǐ zhèngzài zuò shénme?", "Bạn đang làm gì?"),
      line("B", "我正在洗。", "Wǒ zhèngzài xǐ.", "Tôi đang rửa."),
      line("A", "你准备去学校吗？", "Nǐ zhǔnbèi qù xuéxiào ma?", "Bạn chuẩn bị đi trường à?"),
      line("B", "是。现在开始准备。", "Shì. Xiànzài kāishǐ zhǔnbèi.", "Phải. Bây giờ bắt đầu chuẩn bị."),
    ],
    exercises: [
      ex("Tự viết: Tôi đang uống trà.", "我正在喝茶。"),
      ex("Tự viết: Tôi chuẩn bị đi trường.", "我准备去学校。"),
    ],
    scenario: "Bạn hỏi bạn cùng phòng đang làm gì, đã chuẩn bị đi học chưa.",
    start: "你正在做什么？",
  },
  {
    id: 59,
    theme: "Thời lượng",
    kind: "learn",
    vocab: [
      v("时间", "shíjiān", "Thời gian (khoảng)", "你有时间吗？", "Nǐ yǒu shíjiān ma?", "Bạn có thời gian không?"),
      v("小时", "xiǎoshí", "Giờ (độ dài)", "一个小时。", "Yí ge xiǎoshí.", "Một tiếng."),
      v("每", "měi", "Mỗi", "我每天喝茶。", "Wǒ měi tiān hē chá.", "Tôi uống trà mỗi ngày."),
      v("完", "wán", "Xong", "我做完了。", "Wǒ zuò wán le.", "Tôi làm xong rồi."),
    ],
    grammar: {
      title: "每 + buổi / ngày",
      pattern: "每 + 天/早上 + V",
      explainVi: "每 = mỗi. 每天早上我起床。完 sau động từ: làm xong.",
      drills: [
        drill("Dịch: Mỗi ngày tôi dậy.", "我每天起床。"),
        drill("Dịch: Bạn có thời gian không?", "你有时间吗？"),
        drill("Dịch: Một tiếng.", "一个小时。"),
        drill("Dịch: Tôi làm xong rồi.", "我做完了。"),
      ],
    },
    dialogue: [
      line("A", "你有时间吗？", "Nǐ yǒu shíjiān ma?", "Bạn có thời gian không?"),
      line("B", "有。一个小时。", "Yǒu. Yí ge xiǎoshí.", "Có. Một tiếng."),
      line("A", "你每天早上做什么？", "Nǐ měi tiān zǎoshang zuò shénme?", "Mỗi sáng bạn làm gì?"),
      line("B", "我每天早上起床，喝茶。", "Wǒ měi tiān zǎoshang qǐchuáng, hē chá.", "Mỗi sáng tôi dậy, uống trà."),
      line("A", "你做完了吗？", "Nǐ zuò wán le ma?", "Bạn làm xong chưa?"),
      line("B", "做完了。", "Zuò wán le.", "Xong rồi."),
    ],
    exercises: [
      ex("Tự viết: Mỗi ngày tôi dậy.", "我每天起床。"),
      ex("Tự viết: Tôi làm xong rồi.", "我做完了。"),
    ],
    scenario: "Hỏi bạn có rảnh một tiếng không, mỗi sáng làm gì, việc đã xong chưa.",
    start: "你有时间吗？",
  },
  {
    id: 60,
    theme: "Chúng tôi",
    kind: "learn",
    vocab: [
      v("我们", "wǒmen", "Chúng tôi / chúng ta", "我们是学生。", "Wǒmen shì xuésheng.", "Chúng tôi là học sinh."),
      v("自己", "zìjǐ", "Bản thân", "我自己做。", "Wǒ zìjǐ zuò.", "Tôi tự làm."),
      v("大家", "dàjiā", "Mọi người", "大家都很好。", "Dàjiā dōu hěn hǎo.", "Mọi người đều khỏe."),
      v("还", "hái", "Còn / vẫn", "我还在学校。", "Wǒ hái zài xuéxiào.", "Tôi vẫn ở trường."),
    ],
    grammar: {
      title: "还 + động từ",
      pattern: "还 + V / 还在 + nơi",
      explainVi: "还 = vẫn / còn. 我还在学习。我们 / 大家 / 自己 dùng để nói về nhóm và bản thân.",
      drills: [
        drill("Dịch: Chúng tôi là học sinh.", "我们是学生。"),
        drill("Dịch: Tôi tự làm.", "我自己做。"),
        drill("Dịch: Mọi người đều khỏe.", "大家都很好。"),
        drill("Dịch: Tôi vẫn ở trường.", "我还在学校。"),
      ],
    },
    dialogue: [
      line("A", "你是学生吗？", "Nǐ shì xuésheng ma?", "Bạn là học sinh à?"),
      line("B", "我们是学生。大家都很忙。", "Wǒmen shì xuésheng. Dàjiā dōu hěn máng.", "Chúng tôi là học sinh. Mọi người đều bận."),
      line("A", "你还在学校吗？", "Nǐ hái zài xuéxiào ma?", "Bạn vẫn ở trường à?"),
      line("B", "还在。我自己做。", "Hái zài. Wǒ zìjǐ zuò.", "Vẫn. Tôi tự làm."),
    ],
    exercises: [
      ex("Tự viết: Chúng tôi còn đang làm.", "我们还在做。"),
      ex("Tự viết: Tôi tự làm.", "我自己做。"),
    ],
    scenario: "Hỏi nhóm học sinh còn ở trường không, ai tự học, mọi người có bận không.",
    start: "你是学生吗？",
  },
  {
    id: 61,
    theme: "Ở nhà",
    kind: "learn",
    vocab: [
      v("住", "zhù", "Ở / sống", "我住在学校。", "Wǒ zhù zài xuéxiào.", "Tôi ở trường."),
      v("别", "bié", "Đừng", "别说话。", "Bié shuōhuà.", "Đừng nói chuyện."),
      v("再", "zài", "Lại / nữa", "再见。", "Zàijiàn.", "Tạm biệt."),
      v("就", "jiù", "Liền / ngay", "我现在就去。", "Wǒ xiànzài jiù qù.", "Tôi đi ngay bây giờ."),
    ],
    grammar: {
      title: "别 + động từ",
      pattern: "别 + V",
      explainVi: "别 = đừng. 别说话。再 = lại/nữa. 就 nhấn việc xảy ra ngay.",
      drills: [
        drill("Dịch: Đừng nói.", "别说。"),
        drill("Dịch: Tôi ở nhà.", "我住在家。"),
        drill("Dịch: Tôi đi ngay.", "我就去。"),
        drill("Dịch: Tạm biệt. Hẹn gặp lại.", "再见。"),
      ],
    },
    dialogue: [
      line("A", "你住在哪儿？", "Nǐ zhù zài nǎr?", "Bạn ở đâu?"),
      line("B", "我住在家。别说话，太晚了。", "Wǒ zhù zài jiā. Bié shuōhuà, tài wǎn le.", "Tôi ở nhà. Đừng nói, muộn rồi."),
      line("A", "对不起。我现在就去睡觉。", "Duìbuqǐ. Wǒ xiànzài jiù qù shuìjiào.", "Xin lỗi. Tôi đi ngủ ngay."),
      line("B", "好。再见。", "Hǎo. Zàijiàn.", "Được. Tạm biệt."),
    ],
    exercises: [
      ex("Tự viết: Đừng nói to.", "别说。"),
      ex("Tự viết: Tôi ở nhà.", "我住在家。"),
    ],
    scenario: "Hỏi chỗ ở, nhắc đừng nói to vì muộn, rồi đi ngủ.",
    start: "你住在哪儿？",
  },
  {
    id: 62,
    theme: "Tổng hợp ngày thường",
    kind: "review",
    vocab: [
      v("起床", "qǐchuáng", "Thức dậy (ôn)", "我每天起床。", "Wǒ měi tiān qǐchuáng.", "Mỗi ngày tôi dậy."),
      v("正在", "zhèngzài", "Đang (ôn)", "我正在准备。", "Wǒ zhèngzài zhǔnbèi.", "Tôi đang chuẩn bị."),
      v("时间", "shíjiān", "Thời gian (ôn)", "你有时间吗？", "Nǐ yǒu shíjiān ma?", "Bạn có thời gian không?"),
      v("我们", "wǒmen", "Chúng tôi (ôn)", "我们住在这里。", "Wǒmen zhù zài zhèlǐ.", "Chúng tôi ở đây."),
      v("别", "bié", "Đừng (ôn)", "别睡觉。", "Bié shuìjiào.", "Đừng ngủ."),
    ],
    grammar: {
      title: "Đã / đang / mỗi",
      pattern: "已经 / 正在 / 每 + V",
      explainVi: "Ghép tuần 9: kể một ngày — đã dậy, đang làm, mỗi sáng, đừng.",
      drills: [
        drill("Dịch: Tôi đã dậy rồi.", "我已经起床了。"),
        drill("Dịch: Tôi đang chuẩn bị.", "我正在准备。"),
        drill("Dịch: Mỗi sáng tôi dậy.", "我每天早上起床。"),
        drill("Dịch: Đừng ngủ.", "别睡觉。"),
      ],
    },
    dialogue: [
      line("A", "你已经起床了吗？", "Nǐ yǐjīng qǐchuáng le ma?", "Bạn đã dậy chưa?"),
      line("B", "已经起床了。我正在准备。", "Yǐjīng qǐchuáng le. Wǒ zhèngzài zhǔnbèi.", "Rồi. Tôi đang chuẩn bị."),
      line("A", "我们每天早上喝茶。你呢？", "Wǒmen měi tiān zǎoshang hē chá. Nǐ ne?", "Mỗi sáng chúng tôi uống trà. Còn bạn?"),
      line("B", "我也喝茶。晚上别太晚睡觉。", "Wǒ yě hē chá. Wǎnshang bié tài wǎn shuìjiào.", "Tôi cũng uống trà. Tối đừng ngủ quá muộn."),
    ],
    exercises: [
      ex("Tự viết: Kể: Tôi đã dậy, đang chuẩn bị.", "我已经起床了。我正在准备。"),
      ex("Tự viết: Mỗi sáng chúng tôi dậy.", "我们每天早上起床。"),
    ],
    scenario: "Kể một ngày: đã dậy, đang chuẩn bị, mỗi sáng làm gì. Không thêm từ mới tuần 9.",
    start: "你已经起床了吗？",
  },
  {
    id: 63,
    theme: "Bạn cùng phòng hỏi lịch",
    kind: "review",
    vocab: [
      v("睡觉", "shuìjiào", "Ngủ (ôn)", "晚上睡觉。", "Wǎnshang shuìjiào.", "Tối ngủ."),
      v("准备", "zhǔnbèi", "Chuẩn bị (ôn)", "我准备去学校。", "Wǒ zhǔnbèi qù xuéxiào.", "Tôi chuẩn bị đi trường."),
      v("小时", "xiǎoshí", "Giờ (ôn)", "两个小时。", "Liǎng ge xiǎoshí.", "Hai tiếng."),
      v("大家", "dàjiā", "Mọi người (ôn)", "大家都起床了。", "Dàjiā dōu qǐchuáng le.", "Mọi người đều đã dậy."),
      v("住", "zhù", "Ở (ôn)", "你住在哪儿？", "Nǐ zhù zài nǎr?", "Bạn ở đâu?"),
    ],
    grammar: {
      title: "Chỉ kể lịch",
      pattern: "已经 / 正在 / 每 — không mẫu mới",
      explainVi: "Roleplay tuần 9: bạn cùng phòng hỏi lịch trong ngày. Chỉ từ đã khoá.",
      drills: [
        drill("Dịch: Mọi người đã dậy.", "大家都起床了。"),
        drill("Dịch: Tôi có hai tiếng.", "我有两个小时。"),
        drill("Dịch: Bạn ở đâu?", "你住在哪儿？"),
        drill("Dịch: Tôi đang chuẩn bị.", "我正在准备。"),
      ],
    },
    dialogue: [
      line("A", "大家好。你住在这里吗？", "Dàjiā hǎo. Nǐ zhù zài zhèlǐ ma?", "Mọi người khỏe. Bạn ở đây à?"),
      line("B", "对。我住在这里。", "Duì. Wǒ zhù zài zhèlǐ.", "Phải. Tôi ở đây."),
      line("A", "你有两个小时吗？一起去学校。", "Nǐ yǒu liǎng ge xiǎoshí ma? Yìqǐ qù xuéxiào.", "Bạn có hai tiếng không? Cùng đi trường."),
      line("B", "好。我正在准备。", "Hǎo. Wǒ zhèngzài zhǔnbèi.", "Được. Tôi đang chuẩn bị."),
    ],
    exercises: [
      ex("Tự viết: Tôi ở đây. Đang chuẩn bị.", "我住在这里。我正在准备。"),
      ex("Tự viết: Mọi người đã dậy.", "大家都起床了。"),
    ],
    scenario: "Bạn cùng phòng hỏi chỗ ở, còn thời gian không, đã chuẩn bị đi chưa. Chỉ từ tuần 9 trở về trước.",
    start: "你住在这里吗？",
  },
  {
    id: 64,
    theme: "Cơ thể",
    kind: "learn",
    vocab: [
      v("身体", "shēntǐ", "Cơ thể / sức khỏe", "你身体好吗？", "Nǐ shēntǐ hǎo ma?", "Bạn khỏe không?"),
      v("眼睛", "yǎnjing", "Mắt", "我的眼睛很好。", "Wǒ de yǎnjing hěn hǎo.", "Mắt tôi rất tốt."),
      v("药", "yào", "Thuốc", "请吃药。", "Qǐng chī yào.", "Hãy uống thuốc."),
      v("生病", "shēngbìng", "Ốm", "我生病了。", "Wǒ shēngbìng le.", "Tôi ốm rồi."),
      v("医生", "yīshēng", "Bác sĩ", "他是医生。", "Tā shì yīshēng.", "Anh ấy là bác sĩ."),
    ],
    grammar: {
      title: "V + 了 (ốm)",
      pattern: "生病了 / 吃药",
      explainVi: "生病了 = bị ốm rồi. Hỏi sức khỏe: 你身体好吗？ Uống thuốc: 吃药。",
      drills: [
        drill("Dịch: Tôi bị ốm rồi.", "我生病了。"),
        drill("Dịch: Bạn khỏe không?", "你身体好吗？"),
        drill("Dịch: Hãy uống thuốc.", "请吃药。"),
        drill("Dịch: Anh ấy là bác sĩ.", "他是医生。"),
      ],
    },
    dialogue: [
      line("A", "你身体好吗？", "Nǐ shēntǐ hǎo ma?", "Bạn khỏe không?"),
      line("B", "不太好。我生病了。", "Bú tài hǎo. Wǒ shēngbìng le.", "Không được lắm. Tôi ốm rồi."),
      line("A", "去看医生吧。请吃药。", "Qù kàn yīshēng ba. Qǐng chī yào.", "Đi khám bác sĩ đi. Hãy uống thuốc."),
      line("B", "好。我的眼睛也有点儿不舒服。", "Hǎo. Wǒ de yǎnjing yě yǒudiǎnr bù shūfu.", "Được. Mắt tôi cũng hơi khó chịu."),
    ],
    exercises: [
      ex("Tự viết: Tôi bị ốm rồi.", "我生病了。"),
      ex("Tự viết: Hãy uống thuốc.", "请吃药。"),
    ],
    scenario: "Hỏi thăm sức khỏe, khuyên đi bác sĩ, uống thuốc.",
    start: "你身体好吗？",
  },
  {
    id: 65,
    theme: "Người thân 3",
    kind: "learn",
    vocab: [
      v("丈夫", "zhàngfu", "Chồng", "我的丈夫是医生。", "Wǒ de zhàngfu shì yīshēng.", "Chồng tôi là bác sĩ."),
      v("妻子", "qīzi", "Vợ", "他的妻子很好。", "Tā de qīzi hěn hǎo.", "Vợ anh ấy rất tốt."),
      v("孩子", "háizi", "Con", "我们有两个孩子。", "Wǒmen yǒu liǎng ge háizi.", "Chúng tôi có hai con."),
      v("男人", "nánrén", "Đàn ông", "那个男人是医生。", "Nàge nánrén shì yīshēng.", "Người đàn ông kia là bác sĩ."),
      v("女人", "nǚrén", "Phụ nữ", "那个女人是老师。", "Nàge nǚrén shì lǎoshī.", "Người phụ nữ kia là giáo viên."),
    ],
    grammar: {
      title: "N 的 N (ôn)",
      pattern: "我的丈夫 / 他的妻子",
      explainVi: "Ôn 的 với người thân mới: chồng, vợ, con. 男人 / 女人 chỉ người lớn.",
      drills: [
        drill("Dịch: Chồng tôi ốm.", "我的丈夫生病了。"),
        drill("Dịch: Vợ anh ấy là giáo viên.", "他的妻子是老师。"),
        drill("Dịch: Chúng tôi có hai con.", "我们有两个孩子。"),
        drill("Dịch: Người đàn ông kia là bác sĩ.", "那个男人是医生。"),
      ],
    },
    dialogue: [
      line("A", "你的丈夫身体好吗？", "Nǐ de zhàngfu shēntǐ hǎo ma?", "Chồng bạn khỏe không?"),
      line("B", "他生病了。孩子也在家。", "Tā shēngbìng le. Háizi yě zài jiā.", "Anh ấy ốm. Con cũng ở nhà."),
      line("A", "你的妻子呢？", "Nǐ de qīzi ne?", "Còn vợ bạn?"),
      line("B", "我没有妻子。我是男人，还没有家。", "Wǒ méiyǒu qīzi. Wǒ shì nánrén, hái méiyǒu jiā.", "Tôi không có vợ. Tôi là đàn ông, chưa có nhà."),
    ],
    exercises: [
      ex("Tự viết: Chồng tôi ốm.", "我的丈夫生病了。"),
      ex("Tự viết: Chúng tôi có hai con.", "我们有两个孩子。"),
    ],
    scenario: "Hỏi thăm chồng/vợ/con có ốm không.",
    start: "你的丈夫身体好吗？",
  },
  {
    id: 66,
    theme: "Nghĩ / hy vọng",
    kind: "learn",
    vocab: [
      v("觉得", "juéde", "Cảm thấy / nghĩ", "我觉得很累。", "Wǒ juéde hěn lèi.", "Tôi thấy rất mệt."),
      v("希望", "xīwàng", "Hy vọng", "我希望你很好。", "Wǒ xīwàng nǐ hěn hǎo.", "Tôi hy vọng bạn khỏe."),
      v("可能", "kěnéng", "Có thể / có lẽ", "可能下雨。", "Kěnéng xià yǔ.", "Có lẽ mưa."),
      v("真", "zhēn", "Thật", "真好！", "Zhēn hǎo!", "Thật tốt!"),
    ],
    grammar: {
      title: "觉得 + câu",
      pattern: "我觉得 + adj / câu",
      explainVi: "觉得 = cảm thấy/nghĩ. 可能 = có lẽ. 希望 = hy vọng. 真 nhấn mức độ.",
      drills: [
        drill("Dịch: Tôi thấy hơi mệt.", "我觉得很累。"),
        drill("Dịch: Tôi hy vọng bạn khỏe.", "我希望你很好。"),
        drill("Dịch: Có lẽ mưa.", "可能下雨。"),
        drill("Dịch: Thật tốt!", "真好！"),
      ],
    },
    dialogue: [
      line("A", "你觉得怎么样？", "Nǐ juéde zěnmeyàng?", "Bạn thấy thế nào?"),
      line("B", "我觉得很累。可能生病了。", "Wǒ juéde hěn lèi. Kěnéng shēngbìng le.", "Tôi thấy rất mệt. Có lẽ ốm rồi."),
      line("A", "我希望你很好。吃药吧。", "Wǒ xīwàng nǐ hěn hǎo. Chī yào ba.", "Tôi hy vọng bạn khỏe. Uống thuốc đi."),
      line("B", "好。真谢谢你。", "Hǎo. Zhēn xièxie nǐ.", "Được. Thật cảm ơn bạn."),
    ],
    exercises: [
      ex("Tự viết: Tôi thấy hơi mệt.", "我觉得很累。"),
      ex("Tự viết: Có lẽ mưa.", "可能下雨。"),
    ],
    scenario: "Hỏi cảm giác, hy vọng bạn mau khỏe, đoán có lẽ ốm.",
    start: "你觉得怎么样？",
  },
  {
    id: 67,
    theme: "Biết / nói",
    kind: "learn",
    vocab: [
      v("知道", "zhīdào", "Biết tin", "我知道了。", "Wǒ zhīdào le.", "Tôi biết rồi."),
      v("懂", "dǒng", "Hiểu", "我懂了。", "Wǒ dǒng le.", "Tôi hiểu rồi."),
      v("告诉", "gàosu", "Nói cho / bảo", "请告诉我。", "Qǐng gàosu wǒ.", "Làm ơn nói cho tôi."),
      v("帮助", "bāngzhù", "Giúp đỡ", "请帮助我。", "Qǐng bāngzhù wǒ.", "Làm ơn giúp tôi."),
    ],
    grammar: {
      title: "告诉 + người + việc",
      pattern: "告诉 + ai + việc",
      explainVi: "告诉 tôi bảo ai điều gì. 知道 = biết tin. 懂 = hiểu. 帮助 = giúp.",
      drills: [
        drill("Dịch: Tôi biết rồi.", "我知道了。"),
        drill("Dịch: Tôi hiểu rồi.", "我懂了。"),
        drill("Dịch: Làm ơn nói cho tôi.", "请告诉我。"),
        drill("Dịch: Làm ơn giúp tôi.", "请帮助我。"),
      ],
    },
    dialogue: [
      line("A", "你知道吗？他生病了。", "Nǐ zhīdào ma? Tā shēngbìng le.", "Bạn biết không? Anh ấy ốm rồi."),
      line("B", "我不知道。请告诉我。", "Wǒ bù zhīdào. Qǐng gàosu wǒ.", "Tôi không biết. Làm ơn nói cho tôi."),
      line("A", "请帮助他。让他吃药。", "Qǐng bāngzhù tā. Ràng tā chī yào.", "Hãy giúp anh ấy. Bảo anh ấy uống thuốc."),
      line("B", "我懂了。", "Wǒ dǒng le.", "Tôi hiểu rồi."),
    ],
    exercises: [
      ex("Tự viết: Bảo tôi uống thuốc.", "请告诉我吃药。"),
      ex("Tự viết: Tôi hiểu rồi.", "我懂了。"),
    ],
    scenario: "Báo tin ai ốm, nhờ nói giúp, bảo uống thuốc.",
    start: "你知道吗？他生病了。",
  },
  {
    id: 68,
    theme: "Nhờ giúp",
    kind: "learn",
    vocab: [
      v("让", "ràng", "Để / bảo (ai làm)", "让我帮助你。", "Ràng wǒ bāngzhù nǐ.", "Để tôi giúp bạn."),
      v("给", "gěi", "Cho / đưa", "给我药。", "Gěi wǒ yào.", "Đưa tôi thuốc."),
      v("对", "duì", "Đúng / đối với", "对，我知道。", "Duì, wǒ zhīdào.", "Đúng, tôi biết."),
      v("错", "cuò", "Sai", "不对，错了。", "Bú duì, cuò le.", "Không đúng, sai rồi."),
    ],
    grammar: {
      title: "让 / 给",
      pattern: "让 + ai + V / 给 + ai + N",
      explainVi: "让 tôi để/bảo ai làm. 给 = đưa cho. 对 / 错 nói đúng sai.",
      drills: [
        drill("Dịch: Để tôi giúp bạn.", "让我帮助你。"),
        drill("Dịch: Đưa tôi thuốc.", "给我药。"),
        drill("Dịch: Đúng.", "对。"),
        drill("Dịch: Sai rồi.", "错了。"),
      ],
    },
    dialogue: [
      line("A", "让我帮助你。给你药。", "Ràng wǒ bāngzhù nǐ. Gěi nǐ yào.", "Để tôi giúp bạn. Đưa bạn thuốc."),
      line("B", "这是对的吗？", "Zhè shì duì de ma?", "Cái này đúng không?"),
      line("A", "对。别吃错了。", "Duì. Bié chī cuò le.", "Đúng. Đừng uống nhầm."),
      line("B", "谢谢。我知道了。", "Xièxie. Wǒ zhīdào le.", "Cảm ơn. Tôi biết rồi."),
    ],
    exercises: [
      ex("Tự viết: Để tôi giúp bạn.", "让我帮助你。"),
      ex("Tự viết: Đưa tôi thuốc.", "给我药。"),
    ],
    scenario: "Nhờ giúp, đưa thuốc, hỏi đúng/sai.",
    start: "让我帮助你。",
  },
  {
    id: 69,
    theme: "Tổng hợp sức khỏe",
    kind: "review",
    vocab: [
      v("生病", "shēngbìng", "Ốm (ôn)", "我生病了。", "Wǒ shēngbìng le.", "Tôi ốm rồi."),
      v("医生", "yīshēng", "Bác sĩ (ôn)", "去看医生。", "Qù kàn yīshēng.", "Đi khám bác sĩ."),
      v("觉得", "juéde", "Cảm thấy (ôn)", "我觉得很累。", "Wǒ juéde hěn lèi.", "Tôi thấy rất mệt."),
      v("告诉", "gàosu", "Bảo (ôn)", "请告诉医生。", "Qǐng gàosu yīshēng.", "Hãy nói với bác sĩ."),
      v("帮助", "bāngzhù", "Giúp (ôn)", "请帮助我。", "Qǐng bāngzhù wǒ.", "Làm ơn giúp tôi."),
    ],
    grammar: {
      title: "Hỏi thăm",
      pattern: "身体 / 觉得 / 让给",
      explainVi: "Ôn tuần 10: thăm bạn ốm, khuyên bác sĩ, đưa thuốc.",
      drills: [
        drill("Dịch: Bạn thấy thế nào?", "你觉得怎么样？"),
        drill("Dịch: Đi khám bác sĩ đi.", "去看医生吧。"),
        drill("Dịch: Để tôi giúp bạn.", "让我帮助你。"),
        drill("Dịch: Chồng tôi ốm.", "我的丈夫生病了。"),
      ],
    },
    dialogue: [
      line("A", "你身体好吗？我觉得你很累。", "Nǐ shēntǐ hǎo ma? Wǒ juéde nǐ hěn lèi.", "Bạn khỏe không? Tôi thấy bạn rất mệt."),
      line("B", "我生病了。孩子也在家。", "Wǒ shēngbìng le. Háizi yě zài jiā.", "Tôi ốm rồi. Con cũng ở nhà."),
      line("A", "让我帮助你。去看医生吧。", "Ràng wǒ bāngzhù nǐ. Qù kàn yīshēng ba.", "Để tôi giúp. Đi khám đi."),
      line("B", "好。请给我药。", "Hǎo. Qǐng gěi wǒ yào.", "Được. Làm ơn đưa tôi thuốc."),
    ],
    exercises: [
      ex("Tự viết: Tôi thấy mệt. Tôi ốm rồi.", "我觉得很累。我生病了。"),
      ex("Tự viết: Để tôi giúp bạn.", "让我帮助你。"),
    ],
    scenario: "Thăm bạn bị ốm, hỏi cảm giác, khuyên bác sĩ, đưa thuốc. Không thêm từ mới.",
    start: "你身体好吗？",
  },
  {
    id: 70,
    theme: "Bác sĩ vs bệnh nhân",
    kind: "review",
    vocab: [
      v("药", "yào", "Thuốc (ôn)", "请吃药。", "Qǐng chī yào.", "Hãy uống thuốc."),
      v("眼睛", "yǎnjing", "Mắt (ôn)", "眼睛怎么样？", "Yǎnjing zěnmeyàng?", "Mắt thế nào?"),
      v("希望", "xīwàng", "Hy vọng (ôn)", "我希望你很好。", "Wǒ xīwàng nǐ hěn hǎo.", "Tôi hy vọng bạn khỏe."),
      v("可能", "kěnéng", "Có lẽ (ôn)", "可能太累了。", "Kěnéng tài lèi le.", "Có lẽ quá mệt."),
      v("给", "gěi", "Đưa (ôn)", "给您药。", "Gěi nín yào.", "Đưa bạn thuốc."),
    ],
    grammar: {
      title: "Chỉ bệnh / thuốc",
      pattern: "生病 / 吃药 / 觉得",
      explainVi: "Roleplay phòng khám. Chỉ từ đến tuần 10.",
      drills: [
        drill("Dịch: Mắt thế nào?", "眼睛怎么样？"),
        drill("Dịch: Hãy uống thuốc.", "请吃药。"),
        drill("Dịch: Có lẽ quá mệt.", "可能太累了。"),
        drill("Dịch: Tôi hy vọng bạn khỏe.", "我希望你很好。"),
      ],
    },
    dialogue: [
      line("A", "你哪儿不舒服？眼睛怎么样？", "Nǐ nǎr bù shūfu? Yǎnjing zěnmeyàng?", "Chỗ nào khó chịu? Mắt thế nào?"),
      line("B", "我觉得很累。可能生病了。", "Wǒ juéde hěn lèi. Kěnéng shēngbìng le.", "Tôi thấy mệt. Có lẽ ốm."),
      line("A", "给您药。请吃药。", "Gěi nín yào. Qǐng chī yào.", "Đưa bạn thuốc. Hãy uống."),
      line("B", "谢谢医生。我希望明天很好。", "Xièxie yīshēng. Wǒ xīwàng míngtiān hěn hǎo.", "Cảm ơn bác sĩ. Tôi hy vọng mai khỏe."),
    ],
    exercises: [
      ex("Tự viết: Đưa bạn thuốc. Hãy uống.", "给您药。请吃药。"),
      ex("Tự viết: Tôi thấy mệt. Có lẽ ốm.", "我觉得很累。可能生病了。"),
    ],
    scenario: "Bác sĩ hỏi bệnh, bệnh nhân nói mệt, đưa thuốc. Chỉ từ đến tuần 10.",
    start: "你哪儿不舒服？",
  },
  {
    id: 71,
    theme: "Xe cộ",
    kind: "learn",
    vocab: [
      v("公共汽车", "gōnggòng qìchē", "Xe buýt", "坐公共汽车。", "Zuò gōnggòng qìchē.", "Đi xe buýt."),
      v("自行车", "zìxíngchē", "Xe đạp", "我有自行车。", "Wǒ yǒu zìxíngchē.", "Tôi có xe đạp."),
      v("路", "lù", "Đường", "这条路很好。", "Zhè tiáo lù hěn hǎo.", "Con đường này rất tốt."),
      v("远", "yuǎn", "Xa", "家很远。", "Jiā hěn yuǎn.", "Nhà rất xa."),
      v("近", "jìn", "Gần", "学校很近。", "Xuéxiào hěn jìn.", "Trường rất gần."),
    ],
    grammar: {
      title: "A 离 B + tính từ",
      pattern: "A 离 B + 远/近",
      explainVi: "离 nói khoảng cách: 家离学校很远。Ngày này tập 远 / 近; 离 học ngày 73.",
      drills: [
        drill("Dịch: Nhà rất xa.", "家很远。"),
        drill("Dịch: Trường rất gần.", "学校很近。"),
        drill("Dịch: Đi xe buýt.", "坐公共汽车。"),
        drill("Dịch: Tôi có xe đạp.", "我有自行车。"),
      ],
    },
    dialogue: [
      line("A", "学校远吗？", "Xuéxiào yuǎn ma?", "Trường xa không?"),
      line("B", "不远，很近。坐公共汽车。", "Bù yuǎn, hěn jìn. Zuò gōnggòng qìchē.", "Không xa, rất gần. Đi xe buýt."),
      line("A", "你有自行车吗？", "Nǐ yǒu zìxíngchē ma?", "Bạn có xe đạp không?"),
      line("B", "有。这条路很好。", "Yǒu. Zhè tiáo lù hěn hǎo.", "Có. Con đường này rất tốt."),
    ],
    exercises: [
      ex("Tự viết: Nhà xa. Trường gần.", "家很远。学校很近。"),
      ex("Tự viết: Đi xe buýt.", "坐公共汽车。"),
    ],
    scenario: "Hỏi trường xa gần, đi xe buýt hay xe đạp.",
    start: "学校远吗？",
  },
  {
    id: 72,
    theme: "Hướng 2",
    kind: "learn",
    vocab: [
      v("左边", "zuǒbian", "Bên trái", "医院在左边。", "Yīyuàn zài zuǒbian.", "Bệnh viện ở bên trái."),
      v("右边", "yòubian", "Bên phải", "学校在右边。", "Xuéxiào zài yòubian.", "Trường ở bên phải."),
      v("旁边", "pángbiān", "Bên cạnh", "商店在旁边。", "Shāngdiàn zài pángbiān.", "Cửa hàng ở bên cạnh."),
      v("外", "wài", "Ngoài", "我在外面。", "Wǒ zài wàimian.", "Tôi ở ngoài."),
      v("从", "cóng", "Từ", "我从家去学校。", "Wǒ cóng jiā qù xuéxiào.", "Tôi từ nhà đi trường."),
    ],
    grammar: {
      title: "从 A 到 B",
      pattern: "从 + nơi + 到 + nơi",
      explainVi: "从 A 到 B = từ A đến B. 左边 / 右边 / 旁边 / 外 chỉ hướng.",
      drills: [
        drill("Dịch: Bệnh viện ở bên trái.", "医院在左边。"),
        drill("Dịch: Trường ở bên phải.", "学校在右边。"),
        drill("Dịch: Cửa hàng ở bên cạnh.", "商店在旁边。"),
        drill("Dịch: Từ nhà đến trường.", "从家到学校。"),
      ],
    },
    dialogue: [
      line("A", "医院在哪儿？", "Yīyuàn zài nǎr?", "Bệnh viện ở đâu?"),
      line("B", "在左边。学校在右边。", "Zài zuǒbian. Xuéxiào zài yòubian.", "Bên trái. Trường bên phải."),
      line("A", "商店呢？", "Shāngdiàn ne?", "Còn cửa hàng?"),
      line("B", "在旁边。从这里到那里很近。", "Zài pángbiān. Cóng zhèlǐ dào nàlǐ hěn jìn.", "Bên cạnh. Từ đây đến kia rất gần."),
    ],
    exercises: [
      ex("Tự viết: Từ nhà đến trường.", "从家到学校。"),
      ex("Tự viết: Bệnh viện ở bên trái.", "医院在左边。"),
    ],
    scenario: "Hỏi đường: trái, phải, bên cạnh, từ đây đến kia.",
    start: "医院在哪儿？",
  },
  {
    id: 73,
    theme: "Ga / sân bay",
    kind: "learn",
    vocab: [
      v("往", "wǎng", "Về phía", "往前走。", "Wǎng qián zǒu.", "Đi về phía trước."),
      v("离", "lí", "Cách / khỏi", "家离学校很远。", "Jiā lí xuéxiào hěn yuǎn.", "Nhà cách trường rất xa."),
      v("机场", "jīchǎng", "Sân bay", "去机场。", "Qù jīchǎng.", "Đi sân bay."),
      v("火车站", "huǒchēzhàn", "Ga tàu", "火车站在左边。", "Huǒchēzhàn zài zuǒbian.", "Ga ở bên trái."),
      v("票", "piào", "Vé", "买票。", "Mǎi piào.", "Mua vé."),
    ],
    grammar: {
      title: "往 + hướng",
      pattern: "往 + 前/左/右 + 走",
      explainVi: "往 = về phía. 离 nói khoảng cách: A 离 B + 远/近.",
      drills: [
        drill("Dịch: Đi về phía trước.", "往前走。"),
        drill("Dịch: Nhà cách trường rất xa.", "家离学校很远。"),
        drill("Dịch: Đi sân bay.", "去机场。"),
        drill("Dịch: Mua vé.", "买票。"),
      ],
    },
    dialogue: [
      line("A", "火车站离这里远吗？", "Huǒchēzhàn lí zhèlǐ yuǎn ma?", "Ga cách đây xa không?"),
      line("B", "不远。往前走。", "Bù yuǎn. Wǎng qián zǒu.", "Không xa. Đi về phía trước."),
      line("A", "去机场呢？", "Qù jīchǎng ne?", "Còn đi sân bay?"),
      line("B", "有点儿远。买票坐公共汽车。", "Yǒudiǎnr yuǎn. Mǎi piào zuò gōnggòng qìchē.", "Hơi xa. Mua vé đi xe buýt."),
    ],
    exercises: [
      ex("Tự viết: Ga cách đây xa không?", "火车站离这里远吗？"),
      ex("Tự viết: Đi về phía ga.", "往火车站走。"),
    ],
    scenario: "Hỏi ga và sân bay xa không, mua vé, đi về phía nào.",
    start: "火车站离这里远吗？",
  },
  {
    id: 74,
    theme: "Vào ra",
    kind: "learn",
    vocab: [
      v("进", "jìn", "Vào", "请进。", "Qǐng jìn.", "Mời vào."),
      v("出", "chū", "Ra", "出去。", "Chū qù.", "Ra ngoài."),
      v("等", "děng", "Đợi", "请等。", "Qǐng děng.", "Xin đợi."),
      v("找", "zhǎo", "Tìm", "我找票。", "Wǒ zhǎo piào.", "Tôi tìm vé."),
    ],
    grammar: {
      title: "V + 进 / 出",
      pattern: "进 + nơi / 出去",
      explainVi: "进 = vào, 出 = ra. 等 = đợi. 找 = tìm.",
      drills: [
        drill("Dịch: Mời vào.", "请进。"),
        drill("Dịch: Ra ngoài.", "出去。"),
        drill("Dịch: Xin đợi.", "请等。"),
        drill("Dịch: Tôi tìm vé.", "我找票。"),
      ],
    },
    dialogue: [
      line("A", "请进。你找什么？", "Qǐng jìn. Nǐ zhǎo shénme?", "Mời vào. Bạn tìm gì?"),
      line("B", "我找票。去火车站。", "Wǒ zhǎo piào. Qù huǒchēzhàn.", "Tôi tìm vé. Đi ga."),
      line("A", "请等。票在这里。", "Qǐng děng. Piào zài zhèlǐ.", "Xin đợi. Vé ở đây."),
      line("B", "谢谢。我现在出去。", "Xièxie. Wǒ xiànzài chū qù.", "Cảm ơn. Tôi ra ngay."),
    ],
    exercises: [
      ex("Tự viết: Mời vào.", "请进。"),
      ex("Tự viết: Tôi tìm vé.", "我找票。"),
    ],
    scenario: "Vào ga, tìm vé, đợi, rồi ra.",
    start: "请进。你找什么？",
  },
  {
    id: 75,
    theme: "Cửa và phòng",
    kind: "learn",
    vocab: [
      v("开", "kāi", "Mở / lái", "请开门。", "Qǐng kāi mén.", "Xin mở cửa."),
      v("门", "mén", "Cửa", "门在左边。", "Mén zài zuǒbian.", "Cửa ở bên trái."),
      v("房间", "fángjiān", "Phòng", "这是我的房间。", "Zhè shì wǒ de fángjiān.", "Đây là phòng tôi."),
      v("票", "piào", "Vé (ôn)", "我有票。", "Wǒ yǒu piào.", "Tôi có vé."),
    ],
    grammar: {
      title: "开 (mở / lái)",
      pattern: "开门 / 开车",
      explainVi: "开 + cửa = mở. 开车 = lái xe. 房间 = phòng.",
      drills: [
        drill("Dịch: Xin mở cửa.", "请开门。"),
        drill("Dịch: Đây là phòng tôi.", "这是我的房间。"),
        drill("Dịch: Cửa ở bên trái.", "门在左边。"),
        drill("Dịch: Lái xe.", "开车。"),
      ],
    },
    dialogue: [
      line("A", "这是你的房间吗？请开门。", "Zhè shì nǐ de fángjiān ma? Qǐng kāi mén.", "Đây là phòng bạn à? Xin mở cửa."),
      line("B", "是。请进。", "Shì. Qǐng jìn.", "Phải. Mời vào."),
      line("A", "你开车去火车站吗？", "Nǐ kāi chē qù huǒchēzhàn ma?", "Bạn lái xe đến ga à?"),
      line("B", "不。我坐公共汽车。我有票。", "Bù. Wǒ zuò gōnggòng qìchē. Wǒ yǒu piào.", "Không. Tôi đi xe buýt. Tôi có vé."),
    ],
    exercises: [
      ex("Tự viết: Xin mở cửa.", "请开门。"),
      ex("Tự viết: Đây là phòng tôi.", "这是我的房间。"),
    ],
    scenario: "Mở cửa phòng, hỏi đi ga bằng gì.",
    start: "这是你的房间吗？",
  },
  {
    id: 76,
    theme: "Hỏi đường 2",
    kind: "review",
    vocab: [
      v("公共汽车", "gōnggòng qìchē", "Xe buýt (ôn)", "坐公共汽车去机场。", "Zuò gōnggòng qìchē qù jīchǎng.", "Đi xe buýt đến sân bay."),
      v("离", "lí", "Cách (ôn)", "机场离这里远吗？", "Jīchǎng lí zhèlǐ yuǎn ma?", "Sân bay cách đây xa không?"),
      v("往", "wǎng", "Về phía (ôn)", "往右边走。", "Wǎng yòubian zǒu.", "Đi về bên phải."),
      v("进", "jìn", "Vào (ôn)", "进火车站。", "Jìn huǒchēzhàn.", "Vào ga."),
      v("等", "děng", "Đợi (ôn)", "在门那里等。", "Zài mén nàlǐ děng.", "Đợi ở cửa."),
    ],
    grammar: {
      title: "从 / 往 / 离",
      pattern: "从…到… / 往…走 / 离…远",
      explainVi: "Ôn tuần 11: hỏi đường tới sân bay, mua vé, vào ga.",
      drills: [
        drill("Dịch: Sân bay cách đây xa không?", "机场离这里远吗？"),
        drill("Dịch: Đi về bên phải.", "往右边走。"),
        drill("Dịch: Vào ga.", "进火车站。"),
        drill("Dịch: Đợi ở cửa.", "在门那里等。"),
      ],
    },
    dialogue: [
      line("A", "机场离这里远吗？", "Jīchǎng lí zhèlǐ yuǎn ma?", "Sân bay cách đây xa không?"),
      line("B", "有点儿远。往前走，坐公共汽车。", "Yǒudiǎnr yuǎn. Wǎng qián zǒu, zuò gōnggòng qìchē.", "Hơi xa. Đi thẳng, đi xe buýt."),
      line("A", "在哪儿买票？", "Zài nǎr mǎi piào?", "Mua vé ở đâu?"),
      line("B", "进左边的门。请等。", "Jìn zuǒbian de mén. Qǐng děng.", "Vào cửa bên trái. Xin đợi."),
    ],
    exercises: [
      ex("Tự viết: Sân bay cách đây xa không?", "机场离这里远吗？"),
      ex("Tự viết: Đi về phía trước.", "往前走。"),
    ],
    scenario: "Hỏi đường tới sân bay: xa gần, đi xe gì, cửa nào. Không thêm từ mới.",
    start: "机场离这里远吗？",
  },
  {
    id: 77,
    theme: "Du khách mua vé xe buýt",
    kind: "review",
    vocab: [
      v("票", "piào", "Vé (ôn)", "买票。", "Mǎi piào.", "Mua vé."),
      v("远", "yuǎn", "Xa (ôn)", "路很远。", "Lù hěn yuǎn.", "Đường rất xa."),
      v("找", "zhǎo", "Tìm (ôn)", "找火车站。", "Zhǎo huǒchēzhàn.", "Tìm ga."),
      v("房间", "fángjiān", "Phòng (ôn)", "这是房间。", "Zhè shì fángjiān.", "Đây là phòng."),
      v("从", "cóng", "Từ (ôn)", "从这里到机场。", "Cóng zhèlǐ dào jīchǎng.", "Từ đây đến sân bay."),
    ],
    grammar: {
      title: "Chỉ vé / đường",
      pattern: "买票 / 从到 / 离",
      explainVi: "Roleplay du khách mua vé xe buýt. Chỉ từ đến tuần 11.",
      drills: [
        drill("Dịch: Mua vé.", "买票。"),
        drill("Dịch: Từ đây đến sân bay.", "从这里到机场。"),
        drill("Dịch: Tìm ga.", "找火车站。"),
        drill("Dịch: Đường rất xa.", "路很远。"),
      ],
    },
    dialogue: [
      line("A", "从这里到机场，买票。", "Cóng zhèlǐ dào jīchǎng, mǎi piào.", "Từ đây đến sân bay, mua vé."),
      line("B", "好。路很远。二十块。", "Hǎo. Lù hěn yuǎn. Èrshí kuài.", "Được. Đường rất xa. 20 khối."),
      line("A", "谢谢。火车站在哪儿？", "Xièxie. Huǒchēzhàn zài nǎr?", "Cảm ơn. Ga ở đâu?"),
      line("B", "往右边走。请进。", "Wǎng yòubian zǒu. Qǐng jìn.", "Đi về bên phải. Mời vào."),
    ],
    exercises: [
      ex("Tự viết: Từ đây đến sân bay, mua vé.", "从这里到机场，买票。"),
      ex("Tự viết: Đường hơi xa.", "路有点儿远。"),
    ],
    scenario: "Du khách mua vé xe buýt đến sân bay, hỏi ga ở đâu. Chỉ từ đến tuần 11.",
    start: "从这里到机场，买票。",
  },
  {
    id: 78,
    theme: "Quần áo",
    kind: "learn",
    vocab: [
      v("衣服", "yīfu", "Quần áo", "这件衣服很好。", "Zhè jiàn yīfu hěn hǎo.", "Bộ quần áo này rất tốt."),
      v("件", "jiàn", "Cái (áo)", "一件衣服。", "Yí jiàn yīfu.", "Một cái áo."),
      v("颜色", "yánsè", "Màu", "什么颜色？", "Shénme yánsè?", "Màu gì?"),
      v("红", "hóng", "Đỏ", "红色。", "Hóngsè.", "Màu đỏ."),
      v("白", "bái", "Trắng", "白色的衣服。", "Báisè de yīfu.", "Áo màu trắng."),
    ],
    grammar: {
      title: "件 + quần áo",
      pattern: "数 + 件 + 衣服",
      explainVi: "件 là lượng từ cho quần áo. Hỏi màu: 什么颜色？",
      drills: [
        drill("Dịch: Một cái áo.", "一件衣服。"),
        drill("Dịch: Màu gì?", "什么颜色？"),
        drill("Dịch: Áo đỏ.", "红色的衣服。"),
        drill("Dịch: Áo trắng.", "白色的衣服。"),
      ],
    },
    dialogue: [
      line("A", "这件衣服多少钱？什么颜色？", "Zhè jiàn yīfu duōshao qián? Shénme yánsè?", "Áo này bao nhiêu tiền? Màu gì?"),
      line("B", "红色。五十块。", "Hóngsè. Wǔshí kuài.", "Màu đỏ. 50 khối."),
      line("A", "有白色的吗？", "Yǒu báisè de ma?", "Có màu trắng không?"),
      line("B", "有。这件很好。", "Yǒu. Zhè jiàn hěn hǎo.", "Có. Cái này rất tốt."),
    ],
    exercises: [
      ex("Tự viết: Một cái áo đỏ.", "一件红色的衣服。"),
      ex("Tự viết: Màu gì?", "什么颜色？"),
    ],
    scenario: "Mua áo, hỏi màu đỏ hay trắng, giá bao nhiêu.",
    start: "这件衣服多少钱？",
  },
  {
    id: 79,
    theme: "Mặc / bán",
    kind: "learn",
    vocab: [
      v("黑", "hēi", "Đen", "黑色的衣服。", "Hēisè de yīfu.", "Áo màu đen."),
      v("新", "xīn", "Mới", "新衣服。", "Xīn yīfu.", "Áo mới."),
      v("穿", "chuān", "Mặc", "我穿红衣服。", "Wǒ chuān hóng yīfu.", "Tôi mặc áo đỏ."),
      v("卖", "mài", "Bán", "你们卖衣服吗？", "Nǐmen mài yīfu ma?", "Các bạn bán quần áo à?"),
      v("长", "cháng", "Dài", "这件很长。", "Zhè jiàn hěn cháng.", "Cái này rất dài."),
    ],
    grammar: {
      title: "穿 + 衣服",
      pattern: "穿 + màu + 衣服",
      explainVi: "穿 = mặc. 卖 = bán. 新 / 黑 / 长 mô tả áo.",
      drills: [
        drill("Dịch: Tôi mặc áo mới.", "我穿新衣服。"),
        drill("Dịch: Các bạn bán quần áo à?", "你们卖衣服吗？"),
        drill("Dịch: Áo đen.", "黑色的衣服。"),
        drill("Dịch: Cái này rất dài.", "这件很长。"),
      ],
    },
    dialogue: [
      line("A", "你们卖衣服吗？我想穿新的。", "Nǐmen mài yīfu ma? Wǒ xiǎng chuān xīn de.", "Các bạn bán quần áo à? Tôi muốn mặc đồ mới."),
      line("B", "卖。这件黑色的很长。", "Mài. Zhè jiàn hēisè de hěn cháng.", "Bán. Cái đen này rất dài."),
      line("A", "有点儿贵。有便宜的吗？", "Yǒudiǎnr guì. Yǒu piányi de ma?", "Hơi đắt. Có cái rẻ không?"),
      line("B", "有。请看看。", "Yǒu. Qǐng kànkan.", "Có. Xin hãy xem."),
    ],
    exercises: [
      ex("Tự viết: Tôi mặc áo mới.", "我穿新衣服。"),
      ex("Tự viết: Các bạn bán quần áo à?", "你们卖衣服吗？"),
    ],
    scenario: "Hỏi shop có bán áo không, muốn mặc đồ mới, màu đen dài.",
    start: "你们卖衣服吗？",
  },
  {
    id: 80,
    theme: "Lượng từ",
    kind: "learn",
    vocab: [
      v("张", "zhāng", "Tờ (phẳng)", "一张票。", "Yì zhāng piào.", "Một tờ vé."),
      v("本", "běn", "Quyển", "一本书。", "Yì běn shū.", "Một quyển sách."),
      v("公斤", "gōngjīn", "Kilô", "两公斤。", "Liǎng gōngjīn.", "Hai kg."),
      v("报纸", "bàozhǐ", "Báo", "一张报纸。", "Yì zhāng bàozhǐ.", "Một tờ báo."),
      v("手表", "shǒubiǎo", "Đồng hồ đeo tay", "买手表。", "Mǎi shǒubiǎo.", "Mua đồng hồ."),
    ],
    grammar: {
      title: "张 / 本",
      pattern: "数 + 张/本 + N",
      explainVi: "张 cho đồ phẳng (vé, báo). 本 cho sách. 公斤 cho cân nặng.",
      drills: [
        drill("Dịch: Một tờ vé.", "一张票。"),
        drill("Dịch: Một quyển sách.", "一本书。"),
        drill("Dịch: Một tờ báo.", "一张报纸。"),
        drill("Dịch: Hai kg.", "两公斤。"),
      ],
    },
    dialogue: [
      line("A", "我买一张报纸，一本书。", "Wǒ mǎi yì zhāng bàozhǐ, yì běn shū.", "Tôi mua một tờ báo, một quyển sách."),
      line("B", "好。还要手表吗？", "Hǎo. Hái yào shǒubiǎo ma?", "Được. Còn muốn đồng hồ không?"),
      line("A", "不要。苹果两公斤。", "Bú yào. Píngguǒ liǎng gōngjīn.", "Không. Táo hai kg."),
      line("B", "一共三十块。", "Yígòng sānshí kuài.", "Tổng cộng 30 khối."),
    ],
    exercises: [
      ex("Tự viết: Một tờ báo, một quyển sách.", "一张报纸，一本书。"),
      ex("Tự viết: Táo hai kg.", "苹果两公斤。"),
    ],
    scenario: "Mua báo, sách, táo theo kg, hỏi có đồng hồ không.",
    start: "我买一张报纸。",
  },
  {
    id: 81,
    theme: "Đồ uống / quả",
    kind: "learn",
    vocab: [
      v("咖啡", "kāfēi", "Cà phê", "我要咖啡。", "Wǒ yào kāfēi.", "Tôi muốn cà phê."),
      v("牛奶", "niúnǎi", "Sữa bò", "一杯牛奶。", "Yì bēi niúnǎi.", "Một ly sữa."),
      v("鸡蛋", "jīdàn", "Trứng gà", "我吃鸡蛋。", "Wǒ chī jīdàn.", "Tôi ăn trứng."),
      v("西瓜", "xīguā", "Dưa hấu", "西瓜很好吃。", "Xīguā hěn hǎochī.", "Dưa hấu rất ngon."),
    ],
    grammar: {
      title: "ôn 个 / 杯",
      pattern: "一杯牛奶 / 一个西瓜",
      explainVi: "Ôn lượng từ đã học với đồ uống và quả mới.",
      drills: [
        drill("Dịch: Tôi muốn cà phê.", "我要咖啡。"),
        drill("Dịch: Một ly sữa.", "一杯牛奶。"),
        drill("Dịch: Tôi ăn trứng.", "我吃鸡蛋。"),
        drill("Dịch: Dưa hấu rất ngon.", "西瓜很好吃。"),
      ],
    },
    dialogue: [
      line("A", "你要什么？要咖啡吗？", "Nǐ yào shénme? Yào kāfēi ma?", "Bạn muốn gì? Muốn cà phê không?"),
      line("B", "一杯牛奶。再要西瓜。", "Yì bēi niúnǎi. Zài yào xīguā.", "Một ly sữa. Thêm dưa hấu."),
      line("A", "鸡蛋呢？", "Jīdàn ne?", "Còn trứng?"),
      line("B", "我也吃鸡蛋。谢谢。", "Wǒ yě chī jīdàn. Xièxie.", "Tôi cũng ăn trứng. Cảm ơn."),
    ],
    exercises: [
      ex("Tự viết: Một ly sữa, một quả dưa.", "一杯牛奶。西瓜很好吃。"),
      ex("Tự viết: Tôi muốn cà phê.", "我要咖啡。"),
    ],
    scenario: "Gọi sữa, cà phê, trứng, dưa hấu.",
    start: "你要什么？要咖啡吗？",
  },
  {
    id: 82,
    theme: "Món và đẹp",
    kind: "learn",
    vocab: [
      v("鱼", "yú", "Cá", "我喜欢吃鱼。", "Wǒ xǐhuan chī yú.", "Tôi thích ăn cá."),
      v("羊肉", "yángròu", "Thịt cừu", "羊肉多少钱？", "Yángròu duōshao qián?", "Thịt cừu bao nhiêu tiền?"),
      v("漂亮", "piàoliang", "Đẹp", "这件衣服很漂亮。", "Zhè jiàn yīfu hěn piàoliang.", "Áo này rất đẹp."),
      v("衣服", "yīfu", "Quần áo (ôn)", "新衣服很漂亮。", "Xīn yīfu hěn piàoliang.", "Áo mới rất đẹp."),
    ],
    grammar: {
      title: "A 比 B + tính từ",
      pattern: "A 比 B + adj",
      explainVi: "比 so sánh: 这件比那件漂亮。Ngày này tập mẫu nhẹ.",
      drills: [
        drill("Dịch: Tôi thích ăn cá.", "我喜欢吃鱼。"),
        drill("Dịch: Áo này rất đẹp.", "这件衣服很漂亮。"),
        drill("Dịch: Áo này đẹp hơn cái kia.", "这件比那件漂亮。"),
        drill("Dịch: Thịt cừu bao nhiêu tiền?", "羊肉多少钱？"),
      ],
    },
    dialogue: [
      line("A", "这件衣服很漂亮。比那件新。", "Zhè jiàn yīfu hěn piàoliang. Bǐ nà jiàn xīn.", "Áo này rất đẹp. Mới hơn cái kia."),
      line("B", "我也觉得。你还要买鱼和羊肉吗？", "Wǒ yě juéde. Nǐ hái yào mǎi yú hé yángròu ma?", "Tôi cũng thấy vậy. Bạn còn mua cá và thịt cừu không?"),
      line("A", "要。鱼很好吃。", "Yào. Yú hěn hǎochī.", "Có. Cá rất ngon."),
      line("B", "好。请看。", "Hǎo. Qǐng kàn.", "Được. Xin hãy xem."),
    ],
    exercises: [
      ex("Tự viết: Áo này đẹp hơn.", "这件比那件漂亮。"),
      ex("Tự viết: Tôi thích ăn cá.", "我喜欢吃鱼。"),
    ],
    scenario: "So sánh áo đẹp hơn, rồi mua cá và thịt cừu.",
    start: "这件衣服很漂亮。",
  },
  {
    id: 83,
    theme: "Ở cửa hàng 2",
    kind: "review",
    vocab: [
      v("颜色", "yánsè", "Màu (ôn)", "什么颜色？", "Shénme yánsè?", "Màu gì?"),
      v("穿", "chuān", "Mặc (ôn)", "我想穿白色的。", "Wǒ xiǎng chuān báisè de.", "Tôi muốn mặc màu trắng."),
      v("件", "jiàn", "Cái áo (ôn)", "两件衣服。", "Liǎng jiàn yīfu.", "Hai cái áo."),
      v("张", "zhāng", "Tờ (ôn)", "一张报纸。", "Yì zhāng bàozhǐ.", "Một tờ báo."),
      v("漂亮", "piàoliang", "Đẹp (ôn)", "真漂亮。", "Zhēn piàoliang.", "Thật đẹp."),
    ],
    grammar: {
      title: "Hỏi màu / size",
      pattern: "什么颜色 / 件 / 比",
      explainVi: "Ôn tuần 12: mua áo trắng, hỏi màu, lượng từ.",
      drills: [
        drill("Dịch: Màu gì?", "什么颜色？"),
        drill("Dịch: Tôi muốn mặc màu trắng.", "我想穿白色的。"),
        drill("Dịch: Hai cái áo.", "两件衣服。"),
        drill("Dịch: Thật đẹp.", "真漂亮。"),
      ],
    },
    dialogue: [
      line("A", "我想买衣服。有白色的吗？", "Wǒ xiǎng mǎi yīfu. Yǒu báisè de ma?", "Tôi muốn mua áo. Có màu trắng không?"),
      line("B", "有。这件很漂亮。八十块。", "Yǒu. Zhè jiàn hěn piàoliang. Bāshí kuài.", "Có. Cái này rất đẹp. 80 khối."),
      line("A", "有点儿贵。那件呢？", "Yǒudiǎnr guì. Nà jiàn ne?", "Hơi đắt. Còn cái kia?"),
      line("B", "那件五十块。你穿吧。", "Nà jiàn wǔshí kuài. Nǐ chuān ba.", "Cái kia 50 khối. Bạn mặc thử đi."),
    ],
    exercises: [
      ex("Tự viết: Tôi muốn mặc áo trắng.", "我想穿白色的衣服。"),
      ex("Tự viết: Cái này thật đẹp.", "这件真漂亮。"),
    ],
    scenario: "Mua áo trắng, hỏi màu và giá. Không thêm từ mới.",
    start: "我想买衣服。有白色的吗？",
  },
  {
    id: 84,
    theme: "Nhân viên vs khách",
    kind: "review",
    vocab: [
      v("卖", "mài", "Bán (ôn)", "我们卖衣服。", "Wǒmen mài yīfu.", "Chúng tôi bán quần áo."),
      v("咖啡", "kāfēi", "Cà phê (ôn)", "还要咖啡吗？", "Hái yào kāfēi ma?", "Còn muốn cà phê không?"),
      v("本", "běn", "Quyển (ôn)", "这本书。", "Zhè běn shū.", "Quyển sách này."),
      v("新", "xīn", "Mới (ôn)", "新的很漂亮。", "Xīn de hěn piàoliang.", "Cái mới rất đẹp."),
      v("公斤", "gōngjīn", "Kg (ôn)", "西瓜两公斤。", "Xīguā liǎng gōngjīn.", "Dưa hai kg."),
    ],
    grammar: {
      title: "Chỉ quần áo / giá",
      pattern: "件 / 比 / 多少钱",
      explainVi: "Roleplay cửa hàng. Chỉ từ đến tuần 12.",
      drills: [
        drill("Dịch: Chúng tôi bán quần áo.", "我们卖衣服。"),
        drill("Dịch: Cái mới rất đẹp.", "新的很漂亮。"),
        drill("Dịch: Dưa hai kg.", "西瓜两公斤。"),
        drill("Dịch: Còn muốn cà phê không?", "还要咖啡吗？"),
      ],
    },
    dialogue: [
      line("A", "你好。我们卖衣服。你要什么颜色？", "Nǐ hǎo. Wǒmen mài yīfu. Nǐ yào shénme yánsè?", "Xin chào. Chúng tôi bán áo. Bạn muốn màu gì?"),
      line("B", "白色。这件比那件长。多少钱？", "Báisè. Zhè jiàn bǐ nà jiàn cháng. Duōshao qián?", "Trắng. Cái này dài hơn cái kia. Bao nhiêu tiền?"),
      line("A", "六十块。还要西瓜吗？两公斤。", "Liùshí kuài. Hái yào xīguā ma? Liǎng gōngjīn.", "60 khối. Còn dưa không? Hai kg."),
      line("B", "好。谢谢。", "Hǎo. Xièxie.", "Được. Cảm ơn."),
    ],
    exercises: [
      ex("Tự viết: Cái này dài hơn cái kia.", "这件比那件长。"),
      ex("Tự viết: Chúng tôi bán quần áo.", "我们卖衣服。"),
    ],
    scenario: "Nhân viên vs khách: màu, so sánh áo, giá, dưa. Chỉ từ đến tuần 12.",
    start: "你要什么颜色？",
  },
  {
    id: 85,
    theme: "Thể thao",
    kind: "learn",
    vocab: [
      v("唱歌", "chànggē", "Hát", "我喜欢唱歌。", "Wǒ xǐhuan chànggē.", "Tôi thích hát."),
      v("跳舞", "tiàowǔ", "Nhảy", "她会跳舞。", "Tā huì tiàowǔ.", "Cô ấy biết nhảy."),
      v("游泳", "yóuyǒng", "Bơi", "我们去游泳。", "Wǒmen qù yóuyǒng.", "Chúng tôi đi bơi."),
      v("跑步", "pǎobù", "Chạy bộ", "我每天跑步。", "Wǒ měi tiān pǎobù.", "Mỗi ngày tôi chạy bộ."),
      v("运动", "yùndòng", "Thể thao", "做运动。", "Zuò yùndòng.", "Tập thể thao."),
    ],
    grammar: {
      title: "Động từ V-O",
      pattern: "跑步 / 唱歌 / 游泳",
      explainVi: "Nhiều động từ HSK 2 là cụm V-O: 跑步, 唱歌, 跳舞, 游泳. Không tách nếu chưa cần tân ngữ khác.",
      drills: [
        drill("Dịch: Mỗi sáng tôi chạy bộ.", "我每天早上跑步。"),
        drill("Dịch: Tôi thích hát.", "我喜欢唱歌。"),
        drill("Dịch: Chúng tôi đi bơi.", "我们去游泳。"),
        drill("Dịch: Tập thể thao.", "做运动。"),
      ],
    },
    dialogue: [
      line("A", "你喜欢做什么运动？", "Nǐ xǐhuan zuò shénme yùndòng?", "Bạn thích tập môn gì?"),
      line("B", "我每天跑步。也会游泳。", "Wǒ měi tiān pǎobù. Yě huì yóuyǒng.", "Mỗi ngày tôi chạy. Cũng biết bơi."),
      line("A", "你会唱歌跳舞吗？", "Nǐ huì chànggē tiàowǔ ma?", "Bạn hát nhảy được không?"),
      line("B", "会一点儿唱歌。跳舞不会。", "Huì yìdiǎnr chànggē. Tiàowǔ bú huì.", "Hát được một chút. Nhảy thì không."),
    ],
    exercises: [
      ex("Tự viết: Mỗi sáng tôi chạy bộ.", "我每天早上跑步。"),
      ex("Tự viết: Tôi thích hát.", "我喜欢唱歌。"),
    ],
    scenario: "Hỏi thích môn thể thao nào, có hát nhảy bơi không.",
    start: "你喜欢做什么运动？",
  },
  {
    id: 86,
    theme: "Du lịch / chơi",
    kind: "learn",
    vocab: [
      v("旅游", "lǚyóu", "Du lịch", "我想去旅游。", "Wǒ xiǎng qù lǚyóu.", "Tôi muốn đi du lịch."),
      v("玩", "wán", "Chơi", "一起玩吧。", "Yìqǐ wán ba.", "Cùng chơi nhé."),
      v("踢足球", "tī zúqiú", "Đá bóng", "我喜欢踢足球。", "Wǒ xǐhuan tī zúqiú.", "Tôi thích đá bóng."),
      v("打篮球", "dǎ lánqiú", "Chơi bóng rổ", "他会打篮球。", "Tā huì dǎ lánqiú.", "Anh ấy biết chơi bóng rổ."),
      v("北京", "Běijīng", "Bắc Kinh", "去北京。", "Qù Běijīng.", "Đi Bắc Kinh."),
    ],
    grammar: {
      title: "打 / 踢 + môn",
      pattern: "踢足球 / 打篮球",
      explainVi: "踢 cho bóng đá, 打 cho bóng rổ. 旅游 / 玩 nói đi chơi.",
      drills: [
        drill("Dịch: Tôi thích đá bóng.", "我喜欢踢足球。"),
        drill("Dịch: Anh ấy biết chơi bóng rổ.", "他会打篮球。"),
        drill("Dịch: Tôi muốn đi du lịch.", "我想去旅游。"),
        drill("Dịch: Cùng chơi nhé.", "一起玩吧。"),
      ],
    },
    dialogue: [
      line("A", "星期天一起玩吧。踢足球怎么样？", "Xīngqītiān yìqǐ wán ba. Tī zúqiú zěnmeyàng?", "Cuối tuần cùng chơi nhé. Đá bóng thế nào?"),
      line("B", "好。我喜欢踢足球。你会打篮球吗？", "Hǎo. Wǒ xǐhuan tī zúqiú. Nǐ huì dǎ lánqiú ma?", "Được. Tôi thích đá bóng. Bạn chơi rổ được không?"),
      line("A", "会。明天去旅游吗？", "Huì. Míngtiān qù lǚyóu ma?", "Được. Mai đi du lịch không?"),
      line("B", "不去。我很忙。", "Bú qù. Wǒ hěn máng.", "Không. Tôi rất bận."),
    ],
    exercises: [
      ex("Tự viết: Tôi thích đá bóng.", "我喜欢踢足球。"),
      ex("Tự viết: Cùng chơi nhé.", "一起玩吧。"),
    ],
    scenario: "Rủ đá bóng, hỏi bóng rổ, đi du lịch không.",
    start: "星期天一起玩吧。",
  },
  {
    id: 87,
    theme: "Điện thoại",
    kind: "learn",
    vocab: [
      v("手机", "shǒujī", "Điện thoại", "这是我的手机。", "Zhè shì wǒ de shǒujī.", "Đây là điện thoại tôi."),
      v("打电话", "dǎ diànhuà", "Gọi điện", "我给妈妈打电话。", "Wǒ gěi māma dǎ diànhuà.", "Tôi gọi điện cho mẹ."),
      v("喂", "wèi", "Alo", "喂，你好！", "Wèi, nǐ hǎo!", "Alo, xin chào!"),
      v("对不起", "duìbuqǐ", "Xin lỗi", "对不起。", "Duìbuqǐ.", "Xin lỗi."),
      v("没关系", "méi guānxi", "Không sao", "没关系。", "Méi guānxi.", "Không sao."),
    ],
    grammar: {
      title: "给 + người + 打电话",
      pattern: "给 + ai + 打电话",
      explainVi: "Gọi điện: 给朋友打电话。Nhấc máy: 喂。Xin lỗi / không sao: 对不起 / 没关系.",
      drills: [
        drill("Dịch: Alo, xin chào!", "喂，你好！"),
        drill("Dịch: Tôi gọi điện cho mẹ.", "我给妈妈打电话。"),
        drill("Dịch: Xin lỗi.", "对不起。"),
        drill("Dịch: Không sao.", "没关系。"),
      ],
    },
    dialogue: [
      line("A", "喂，你好！是小王吗？", "Wèi, nǐ hǎo! Shì Xiǎo Wáng ma?", "Alo, xin chào! Là Tiểu Vương phải không?"),
      line("B", "对不起，不是。", "Duìbuqǐ, bú shì.", "Xin lỗi, không phải."),
      line("A", "对不起！", "Duìbuqǐ!", "Xin lỗi!"),
      line("B", "没关系。再见。", "Méi guānxi. Zàijiàn.", "Không sao. Tạm biệt."),
    ],
    exercises: [
      ex("Tự viết: Alo, xin lỗi.", "喂，对不起。"),
      ex("Tự viết: Tôi gọi điện cho bạn.", "我给朋友打电话。"),
    ],
    scenario: "Gọi điện, xin lỗi vì gọi nhầm, đối phương nói không sao.",
    start: "喂，你好！",
  },
  {
    id: 88,
    theme: "Nghe / đọc",
    kind: "learn",
    vocab: [
      v("听", "tīng", "Nghe", "请听。", "Qǐng tīng.", "Xin hãy nghe."),
      v("读", "dú", "Đọc", "读这本书。", "Dú zhè běn shū.", "Đọc quyển sách này."),
      v("学习", "xuéxí", "Học", "我在学习汉语。", "Wǒ zài xuéxí Hànyǔ.", "Tôi đang học tiếng Trung."),
      v("课", "kè", "Buổi học / tiết", "现在上课。", "Xiànzài shàng kè.", "Bây giờ vào học."),
    ],
    grammar: {
      title: "听 / 读 + tân ngữ",
      pattern: "听 / 读 + N",
      explainVi: "听 = nghe, 读 = đọc, 学习 = học. 课 = tiết học.",
      drills: [
        drill("Dịch: Xin hãy nghe.", "请听。"),
        drill("Dịch: Đọc quyển sách này.", "读这本书。"),
        drill("Dịch: Tôi đang học tiếng Trung.", "我在学习汉语。"),
        drill("Dịch: Bây giờ vào học.", "现在上课。"),
      ],
    },
    dialogue: [
      line("A", "现在上课。请听，请读。", "Xiànzài shàng kè. Qǐng tīng, qǐng dú.", "Vào học. Xin hãy nghe, hãy đọc."),
      line("B", "好。我在学习汉语。", "Hǎo. Wǒ zài xuéxí Hànyǔ.", "Được. Tôi đang học tiếng Trung."),
      line("A", "这本书怎么样？", "Zhè běn shū zěnmeyàng?", "Quyển sách này thế nào?"),
      line("B", "很好。我每天读。", "Hěn hǎo. Wǒ měi tiān dú.", "Rất tốt. Mỗi ngày tôi đọc."),
    ],
    exercises: [
      ex("Tự viết: Nghe bài, đọc chữ.", "请听。请读。"),
      ex("Tự viết: Tôi đang học tiếng Trung.", "我在学习汉语。"),
    ],
    scenario: "Trong lớp: nghe, đọc, học tiếng Trung.",
    start: "现在上课。请听。",
  },
  {
    id: 89,
    theme: "Giới thiệu",
    kind: "learn",
    vocab: [
      v("介绍", "jièshào", "Giới thiệu", "我介绍一下。", "Wǒ jièshào yíxià.", "Tôi giới thiệu một chút."),
      v("姓", "xìng", "Họ", "我姓王。", "Wǒ xìng Wáng.", "Tôi họ Vương."),
      v("先生", "xiānsheng", "Ông / ngài", "王先生。", "Wáng xiānsheng.", "Ông Vương."),
      v("字", "zì", "Chữ", "这是什么字？", "Zhè shì shénme zì?", "Đây là chữ gì?"),
    ],
    grammar: {
      title: "姓 + họ",
      pattern: "我姓 + họ",
      explainVi: "Họ dùng 姓, không dùng 叫 cho họ. 先生 sau họ. 介绍 = giới thiệu. 字 = chữ (nghĩa đầy đủ học 意思 tuần 14; câu mẫu dùng 什么).",
      drills: [
        drill("Dịch: Tôi họ Trần.", "我姓陈。"),
        drill("Dịch: Ông Vương.", "王先生。"),
        drill("Dịch: Tôi giới thiệu một chút.", "我介绍一下。"),
        drill("Dịch: Đây là chữ gì?", "这是什么字？"),
      ],
    },
    dialogue: [
      line("A", "我介绍一下。这是王先生。", "Wǒ jièshào yíxià. Zhè shì Wáng xiānsheng.", "Tôi giới thiệu. Đây là ông Vương."),
      line("B", "您好。我姓李。", "Nín hǎo. Wǒ xìng Lǐ.", "Xin chào. Tôi họ Lý."),
      line("A", "这个字您认识吗？", "Zhège zì nín rènshi ma?", "Chữ này ngài có biết không?"),
      line("B", "认识。我正在学习。", "Rènshi. Wǒ zhèngzài xuéxí.", "Biết. Tôi đang học."),
    ],
    exercises: [
      ex("Tự viết: Tôi họ Trần.", "我姓陈。"),
      ex("Tự viết: Tôi giới thiệu ông Vương.", "我介绍一下。这是王先生。"),
    ],
    scenario: "Giới thiệu ông Vương, hỏi họ, hỏi chữ.",
    start: "我介绍一下。",
  },
  {
    id: 90,
    theme: "Rủ đi chơi",
    kind: "review",
    vocab: [
      v("跑步", "pǎobù", "Chạy bộ (ôn)", "一起跑步吧。", "Yìqǐ pǎobù ba.", "Cùng chạy bộ nhé."),
      v("踢足球", "tī zúqiú", "Đá bóng (ôn)", "星期天踢足球。", "Xīngqītiān tī zúqiú.", "Cuối tuần đá bóng."),
      v("游泳", "yóuyǒng", "Bơi (ôn)", "去游泳。", "Qù yóuyǒng.", "Đi bơi."),
      v("玩", "wán", "Chơi (ôn)", "一起玩。", "Yìqǐ wán.", "Cùng chơi."),
      v("打电话", "dǎ diànhuà", "Gọi điện (ôn)", "给我打电话。", "Gěi wǒ dǎ diànhuà.", "Gọi điện cho tôi."),
    ],
    grammar: {
      title: "一起 + V (ôn)",
      pattern: "一起 + 踢足球 / 游泳",
      explainVi: "Ôn tuần 13: rủ cuối tuần đá bóng, bơi, gọi điện.",
      drills: [
        drill("Dịch: Cùng chạy bộ nhé.", "一起跑步吧。"),
        drill("Dịch: Cuối tuần đá bóng.", "星期天踢足球。"),
        drill("Dịch: Đi bơi.", "去游泳。"),
        drill("Dịch: Gọi điện cho tôi.", "给我打电话。"),
      ],
    },
    dialogue: [
      line("A", "星期天一起玩吧。踢足球怎么样？", "Xīngqītiān yìqǐ wán ba. Tī zúqiú zěnmeyàng?", "Cuối tuần cùng chơi. Đá bóng thế nào?"),
      line("B", "好。我喜欢运动。也会游泳。", "Hǎo. Wǒ xǐhuan yùndòng. Yě huì yóuyǒng.", "Được. Tôi thích thể thao. Cũng bơi được."),
      line("A", "明天给我打电话。", "Míngtiān gěi wǒ dǎ diànhuà.", "Mai gọi điện cho tôi."),
      line("B", "好。喂，明天见！", "Hǎo. Wèi, míngtiān jiàn!", "Được. Alo, mai gặp!"),
    ],
    exercises: [
      ex("Tự viết: Cuối tuần đá bóng nhé.", "星期天一起踢足球吧。"),
      ex("Tự viết: Mai gọi điện cho tôi.", "明天给我打电话。"),
    ],
    scenario: "Rủ cuối tuần đá bóng, bơi, hẹn gọi điện. Không thêm từ mới.",
    start: "星期天一起玩吧。",
  },
  {
    id: 91,
    theme: "Gọi bạn đi bơi",
    kind: "review",
    vocab: [
      v("喂", "wèi", "Alo (ôn)", "喂，是小李吗？", "Wèi, shì Xiǎo Lǐ ma?", "Alo, là Tiểu Lý phải không?"),
      v("对不起", "duìbuqǐ", "Xin lỗi (ôn)", "对不起，我很忙。", "Duìbuqǐ, wǒ hěn máng.", "Xin lỗi, tôi rất bận."),
      v("没关系", "méi guānxi", "Không sao (ôn)", "没关系。", "Méi guānxi.", "Không sao."),
      v("旅游", "lǚyóu", "Du lịch (ôn)", "去旅游。", "Qù lǚyóu.", "Đi du lịch."),
      v("介绍", "jièshào", "Giới thiệu (ôn)", "介绍我的朋友。", "Jièshào wǒ de péngyou.", "Giới thiệu bạn tôi."),
    ],
    grammar: {
      title: "Chỉ gọi điện / rủ",
      pattern: "给…打电话 / 一起V",
      explainVi: "Roleplay gọi rủ đi bơi. Chỉ từ đến tuần 13.",
      drills: [
        drill("Dịch: Alo, là Tiểu Lý phải không?", "喂，是小李吗？"),
        drill("Dịch: Xin lỗi, tôi rất bận.", "对不起，我很忙。"),
        drill("Dịch: Không sao.", "没关系。"),
        drill("Dịch: Đi bơi nhé.", "去游泳吧。"),
      ],
    },
    dialogue: [
      line("A", "喂，是小李吗？一起去游泳吧。", "Wèi, shì Xiǎo Lǐ ma? Yìqǐ qù yóuyǒng ba.", "Alo, Tiểu Lý phải không? Cùng đi bơi nhé."),
      line("B", "对不起，我很忙。可能明天。", "Duìbuqǐ, wǒ hěn máng. Kěnéng míngtiān.", "Xin lỗi, tôi bận. Có lẽ mai."),
      line("A", "没关系。我给朋友打电话。", "Méi guānxi. Wǒ gěi péngyou dǎ diànhuà.", "Không sao. Tôi gọi bạn khác."),
      line("B", "好。我介绍一下，他姓王。", "Hǎo. Wǒ jièshào yíxià, tā xìng Wáng.", "Được. Tôi giới thiệu, anh ấy họ Vương."),
    ],
    exercises: [
      ex("Tự viết: Alo, cùng đi bơi nhé.", "喂，一起去游泳吧。"),
      ex("Tự viết: Xin lỗi. Không sao.", "对不起。没关系。"),
    ],
    scenario: "Gọi bạn đi bơi; bạn bận, xin lỗi; không sao. Chỉ từ đến tuần 13.",
    start: "喂，一起去游泳吧。",
  },
  {
    id: 92,
    theme: "Kiểm tra",
    kind: "learn",
    vocab: [
      v("考试", "kǎoshì", "Kỳ thi", "明天考试。", "Míngtiān kǎoshì.", "Mai thi."),
      v("题", "tí", "Câu hỏi (bài)", "这个题很难。", "Zhège tí hěn nán.", "Câu này khó."),
      v("问题", "wèntí", "Vấn đề / câu hỏi", "我有问题。", "Wǒ yǒu wèntí.", "Tôi có câu hỏi."),
      v("意思", "yìsi", "Nghĩa", "什么意思？", "Shénme yìsi?", "Nghĩa là gì?"),
      v("教室", "jiàoshì", "Phòng học", "在教室考试。", "Zài jiàoshì kǎoshì.", "Thi ở phòng học."),
    ],
    grammar: {
      title: "有问题",
      pattern: "有问题 / 什么意思",
      explainVi: "问题 = câu hỏi/vấn đề. 题 = câu trong bài. 意思 = nghĩa.",
      drills: [
        drill("Dịch: Bài này nghĩa là gì?", "这是什么意思？"),
        drill("Dịch: Tôi có câu hỏi.", "我有问题。"),
        drill("Dịch: Mai thi.", "明天考试。"),
        drill("Dịch: Thi ở phòng học.", "在教室考试。"),
      ],
    },
    dialogue: [
      line("A", "明天在教室考试。你准备了吗？", "Míngtiān zài jiàoshì kǎoshì. Nǐ zhǔnbèi le ma?", "Mai thi ở phòng học. Bạn chuẩn bị chưa?"),
      line("B", "准备了。这个题什么意思？", "Zhǔnbèi le. Zhège tí shénme yìsi?", "Rồi. Câu này nghĩa là gì?"),
      line("A", "我也不知道。有问题告诉老师。", "Wǒ yě bù zhīdào. Yǒu wèntí gàosu lǎoshī.", "Tôi cũng không biết. Có câu hỏi thì nói với thầy."),
      line("B", "好。我去教室。", "Hǎo. Wǒ qù jiàoshì.", "Được. Tôi đến phòng học."),
    ],
    exercises: [
      ex("Tự viết: Bài này nghĩa là gì?", "这是什么意思？"),
      ex("Tự viết: Tôi có câu hỏi.", "我有问题。"),
    ],
    scenario: "Mai thi, hỏi nghĩa câu, có vấn đề thì hỏi thầy.",
    start: "明天考试。你准备了吗？",
  },
  {
    id: 93,
    theme: "Công ty",
    kind: "learn",
    vocab: [
      v("公司", "gōngsī", "Công ty", "我在公司工作。", "Wǒ zài gōngsī gōngzuò.", "Tôi làm ở công ty."),
      v("上班", "shàngbān", "Đi làm", "我八点上班。", "Wǒ bā diǎn shàngbān.", "Tôi đi làm lúc 8 giờ."),
      v("第一", "dì-yī", "Thứ nhất", "第一次。", "Dì-yī cì.", "Lần đầu."),
      v("次", "cì", "Lần", "去过三次。", "Qù guo sān cì.", "Đã đi ba lần."),
      v("千", "qiān", "Nghìn", "一千块。", "Yì qiān kuài.", "Một nghìn khối."),
    ],
    grammar: {
      title: "第 + số; V + 次",
      pattern: "第一 / 两次",
      explainVi: "第 + số = thứ tự. 次 đếm lần. 上班 = đi làm. 公司 = công ty.",
      drills: [
        drill("Dịch: Lần đầu đi làm.", "第一次上班。"),
        drill("Dịch: Tôi làm ở công ty.", "我在公司工作。"),
        drill("Dịch: Tôi đi làm lúc 8 giờ.", "我八点上班。"),
        drill("Dịch: Một nghìn khối.", "一千块。"),
      ],
    },
    dialogue: [
      line("A", "你在哪儿上班？", "Nǐ zài nǎr shàngbān?", "Bạn đi làm ở đâu?"),
      line("B", "在公司。这是我第一次上班。", "Zài gōngsī. Zhè shì wǒ dì-yī cì shàngbān.", "Ở công ty. Đây là lần đầu tôi đi làm."),
      line("A", "一个月多少钱？", "Yí ge yuè duōshao qián?", "Một tháng bao nhiêu tiền?"),
      line("B", "五千块。还好。", "Wǔ qiān kuài. Hái hǎo.", "Năm nghìn khối. Cũng ổn."),
    ],
    exercises: [
      ex("Tự viết: Lần đầu đi làm.", "第一次上班。"),
      ex("Tự viết: Tôi làm ở công ty.", "我在公司工作。"),
    ],
    scenario: "Hỏi làm ở đâu, lần đầu đi làm, lương khoảng nghìn.",
    start: "你在哪儿上班？",
  },
  {
    id: 94,
    theme: "Nhanh / cao",
    kind: "learn",
    vocab: [
      v("快", "kuài", "Nhanh", "说得很快。", "Shuō de hěn kuài.", "Nói rất nhanh."),
      v("慢", "màn", "Chậm", "请说慢一点儿。", "Qǐng shuō màn yìdiǎnr.", "Xin nói chậm một chút."),
      v("高", "gāo", "Cao", "他很高。", "Tā hěn gāo.", "Anh ấy rất cao."),
      v("大", "dà", "To / lớn", "公司很大。", "Gōngsī hěn dà.", "Công ty rất lớn."),
    ],
    grammar: {
      title: "V + 得 + tính từ",
      pattern: "V + 得 + adj",
      explainVi: "得 sau động từ bổ nghĩa mức độ: 说得很快。说得很慢。",
      drills: [
        drill("Dịch: Nói được nhanh.", "说得很快。"),
        drill("Dịch: Xin nói chậm.", "请说慢一点儿。"),
        drill("Dịch: Anh ấy rất cao.", "他很高。"),
        drill("Dịch: Công ty rất lớn.", "公司很大。"),
      ],
    },
    dialogue: [
      line("A", "你汉语说得很快。", "Nǐ Hànyǔ shuō de hěn kuài.", "Bạn nói tiếng Trung rất nhanh."),
      line("B", "谢谢。请说慢一点儿，我听。", "Xièxie. Qǐng shuō màn yìdiǎnr, wǒ tīng.", "Cảm ơn. Xin nói chậm, tôi nghe."),
      line("A", "你的公司大吗？", "Nǐ de gōngsī dà ma?", "Công ty bạn lớn không?"),
      line("B", "很大。人也很多。", "Hěn dà. Rén yě hěn duō.", "Rất lớn. Người cũng rất nhiều."),
    ],
    exercises: [
      ex("Tự viết: Nói được nhanh.", "说得很快。"),
      ex("Tự viết: Xin nói chậm một chút.", "请说慢一点儿。"),
    ],
    scenario: "Khen nói nhanh, xin nói chậm, hỏi công ty lớn không.",
    start: "你汉语说得很快。",
  },
  {
    id: 95,
    theme: "Nhiều / ít",
    kind: "learn",
    vocab: [
      v("小", "xiǎo", "Nhỏ", "房间很小。", "Fángjiān hěn xiǎo.", "Phòng rất nhỏ."),
      v("多", "duō", "Nhiều", "人很多。", "Rén hěn duō.", "Người rất nhiều."),
      v("少", "shǎo", "Ít", "时间很少。", "Shíjiān hěn shǎo.", "Thời gian rất ít."),
      v("非常", "fēicháng", "Rất / vô cùng", "非常忙。", "Fēicháng máng.", "Rất bận."),
    ],
    grammar: {
      title: "太 + tính từ",
      pattern: "太多 / 太少 / 非常",
      explainVi: "多 / 少 nói nhiều ít. 非常 mạnh hơn 很. 太…了 = quá.",
      drills: [
        drill("Dịch: Việc hơi nhiều.", "人太多了。"),
        drill("Dịch: Thời gian rất ít.", "时间很少。"),
        drill("Dịch: Phòng rất nhỏ.", "房间很小。"),
        drill("Dịch: Rất bận.", "非常忙。"),
      ],
    },
    dialogue: [
      line("A", "公司人多吗？", "Gōngsī rén duō ma?", "Công ty nhiều người không?"),
      line("B", "非常多。我的房间很小。", "Fēicháng duō. Wǒ de fángjiān hěn xiǎo.", "Rất nhiều. Phòng tôi rất nhỏ."),
      line("A", "时间呢？", "Shíjiān ne?", "Còn thời gian?"),
      line("B", "太少了。非常忙。", "Tài shǎo le. Fēicháng máng.", "Quá ít. Rất bận."),
    ],
    exercises: [
      ex("Tự viết: Người hơi nhiều.", "人太多了。"),
      ex("Tự viết: Thời gian rất ít.", "时间很少。"),
    ],
    scenario: "Nói công ty nhiều người, phòng nhỏ, thời gian ít, rất bận.",
    start: "公司人多吗？",
  },
  {
    id: 96,
    theme: "Việc đã qua",
    kind: "learn",
    vocab: [
      v("事情", "shìqing", "Việc", "有事情。", "Yǒu shìqing.", "Có việc."),
      v("去年", "qùnián", "Năm ngoái", "去年我去中国。", "Qùnián wǒ qù Zhōngguó.", "Năm ngoái tôi đi Trung Quốc."),
      v("生日", "shēngrì", "Sinh nhật", "今天是我的生日。", "Jīntiān shì wǒ de shēngrì.", "Hôm nay là sinh nhật tôi."),
      v("零", "líng", "Số không", "二零二零年。", "Èr líng èr líng nián.", "Năm 2020."),
    ],
    grammar: {
      title: "去年 + V",
      pattern: "去年 + V",
      explainVi: "去年 đặt trước động từ. 事情 = việc. 生日 = sinh nhật. 零 dùng trong năm.",
      drills: [
        drill("Dịch: Năm ngoái tôi đi Trung Quốc.", "去年我去中国。"),
        drill("Dịch: Hôm nay là sinh nhật tôi.", "今天是我的生日。"),
        drill("Dịch: Có việc.", "有事情。"),
        drill("Dịch: Năm 2020.", "二零二零年。"),
      ],
    },
    dialogue: [
      line("A", "去年你做什么？", "Qùnián nǐ zuò shénme?", "Năm ngoái bạn làm gì?"),
      line("B", "去年我去公司上班。有很多事情。", "Qùnián wǒ qù gōngsī shàngbān. Yǒu hěn duō shìqing.", "Năm ngoái tôi đi làm. Có nhiều việc."),
      line("A", "今天是你的生日吗？", "Jīntiān shì nǐ de shēngrì ma?", "Hôm nay là sinh nhật bạn à?"),
      line("B", "是。二零零八年。谢谢。", "Shì. Èr líng líng bā nián. Xièxie.", "Phải. Năm 2008. Cảm ơn."),
    ],
    exercises: [
      ex("Tự viết: Năm ngoái tôi đi làm.", "去年我上班。"),
      ex("Tự viết: Hôm nay là sinh nhật tôi.", "今天是我的生日。"),
    ],
    scenario: "Hỏi năm ngoái làm gì, hôm nay có phải sinh nhật không.",
    start: "去年你做什么？",
  },
  {
    id: 97,
    theme: "Tổng hợp học / làm",
    kind: "review",
    vocab: [
      v("考试", "kǎoshì", "Thi (ôn)", "昨天考试。", "Zuótiān kǎoshì.", "Hôm qua thi."),
      v("上班", "shàngbān", "Đi làm (ôn)", "我去上班。", "Wǒ qù shàngbān.", "Tôi đi làm."),
      v("得", "de", "Được (ôn mẫu)", "说得很好。", "Shuō de hěn hǎo.", "Nói rất tốt."),
      v("次", "cì", "Lần (ôn)", "第一次。", "Dì-yī cì.", "Lần đầu."),
      v("非常", "fēicháng", "Rất (ôn)", "非常忙。", "Fēicháng máng.", "Rất bận."),
    ],
    grammar: {
      title: "得 / 次",
      pattern: "V得adj / 第…次",
      explainVi: "Ôn tuần 14: kể một ngày đi làm, thi, nói được nhanh.",
      drills: [
        drill("Dịch: Nói rất tốt.", "说得很好。"),
        drill("Dịch: Lần đầu đi làm.", "第一次上班。"),
        drill("Dịch: Hôm qua thi.", "昨天考试。"),
        drill("Dịch: Rất bận.", "非常忙。"),
      ],
    },
    dialogue: [
      line("A", "你上班说得很快。第一次吗？", "Nǐ shàngbān shuō de hěn kuài. Dì-yī cì ma?", "Bạn đi làm nói rất nhanh. Lần đầu à?"),
      line("B", "不是。昨天考试，非常忙。", "Bú shì. Zuótiān kǎoshì, fēicháng máng.", "Không. Hôm qua thi, rất bận."),
      line("A", "公司大吗？", "Gōngsī dà ma?", "Công ty lớn không?"),
      line("B", "很大。教室也很大。", "Hěn dà. Jiàoshì yě hěn dà.", "Rất lớn. Phòng học cũng lớn."),
    ],
    exercises: [
      ex("Tự viết: Lần đầu đi làm, nói được nhanh.", "第一次上班。说得很快。"),
      ex("Tự viết: Hôm qua thi, rất bận.", "昨天考试，非常忙。"),
    ],
    scenario: "Kể một ngày đi làm: thi, nói nhanh, công ty lớn. Không thêm từ mới.",
    start: "你上班说得很快。",
  },
  {
    id: 98,
    theme: "Đồng nghiệp hỏi lịch",
    kind: "review",
    vocab: [
      v("公司", "gōngsī", "Công ty (ôn)", "去公司。", "Qù gōngsī.", "Đến công ty."),
      v("意思", "yìsi", "Nghĩa (ôn)", "什么意思？", "Shénme yìsi?", "Nghĩa là gì?"),
      v("生日", "shēngrì", "Sinh nhật (ôn)", "生日快乐。", "Shēngrì kuàilè.", "Chúc mừng sinh nhật."),
      v("去年", "qùnián", "Năm ngoái (ôn)", "去年在这里。", "Qùnián zài zhèlǐ.", "Năm ngoái ở đây."),
      v("问题", "wèntí", "Câu hỏi (ôn)", "没有问题。", "Méiyǒu wèntí.", "Không có vấn đề."),
    ],
    grammar: {
      title: "Chỉ trường / công ty",
      pattern: "上班 / 考试 / 得",
      explainVi: "Roleplay đồng nghiệp hỏi lịch. Chỉ từ đến tuần 14. 快乐 học tuần 15 — câu mẫu dùng 生日很好.",
      drills: [
        drill("Dịch: Đến công ty.", "去公司。"),
        drill("Dịch: Nghĩa là gì?", "什么意思？"),
        drill("Dịch: Năm ngoái ở đây.", "去年在这里。"),
        drill("Dịch: Không có vấn đề.", "没有问题。"),
      ],
    },
    dialogue: [
      line("A", "你去公司吗？有问题吗？", "Nǐ qù gōngsī ma? Yǒu wèntí ma?", "Bạn đến công ty à? Có vấn đề không?"),
      line("B", "去。没有问题。今天是我的生日。", "Qù. Méiyǒu wèntí. Jīntiān shì wǒ de shēngrì.", "Có. Không vấn đề. Hôm nay sinh nhật tôi."),
      line("A", "真好！去年你也在这里吗？", "Zhēn hǎo! Qùnián nǐ yě zài zhèlǐ ma?", "Thật tốt! Năm ngoái bạn cũng ở đây à?"),
      line("B", "在。第一次上班就在这里。", "Zài. Dì-yī cì shàngbān jiù zài zhèlǐ.", "Có. Lần đầu đi làm đã ở đây."),
    ],
    exercises: [
      ex("Tự viết: Không có vấn đề. Đi công ty.", "没有问题。去公司。"),
      ex("Tự viết: Hôm nay là sinh nhật tôi.", "今天是我的生日。"),
    ],
    scenario: "Đồng nghiệp hỏi có đến công ty không, có vấn đề gì, sinh nhật. Chỉ từ đến tuần 14.",
    start: "你去公司吗？",
  },
  {
    id: 99,
    theme: "Nguyên nhân",
    kind: "learn",
    vocab: [
      v("因为", "yīnwèi", "Vì", "因为下雨。", "Yīnwèi xià yǔ.", "Vì mưa."),
      v("所以", "suǒyǐ", "Nên", "所以我在家。", "Suǒyǐ wǒ zài jiā.", "Nên tôi ở nhà."),
      v("为什么", "wèishénme", "Tại sao", "你为什么不来？", "Nǐ wèishénme bù lái?", "Vì sao bạn không đến?"),
      v("但是", "dànshì", "Nhưng", "我很忙，但是我想去。", "Wǒ hěn máng, dànshì wǒ xiǎng qù.", "Tôi bận, nhưng muốn đi."),
      v("虽然", "suīrán", "Mặc dù", "虽然很累。", "Suīrán hěn lèi.", "Mặc dù rất mệt."),
    ],
    grammar: {
      title: "因为…所以…",
      pattern: "因为 A，所以 B / 虽然…但是…",
      explainVi: "Vì… nên… 为什么 hỏi lý do. 虽然…但是… = mặc dù… nhưng…",
      drills: [
        drill("Dịch: Vì mưa nên ở nhà.", "因为下雨，所以我在家。"),
        drill("Dịch: Vì sao bạn không đến?", "你为什么不来？"),
        drill("Dịch: Mặc dù mệt nhưng tôi đi.", "虽然很累，但是我去。"),
        drill("Dịch: Tôi bận, nhưng muốn đi.", "我很忙，但是我想去。"),
      ],
    },
    dialogue: [
      line("A", "你为什么不来？", "Nǐ wèishénme bù lái?", "Vì sao bạn không đến?"),
      line("B", "因为下雨，所以我在家。", "Yīnwèi xià yǔ, suǒyǐ wǒ zài jiā.", "Vì mưa nên tôi ở nhà."),
      line("A", "虽然下雨，但是我们可以去。", "Suīrán xià yǔ, dànshì wǒmen kěyǐ qù.", "Mặc dù mưa, nhưng chúng ta có thể đi."),
      line("B", "好。我现在去。", "Hǎo. Wǒ xiànzài qù.", "Được. Tôi đi ngay."),
    ],
    exercises: [
      ex("Tự viết: Vì mưa nên ở nhà.", "因为下雨，所以我在家。"),
      ex("Tự viết: Vì sao bạn không đến?", "你为什么不来？"),
    ],
    scenario: "Hỏi vì sao không đến; vì mưa nên ở nhà; mặc dù mưa vẫn đi được.",
    start: "你为什么不来？",
  },
  {
    id: 100,
    theme: "So sánh / từng",
    kind: "learn",
    vocab: [
      v("比", "bǐ", "Hơn / so với", "他比我高。", "Tā bǐ wǒ gāo.", "Anh ấy cao hơn tôi."),
      v("最", "zuì", "Nhất", "最好。", "Zuì hǎo.", "Tốt nhất."),
      v("得", "de", "Được (bổ ngữ)", "跑得很快。", "Pǎo de hěn kuài.", "Chạy rất nhanh."),
      v("过", "guo", "Đã từng", "我去过北京。", "Wǒ qù guo Běijīng.", "Tôi đã từng đến Bắc Kinh."),
      v("还是", "háishi", "Hay là", "茶还是咖啡？", "Chá háishi kāfēi?", "Trà hay cà phê?"),
    ],
    grammar: {
      title: "A 比 B; V + 过",
      pattern: "A 比 B + adj / V过 / 还是",
      explainVi: "比 so sánh. 过 việc đã trải qua. 还是 hỏi chọn. 最 = nhất. 得 ôn bổ ngữ.",
      drills: [
        drill("Dịch: Bạn cao hơn tôi.", "你比我高。"),
        drill("Dịch: Tôi đã từng đến Bắc Kinh.", "我去过北京。"),
        drill("Dịch: Trà hay cà phê?", "茶还是咖啡？"),
        drill("Dịch: Tốt nhất.", "最好。"),
      ],
    },
    dialogue: [
      line("A", "你去过北京吗？", "Nǐ qù guo Běijīng ma?", "Bạn đã từng đến Bắc Kinh chưa?"),
      line("B", "去过。北京比这里大。", "Qù guo. Běijīng bǐ zhèlǐ dà.", "Rồi. Bắc Kinh lớn hơn đây."),
      line("A", "茶还是咖啡？", "Chá háishi kāfēi?", "Trà hay cà phê?"),
      line("B", "茶最好。谢谢。", "Chá zuì hǎo. Xièxie.", "Trà là tốt nhất. Cảm ơn."),
    ],
    exercises: [
      ex("Tự viết: Bạn cao hơn tôi.", "你比我高。"),
      ex("Tự viết: Tôi đã từng đến Bắc Kinh.", "我去过北京。"),
    ],
    scenario: "Hỏi đã từng đến Bắc Kinh chưa, so sánh lớn hơn, chọn trà hay cà phê.",
    start: "你去过北京吗？",
  },
  {
    id: 101,
    theme: "Thời tiết 2",
    kind: "learn",
    vocab: [
      v("晴", "qíng", "Nắng", "今天很晴。", "Jīntiān hěn qíng.", "Hôm nay nắng."),
      v("阴", "yīn", "U ám", "天阴了。", "Tiān yīn le.", "Trời u ám."),
      v("雪", "xuě", "Tuyết", "下雪了。", "Xià xuě le.", "Tuyết rơi rồi."),
      v("欢迎", "huānyíng", "Hoan nghênh", "欢迎！", "Huānyíng!", "Hoan nghênh!"),
      v("送", "sòng", "Tặng / đưa tiễn", "送给你。", "Sòng gěi nǐ.", "Tặng bạn."),
    ],
    grammar: {
      title: "要…了",
      pattern: "要 + V + 了",
      explainVi: "要…了 = sắp. 要下雨了。晴 / 阴 / 雪 nói thời tiết.",
      drills: [
        drill("Dịch: Trời sắp nắng.", "天要晴了。"),
        drill("Dịch: Tuyết rơi rồi.", "下雪了。"),
        drill("Dịch: Hoan nghênh!", "欢迎！"),
        drill("Dịch: Tặng bạn.", "送给你。"),
      ],
    },
    dialogue: [
      line("A", "欢迎！今天下雪了。", "Huānyíng! Jīntiān xià xuě le.", "Hoan nghênh! Hôm nay tuyết rơi."),
      line("B", "昨天很阴。今天要晴了吗？", "Zuótiān hěn yīn. Jīntiān yào qíng le ma?", "Hôm qua u ám. Hôm nay sắp nắng à?"),
      line("A", "可能。我送你一件衣服。", "Kěnéng. Wǒ sòng nǐ yí jiàn yīfu.", "Có lẽ. Tôi tặng bạn một cái áo."),
      line("B", "真好。谢谢。", "Zhēn hǎo. Xièxie.", "Thật tốt. Cảm ơn."),
    ],
    exercises: [
      ex("Tự viết: Trời sắp nắng.", "天要晴了。"),
      ex("Tự viết: Tuyết rơi rồi.", "下雪了。"),
    ],
    scenario: "Chào khách lúc tuyết, hỏi sắp nắng không, tặng áo.",
    start: "欢迎！今天下雪了。",
  },
  {
    id: 102,
    theme: "Tặng / vui",
    kind: "learn",
    vocab: [
      v("向", "xiàng", "Hướng / về", "向左走。", "Xiàng zuǒ zǒu.", "Đi về bên trái."),
      v("笑", "xiào", "Cười", "他笑了。", "Tā xiào le.", "Anh ấy cười."),
      v("快乐", "kuàilè", "Vui (lâu)", "生日快乐！", "Shēngrì kuàilè!", "Chúc mừng sinh nhật!"),
      v("漂亮", "piàoliang", "Đẹp (ôn)", "很漂亮。", "Hěn piàoliang.", "Rất đẹp."),
    ],
    grammar: {
      title: "V + 给; 向",
      pattern: "送给 / 向 + hướng",
      explainVi: "向 = về phía (gần 往). 笑 = cười. 快乐 dùng trong lời chúc.",
      drills: [
        drill("Dịch: Chúc mừng sinh nhật!", "生日快乐！"),
        drill("Dịch: Đi về bên trái.", "向左走。"),
        drill("Dịch: Anh ấy cười.", "他笑了。"),
        drill("Dịch: Tặng bạn.", "送给你。"),
      ],
    },
    dialogue: [
      line("A", "生日快乐！送给你。", "Shēngrì kuàilè! Sòng gěi nǐ.", "Chúc mừng sinh nhật! Tặng bạn."),
      line("B", "真漂亮！谢谢。", "Zhēn piàoliang! Xièxie.", "Thật đẹp! Cảm ơn."),
      line("A", "向这里看。我笑了。", "Xiàng zhèlǐ kàn. Wǒ xiào le.", "Nhìn về đây. Tôi cười rồi."),
      line("B", "我也快乐。", "Wǒ yě kuàilè.", "Tôi cũng vui."),
    ],
    exercises: [
      ex("Tự viết: Chúc mừng sinh nhật! Tặng bạn.", "生日快乐！送给你。"),
      ex("Tự viết: Anh ấy cười.", "他笑了。"),
    ],
    scenario: "Chúc sinh nhật, tặng quà, cười vui.",
    start: "生日快乐！送给你。",
  },
  {
    id: 103,
    theme: "Xưng hô",
    kind: "learn",
    vocab: [
      v("它", "tā", "Nó (đồ vật/động vật)", "它很漂亮。", "Tā hěn piàoliang.", "Nó rất đẹp."),
      v("小姐", "xiǎojie", "Cô / chị", "李小姐。", "Lǐ xiǎojie.", "Cô Lý."),
      v("船", "chuán", "Thuyền", "坐船。", "Zuò chuán.", "Đi thuyền."),
      v("因为", "yīnwèi", "Vì (ôn)", "因为有船。", "Yīnwèi yǒu chuán.", "Vì có thuyền."),
    ],
    grammar: {
      title: "ôn 比 / 因为",
      pattern: "因为…所以… / 比",
      explainVi: "Ôn so sánh và lý do với từ mới: 它, 小姐, 船.",
      drills: [
        drill("Dịch: Cô Lý.", "李小姐。"),
        drill("Dịch: Đi thuyền.", "坐船。"),
        drill("Dịch: Nó rất đẹp.", "它很漂亮。"),
        drill("Dịch: Vì có thuyền nên chúng ta đi.", "因为有船，所以我们去。"),
      ],
    },
    dialogue: [
      line("A", "李小姐，那是船吗？", "Lǐ xiǎojie, nà shì chuán ma?", "Cô Lý, kia là thuyền à?"),
      line("B", "是。它比车慢，但是很漂亮。", "Shì. Tā bǐ chē màn, dànshì hěn piàoliang.", "Phải. Nó chậm hơn xe, nhưng rất đẹp."),
      line("A", "为什么坐船？", "Wèishénme zuò chuán?", "Vì sao đi thuyền?"),
      line("B", "因为路很远，所以坐船。", "Yīnwèi lù hěn yuǎn, suǒyǐ zuò chuán.", "Vì đường xa nên đi thuyền."),
    ],
    exercises: [
      ex("Tự viết: Cô ấy / chiếc thuyền.", "李小姐。坐船。"),
      ex("Tự viết: Nó chậm hơn xe.", "它比车慢。"),
    ],
    scenario: "Hỏi cô Lý về thuyền, so sánh với xe, vì sao đi thuyền.",
    start: "李小姐，那是船吗？",
  },
  {
    id: 104,
    theme: "Tổng hợp ý kiến",
    kind: "review",
    vocab: [
      v("因为", "yīnwèi", "Vì (ôn)", "因为很累。", "Yīnwèi hěn lèi.", "Vì rất mệt."),
      v("比", "bǐ", "Hơn (ôn)", "这个比那个好。", "Zhège bǐ nàge hǎo.", "Cái này hơn cái kia."),
      v("还是", "háishi", "Hay là (ôn)", "这家还是那家？", "Zhè jiā háishi nà jiā?", "Quán này hay quán kia?"),
      v("过", "guo", "Từng (ôn)", "你去过吗？", "Nǐ qù guo ma?", "Bạn đã từng đến chưa?"),
      v("虽然", "suīrán", "Mặc dù (ôn)", "虽然贵。", "Suīrán guì.", "Mặc dù đắt."),
    ],
    grammar: {
      title: "vì / nhưng / hơn",
      pattern: "因为所以 / 虽然但是 / 比 / 还是",
      explainVi: "Ôn tuần 15: chọn quán ăn, nêu lý do, so sánh.",
      drills: [
        drill("Dịch: Quán này hay quán kia?", "这家还是那家？"),
        drill("Dịch: Cái này hơn cái kia.", "这个比那个好。"),
        drill("Dịch: Bạn đã từng đến chưa?", "你去过吗？"),
        drill("Dịch: Mặc dù đắt nhưng ngon.", "虽然贵，但是好吃。"),
      ],
    },
    dialogue: [
      line("A", "吃饭，这家还是那家？", "Chī fàn, zhè jiā háishi nà jiā?", "Ăn cơm, quán này hay quán kia?"),
      line("B", "这家比那家好。你去过吗？", "Zhè jiā bǐ nà jiā hǎo. Nǐ qù guo ma?", "Quán này hơn. Bạn đã từng đến chưa?"),
      line("A", "没去过。为什么？", "Méi qù guo. Wèishénme?", "Chưa. Vì sao?"),
      line("B", "因为好吃。虽然有点儿贵。", "Yīnwèi hǎochī. Suīrán yǒudiǎnr guì.", "Vì ngon. Mặc dù hơi đắt."),
    ],
    exercises: [
      ex("Tự viết: Quán này hay quán kia?", "这家还是那家？"),
      ex("Tự viết: Vì ngon nên đến.", "因为好吃，所以去。"),
    ],
    scenario: "Chọn quán ăn: so sánh, đã từng đến chưa, vì sao. Không thêm từ mới.",
    start: "这家还是那家？",
  },
  {
    id: 105,
    theme: "Vì sao không đi chơi",
    kind: "review",
    vocab: [
      v("为什么", "wèishénme", "Tại sao (ôn)", "你为什么不去？", "Nǐ wèishénme bú qù?", "Vì sao bạn không đi?"),
      v("所以", "suǒyǐ", "Nên (ôn)", "所以在家。", "Suǒyǐ zài jiā.", "Nên ở nhà."),
      v("最", "zuì", "Nhất (ôn)", "最好明天去。", "Zuì hǎo míngtiān qù.", "Tốt nhất mai đi."),
      v("欢迎", "huānyíng", "Hoan nghênh (ôn)", "欢迎来！", "Huānyíng lái!", "Hoan nghênh đến!"),
      v("雪", "xuě", "Tuyết (ôn)", "要下雪了。", "Yào xià xuě le.", "Sắp tuyết."),
    ],
    grammar: {
      title: "Chỉ lý do + so sánh",
      pattern: "为什么 / 因为所以 / 比",
      explainVi: "Roleplay vì sao không đi chơi. Chỉ từ đến tuần 15.",
      drills: [
        drill("Dịch: Vì sao bạn không đi?", "你为什么不去？"),
        drill("Dịch: Tốt nhất mai đi.", "最好明天去。"),
        drill("Dịch: Sắp tuyết.", "要下雪了。"),
        drill("Dịch: Hoan nghênh đến!", "欢迎来！"),
      ],
    },
    dialogue: [
      line("A", "你为什么不去玩？", "Nǐ wèishénme bú qù wán?", "Vì sao bạn không đi chơi?"),
      line("B", "因为要下雪了，所以我在家。", "Yīnwèi yào xià xuě le, suǒyǐ wǒ zài jiā.", "Vì sắp tuyết nên tôi ở nhà."),
      line("A", "虽然下雪，但是很好。欢迎来！", "Suīrán xià xuě, dànshì hěn hǎo. Huānyíng lái!", "Mặc dù tuyết, nhưng tốt. Hoan nghênh đến!"),
      line("B", "最好明天去。谢谢。", "Zuì hǎo míngtiān qù. Xièxie.", "Tốt nhất mai đi. Cảm ơn."),
    ],
    exercises: [
      ex("Tự viết: Vì sao bạn không đi chơi?", "你为什么不去玩？"),
      ex("Tự viết: Vì sắp tuyết nên ở nhà.", "因为要下雪了，所以我在家。"),
    ],
    scenario: "Hỏi vì sao không đi chơi; vì tuyết; mặc dù tuyết vẫn mời. Chỉ từ đến tuần 15.",
    start: "你为什么不去玩？",
  },
  {
    id: 106,
    theme: "Ôn ngày thường + sức khỏe",
    kind: "review",
    vocab: [
      v("已经", "yǐjīng", "Đã (ôn)", "我已经起床了。", "Wǒ yǐjīng qǐchuáng le.", "Tôi đã dậy rồi."),
      v("正在", "zhèngzài", "Đang (ôn)", "我正在吃药。", "Wǒ zhèngzài chī yào.", "Tôi đang uống thuốc."),
      v("着", "zhe", "Tiếp diễn (ôn)", "门开着。", "Mén kāi zhe.", "Cửa đang mở."),
      v("生病", "shēngbìng", "Ốm (ôn)", "他生病了。", "Tā shēngbìng le.", "Anh ấy ốm rồi."),
      v("身体", "shēntǐ", "Sức khỏe (ôn)", "身体怎么样？", "Shēntǐ zěnmeyàng?", "Sức khỏe thế nào?"),
    ],
    grammar: {
      title: "已经 正在 着",
      pattern: "已经 / 正在 / V着",
      explainVi: "Tuần 16: ôn ngày thường và hỏi thăm sức khỏe. Không thêm từ mới.",
      drills: [
        drill("Dịch: Tôi đã dậy rồi.", "我已经起床了。"),
        drill("Dịch: Tôi đang uống thuốc.", "我正在吃药。"),
        drill("Dịch: Cửa đang mở.", "门开着。"),
        drill("Dịch: Sức khỏe thế nào?", "身体怎么样？"),
      ],
    },
    dialogue: [
      line("A", "你已经起床了吗？身体怎么样？", "Nǐ yǐjīng qǐchuáng le ma? Shēntǐ zěnmeyàng?", "Bạn đã dậy chưa? Sức khỏe thế nào?"),
      line("B", "起床了。我正在吃药，因为昨天生病了。", "Qǐchuáng le. Wǒ zhèngzài chī yào, yīnwèi zuótiān shēngbìng le.", "Rồi. Tôi đang uống thuốc vì hôm qua ốm."),
      line("A", "门开着。我进来帮助你。", "Mén kāi zhe. Wǒ jìn lai bāngzhù nǐ.", "Cửa đang mở. Tôi vào giúp bạn."),
      line("B", "谢谢。我希望明天很好。", "Xièxie. Wǒ xīwàng míngtiān hěn hǎo.", "Cảm ơn. Tôi hy vọng mai khỏe."),
    ],
    exercises: [
      ex("Tự viết: Tôi đã dậy. Đang uống thuốc.", "我已经起床了。我正在吃药。"),
      ex("Tự viết: Sức khỏe thế nào?", "身体怎么样？"),
    ],
    scenario: "Kể một ngày + hỏi thăm ốm. Chỉ từ HSK 1–2 đã học.",
    start: "你已经起床了吗？身体怎么样？",
  },
  {
    id: 107,
    theme: "Ôn đi lại + mua sắm",
    kind: "review",
    vocab: [
      v("从", "cóng", "Từ (ôn)", "从家到商店。", "Cóng jiā dào shāngdiàn.", "Từ nhà đến cửa hàng."),
      v("离", "lí", "Cách (ôn)", "商店离这里近。", "Shāngdiàn lí zhèlǐ jìn.", "Cửa hàng cách đây gần."),
      v("件", "jiàn", "Cái áo (ôn)", "一件白衣服。", "Yí jiàn bái yīfu.", "Một cái áo trắng."),
      v("比", "bǐ", "Hơn (ôn)", "这件比那件便宜。", "Zhè jiàn bǐ nà jiàn piányi.", "Cái này rẻ hơn cái kia."),
      v("票", "piào", "Vé (ôn)", "买票坐公共汽车。", "Mǎi piào zuò gōnggòng qìchē.", "Mua vé đi xe buýt."),
    ],
    grammar: {
      title: "从 离 件 比",
      pattern: "从到 / 离 / 件 / 比",
      explainVi: "Ôn mua áo rồi hỏi đường. Không thêm từ mới.",
      drills: [
        drill("Dịch: Từ nhà đến cửa hàng.", "从家到商店。"),
        drill("Dịch: Cái này rẻ hơn cái kia.", "这件比那件便宜。"),
        drill("Dịch: Một cái áo trắng.", "一件白衣服。"),
        drill("Dịch: Cửa hàng cách đây gần.", "商店离这里近。"),
      ],
    },
    dialogue: [
      line("A", "商店离这里远吗？", "Shāngdiàn lí zhèlǐ yuǎn ma?", "Cửa hàng cách đây xa không?"),
      line("B", "不远。从这里往前走。", "Bù yuǎn. Cóng zhèlǐ wǎng qián zǒu.", "Không xa. Từ đây đi thẳng."),
      line("A", "我买一件白衣服。这件比那件便宜。", "Wǒ mǎi yí jiàn bái yīfu. Zhè jiàn bǐ nà jiàn piányi.", "Tôi mua một áo trắng. Cái này rẻ hơn."),
      line("B", "好。还要买票坐公共汽车吗？", "Hǎo. Hái yào mǎi piào zuò gōnggòng qìchē ma?", "Được. Còn mua vé xe buýt không?"),
    ],
    exercises: [
      ex("Tự viết: Mua áo rồi hỏi đường.", "买一件衣服。商店在哪儿？"),
      ex("Tự viết: Cái này rẻ hơn cái kia.", "这件比那件便宜。"),
    ],
    scenario: "Mua áo rồi hỏi đường đi xe buýt. Chỉ từ HSK 1–2.",
    start: "商店离这里远吗？",
  },
  {
    id: 108,
    theme: "Ôn giải trí + gọi điện",
    kind: "review",
    vocab: [
      v("打电话", "dǎ diànhuà", "Gọi điện (ôn)", "给朋友打电话。", "Gěi péngyou dǎ diànhuà.", "Gọi điện cho bạn."),
      v("游泳", "yóuyǒng", "Bơi (ôn)", "一起去游泳。", "Yìqǐ qù yóuyǒng.", "Cùng đi bơi."),
      v("喂", "wèi", "Alo (ôn)", "喂，在吗？", "Wèi, zài ma?", "Alo, có đó không?"),
      v("踢足球", "tī zúqiú", "Đá bóng (ôn)", "去踢足球。", "Qù tī zúqiú.", "Đi đá bóng."),
      v("运动", "yùndòng", "Thể thao (ôn)", "做运动。", "Zuò yùndòng.", "Tập thể thao."),
    ],
    grammar: {
      title: "给…打电话",
      pattern: "给 + ai + 打电话",
      explainVi: "Ôn rủ bạn đi bơi qua điện thoại. Không thêm từ mới.",
      drills: [
        drill("Dịch: Gọi điện cho bạn.", "给朋友打电话。"),
        drill("Dịch: Cùng đi bơi.", "一起去游泳。"),
        drill("Dịch: Alo, có đó không?", "喂，在吗？"),
        drill("Dịch: Đi đá bóng.", "去踢足球。"),
      ],
    },
    dialogue: [
      line("A", "喂，在吗？一起去游泳吧。", "Wèi, zài ma? Yìqǐ qù yóuyǒng ba.", "Alo, có đó không? Cùng đi bơi nhé."),
      line("B", "好。还是去踢足球？", "Hǎo. Háishi qù tī zúqiú?", "Được. Hay là đi đá bóng?"),
      line("A", "游泳最好。我给你打电话。", "Yóuyǒng zuì hǎo. Wǒ gěi nǐ dǎ diànhuà.", "Bơi tốt nhất. Tôi gọi cho bạn."),
      line("B", "我正在准备。明天见。", "Wǒ zhèngzài zhǔnbèi. Míngtiān jiàn.", "Tôi đang chuẩn bị. Mai gặp."),
    ],
    exercises: [
      ex("Tự viết: Alo, cùng đi bơi nhé.", "喂，一起去游泳吧。"),
      ex("Tự viết: Gọi điện cho bạn.", "给朋友打电话。"),
    ],
    scenario: "Gọi điện rủ bạn đi bơi hoặc đá bóng. Chỉ từ HSK 1–2.",
    start: "喂，一起去游泳吧。",
  },
  {
    id: 109,
    theme: "Ôn trường / công ty",
    kind: "review",
    vocab: [
      v("得", "de", "Được (ôn)", "学习得很好。", "Xuéxí de hěn hǎo.", "Học rất tốt."),
      v("次", "cì", "Lần (ôn)", "三次考试。", "Sān cì kǎoshì.", "Ba lần thi."),
      v("第一", "dì-yī", "Thứ nhất (ôn)", "第一次上班。", "Dì-yī cì shàngbān.", "Lần đầu đi làm."),
      v("教室", "jiàoshì", "Phòng học (ôn)", "在教室学习。", "Zài jiàoshì xuéxí.", "Học ở phòng học."),
      v("公司", "gōngsī", "Công ty (ôn)", "去公司上班。", "Qù gōngsī shàngbān.", "Đi làm công ty."),
    ],
    grammar: {
      title: "得 次 第",
      pattern: "V得 / 第…次",
      explainVi: "Ôn kể việc học / làm. Không thêm từ mới.",
      drills: [
        drill("Dịch: Học rất tốt.", "学习得很好。"),
        drill("Dịch: Lần đầu đi làm.", "第一次上班。"),
        drill("Dịch: Ba lần thi.", "三次考试。"),
        drill("Dịch: Học ở phòng học.", "在教室学习。"),
      ],
    },
    dialogue: [
      line("A", "你学习得怎么样？", "Nǐ xuéxí de zěnmeyàng?", "Bạn học thế nào?"),
      line("B", "还好。第一次考试有问题。", "Hái hǎo. Dì-yī cì kǎoshì yǒu wèntí.", "Ổn. Lần thi đầu có vấn đề."),
      line("A", "你在公司上班吗？", "Nǐ zài gōngsī shàngbān ma?", "Bạn làm ở công ty à?"),
      line("B", "是。上午在教室，下午去公司。", "Shì. Shàngwǔ zài jiàoshì, xiàwǔ qù gōngsī.", "Phải. Sáng ở phòng học, chiều đến công ty."),
    ],
    exercises: [
      ex("Tự viết: Học rất tốt. Lần đầu đi làm.", "学习得很好。第一次上班。"),
      ex("Tự viết: Sáng ở phòng học, chiều đi công ty.", "上午在教室，下午去公司。"),
    ],
    scenario: "Kể việc học và làm: thi, công ty, phòng học. Chỉ từ HSK 1–2.",
    start: "你学习得怎么样？",
  },
  {
    id: 110,
    theme: "Mock mini-test",
    kind: "review",
    vocab: [
      v("知道", "zhīdào", "Biết (ôn)", "你知道吗？", "Nǐ zhīdào ma?", "Bạn biết không?"),
      v("意思", "yìsi", "Nghĩa (ôn)", "什么意思？", "Shénme yìsi?", "Nghĩa là gì?"),
      v("为什么", "wèishénme", "Tại sao (ôn)", "为什么？", "Wèishénme?", "Tại sao?"),
      v("过", "guo", "Từng (ôn)", "你看过吗？", "Nǐ kàn guo ma?", "Bạn đã xem chưa?"),
      v("最", "zuì", "Nhất (ôn)", "最好的。", "Zuì hǎo de.", "Cái tốt nhất."),
    ],
    grammar: {
      title: "Ngân 20 câu",
      pattern: "HSK 2 — nghe + đọc hiểu ngắn",
      explainVi: "Mini-test: đúng/sai, so sánh, lý do, đã từng. Không thêm từ mới.",
      drills: [
        drill("Dịch: Bạn biết không? Nghĩa là gì?", "你知道吗？什么意思？"),
        drill("Dịch: Tại sao?", "为什么？"),
        drill("Dịch: Bạn đã xem chưa?", "你看过吗？"),
        drill("Dịch: Cái tốt nhất.", "最好的。"),
      ],
    },
    dialogue: [
      line("A", "你知道这是什么意思吗？", "Nǐ zhīdào zhè shì shénme yìsi ma?", "Bạn biết cái này nghĩa là gì không?"),
      line("B", "知道。你为什么问？", "Zhīdào. Nǐ wèishénme wèn?", "Biết. Vì sao bạn hỏi?"),
      line("A", "因为考试。你看过题吗？", "Yīnwèi kǎoshì. Nǐ kàn guo tí ma?", "Vì thi. Bạn đã xem câu chưa?"),
      line("B", "看过。这个最好。", "Kàn guo. Zhège zuì hǎo.", "Rồi. Cái này tốt nhất."),
    ],
    exercises: [
      ex("Tự viết: Bạn biết không? Nghĩa là gì?", "你知道吗？什么意思？"),
      ex("Tự viết: Vì thi nên hỏi.", "因为考试，所以问。"),
    ],
    scenario: "Mini-test nói: hỏi nghĩa, lý do, đã từng xem đề chưa. Chỉ ~300 từ HSK 1–2.",
    start: "你知道这是什么意思吗？",
  },
  {
    id: 111,
    theme: "Khám bệnh rồi mua thuốc",
    kind: "review",
    vocab: [
      v("医生", "yīshēng", "Bác sĩ (ôn)", "看医生。", "Kàn yīshēng.", "Khám bác sĩ."),
      v("药", "yào", "Thuốc (ôn)", "买药。", "Mǎi yào.", "Mua thuốc."),
      v("觉得", "juéde", "Cảm thấy (ôn)", "我觉得不舒服。", "Wǒ juéde bù shūfu.", "Tôi thấy không khỏe."),
      v("给", "gěi", "Đưa (ôn)", "给您药。", "Gěi nín yào.", "Đưa bạn thuốc."),
      v("希望", "xīwàng", "Hy vọng (ôn)", "希望你很好。", "Xīwàng nǐ hěn hǎo.", "Hy vọng bạn khỏe."),
    ],
    grammar: {
      title: "Toàn mẫu",
      pattern: "觉得 / 让给 / 因为",
      explainVi: "Hội thoại A: khám bệnh rồi mua thuốc. Khoá HSK 2.",
      drills: [
        drill("Dịch: Khám bác sĩ.", "看医生。"),
        drill("Dịch: Tôi thấy không khỏe.", "我觉得不舒服。"),
        drill("Dịch: Đưa bạn thuốc.", "给您药。"),
        drill("Dịch: Hy vọng bạn khỏe.", "希望你很好。"),
      ],
    },
    dialogue: [
      line("A", "医生，我觉得不舒服。可能生病了。", "Yīshēng, wǒ juéde bù shūfu. Kěnéng shēngbìng le.", "Bác sĩ, tôi thấy không khỏe. Có lẽ ốm."),
      line("B", "我知道了。给您药。请吃药。", "Wǒ zhīdào le. Gěi nín yào. Qǐng chī yào.", "Tôi biết rồi. Đưa bạn thuốc. Hãy uống."),
      line("A", "在哪儿买药？", "Zài nǎr mǎi yào?", "Mua thuốc ở đâu?"),
      line("B", "往左边走。希望你很好。", "Wǎng zuǒbian zǒu. Xīwàng nǐ hěn hǎo.", "Đi về bên trái. Hy vọng bạn khỏe."),
    ],
    exercises: [
      ex("Tự viết: Tôi thấy không khỏe. Có lẽ ốm.", "我觉得不舒服。可能生病了。"),
      ex("Tự viết: Đưa bạn thuốc. Hãy uống.", "给您药。请吃药。"),
    ],
    scenario: "Khám bệnh rồi hỏi chỗ mua thuốc. Khoá toàn từ HSK 1–2.",
    start: "医生，我觉得不舒服。",
  },
  {
    id: 112,
    theme: "Ngày đầu đi làm ở Bắc Kinh",
    kind: "review",
    vocab: [
      v("上班", "shàngbān", "Đi làm (ôn)", "去公司上班。", "Qù gōngsī shàngbān.", "Đi làm công ty."),
      v("介绍", "jièshào", "Giới thiệu (ôn)", "我介绍一下。", "Wǒ jièshào yíxià.", "Tôi giới thiệu."),
      v("欢迎", "huānyíng", "Hoan nghênh (ôn)", "欢迎来北京。", "Huānyíng lái Běijīng.", "Hoan nghênh đến Bắc Kinh."),
      v("第一", "dì-yī", "Thứ nhất (ôn)", "第一次来。", "Dì-yī cì lái.", "Lần đầu đến."),
      v("快乐", "kuàilè", "Vui (ôn)", "我很快乐。", "Wǒ hěn kuàilè.", "Tôi rất vui."),
    ],
    grammar: {
      title: "Không thêm mẫu mới",
      pattern: "HSK 1–2 toàn mẫu",
      explainVi: "Tốt nghiệp HSK 2: ngày đầu đi làm ở Bắc Kinh. Chỉ từ đã khoá.",
      drills: [
        drill("Dịch: Hoan nghênh đến Bắc Kinh.", "欢迎来北京。"),
        drill("Dịch: Lần đầu đi làm.", "第一次上班。"),
        drill("Dịch: Tôi giới thiệu một chút.", "我介绍一下。"),
        drill("Dịch: Tôi rất vui.", "我很快乐。"),
      ],
    },
    dialogue: [
      line("A", "欢迎来北京！你是第一次来吗？", "Huānyíng lái Běijīng! Nǐ shì dì-yī cì lái ma?", "Hoan nghênh đến Bắc Kinh! Lần đầu bạn đến à?"),
      line("B", "是。我来公司上班。", "Shì. Wǒ lái gōngsī shàngbān.", "Phải. Tôi đến công ty làm."),
      line("A", "我介绍一下。我姓王。你呢？", "Wǒ jièshào yíxià. Wǒ xìng Wáng. Nǐ ne?", "Tôi giới thiệu. Tôi họ Vương. Còn bạn?"),
      line("B", "我姓李。今天我很快乐。谢谢。", "Wǒ xìng Lǐ. Jīntiān wǒ hěn kuàilè. Xièxie.", "Tôi họ Lý. Hôm nay tôi rất vui. Cảm ơn."),
    ],
    exercises: [
      ex("Tự viết: Hoan nghênh đến Bắc Kinh. Lần đầu đi làm.", "欢迎来北京。第一次上班。"),
      ex("Tự viết: Tôi giới thiệu. Tôi họ Lý.", "我介绍一下。我姓李。"),
    ],
    scenario: "Ngày đầu đi làm ở Bắc Kinh: chào, giới thiệu họ, lần đầu. Chỉ từ HSK 1–2.",
    start: "欢迎来北京！",
  },
];

function weekOf(id) {
  return Math.ceil(id / 7);
}

function systemPrompt(level, words, start) {
  return `Bạn là bạn nói tiếng Trung trình độ HSK ${level}. Chỉ dùng các từ: ${words.join(", ")}. Mỗi lượt 1–2 câu ngắn. Viết Hán + pinyin. Nếu học viên sai, sửa nhẹ bằng tiếng Việt rồi hỏi lại. Không thêm từ mới. Bắt đầu bằng: ${start}`;
}

const hsk1 = JSON.parse(readFileSync(join(dir, "056.json"), "utf8"));
let allowed = [...hsk1.aiPrompt.allowedWords];

for (const lesson of LESSONS) {
  if (lesson.kind === "learn") {
    for (const item of lesson.vocab) {
      if (!item.vi.includes("(ôn") && !allowed.includes(item.han)) {
        allowed.push(item.han);
      }
    }
  }
  const week = weekOf(lesson.id);
  const payload = {
    id: lesson.id,
    week,
    hsk: 2,
    theme: lesson.theme,
    kind: lesson.kind,
    vocab: lesson.vocab,
    grammar: lesson.grammar,
    dialogue: lesson.dialogue,
    exercises: lesson.exercises,
    aiPrompt: {
      scenario: lesson.scenario,
      system: systemPrompt(2, allowed, lesson.start),
      allowedWords: [...allowed],
      turns: 5,
    },
    timer: TIMER,
  };
  const name = `${String(lesson.id).padStart(3, "0")}.json`;
  writeFileSync(join(dir, name), `${JSON.stringify(payload, null, 2)}\n`);
}

console.log(`Wrote ${LESSONS.length} lessons, last allowed ${allowed.length} words`);

